### ISSUE TITLE
CDN In AdminCP

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1054]
I'm not sure if this is a bug or not, but the CDN URL is not being used in the AdminCP. It would be nice if the CDN is used for avatars in the AdminCP when searching for users or editing profiles.

Original thread: [CDN In AdminCP](http://community.mybb.com/thread-156558.html)

**Comment by JN-Jones** [comment]
@euantorano As you were the one implementing the CDN stuff can you take a look at this (and #1829)? Would be good to get this done.

**Comment by euantorano** [comment]
As Omar said, I'm not sure if using the CDN in the ACP is the best idea in case the CDN fails. The ACP is sued by fewer people and less often than the front-end anyway, so it shouldn't cause bandwidth issues.

**Comment by JN-Jones** [comment]
So instead of falling back to local files in case the CDN fails you're suggesting to simply use local files from the start? I'm fine with but let's hear what @mybb/management the management says

**Comment by Stefan-ST** [comment]
How would you fall back to local files in case the CDN fails?

**Comment by euantorano** [comment]
The system has no way of knowing if the CDN fails unless we start pinging the CDN server and checking responses match local content. It's easier to just simply use local files from the start in the ACP.

**Comment by JN-Jones** [comment]
Closing this then
