### ISSUE TITLE
ACP: Replace hardcoded placeholder language string with an actual language variable

### ISSUE THREAD

**Issue by Kaeden** [mybb/mybb#1056]
There are a few areas in the ACP that still use a hardcoded English language string for the selectable fields placeholder instead of an actual language variable.

I have pinpointed the following locations which need to be fixed:
- [x] Forum Management -> Moderators -> Add User as Moderator (admin/modules/forum/management.php line 2632)
- [x] Users & Groups -> Find Users -> Username contains (admin/modules/user/users.php line 4074)
- [x] Users & Groups -> Merge Users -> Source and Destination Account (admin/modules/user/users.php lines 2083, 2113)
- [x] Users & Groups -> Banning -> Banned Accounts (admin/modules/user/banning.php line 564)

**Comment by Destroy666x** [comment]
This should be translated too: https://github.com/Sama34/mybb/blob/improve-1354/admin/modules/user/banning.php#L500

**Comment by Sama34** [comment]
It should probably be `-1` and be set as `MyBB Engine` in the proper places.

**Comment by Cu8eR** [comment]
I will push a PR with fix... but I need to merge some of my PRs before this (GitHub client is the most stupid thing ever)
