### ISSUE TITLE
Pagination not updated after unapproving post

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1168]
https://github.com/mybb/mybb/issues/1116#issuecomment-51595306

**Comment by JN-Jones** [comment]
As there weren't any users wondering about some weird pagination I'd still vote for simply ignoring this and closing the issue. @mybb/developers

**Comment by JN-Jones** [comment]
Anyone against closing?

**Comment by euantorano** [comment]
No objections from me.
