### ISSUE TITLE
Report reasons enhancements

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1223]
__Reference:__ http://community.mybb.com/thread-156899.html

**Comment by Ben-Conway** [comment]
@Sama34 Is there any progress with this?

**Comment by Destroy666x** [comment]
Definitely would be great to get it into MyBB 1.8.x. Possibility to report profiles for wrong forum is just unprofessional.

**Comment by groovybluedog** [comment]
Wow I only just noticed that my thread was put in to an issue <3
So I'm not as useless as I thought XD!
Definitely needed though, I'm setting up a new forum now and STILL using that method, which is quite tiresome and very, very, limited.

**Comment by Ben-Conway** [comment]
@Destroy666x Isn't this a bug more than an enhancement then?

**Comment by groovybluedog** [comment]
I honestly think the best way to handle this is to have a box for the different reasons and have users enter other reasons on a new line. Other would be an on/off option and this all could just be a main configuration option. No need for language files either. For example:

Report reasons for threads: (Yes, separate is better :P)
Wrong forum
Bad language
Poll that breaks the rules

Report reasons for posts:
Off topic from the first post
Back seat moderating
Bad language

Report reasons for PMs:
For reputation: [X]
For calendar events: [X]
For profiles: [X]
Anywhere else!: [X]

It would be as simple as a user typing in reasons in the admincp on new lines.

**Comment by dequeues** [comment]
I was thinking of having a module in ACP which would show a table like so:
```
Type | Reason | Options
```
Type: Private messages/posts/profiles/global(all) or any other combination like so
Reason: The report reason
Options: Modify/Delete

Thoughts?

**Comment by Ben-Conway** [comment]
@dequeues Sounds good. Now we just need someone to work on it. This 'bug' has been open for long enough and it needs fixed ASAP.

**Comment by groovybluedog** [comment]
@dequeues That way sounds quite messy especially in a longer list, but maybe I'm visualising it wrong.

Something like the Help pages AdminCP page?

**Comment by dequeues** [comment]
I was thinking more of something like Custom Profile Fields in ACP.

**Comment by groovybluedog** [comment]
I think that could really get quite messy. If you were to do it this way where each reason is a separate entry, I think something nested like the help pages ACP page would be better.

**Comment by dequeues** [comment]
Let's say we had nested, how would we show a reason for example which is both for Private Messages and Posts?

**Comment by groovybluedog** [comment]
Create to seperate entries. I do this all of the time on the help topics when the same question comes under multiple categories and it works out far less messy than a dump of report reasons in one list especially when people like me want several (10+) reasons to allow moderators to prioritise jobs.

**Comment by Destroy666x** [comment]
I don't see how @dequeues solution is messy, that looks like the proper way of doing it. The only problem are plugins that add reports to other places - hooks need to be properly placed so that reason editing module will be extendable.

**Comment by wagey** [comment]
Looking forward to this.

**Comment by JordanMussi** [comment]
Fixed in #2460 :smile:

**Comment by Ben-Conway** [comment]
@JordanMussi Thanks for this, I was looking to get this done :)

**Comment by JordanMussi** [comment]
@Ben-Conway No problem! :grinning:
