### ISSUE TITLE
Jquery collapsing problem

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1366]
Hello.
Mybb 1.8 have bug with collapse item.
Why  ?
Because template like a forumbit for make forums are buged on IE11, but work better from Chrome.

Code:
expandedItem.toggle("fast");
Hmmm.... this section collapse in general.js put height: into &lt;tbody&gt; lol
See at reference http://api.jquery.com/toggle/
On chrome i have only fade effect, but where is animation on fade this item ?
Normally I cannot change jquery effect like .slideToggle because construction of table don't accept it on Chrome, but accept on IE11.
Here is example template for forumbit to better work this effect, or any other jQuery effect like slideToggle, or fade ;)
Sorry for lame code, but it was maked fast.

Code:
&lt;table border="0" cellspacing="0" cellpadding="0" class="tborder"&gt;

&lt;thead&gt;
&lt;tr&gt;
&lt;td class="thead" colspan="5"&gt;
&lt;div class="forum-icon float-left"&gt;&lt;img src="{&#36;theme['imgdir']}/forum-icons/forum-icon-{&#36;forum['fid']}.png" /&gt;&lt;/div&gt;
&lt;div class="expcolimage"&gt;&lt;img src="{&#36;theme['imgdir']}/{&#36;expcolimage}" id="cat_{&#36;forum['fid']}_img" class="expander" alt="{&#36;expaltext}" title="{&#36;expaltext}" /&gt;&lt;/div&gt;
&lt;div&gt;&lt;a href="{&#36;forum_url}" class="cat-link"&gt;{&#36;forum['name']}&lt;/a&gt;&lt;div class="smalltext cat-description"&gt;{&#36;forum['description']}&lt;/div&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/thead&gt;
&lt;/table&gt;

&lt;div style="{&#36;expdisplay}" id="cat_{&#36;forum['fid']}_e"&gt;
&lt;table border="0" cellspacing="0" cellpadding="0" class="tborder"&gt;
&lt;tbody &gt;
&lt;tr&gt;
&lt;td class="tcat" colspan="2"&gt;&lt;span class="smalltext"&gt;{&#36;lang-&gt;forumbit_forum}&lt;/span&gt;&lt;/td&gt;
&lt;td class="tcat forumnum-post-tcat" width="170" align="center" style="white-space: nowrap;"&gt;&lt;span class="smalltext" style=" margin-right: 25px; "&gt;{&#36;lang-&gt;forumbit_threads} &amp; {&#36;lang-&gt;forumbit_posts}&lt;/strong&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td class="tcat last-post-tcat" width="220" align="center"&gt;&lt;span class="smalltext"&gt;{&#36;lang-&gt;forumbit_lastpost}&lt;/span&gt;&lt;/td&gt;
&lt;/tr&gt;
{&#36;sub_forums}
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;br /&gt;

Original thread: [Jquery collapsing problem](http://community.mybb.com/thread-158248.html)

**Comment by cybernetwebdesign** [comment]
fix it ASAP

**Comment by Cu8eR** [comment]
@cybernetwebdesign - you can send a PR ;)

**Comment by Destroy666x** [comment]
Why would we fix an animation issue connected with a rarely used functionality that affects one browser (maybe also Edge, haven't checked) "ASAP" over other issues, e.g. nearly completely broken functionalities?

Also, I don't seem to have the problem on the latest IE11 in the first place, Microsoft may have improved how they handle such JS/HTML/CSS combination. Can anyone still confirm the issue (video/.gif would be nice)?

**Comment by JN-Jones** [comment]
I've some weird behavior in IE but I'm not sure whether it's related to this. However I can at least confirm that Edge doesn't have the same issue. I'll try to take a look later to see whether it's exactly related to this.

**Comment by Eldenroot** [comment]
@euantorano @Sama34 - IE11 was replaced, now it is abandoned... so I think there is no need to make a fix for this issue. I havent been fixed for 6 years... I vote for close this one.

**Comment by Sama34** [comment]
Anything for IE should be dropped  by now, yes. I will close this unless another team member knows better.
