### ISSUE TITLE
Stats Performance w/ Today's Top Poster

### ISSUE THREAD

**Issue by labrocca** [mybb/mybb#139]
It runs like crap on a large forum.  I changed the default query to something much faster then added some php to sort. Query went from 40 seconds to under 1. 

```
default:
    $query = $db->query("
        SELECT u.uid, u.username, COUNT(*) AS poststoday
        FROM ".TABLE_PREFIX."posts p
        LEFT JOIN ".TABLE_PREFIX."users u ON (p.uid=u.uid)
        WHERE p.dateline > $timesearch
        GROUP BY p.uid ORDER BY NULL DESC
    ");
```

//Custom for fix of max poster
while($user = $db->fetch_array($query))
{
    $topposter[] = array('poststoday' =>$user['poststoday'],'uid' => $user['uid'], 'username' => $user['username'] );
}

$user = max($topposter);

**Comment by JN-Jones** [comment]
@euantorano @Devilshakerz @Destroy666x @Stefan-ST This issue is open since 3 years. So do we want to work on this or close it as suggested two years ago?

**Comment by euantorano** [comment]
I've not looked at it, but if it's not an easy fix I doubt we'll get it done for 1.8.

**Comment by WildcardSearch** [comment]
@mybb/developers @mybb/sqa it would be good to test this on a database with many active users with posts, which I don't have access to. I saw only a minimal increase in speed, but that is to be expected when you have ten fake users with two posts apiece.

**Comment by WildcardSearch** [comment]
I have finally had time to conduct a proper test of this matter.

On a fresh installation of MyBB 1.8.12, I created over one million users, and created threads and posts totaling over one hundred thousand posts-- all of them being made in the same day (and in the range of the top poster statistic).

![Top Poster Test Forum Stats](https://i.imgur.com/xWV11vD.png)

Running the query as it is currently in the source yielded the following results:

![Before](https://i.imgur.com/gNkMWR0.png)

Modifying the code as written above and refreshing the statistics page gave the following results:

![After](https://i.imgur.com/NfpFHuB.png)

I conclude that there is no need to change the code-- at least not to this particular method.

**Comment by labrocca** [comment]
Great conclusion based on 100,000 posts.  Try 20 million and see how it does. Your test doesn't really strain the limits.  You need a lot more posts than 100k for this to be a problem.  And it's not the users table that's the issue.  It's the posts table.

This is a 3 year old thread.  I don't think it matters anyways.

**Comment by Shade-** [comment]
20 million posts... a day? 😮  Not sure if it's feasible, but @WildcardSearch can you benchmark this fix with such a massive amount of posts?

**Comment by WildcardSearch** [comment]
> Great conclusion based on 100,000 posts. Try 20 million and see how it does. Your test doesn't really strain the limits. You need a lot more posts than 100k for this to be a problem. And it's not the users table that's the issue. It's the posts table.

You mean to tell me that you have a forum that receives twenty millions posts per day!?

> 20 million posts... a day? 😮 Not sure if it's feasible, but @WildcardSearch can you benchmark this fix with such a massive amount of posts?

It would take me forever to create that many random threads. I'm sorry, but I can't agree with @labrocca -- I feel that one hundred thousand posts in a single day is WAY beyond the realm of probability for any forum, anywhere.

**Comment by Shade-** [comment]
That would mean 230 posts per second on average. With a hundred thousands posts we are talking about 1.16 per second which is still a huge amount.

**Comment by labrocca** [comment]
You're not listening to the guy who has an actual forum with millions of posts.  At the time I wrote this issue up the query was a huge problem due to the GROUP BY statement.  It has nothing to do with how many actual post per day there was.  It had to do with the size of the posts table.  When your post table is 30Gb, you experience issues with GROUP BY rather frequently due to cache sizes, ram, and optimization needs.  

If you want to test the problem then do it correctly and make a 10Gb posts table with about 20 million entries.  And have about 1 million users.  The amount of posts in the day won't matter.

My changes aren't that severe but then again my use-case situation isn't different then most.  I gave you a fix to optimize the query.  Really not sure why it's been so long.  Try my changes on a test forum and if it works then why not add it?

**Comment by WildcardSearch** [comment]
> You're not listening to the guy who has an actual forum with millions of posts. At the time I wrote this issue up the query was a huge problem due to the GROUP BY statement. It has nothing to do with how many actual post per day there was. It had to do with the size of the posts table. When your post table is 30Gb, you experience issues with GROUP BY rather frequently due to cache sizes, ram, and optimization needs.

You never made it clear to me what the problem was at all-- I was just trusting your experience and trying to close this issue. I don't think it is fair to say that I am not listening to you. Look back and you will see that I took the initiative to do a large portion of the work to resolve this.

> If you want to test the problem then do it correctly and make a 10Gb posts table with about 20 million entries. And have about 1 million users. The amount of posts in the day won't matter.

Fine, I'll give it a shot, but I have issues with timeouts and I don't want to spend the rest of my life trying to create fake posts.

Do you perhaps have a script to create that many fake users?

**Comment by tommm** [comment]
@WildcardSearch - it isn't just about testing in a local environment. You won't see the benefits just adding a bunch of posts and users. You'll actually need to put the local SQL server under the same stress as a production server.

Could we ask BBOs to download an official changed file via the forum, and get this out into the community to trial? @euantorano

**Comment by euantorano** [comment]
I would say that would be a good idea. There’s little chance it’s going to decrease performance, and a good chance it’ll help improve performance in cases where it’s needed.

**Comment by labrocca** [comment]
Just reviewed 1.8x stats.php and the page is entirely different.  I don't even see where topposters query is run.

**Comment by WildcardSearch** [comment]
It runs in the `class_datacache.php` -- `datacache::update_statistics`

**Comment by labrocca** [comment]
Oh, I remember now.  I see the difference. Old query has an ORDER BY poststoday DESC. What that will do is sort the entire posts table into memory.  This is why my change is to do the query then sort with PHP the smaller results.  It saved huge resources and it's not that big of a change really.  The query is not optimal at all.  Posts table on a larger board is very busy. 

At the time I spent a decent amount of work optimization queries and code that caused heavy load.  My changes benefit MyBB with no downside.  Suggest you test to ensure it works as expected and just commit the change.  

What's the big deal?

**Comment by euantorano** [comment]
Makes perfect sense to me. As I said before, it’s hardly going to be slower, and any performance increase is worthwhile.

**Comment by tommm** [comment]
Yeah I'm good with that. I thought it was a larger change than this.

**Comment by WildcardSearch** [comment]
Fine by me. 👍

**Comment by JordanMussi** [comment]
This needs to be added to the 1.8.15 milestone.

**Comment by kawaii** [comment]
Thanks @JordanMussi. :)
