### ISSUE TITLE
Change max. recipients

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1427]
Quote:You may send this message to a maximum of 5 people.

How to change this number?

Original thread: [Change max. recipients](http://community.mybb.com/thread-158970.html)

**Comment by Stefan-ST** [comment]
@mybb/developers Any chance to fix this in 1.8.4 as it breaks functionality? I see @Destroy666x already worked on it.

**Comment by Destroy666x** [comment]
I can finish it if you want to move it for 1.8.4. Only 1 JS change more is needed for PR.

**Comment by Cu8eR** [comment]
I tried to fix this but without success, is there any way how to fix this easily? Now, I use on my forum hardcoded version of fix :(

**Comment by dequeues** [comment]
@Destroy666x - did you ever manage to get a solution for this?

**Comment by Cu8eR** [comment]
@dequeues - feel free to push a PR if you know how to properly fix this. Destroy assigned himself in 2014.

**Comment by Stefan-ST** [comment]
Any progress?

**Comment by PaulBender** [comment]
I fixed this in #2195

**Comment by Destroy666x** [comment]
It's not completely fixed yet (JS solution is needed to combine both recipient and BCC fields), I'll be able to do more than testing after 10.07 at earliest, so feel free to takeover my stuff if you want.

**Comment by JN-Jones** [comment]
@mybb/developers If this is only a small change like @Destroy666x said it'd be nice getting a PR for this.
