### ISSUE TITLE
Modal & Confirm dialogs

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1429]
There is a little bit of inconsistensy between the two libraries we introduced.

![delete](https://cloud.githubusercontent.com/assets/1786584/4265093/0f7e2f28-3c3f-11e4-889f-6271fed641c6.jpg)
![rate](https://cloud.githubusercontent.com/assets/1786584/4265094/0f809cae-3c3f-11e4-8048-a4ecfc877aa7.jpg)
![report](https://cloud.githubusercontent.com/assets/1786584/4265095/0f82ebee-3c3f-11e4-9c0e-a5b8328d3947.jpg)

Both of them are modals, one of those modals try to mimic the confirm dialog design.

This is mostly design issues.

**Comment by JN-Jones** [comment]
@justinsoltesz Can you take a look at this? Otherwise I'd say this isn't worth fixing.

**Comment by justinsoltesz** [comment]
Personally I think the pain this would likely cause theme authors at this point now that 1.8 has been out for over 2 years outweighs the benefits from addressing this.

I can look at it if absolutely necessary, but I won't be able to any time soon as there are other higher priority things on my task list I need to accomplish.

**Comment by JN-Jones** [comment]
I'm fine with that, @euantorano are you ok with closing this?

**Comment by euantorano** [comment]
Yep, I'm fine to close this.
