### ISSUE TITLE
Copy/Paste Undo editor bug

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1437]
Copy and paste something, paste it in to your editor. Continue typing. Then control+Z back so the editor is empty. What you pasted will stay regardless of it's place. 

Steps to reproduce:

Type sentence.

Copy this post and paste it into your post.

Attempt to undo.

I've not tried any other browsers or OS.

Windows 7, Chrome Version 37.0.2062.103.

Thank you.

Original thread: [Copy/Paste Undo editor bug](http://community.mybb.com/thread-158872.html)

**Comment by Sama34** [comment]
If 1.4.6 is not released at time we should probably skip it for the next update. Or include the plugin that solves it:
https://github.com/samclarke/SCEditor/blob/1.4.6-dev/src/plugins/undo.js

**Comment by Cu8eR** [comment]
plugin would be a temporary solution - better to fix this issue by a plugin and then replace the plugin by new version of sceditor

**Comment by Destroy666x** [comment]
Yeah, we should just use the plugin.

**Comment by Sama34** [comment]
@Cu8eR The plugin is the solution applied by the SCEditor team in 1.4.6

So if MyBB 1.8.4 is to be released before SCEditor 1.4.6 we should fix this by using the plugin and thenon future MyBB version we can update SCEditor. Hope I was clear :P

**Comment by Cu8eR** [comment]
@Sama34 - dont worry, I understood :) 

Another solution is to use SCeditor 1.4.6dev version - there is only one issue left (feature request). Of course there could be some issues, but many other bugs were fixed in this version.

**Comment by Sama34** [comment]
That could be another solution but I think we should simply wait for the official release to update the full package.

**Comment by Cu8eR** [comment]
It would be really better to use 1.4.6dev - it is almost done, all fixes now go into 1.4.7. Only one feature is missing in 1.4.6 (special chars) but this versions fixes really a lot of issues.

**Comment by Sama34** [comment]
I don't think we have the time for complains because MyBB is using an _unstable_ third-party library.

**Comment by JN-Jones** [comment]
As said above: if there's a plugin for the current version we should try to use that as long as 1.4.6 isn't released.
