### ISSUE TITLE
Smilie breaks JS when ending with backslash

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1453]
Hi all

After upgrading my forum to 1.8 I noticed that no js based stuff worked at all and I tracked it back to one of my smilies, which had the code ":-\" at the time. That code is inserted in the smilie function in js and escapes the closing quote =&gt; js syntax error.
I've changed to ":-/" for now so it works but the smilie codes should be checked before inserting them in js.

Bye.

Original thread: [Smilie breaks JS when ending with backslash](http://community.mybb.com/thread-159684.html)

**Comment by Destroy666x** [comment]
Note: I'm still working on it since this wasn't the best fix, `addslashes()` works but one character is escaped for no reason (sometimes `'` and sometimes `"`) and that may cause problems with smilies that contain one of these character. I wanted to finish the PR later today, will submit a new one.

**Comment by JN-Jones** [comment]
Any other issue you're still working on before I start merging anymore?

**Comment by Destroy666x** [comment]
https://github.com/mybb/mybb/pull/1595 (almost finished) and peekers.

**Comment by Destroy666x** [comment]
This is finished now too.

**Comment by PaulBender** [comment]
All fixed in #1800
