### ISSUE TITLE
Custom mod tools and inline moderation

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1463]
1. I created a custom thread tool with these options:
 - confirmation page: yes
 - stick/unstick thread: toggle
 - random PM and reply text
2. Then I created 2 threads and went to Today's Posts.
3. Selected them and used the custom thread tool.
4. I tried using the tool multiple times. The threads' sticky status <b>never changed</b>. PMs and replies were sent, but sometimes they were bugged too - one execution should create 1 PM and 1 reply per thread, but the tool created 2.

It seems to work just fine when used in showthread.php - sticky status is changed and always only 1 reply/PM is created.

**Comment by Sama34** [comment]
Doesn't seems to work on forum display either. Seems weird because debugging shows that the query gets executed..
