### ISSUE TITLE
Soft deleted content is checked for duplicate content.

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1469]
In MyBB 1.6/1.8 a post check for duplicated posts by the user while summiting a reply is done.

In 1.8 the this check is also applied over soft deleted posts. So the following error message:
Quote:There was an error posting your reply: You have already posted this reply to the specified thread. Please visit the thread to see your reply.

Shows even if the former post is soft deleted. I'm unsure if this is the expected behavior but IMO it shouldn't.

Please suggest.

Original thread: [Soft deleted content is checked for duplicate content.](http://community.mybb.com/thread-160022.html)

**Comment by JN-Jones** [comment]
There should clearly be a proper error message but simply modifying it depending on the status of the duplicated post should be fine.
