### ISSUE TITLE
Make usage of $mybb->get_input() instead of $mybb->input[]

### ISSUE THREAD

**Issue by JanMalte** [mybb/mybb#1526]
The input should be accessed by ```$mybb->get_input()``` instead of ```$mybb->input[]```.

**Comment by JanMalte** [comment]
@Sama34 I'm working on it, but as already stated, it is quite a lot of work to be done and tested.

**Comment by JanMalte** [comment]
I think all changes are made and can be merged. Only calls with casting were replaced by the method call alternative.

**Comment by Destroy666x** [comment]
It's still not optimised (UserCP actions), `MyBB::INPUT_STRING` was used inconsistently only in several function calls (the rest is empty and in my opinon all should have stayed empty) and you introduced a syntax error in admin/modules/config/mod_tools.php

**Comment by JanMalte** [comment]
@Destroy666x Could you show me the syntax error?

I've added some more commits to fix the points Destroy666x mentioned. If something still doesn't fit, please tell me and give an example how it should be.

**Comment by Destroy666x** [comment]
I think we can close this too, unless someone has time to work on it properly.

**Comment by euantorano** [comment]
Yep, I'm all for closing it unless somebody is willing to put themselves forwards to work upon it.

**Comment by Destroy666x** [comment]
Closing then, feel free to reopen if you're going to make a PR.
