### ISSUE TITLE
Select All for Reports

### ISSUE THREAD

**Issue by labrocca** [mybb/mybb#154]
In the modcp when marking selected reports as read the select all checkbox will not mark all reports on all pages as read.  

That's not how it behaved before and not in line with how other pages of MyBB work for selection of all on a page.  

I can have as many as 300 open reports and now when moderators go through a single page they can't use the mark all anymore and have to manually click each box.  That's time consuming and like I said...wasn't that way before.  

Please fix.

**Comment by JN-Jones** [comment]
Can confirm this. When selecting all threads it shows a notification "x Threads on this page have been selected, click here to select all x threads on all pages". Something similar should be done in the Report Center. Also something else I've noticed which should probably be fixed here too as it's a small issue: The all reports page shows "There are currently no unread reports" if there are no reports however the page does show read reports too so the error message is a bit misleading.

**Comment by Cu8eeeR** [comment]
@JordanMussi - can you please look at this? Thx

**Comment by JordanMussi** [comment]
Fixed in #2774 (forgot to comment when I submitted the pull)
