### ISSUE TITLE
generate_numeric_field improvements

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#1544]
In 1.8.1 we added a generate_numeric_field to the Admin CP forms. However, this addition didn't take full advantage of some of the attributes input type="number" offers.

- [x] A minimum value of 0 should be enforced on almost all fields.
- [x] A maximum value of 100 should be enforced on the field Percentage of Maximum Warning Points when adding/editing a warning level.
- [x] Some form boxes need to made bigger.
- [x] generate_date_select function should use generate_numeric_field for the year value.

**Comment by PirataNervo** [comment]
@PaulBender just to be sure, everything's ready to be tested?

**Comment by PaulBender** [comment]
Yes, everything's ready for testing.

**Comment by Destroy666x** [comment]
Note that possible unwanted 0 issues similar to this: https://github.com/mybb/mybb/issues/1613 should be checked too. I feel like Group Promotions and Mass Mails may have a similar problem with some numeric inputs, haven't tested yet.

**Comment by Destroy666x** [comment]
Has anyone checked the above? For example ACP -> Users & Groups -> Group Promotions -> Add New Promotion. There are 5 fields with 0 and Greater Than selected by default. If someone forgets to remove some 0s, I'm quite sure he may get unwanted results.

Reopening just to confirm that won't happen and we won't get other bug reports like this: https://github.com/mybb/mybb/issues/1613

**Comment by PaulBender** [comment]
It should be fine, since you need to select which fields you'll be checking.

https://github.com/mybb/mybb/blob/feature/inc/tasks/promotions.php#L35

**Comment by Destroy666x** [comment]
You're right. What about 3 fields in new Mass Mail?

**Comment by Sama34** [comment]
> But ACP -> Forums & Posts -> Attachments -> Download count is may be affected.

How come? It works similar to the two settings above it. Or am I missing something?

What I find weird is that after clicking the find attachment button and the `No attachments were found with the specified search criteria.` is shown the `Date posted is` and `File size is` field values get multiplied..

**Comment by Destroy666x** [comment]
> It works similar to the two settings above it. Or am I missing something?

File size can't be 0, 0 days ago is now. But download count can be 0.

Anyways, just checked the code for it and it's similar to the mass mail task conditions - Greater Than 0 downloads doesn't work at all and shows attachments with 0 downloads too. So this bug doesn't exist here, but I'd consider it another bug, thus I'm closing this and will open a new issue.

> that is weird.

Yep, you found yet another bug, I'll open an issue for it too.

**Comment by Sama34** [comment]
But if the file size is set to 0 then that search filter is to be ignored isn't it?

Description tells so:
> All fields are optional and won't be included in the criteria unless they contain a value."

Now, what if I want to ignore download count in the search query...?

Now if I empty the value and click the button, in the next page the field will be filled once again with 0.

**Comment by Destroy666x** [comment]
But the 0 is ignored by the code as I said above, that's the point :P As for the wrong description, I opened a new issue that should take care of it: https://github.com/mybb/mybb/issues/1766

**Comment by Sama34** [comment]
There is a difference between ignoring download count with 0 and search download count equals 0.

How are we handling this now? Can I search attachments with a download count of 0 or not?

**Comment by Destroy666x** [comment]
Read my two comments above and open the issue link...

**Comment by Sama34** [comment]
Just giving my opinion not really sure how deep the changes need to be.

**Comment by Sama34** [comment]
TBH the implementation of the _generate_numeric_field_ method should have been deeply tested before merging.
