### ISSUE TITLE
Refreshing registration question works only partially

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1549]
While trying to fix https://github.com/mybb/mybb/issues/1454 I noticed that you can only refresh the question few times and then a 
> There was an error fetching the new question. The question you are trying to answer does not exist. 

error shows up all the time.

Just in case someone needs reproduction steps:
1. Open http://community.mybb.com/member.php?action=register
2. Refresh the registration question 3-10 times.

**Comment by PaulBender** [comment]
Fixed in #1651
