### ISSUE TITLE
It's impossible to send a PM to a user with a short username

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#1567]
If a username is shorter than 3 characters it impossible to send him a PM because Select2 doesn't accept anything that short.

**Comment by Stefan-ST** [comment]
@mybb/developers Any chance to fix this in 1.8.4 as it's pretty annoying for affected users?

**Comment by PaulBender** [comment]
So what's the best solution for this? Shorten the autocomplete to 2 characters?

**Comment by JN-Jones** [comment]
What's our min length for usernames? Or is there a setting for that?

The minimum length should be used as a settings can be changed.

**Comment by Destroy666x** [comment]
> Or is there a setting for that?

There is, but users may register with a short name before it gets increased, which will cause problems with searching too.

I guess we can just remove the minimum or set it to 1 (I doubt that's needed, 1 is most likely default)? I don't see why not, `LIKE` will work regardless of that. Don't forget to change it here too: https://github.com/mybb/mybb/blob/feature/xmlhttp.php#L215

**Comment by Qiaoj** [comment]
Minimum should be set to 1. 
You can disable auto-search for 1-2 chars, but you should be able to enter short names as usual.

1 is not that seldom for username in languages with hieroglyphs. 2 is very common case.
