### ISSUE TITLE
"Email Verification & Administrator Activation" usless

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#1569]
The Registration Method setting "Email Verification & Administrator Activation" is useless right now because the administrator is unable to determine if the user has verified his email or not.

**Comment by PaulBender** [comment]
The way I see it, there's two ways to fix this problem. Either we: create a dedicated activation page that distinguishes what type of activation the user needs or create a second activation usergroup just for users that are awaiting Admin Activation (while leaving the current activation usergroup for users awaiting Email Verification).

**Comment by Sama34** [comment]
We should avoid creating a new group IMO, so go with the first option.

**Comment by Stefan-ST** [comment]
I agree with @Sama34.

**Comment by lf-schmidt** [comment]
I'd go with the two groups. And I'd prefer that the Admins only be notified via email of new user registration after he/she confirms email.

**Comment by lf-schmidt** [comment]
I just found out that the "Activate users from ModCP" plugin (http://community.mybb.com/mods.php?action=view&pid=154) is a workaround. With the plugin installed, the ModCP shows "Email activation" for users that didn't verify email yet and "Admin activation" for those that already verified and are awaiting for the admin.

**Comment by groovybluedog** [comment]
I was just about to make a thread about this as it is exactly that; too difficult to determine if email has been verified. This really needs to be fixed!

**Comment by premiumcuyuz** [comment]
Good job mybb team 👍
