### ISSUE TITLE
More proper URL validation

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1589]
Some places don't validate URLs properly (they don't take `https://` and other cases into consideration). For example:
https://github.com/mybb/mybb/blob/feature/inc/functions.php#L3721
https://github.com/mybb/mybb/blob/feature/admin/modules/config/smilies.php#L637 (and one more in that file)
https://github.com/mybb/mybb/blob/feature/admin/modules/config/post_icons.php#L468
https://github.com/PaulBender/mybb/blob/ce5804c7e30eaaa583c8bd7b4d61e3c9eda1b9a6/admin/modules/config/attachment_types.php#L322
https://github.com/mybb/mybb/blob/feature/admin/modules/user/users.php#L1455
https://github.com/mybb/mybb/blob/feature/usercp.php#L2250

There may be more of them.

**Comment by Sama34** [comment]
I think this is covered.
