### ISSUE TITLE
Incomplete forum deletion

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1609]
Continuation of https://github.com/mybb/mybb/pull/1605

If you delete a forum, the following things are incorrect:
- [x] all threads and posts are deleted, but records associated with them such as forumsread/threadratings/threadsubscriptions/reportedcontent/polls/polloptions/attachments/etc. are left as orphaned litter in the database. Not good if you delete a forum with many threads. Deleting users works much much better: https://github.com/mybb/mybb/blob/feature/inc/datahandlers/user.php#L1426
- [x] global threads/posts stats are recounted, but stats for the parent forum(s) and for users that posted in the deleted forum (if the forum settings don't disable user post/thread counting) aren't recounted
- [x] `get_forum()` cache read is used to get the name of the deleted forum, but that doesn't make any sense since it can be selected in the forums table query 2 lines below too

**Comment by Sama34** [comment]
This is now done. We shall now hope there aren't many threads being deleted but lets assume that an administrators is just not deleting a bazillion threads this way.

About the usage of `get_forum()`, if we remove it now there may be plugins affected. Makes no difference anyways.

I simply added an note to run the recount & rebuild tools once deleting the forum. IMO there is no need to rewrite that.
