### ISSUE TITLE
Add 2 Factor Authentication to Admin CP

### ISSUE THREAD

**Issue by PirataNervo** [mybb/mybb#1623]
To enhance security on MyBB forums, we're adding 2-FA on the Admin CP.

A new table/container will be added to Home - Preferences in which admins can turn On 2-FA by doing the following:
- Scan QR code (which changes on each page load)
- After scanning, the user must enter the code provided by his QR code scanner (like Google Authenticator) in a textbox to validate the QR code. There should exist a 2 minute relaxation time (- and + 2 minutes) for time computation differences.

After it's enabled, the QR code displayed on that page does not change. Enabling or disabling gets logged in the Administrator Logs.

When logging in, the 2FA code should requested after the username/password combination is valid, if the specified user has 2FA enabled.

**Comment by Sama34** [comment]
@JN-Jones would you be willing to include MyBB-2FA?

**Comment by JN-Jones** [comment]
Sorry, was busy during the weekend. Yes I can work on it if we agree where and how to add it. As already said: IMHO we should add it to the front end too (similar to my 2FA plugin) and not only to the acp @Stefan-ST

**Comment by Destroy666x** [comment]
If you want to add it to front-end too, I don't see why not.

**Comment by JN-Jones** [comment]
Any objections against the way my plugin works? The code will be optimized of course as I don't need to relay on hooks but the general way. (Recovery codes will be added too but they aren't included in the plugin atm)

**Comment by Stefan-ST** [comment]
@JN-Jones I think 2FA is not needed for the front-end because 99% of the forum users won't use it and we mainly want to secure the back-end.
However if you already have a solution that protects both, why not.

**Comment by JN-Jones** [comment]
I'd use the solution from my plugin: https://github.com/JN-Jones/MyBB-2FA
It displays the QR Code in the UCP and sets a new column to the secret. If the secret isn't empty the login page (frontend and acp) will redirect to a new page where the token should be entered. The "block" part of the plugin will be modified of course. The login part is nearly the same for both.
I need to look into an issue with Google Authenticator someone reported first but noone else had any problems with the implementation so far.

**Comment by Sama34** [comment]
I agree it should be implemented in both areas considering you already have most of the code anyways.

**Comment by JN-Jones** [comment]
Ok, I've a made something for the frontend, however there's one issue: I need to save whether or not the 2FA challenge has been entered for the current session. But as MyBB only saves one session per user I'd either need to save it as a cookie (problem: user can change it) or the value may be screwed when the same user is logged in from two pc's (either the user needs to reenter a new code on every page visit or one of the two sessions is automatically validated though it shouldn't).

I can leave it as it is in my plugin (one session is probably validated) or only implement it to the acp where multiple sessions are saved. I'd go for the second as it doesn't make sense to implement it when it's easy to break.

**Comment by Sama34** [comment]
So we are presented with session l;imitations in the front-end? We can leave it for the ACP at first then and then over time implemented in the front-end, which would mean to modify the sessions system on it too.

**Comment by JN-Jones** [comment]
Modifying wouldn't help, we'd need nearly a complete rewrite :P

**Comment by JN-Jones** [comment]
Todo:

- [ ] Test with Google Authenticator
- [ ] Add recovery codes
- [ ] Log enabling/disabling (is that really necessary?)

**Comment by Sama34** [comment]
> Log enabling/disabling (is that really necessary?)

Since it would only apply to the ACP, yes it wouldn't hurt having it.

**Comment by JN-Jones** [comment]
The functionality has been added, only testing is needed. I've used Authy as app, however many people use Google Authenticator so that app should be tested too. Also the upgrade/installation process hasn't been tested.

**Comment by Sama34** [comment]
I can't find your PR :P

**Comment by ATofighi** [comment]
@Sama34 #1777

**Comment by JN-Jones** [comment]
I didn't want to create a PR before testing it... Also a PR isn't needed at all for testing as you can simply go to my repo, select the branch and download it

**Comment by Sama34** [comment]
Alright, I just noted some issues without testing.

**Comment by PaulBender** [comment]
Fixed in #1777

**Comment by Cu8eR** [comment]
@JN-Jones - what about "remember this PC" option - no codes are needed in future (for example for another 14 days)

**Comment by Sama34** [comment]
@Cu8eR please open a new issue with your suggestion.
