### ISSUE TITLE
username's should be htmlspecialchars_uni()'d

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1631]
#1304

Functions that need revision:
- [ ] format_name
- [ ] build_profile_link
- [ ] log_admin_action
- [ ] log_moderation_action or whatever

Special attention to:
- [ ] parser
- [ ] build_postbit
- [ ] templates
- [ ] cache class

**Comment by Sama34** [comment]
@mybb/developers @Destroy666x @JN-Jones @

This is quite a big change, many places were usernames are used. Also, is http://www.mybb.com/mybb_team.xml already sanitazed? If so, we also need to sanitaze names in the core. Which I did.

@JN-Jones I noticed the following:
https://github.com/mybb/mybb/blob/feature/admin/modules/home/preferences.php#L152

Wouldn't there be any issue if the user changes his username? Because IIRC there is no warn about this anywhere.

E-mail meesages were not affected.

**Comment by Sama34** [comment]
Hopefully this is done. Just need extensive testing.

**Comment by JN-Jones** [comment]
It's only the name of the QR code displayed in the 2FA app and isn't used to generate the code. It'll simply show your old username in the app (if you haven't changed it there).

**Comment by Destroy666x** [comment]
Reopening so that we don't forget about the  change that needs to be pushed

**Comment by xykul** [comment]
admin/modules/user/users.php 1363 and 3848 lines of code are incorrect.
**Sample:**
line 1363
`$form_container = new FormContainer($lang->signature.': '.htmlspecialchars_uni($user['username']));`
line 3848
`$user['view']['username'] != htmlspecialchars_uni($user['view']['username']);`

**Comment by PaulBender** [comment]
I can confirm both issues.

There are also a few places that usernames aren't being sanitized. Reopening.

**Comment by Sama34** [comment]
So is there a issue with what was modified or are there instances where names are not being sanitized only?

**Comment by Destroy666x** [comment]
Well, if you take a look at your PR, both lines were modified by you. One of them has a syntax error, not sure about the other.
