### ISSUE TITLE
Remove Attachment not working without refresh

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1647]
To reproduce...

1. Create a new thread
2. Upload a file and hit "Add attachment"
3. File will be added and shown in the attachments list
4. Click "Remove Attachment"
5. Nothing happens
6. Click Preview post, the attachment is gone

Original thread: [Remove Attachment not working without refresh](http://community.mybb.com/thread-163103.html)

**Comment by Destroy666x** [comment]
@Sama34, did you start working on it? Because I have a ready fix to push (thought I assigned myself but apparently not).

**Comment by Sama34** [comment]
I don't know why I assigned myself at this to be honest. JS (jQuery, etc) is my weakness. I was probably confident to be able to fix this at the time.

Anyways, feel free to take this or any other of my assigned issues that do not hold the `s:fixed` or `s:in-progress` labels.

**Comment by Sama34** [comment]
Just remember to assign those to you and as a suggestion make sure to use of the before mentioned labels to identify that there is work being done.

**Comment by Cu8eR** [comment]
@Destroy666x - do you still have a PR ready for this issue as you mentioned above? thx

**Comment by Destroy666x** [comment]
Not anymore, lost these changes/files so feel free to push before I redo it.

**Comment by Cu8eR** [comment]
@Destroy666x - Unfortunately my fix is not working. I am not good at JS, I am a beginner but I do my best.

If you have time, please make a PR, if not I will try to fix my PR but I cannot promise anything

**Comment by Stefan-ST** [comment]
I have a fix in mind but it probably doesn't work with all custom themes. Refreshing the page may be the best option.

**Comment by ATofighi** [comment]
my idea is change the `Post.removeAttachment` to this code:
```js
	function(aid)
	{
		var $row = $(event.target).parent().parent();
		$.prompt(removeattach_confirm, {
			buttons:[
					{title: yes_confirm, value: true},
					{title: no_confirm, value: false}
			],
			submit: function(e,v,m,f){
				if(v == true)
				{
					$row.hide();
					document.input.attachmentaid.value = aid;
					document.input.attachmentact.value = "remove";
					
					$("form#editpost").submit();
				}
				else
				{
					document.input.attachmentaid.value = 0;
					document.input.attachmentact.value = "";
				}
			}
		});
		
		return false;
	};
```

**Comment by Stefan-ST** [comment]
This probably works unless the themes has replaced the table with something else. And it always assumes removing actually worked.

**Comment by Destroy666x** [comment]
AFAIR `$("form#editpost").submit();` doesn't work in some browsers as I mentioned above.

**Comment by Cu8eR** [comment]
@Destroy666x - what was your idea in your old PR?

**Comment by Destroy666x** [comment]
The idea was similar to the above, but the form also needs to be edited so that it submits correctly.

**Comment by Sama34** [comment]
If the page is refreshed upon adding it _should be_ upon removing. Otherwise it is inconsistent.

That plus being the easier solution.

**Comment by Destroy666x** [comment]
I think that would be a step behind in times when people expect fully AJAXified drop file uploads, I don't see a reason to revert this instead of fixing it, I don't think it would be much easier either.

**Comment by Sama34** [comment]
It would be nice if AJAX was added to the addition when fixing this with that method, yes.

**Comment by Cu8eR** [comment]
Yes, I agree with both of you. AJAX would be really nice addition
