### ISSUE TITLE
xmlhttp improvements

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1653]
- [ ] as mentioned here: https://github.com/mybb/mybb/pull/1649 I'm nearly sure `username_exists` isn't used anywhere so it can be removed. Correct me if I'm wrong. @mybb/developers 
- [ ] there is username AJAX validation during registration. but duplicate/invalid Email validation doesn't exist in xmlhttp.php, so an inline error is printed instead after submitting the form. Would be nice to add it.
- [ ] passwords are checked against username/Email for being the same (insecure), not by AJAX though - another thing that would be nice to add
- [ ] `get_users` action lists all users that begin with a search term, but would be nice to check all users that contain it instead. http://community.mybb.com/thread-168070-post-1145266.html#pid1145266 + possibly return UIDs (which are already selected in queries) if noone disagrees (?): http://community.mybb.com/thread-171952.html

**Comment by WildcardSearch** [comment]
@Destroy666x 

> I'm nearly sure `username_exists` isn't used anywhere
It is only used in the upgrade script as far as I can tell: https://github.com/mybb/mybb/blob/5bdaafb3c84050ebdabb7217f6a53eaa9417a62a/install/upgrade.php#L188

**Comment by JordanMussi** [comment]
Fixed in #2790

**Comment by Cu8eeeR** [comment]
Great, you are on fire! Thank you!!!!

**Comment by WildcardSearch** [comment]
In my opinion `username_exists` should be left as it is a part of the API-- removing it could break plugins dependent on it.
