### ISSUE TITLE
View online list shows buddy list popup link

### ISSUE THREAD

**Issue by ATofighi** [mybb/mybb#1673]
>When viewing the online list it shows "Viewing Buddy List".
I don't think this is intended as you see the raw content that's meant to be shown in a popup window: 

Original thread: [View online list shows buddy list popup link](http://community.mybb.com/thread-163647.html)

**Comment by Cu8eR** [comment]
@Destroy666x - do you plan to fix this for 1.8.4? Thank you

**Comment by PirataNervo** [comment]
This is set to 1.8.5 so only 1.8.5.

**Comment by Cu8eR** [comment]
@PirataNervo if Destroy doenst have time I can make a PR. It is a small change

**Comment by PirataNervo** [comment]
Feel free to create a PR then :) we'd appreciate it
