### ISSUE TITLE
Custom MyCodes not accepted by editor.

### ISSUE THREAD

**Issue by ATofighi** [mybb/mybb#1674]
> Create a new custom MyCode:
> Regular Expression:
> 
> ``` regex
> \[code=gist\](.*?)\[/code\]
> ```
> 
> Now try your new MyCode in a new thread/post. The code gets replaced by a common `[code]` MyCode.
> 
> Full or source editor doesn't makes the difference it seems.

Original thread: [Custom MyCodes not accepted by editor.](http://community.mybb.com/thread-163255.html)

**Comment by Sama34** [comment]
> Alternatively, I may change SCE such that there's a "get" for the a tag definition (both BBCode and WYSIWYG mode) that allows changes to be applied to the default settings. Does that suffice?

The thing is, the tags mentioned ([code=anything]) are not declared anywhere regarding SCE's JS code or similar. Will it still work? I'm not very familiar about how the editor is implemented in MyBB @mybb/developers @ATofighi @JN-Jones @Destroy666x

**Comment by brunoais** [comment]
If you want your own take on how `[code]` should work, then just make your own tag :).

**Comment by martec** [comment]
@brunoais 
if made to all hr, b, i, s, u etc...  The size of bbcodes_sceditor.js will become very big.
It´s something that we want avoid...

**Comment by Sama34** [comment]
I suppose this is not to be fixed then, new codes should be added to the script dynamically but MyBB doesn't offers such feature unfortunately.

**Comment by brunoais** [comment]
SCE's tag definition is also long.
Changing how SCE works on that is NG for me. If you want it to be changed ask Sam. I won't do it.

**Comment by martec** [comment]
@brunoais 

but not planned to add sceditor in phpbb too?
what i remember, phpbb too has same feature of mycode...
and if user create something this in acp [code={TEXT1}]{TEXT2}[/code] not will has same problem too?

**Comment by brunoais** [comment]
In phpBB, I will make all custom BBCode on SCE. I won't use any of the original code for processing BBCode.

**Comment by martec** [comment]
@Sama34 
i will try fix this...
sceditor 1.4.6 and 1.4.7 or above is modular...
so i will edit bbcode plugin https://github.com/samclarke/SCEditor/blob/master/src/plugins/bbcode.js

and this change will make better, because not need more create duplicated tags.

One question @mybb/developers @Destroy666x best kept or remove tags not used in mybb like youtube, center, right, justify, superscript, subscript, table, tr, th, td  tags?

**Comment by brunoais** [comment]
@martec
You could just change the BBCode's definitions so that the parameters object is read and stored in an HTML parameter and then loaded back into the BBCode when changing back.

I still find it weird, though, why an undefined BBCode parameter should be accepted...

**Comment by martec** [comment]
@brunoais 

what we want return plain text when has description...
so need rewrite all tags...

**Comment by JN-Jones** [comment]
@brunoais @mybb/developers As this issue and the one over at the SCE repo are still open I'd like to have a descision whether this is an issue on our side or on yours (so who's the one who should fix this?)

**Comment by brunoais** [comment]
It's not me to decide, actually. I may have been added as a developer and I may have been more active but it is actually @samclarke who can answer that question.

**Comment by JN-Jones** [comment]
@samclarke would be nice to get your input on this.

**Comment by samclarke** [comment]
In attempt to be more forgiving and allow invalid BBCodes the default handlers just throw away any attributes they understand. Originally the idea was for people to create custom BBCode handlers for any BBCodes they want to use with the editor so that behaviour wouldn't be a problem.

Thinking about it though that behaviour is probably not the best, at least for the default handlers. I've created an issue (samclarke/SCEditor#544) to change them to treat any BBCode with unknown attributes as unknown and leave them as is.

**Comment by JN-Jones** [comment]
As per @samclarke this is going to be fixed in one of the future SCEditor releases. However he also suggested to use something similar to this function in the meantime @mybb/developers 
```js
function ignoreIfHasAttributes(bbcode) {
		var plugin = $.sceditor.plugins.bbcode;
		var format = plugin.bbcode.get(bbcode).html;

		plugin.bbcode.set(bbcode, {
			html: function (token, attrs, content) {
				console.log(token, attrs)
				// Has attributes so ignore
				if (!$.isEmptyObject(attrs)) {
					// A <br /> is appended to the end of the contents of block level tags
					content = content.replace(/<br \/>$/, '');
					return token.val + content + (token.closing ? token.closing.val : '');
				}

				if (typeof format === 'string') {
					// Set content to {0} for string formats
					attrs['0'] = content;
					return plugin.formatBBCodeString(format, attrs);
				} else {
					return format.call(this, token, token.attrs, content);
				}
			}
		});
	}

	ignoreIfHasAttributes('code');
	ignoreIfHasAttributes('b');
	// etc.
```
