### ISSUE TITLE
Outdated CHMOD wiki link (and more docs.mybb.com links)

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1729]
http://community.mybb.com/thread-164820-post-1128055.html#pid1128055

The link here is wrong:
https://github.com/mybb/mybb/blob/feature/admin/modules/tools/system_health.php#L915

EDIT: actually, there are many more links to update if you grep `docs.mybb.com`. And some docs are not even available (they need to be worked on but noone has decided to take care of them yet)... So moving to 1.8.5.

EDIT2: I listem them in https://github.com/mybb/docs.mybb.com/issues/61

**Comment by andrewjs18** [comment]
some links have been updated per this PR: https://github.com/mybb/mybb/pull/2453

**Comment by andrewjs18** [comment]
this should be all fixed now.

closing!
