### ISSUE TITLE
"Forum Permissions" group "Moderation" click disappearing

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1735]
1-)  Forum Management &gt; Forum =&gt; Options =&gt; Permisions &gt; Registered Group =&gt; Set Custom Permissions &gt; Moderation -&gt;  Put click bay =&gt; Save Forum Permisions
http://oi57.tinypic.com/21erx1i.jpg

2-) Bottom of the page "Save Forum Permissions" 
http://oi58.tinypic.com/25tc87c.jpg
or "Edit Forum &gt; Save Forum"
http://oi58.tinypic.com/1zx4a4l.jpg

3-) Let's turn our permissions again..
http://oi62.tinypic.com/11bhibp.jpg

You will see that clicks have disappeared.

Original thread: ["Forum Permissions" group "Moderation" click disappearing](http://community.mybb.com/thread-163319.html)

**Comment by Sama34** [comment]
Are the boxes just lacking the proper select marking or are permissions not saved at all?

**Comment by Destroy666x** [comment]
If you save them in the modal and refresh the whole page - they're ok.
If you save them in the modal and then save all permissions on the bottom of the page - they're reset.

Happens only with these 4 Moderation permissions.

**Comment by Destroy666x** [comment]
The only thing I could find is that they're missing from a variable in install/upgrade files:
https://github.com/mybb/mybb/blob/21c2697a4594178ad5de9f3fabf00fcce87f66cf/install/index.php#L69
https://github.com/mybb/mybb/blob/3f5d5caf8d5a7709550c1847bad0777252cd9577/install/upgrade.php#L145
Should be added there.

EDIT: and all columns except these 4 have `can` at the beginning of their name. But the `strpos` checks seem to consider it: https://github.com/mybb/mybb/blob/feature/admin/modules/forum/management.php#L496
so no idea what's the issue. But the columns should have followed the `can...` naming pattern in the first place.
