### ISSUE TITLE
Can view/reply only own threads and guests

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1758]
As @ATofighi mentioned here: https://github.com/mybb/mybb/pull/1574 if you turn that permission on for guests, they will be able to view/reply to all threads regardless of it due to 0 UID matching the `$thread['uid']`.

Not sure what we should do here. Probably either:
a) check the IP of the 1st post
b) hide all threads for guests when the 1st permission is enabled for them. And the reply buttons if the 2nd is enabled.
c) hide these permissions for the guest group

@mybb/developers @JN-Jones

**Comment by Sama34** [comment]
IP is not a reliable method of user authentication. Those permissions (to reply, edit, delete, etc.) should be ignored for guests.

**Comment by Cu8eR** [comment]
@Sama34 - I agree, IP check is not a good method

**Comment by Destroy666x** [comment]
I think b) is the best too. Maybe combined with c) but we would have to do that for all fields which are unavailable for guests.

**Comment by Sama34** [comment]
What do you mean to "hide all threads"? So if "Can post threads?" is on for guest all threads should be hidden?

**Comment by effone** [comment]
Related: https://github.com/mybb/mybb/issues/2058

**Comment by Sama34** [comment]
I think the use of user features (delete, edit, etc) should be based on the availability of a `UID`.

**Comment by Eldenroot** [comment]
I agree - this is changed in this PR - https://github.com/mybb/mybb/pull/4072 - it removes the redundant permissions for guests.

I hope that @Ben-MyBB will finish the upgrade script for 1.8.27

**Comment by Sama34** [comment]
Fixed by #4353
