### ISSUE TITLE
Deprecate update_password

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1760]
> MyBB has update_password in ./inc/functions_user.php, which is only used to update a user's password when it is reset.

> This should be deprecated and the user datahandler should be used instead, as is standard elsewhere in MyBB where user fields are updated.

http://community.mybb.com/thread-165506.html

**Comment by tommm** [comment]
@Sama34 do you intend to work on this?

**Comment by Sama34** [comment]
Feel free to work on it if you please to, I will finish all of my 1.8.4 milestone issues before working on any other (1.8.5).
