### ISSUE TITLE
Invalid subscribed forum icon code

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1762]
Not sure how it hasn't been noticed yet, but the subscribed forum icon in the User CP should be changed to the sprite code, now nothing is displayed unless you have old icons uploaded.

**Comment by Stefan-ST** [comment]
@Destroy666x This actually shouldn't have been merged yet (template version code was 1805). ;)

**Comment by Destroy666x** [comment]
I don't see any reason to create a one-line PR for next version when we still have 2 weeks till release. Should've been more careful with the numbers though, didn't notice 5 at the end, I'll change it here: https://github.com/mybb/mybb/pull/1616
