### ISSUE TITLE
HTTP status codes for errors

### ISSUE THREAD

**Issue by rob006** [mybb/mybb#1764]
Why MyBB not use http status codes for handle 404 and 403 errors? When I try to display non existing topic, i got error page with 200 status code, so it is like a regular page for google spider.

**Comment by Cu8eR** [comment]
Please read: https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md

**Comment by rob006** [comment]
I read. I also read this: http://community.mybb.com/announcement-22.html
> Advanced users may also report issues directly on GitHub if they prefer.

**Comment by Stefan-ST** [comment]
This is not a bug so please use the appropriate forum for suggestions: http://community.mybb.com/forum-158.html
Thanks!
