### ISSUE TITLE
The type of file that you attached is not allowed.

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1765]
I'm using the latest GitHub download-able pack and the following appears when trying to upload an allowed file type as attachment to a post.

> The type of file that you attached is not allowed. Please remove the attachment or choose a different type.

**Comment by Stefan-ST** [comment]
@Sama34 It would be helpful to know which pull request caused the problem. ;)

**Comment by Destroy666x** [comment]
I'm quite sure it's caused by the `unserialize()` limits too (the default array is quite big), check in the Cache Manager if the `attachtypes` cache is ok.

**Comment by ATofighi** [comment]
I change the MAX_SERIALIZED_INPUT_LENGTH to 16777215 and test it, it's works good...

**Comment by ATofighi** [comment]
#1733

**Comment by Sama34** [comment]
Funny I didn't thought about that being the issue seeing I checked that issue one hour before..
