### ISSUE TITLE
Future Timestamps are always displayed as "in XXXXX minutes"

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1780]
Currently there is a problem with displaying future timestamps in MyBB.

The only location where future timestamps seem to be displayed in "relative" format, is when a user opens his usercp and sees his own warning end times. Currently it will always be displayed in minutes, even if it is months in the future.

This will only happen in usercp.php reviewing your own warnings, not in warnings.php, where e.g. moderators would check the warnings of a user (there the time is always displayed in the "normal" date/time format that was used in MyBB 1.6.

The problem is the logic for the new relative timestamp format and very easy to fix.

Here is a matching pull request that fixes the problem with very small changes:

https://github.com/mybb/mybb/pull/1779

Original thread: [Future Timestamps are always displayed as "in XXXXX minutes"](http://community.mybb.com/thread-166148.html)

**Comment by Sama34** [comment]
Shouldn't warnings and similar use the nice_time funtion used for expiration dates, etc?

**Comment by Destroy666x** [comment]
@Sama34, I guess so, but that's another issue not connected with this `my_date()` bug. So I'd probably open another ticket for that.
