### ISSUE TITLE
Time of posting changed after DST went back to standard time

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1781]
Hi,

while being on DST the time of posting was displayed correctly.
After having switched back to standard time last weekend, the posting time of these posts is off by one hour (-1).

Automatic DST correction is active in admin settings and user CP.
Server time is correct.

It seems to affect only posts that were made during DST.

[attachment=32897]

Original thread: [Time of posting changed after DST went back to standard time](http://community.mybb.com/thread-162091.html)

**Comment by Sama34** [comment]
Why was this added to the 1.8.4 milestone?

**Comment by Destroy666x** [comment]
Because there is a PR with 2 lines which shouldn't be too hard to test. And if noone will check it before 1.8.4, what's the problem of moving it to 1.8.5?

**Comment by Sama34** [comment]
It delays the process of 1.8.4 work. You know the expected internal ETA and the list of opened issues never seems to decrease IMO.

We should move anything that is not critical or lacks a PR to 1.8.5 and start testing the script.

**Comment by Destroy666x** [comment]
There's still a week and creating an issue doesn't delay anything if it's not checked by anyone. Unless its existence and milestone influence you in any way other than discussing this now, which is redundant since if you feel it's not serious (I wouldn't say that displaying wrong time in some cases is not serious, but that's just my opinion), you can simply do 2 mouse clicks to move it to 1.8.5. That's all what needs to be done.

**Comment by Stefan-ST** [comment]
Closing this because we haven't found a solution to this problem.
