### ISSUE TITLE
Unnecessary datecut param in forumdisplay.php

### ISSUE THREAD

**Issue by zingaburga** [mybb/mybb#1785]
MyBB seems to always stick in the datecut parameter on paged links for forumdisplay.

Example: http://community.mybb.com/forum-176.html
The link for page 2 is: http://community.mybb.com/forum-176-page-2.html?datecut=9999

Not a big deal, but I don't recall MyBB 1.6.x doing this.

Fix is probably along the lines of finding:

	if($datecut > 0)

And replacing with

	if($datecut > 0 && $datecut != 9999)

Thanks

**Comment by Stefan-ST** [comment]
I've noticed that, too, but apparently forgot to create a ticket about it.

**Comment by Stefan-ST** [comment]
If someone wants to have the fix in 1.8.4, just merge it. ;)
