### ISSUE TITLE
Weird global.php is_super_admin() check

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1789]
https://github.com/mybb/mybb/blob/feature/global.php#L561 - any reason we're checking whether undefined `$recipient['uid']` is a super admin? Should probably be `$mybb->user['uid']`, correct me if I'm missing something.

**Comment by JN-Jones** [comment]
`$recipient` isn't defined at that point anyways. However we have the old problem again: What is a superadmin? IIRC we decided that it shouldn't be possible to edit a superadmin and that they don't have any other power. That'd mean the whole check is wrong at that place.

**Comment by Destroy666x** [comment]
> `$recipient` isn't defined at that point anyways

Yeah, that's why this issue was created.

> IIRC we decided that it shouldn't be possible to edit a superadmin and that they don't have any other power.

I'm not sure if we decided that, they do have other powers already. For example, in ACP they can do everything regardless of permissions, check: http://community.mybb.com/thread-161705.html. Since this code checks ACP permissions, I believe we should leave it for consistency.

**Comment by Sama34** [comment]
Super admins have absolute power in the ACP however in the front-end there may be some inconsistencies.
