### ISSUE TITLE
Expcolimage in Board Statistic

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#1790]
Basically, this is not important but slightly disturbing. In this image --&gt; http://prntscr.com/5xllhq if I click [-], Board statistic will be slide up. It's work fine.Expcolimage will show [+]. 
And when I refresh the page with board statistic still slide up, it's work fine too. 
The problem is when my cursor pointing to expcolimage after refresh (still slide up), it will show [-] should be to [+]. 
It's happened in this forum too.

Original thread: [Expcolimage in Board Statistic](http://community.mybb.com/thread-166219.html)

**Comment by PaulBender** [comment]
Also happen with the Quick Reply expcolimage.

**Comment by Destroy666x** [comment]
^ And thread notes.

**Comment by JN-Jones** [comment]
@Destroy666x This should be a fairly small change, can you take a look or unassign yourself?
