### ISSUE TITLE
Random generated password can throw error

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#1793]
When you register and sending a random password is selected it's possible that the password is not accepted.
The random password has always 8 chars and is never complex however there will be an error if you require a longer or a complex password. Since there is no way to chose another password it's impossible to register.
```php
$mybb->input['password'] = random_str();
```

**Comment by Devilshakerz** [comment]
> and is never complex

Are you sure? `random_str()`'s set includes digits and uppercase & lowercase letters, which meets the password complexity check, but not *always*.

IMO in terms of generating the password, the complexity check should be skipped in that case - the requirements are there to ensure that people will use strong passwords, and the MyBB's proposition is purely random and cryptographically secure (ensuring the passwords meet the requirement would require a more complex algorithm, and generating them till one fits would be silly).

The password length is correct on reset: https://github.com/mybb/mybb/blob/feature/member.php#L1594 and the same mechanism could be used on registration.

**Comment by Stefan-ST** [comment]
@Devilshakerz You are right but it can also be too long or too short which makes registrations impossible.

**Comment by Destroy666x** [comment]
> generating them till one fits would be silly

No need to generate them till they fit. I guess we could also:
1. If the complex passwords setting is enabled, check the count of uppercase/lowercase/numbers in the generated password and assign results to 3 variables - should be simple and very quick with 3 `preg_replace()`s and `strlen()`s. 
2.Then use a simple loop to check each count. In case any of them is 0, compare 2 other counts and replace the first character in the generated password that matches the character set that has higher count with a random character, otherwise do nothing. Should also be fast.

**Comment by Devilshakerz** [comment]
>as for the length, I think it should be a number between minimum/maximum

That would generate 30-character long strings, or even longer if the admin has set a higher limit (as there is no point in limiting the password length), which is somewhat inconvenient.

A second parameter will have to be added to `random_str()` to indicate the characters sets - I suggest an array like `array('digits', 'lowercase', 'uppercase')`.

**Comment by Stefan-ST** [comment]
> BTW, just noticed, is there any reason  0  char is skipped here? https://github.com/mybb/mybb/blob/feature/inc/functions.php#L2941

@Destroy666x Probably to avoid confusion with O.

Not checking generated passwords is probably easier. They are meant to be changed anyway.

**Comment by ATofighi** [comment]
I change the random_str to make complex passwords.
https://gist.github.com/ATofighi/2afd730cab57e0612f5e

**Comment by Stefan-ST** [comment]
> Not checking generated passwords is probably easier. They are meant to be changed anyway.

**Comment by Devilshakerz** [comment]
@ATofighi your code is generating strings till one fits; the method described by Destroy666x seems fine (if anything).

>Probably to avoid confusion with O.

How about adding "0" to the character pool? That function isn't being used for passwords only, and I don't think it's that much of a problem anyway.

**Comment by ATofighi** [comment]
@Stefan-ST it's easier but Is it better?

**Comment by Stefan-ST** [comment]
@Devilshakerz
> How about adding "0" to the character pool? That function isn't being used for passwords only, and I don't think it's that much of a problem anyway.

That will result in challenging captchas... ;)

**Comment by Devilshakerz** [comment]
>That will result in challenging captchas... ;)

The MyBB's native CAPTCHA could interpret "0" as "O" then.

**Comment by ATofighi** [comment]
@Stefan-ST you're right.

**Comment by Destroy666x** [comment]
> That will result in challenging captchas... ;)

I didn't know that 0 is not available for random strings until I made that comment, so I often typed it in for captchas with O and always had an error then. Most users don't know that fact either, so I don't think it would make it harder (still 50/50 chance to guess if it's 0 or O).

> A password with 8 completely random chars is probably secure enough for a new account, isn't it?

You're right, it is secure enough, but that doesn't make it consistent with the setting. And admins may turn it on for example for integration with other software that requires small/big letter and a number too. Who knows. So I still think we should make the generated password compatible with the setting, shouldn't be much harder.

And the PR will have to be updated anyways after https://github.com/mybb/mybb/pull/1850 gets merged.
