### ISSUE TITLE
Delayed moderation - time bug

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1796]
I use 24H format in my forum. There is a problem with time in delayed moderation option. 

pm/am is shown. There should be 22:16

There should be a selector for time (for hours and minutes) - same like for date. It would be better

Another problem: problem with time in moderation - forum time is 23:16 (GTM+1) but delayed moderation automaticaly uses -1 hour time. 

Original thread: [Delayed moderation - time bug](http://community.mybb.com/thread-165257.html)

**Comment by dequeues** [comment]
Merged in #1795
