### ISSUE TITLE
Weird IN_PORTAL checks

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1799]
This code is invalid: https://github.com/mybb/mybb/blob/feature/inc/functions.php#L4005 considering that the attachment icon may point to an external site.

Also, why is this only applied to attachment icons? Can't find any other IN_PORTAL checks except the 2 in that function.

**Comment by Sama34** [comment]
IIRC this also applies for smiles with the `IN_ARCHIVE` constant.

**Comment by Sama34** [comment]
IIRC post smilies should also be checked.
