### ISSUE TITLE
Wrong User On Get PM IP Address

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1802]
When pressing on the "IP Address: Logged" link, a page will open and you will be able to see what is the IP address.
However, it will show the wrong user the IP address belongs to. It will show the viewer's username instead of the owner of the IP address.

The bug is in moderation.php in case "getpmip".

PHP Code:
&#36;user&nbsp;=&nbsp;get_user(&#36;pm['uid']);&nbsp;

This code will always have the viewer of the PM.
It should be 'fromid'.

Original thread: [Wrong User On Get PM IP Address](http://community.mybb.com/thread-166436.html)

**Comment by PaulBender** [comment]
Fixed in #1671
