### ISSUE TITLE
Disabled MyCode SCEeditor inconsistency

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1803]
When MyCodes are disabled for PMs in settings:
Send new PM - SCEditor is hidden

When MyCodes are disabled for signatures in settings:
ACP edit user's signature - SCEditor is hidden
User CP Edit Signature - SCEditor is shown, it should be hidden too

**Comment by Sama34** [comment]
> Send new PM - SCEditor is hidden

I assume this is correct behavior?

**Comment by Destroy666x** [comment]
Yes.

**Comment by Ben-MyBB** [comment]
This still seems to be a valid issue @effone
