### ISSUE TITLE
[1.6.X] MyCode Bug

### ISSUE THREAD

**Issue by Kapsonfire** [mybb/mybb#1826]
I made a MyCode in Adminpanel
`\[blizzquote\](.*?)\[/blizzquote\]`
to be replaced with
`<cite class="blizzquote"><p>$1</p></cite>`

On normal Forumview it's replaced correctly
On Portalview (portal.php) it's broken and the given html code is following
`<cite class="blizzquote"></cite><p>Text</p>`

When i change the `<p>` to `<span>` it's working correctly

**Comment by Destroy666x** [comment]
1.6 development is closed, only security fixes are applied. If you can reproduce it in 1.8 too, feel free to open a thread on our forum: http://community.mybb.com/forum-157.html
