### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1827]
https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md - 1.6 bugs shouldn't be reported anymore and the linked forum is closed, so the info should be updated.

**Comment by Stefan-ST** [comment]
@Destroy666x You can just update it without a ticket or a pull request. The file isn't part of releases anyway. ;)

**Comment by Destroy666x** [comment]
Well, I'm not working on it atm
