### ISSUE TITLE
Videos and images forum settings not respected by SCEditor

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1828]
If you disable videos/images in a forum, they can still be used in SCEditor.

The solution is simple - pass these 2 forum settings as parameters just like it's done with smilies.

EDIT: same applies to signatures (images) and PMs (images and videos) controlled by settings.

**Comment by Ben-MyBB** [comment]
It doesn't seem this is a valid issue anymore. When having the setting turned off it un-formats the code and does not directly embed the img/video tag.
