### ISSUE TITLE
Avatars set via ACP are not pushed to CDN

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#1829]
http://community.mybb.com/thread-165704-post-1138984.html#pid1138984

Changing a user avatar via the ACP does not result in the new avatar being uploaded to the CDN if one is specified.

**Comment by Cu8eR** [comment]
https://github.com/mybb/mybb/issues/1054

**Comment by Destroy666x** [comment]
Closing since it's duplicate.

**Comment by Sama34** [comment]
Yes it may be related, the original issue is about the ACP not using the CDN at all IIRC.

**Comment by euantorano** [comment]
THis is a separate issue, so I'll re-open this and work on it.

**Comment by euantorano** [comment]
I've just tested this locally, and an avatar uploaded via the ACP was pushed to the CDN fine. The ACP uses the `upload_avatar` function, which calls `upload_file`, which runs `copy_file_to_cdn`.

Can anybody replicate this issue on 1.8.8? @mybb/sqa

**Comment by effone** [comment]
@euantorano I have checked this few times now. I can't replicate. avatar going to CDN smooth.
This should be closed.

**Comment by Sama34** [comment]
Din't he mean when using URL?
