### ISSUE TITLE
Urgent: Warning System Throwing SQL Errors

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1831]
I'm running a mybb forum on localhost and have setup quite the system; however, the warning system is super bugged right now.

The first and major bug is that it throws an SQL error if you try to ban a user with the warning system by stating that you didn't state a display group.

SQL Version: MySQLi 5.6.14
Mybb Version: 1.8.3
PHP Version: 5.6.3

Also, with my version of MySQL, most plugins I have to manually edit due to the use of null values for sid.

I also got an SQL error for length but I can't remember if it was for time of post suspension or for expiration time… Both choices were never/permanent

Original thread: [Urgent: Warning System Throwing SQL Errors](http://community.mybb.com/thread-166929.html)

**Comment by Ircher** [comment]
I made the changes stated in the thread to the file, and it seems to work

**Comment by Cu8eR** [comment]
@Ircher - good to know
@Destroy666x - is it something what needs to be fixed in 1.8.4?

**Comment by JN-Jones** [comment]
No, the milestone is 1.8.5
