### ISSUE TITLE
Useless variable in class_parser.php

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#1835]
https://github.com/mybb/mybb/blob/feature/inc/class_parser.php#L1056-L1064

```php
		if($name == $url && !empty($this->options['shorten_urls']))
		{
			if(my_strlen($url) > 55)
			{
				$name = htmlspecialchars_decode($name);
				$name = my_substr($url, 0, 40)."...".my_substr($url, -10);
				$name = htmlspecialchars_uni($name);
			}
		}
```

The `htmlspecialchars_decode` call is useless as it get's overwritten anyways in the next line.

**Comment by ATofighi** [comment]
@Stefan-ST https://github.com/mybb/mybb/commit/53ff27f8e857cae7a37208bacd0b24e8ca38c5a5

**Comment by Destroy666x** [comment]
It's used to cut the URL correctly with `my_substr()`, otherwise it would count the encoded characters and possibly break them. So I think it's valid and the issue should be closed.

**Comment by Stefan-ST** [comment]
I think it should be:
```php
$name = my_substr($name, 0, 40)."...".my_substr($name, -10);
```

**Comment by Destroy666x** [comment]
Ah yes, wrong variable is used in that line.

**Comment by Sama34** [comment]
And shouldn't the decode be before the if check if that was the case anyways?

**Comment by Stefan-ST** [comment]
@Sama34 Why? It is encoded again after shortening the url.

**Comment by Sama34** [comment]
> @Sama34 Why? It is encoded again after shortening the url.

> It's used to cut the URL correctly with my_substr(), otherwise it would count the encoded characters and possibly break them in the middle

The length of the url is counted in the if character first.

With the current code the url may not need to be shortened at all.
