### ISSUE TITLE
Birthday bug

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1838]
Month in the birthday on user profile is not shown properly. (MyBB 1.8.4). It should be 21.8.1987 not 21.n.1987 (date is set correctly in user profile)

Original thread: [Birthday bug](http://community.mybb.com/thread-167159.html)

EDIT: Confirmed, it only applies to years over 1970 so format_bdays() function is the culprit: https://github.com/mybb/mybb/blob/feature/inc/functions.php#L5238 - it doesn't support n parameter at all.
EDIT2: Not sure what's the purpose of that function and why `mktime()` and `my_date()` aren't used.. @mybb/developers

**Comment by Sama34** [comment]
IIRC `mktime` has a bug with dates which year is before 1970.
https://bugs.php.net/bug.php?id=23475
https://bugs.php.net/bug.php?id=17123

**Comment by Destroy666x** [comment]
Yes, but:
1. As I said in the EDIT above, the bug applies to years <b>after</b> 1970: https://github.com/mybb/mybb/blob/feature/member.php#L2184 - this is the only situation when the bug applies and the single place in the whole core where `format_bdays()` is used.
2. We use `fix_mktime()` for years before 1970 and it works fine because the buggy `format_bdays()` is not used there: https://github.com/mybb/mybb/blob/feature/member.php#L2191

**Comment by Sama34** [comment]
I was replying to your comment.

> why `mktime()` and `my_date()` aren't used

**Comment by Destroy666x** [comment]
Yes and I was replying to your. Since the bug is for years after 1970 I see no reason to not use `mktime()` and `my_date()` instead of `format_bdays()`

**Comment by Destroy666x** [comment]
Note that while it fixed `n` in the weird function, the admin can still enter for example `r` as the date format and it will get broken again..
