### ISSUE TITLE
Upgrade to 1.8.4 fails with SQLite

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#1840]
```SQLSTATE[HY000]: General error: 1 unrecognized token: "2fasecret"'```
SQLite/PgSQL seams not to support column names starting with a digit: http://stackoverflow.com/questions/3694276/what-are-valid-table-names-in-sqlite/3694305#3694305

http://community.mybb.com/thread-167214.html
@JN-Jones

**Comment by tommm** [comment]
A simple rename to authsecret?

**Comment by Stefan-ST** [comment]
@tommm Before the release that would have been that simple... It's nothing we can fix by replacing a file so we need a workaround for SQLite users.

**Comment by euantorano** [comment]
Use the square brackets? IIRC, it'll work the same in MySQL too.

**Comment by Destroy666x** [comment]
Brackets?

@Stefan-ST, what about releasing 1.8.5 asap with another upgrade script? In it rename the column if it exists and create it if it doesn't. And remove the wrong code from 1.8.4 upgrade. This should work.

**Comment by Stefan-ST** [comment]
@Destroy666x It depends on the extent of the fix. Releasing a new version for a few SQLite users seams a bit overkill to me in case we can provide a **feasible** workaround. I'm also not against preponing the next (security) release but it shouldn't fix just one issue.

**Comment by Destroy666x** [comment]
Well, it affect both SQLite <b>and</b> PostgreSQL users:
http://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
> SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). 
I don't think we should let them wait with upgrading, especially that 1.8.4 fixed several security issues.

**Comment by euantorano** [comment]
I agree @Destroy666x. This is a fairly major issue.

**Comment by Stefan-ST** [comment]
It is indeed a major issue and we need to provide a solution. However releasing a new version isn't the only possible solution. It may be possible to fix the 1.8.4 package for the affected users (rather ugly with conditionals for SQLite and PgSQL) or to provide a separate patched package until the next version is released. Just waiting 2 months is out of question.

**Comment by Cu8eR** [comment]
I think we could provide only a package with a patch. This patch would be incorporated into mybb for 1.8.5 release.

It is too soon for 1.8.5 - there could be more urgent or high priority bugs - wait more days, more users = more testers = more reports

**Comment by Sama34** [comment]
DB Type checking was not the best approach IMO.

**Comment by Stefan-ST** [comment]
@Sama34 Yes it wasn't meant to be used for a final solution.
