### ISSUE TITLE
PM Verification Incorrect (ignore list)

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1845]
Hi,

inc/datahandlers/pm.php

PHP Code:
  &nbsp;   &nbsp;   &nbsp;    &nbsp;&#36;ignorelist&nbsp;=&nbsp;explode(",",&nbsp;&#36;user['ignorelist']);  &nbsp;   &nbsp;   &nbsp;   &nbsp; if(!empty(&#36;ignorelist)&nbsp;&amp;&amp;&nbsp;in_array(&#36;pm['fromid'],&nbsp;&#36;ignorelist))  &nbsp;   &nbsp;   &nbsp;   &nbsp; {  &nbsp;   &nbsp;   &nbsp;   &nbsp;   &nbsp; &#36;this-&gt;set_error("recipient_is_ignoring",&nbsp;array(&#36;user['username']));  &nbsp;   &nbsp;   &nbsp;   &nbsp; }&nbsp;

That is wrong. &#36;user['ignorelist'] should be checked if it's empty before exploding it, otherwise an array will be created:

Code:
array (
     [0] =&gt;
)

At first glance there are no problems. Now look at send_pm in functions.php. &#36;fromid can be set to 0 / empty, therefore in_array(&#36;pm['fromid'], &#36;ignorelist) is true even though the ignorelist is empty.

Fix:

PHP Code:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(&#36;user['ignorelist']&nbsp;!=&nbsp;'')&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;ignorelist&nbsp;=&nbsp;explode(",",&nbsp;&#36;user['ignorelist']);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(!empty(&#36;ignorelist)&nbsp;&amp;&amp;&nbsp;in_array(&#36;pm['fromid'],&nbsp;&#36;ignorelist))&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;this-&gt;set_error("recipient_is_ignoring",&nbsp;array(&#36;user['username']));&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;

The same thing should be done to the buddy list (a few lines below).

Regards,
Diogo

Original thread: [PM Verification Incorrect (ignore list)](http://community.mybb.com/thread-167291.html)

**Comment by Cu8eR** [comment]
What about the fix which was mentioned in the thread?
