### ISSUE TITLE
fetch_array() issues

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1871]
Based on commments here: https://github.com/mybb/mybb/commit/1b8b3fe1463702f8ad4aeba142ee772aa87ca1e3#commitcomment-9796051
- [x] the interface `fetch_array()` definition uses MYSQL_ASSOC constant as default value for 2nd argument and it may be not available
- [x] SQLite doesn't support 2nd parameter changes, but PDO allows ASSOC/NUM/BOTH too, so they could be added

**Comment by Sama34** [comment]
I assume that is it?
