### ISSUE TITLE
Selecting Endless while Editing Template

### ISSUE THREAD

**Issue by Firelad97** [mybb/mybb#1872]
In template editor, once I click in text area (anywhere in text area) and it will start endlessly selecting texts when I move mouse again. Is this just me, or really a bug? It had happened to me on two computers. I don't mean click and hold while moving mouse. Just a click and it will start.

**Comment by Destroy666x** [comment]
Doesn't happen to me - please use our forums to report bugs with more details (for example browser[s] you used in this case).
