### ISSUE TITLE
Moderators can see IP address link in PMs

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#1884]
Forum Moderators can see the IP Address: Logged link in a PM even though they aren't supposed to see PM IPs.

**Comment by JoshH99** [comment]
My understanding is that we only have canviewips for moderator permissions. I don't *see* anything separate for PM IP viewing permissions.

Is there a permission I'm missing for PM IPs?

**Comment by Cu8eR** [comment]
I can confirm this. There should be separated option for this or use same value which is set for see IP in posts

**Comment by Destroy666x** [comment]
There's already Show Private Message IP Addresses, but the problem here is, IIRC, that both permission allow viewing IP.

**Comment by Cu8eeeR** [comment]
@Destroy666x - you are assigned to this issue, can you please take a look?

**Comment by effone** [comment]
I can't see the IP address link issue. Sorry.
`Show Posting IP Addresses` is not the right settings. You disable `Show Private Message IP Addresses` and the IP address will not be seen in PM.
