### ISSUE TITLE
Who Posted not considering soft deleted posts.

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1885]
The "Who Posted link" in forum display under thread replies doesn't display users if their posts have been soft deleted.

IMO if the moderator has permission to view such posts then they should be visible.

Original thread: [Who Posted not considering soft deleted posts.](http://community.mybb.com/thread-167591.html)

**Comment by Nik101010** [comment]
Imo there should be a difference between users only having soft deleted posts in the thread and users who who have 'existing' posts...

**Comment by Destroy666x** [comment]
We show unapproved + soft deleted in parentheses: https://github.com/mybb/mybb/blob/feature/forumdisplay.php#L1115 so the same could be done here.

**Comment by Sama34** [comment]
Everything that has to do with counters is confusing.
