### ISSUE TITLE
Quick login does not accept logins

### ISSUE THREAD

**Issue by GravzyIT** [mybb/mybb#1886]
When using the quick login method, the input is never accepted.
Doesn't matter is username or email is needed, it fails every time.
Normal login method works.

**Comment by Nik101010** [comment]
First of all - please read the contribution guidelines (https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md) - new issues should be reported on the community forums...

The quick login (login link at the top of every page) works fine for me... So... what do you mean with quick login? Are there any steps you can provide to reproduce this bug?

**Comment by Stefan-ST** [comment]
Closing this as it's pretty unlikely to be a bug (there would have been more complaints).

**Comment by Destroy666x** [comment]
@GravzyIT, you're either using a 1.6 theme in 1.8 or the board URL/cookies in settings are wrong. But this is a question for our support forums.
