### ISSUE TITLE
Sort threads by prefix bug

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1890]
Okay so I'm not entirely sure if this is intended or if it these are bugs.

In the plug-ins section, when I sort the threads by the 1.8 prefix it displays all threads with the 1.8 prefix. There are two issues that I noticed. There are only 6 pages of 1.8 plug-ins,  yet on the pagination it shows 42 pages. 

Second issue is that on the 7th page it displays one thread. The thread is "Becoming an Approved Developer and Modifications Website Guide." It displays only this thread for every page after page 6. 

Page 7: http://community.mybb.com/forum-102-page-7.html?prefix=28

To see what I'm talking about just look at random pages after page 6.

Original thread: [Sort threads by prefix bug](http://community.mybb.com/thread-167723.html)

EDIT: This code looks wrong: https://github.com/mybb/mybb/blob/feature/forumdisplay.php#L613-626 The first query doesn't consider any parameters at all (why?) and the 2nd query misses prefix.

**Comment by Sama34** [comment]
The first query relying on counters is for performance reasons? @Stefan-ST  I don't think that should be used.

**Comment by Destroy666x** [comment]
Performance reasons probably, but not sure if works in all cases besides the thread prefix issue.

If it does, for prefixes the simpliest fix would be to change `($datecut > 0 && $datecut != 9999)` to `($datecut > 0 && $datecut != 9999) || ($tprefix >= -2 && $tprefix != 0)`

**Comment by Sama34** [comment]
> I don't understand the `if($threadcount == 0)` part

I would assume that is a fall-back case that fixed an issue before.

> is probably the best thing to do here

I can see the performance gain from doing it this way, so I would rather do keep it.

The mistake was not to check for prefix filtering in pagination while implementing this feature. The following piece of code works for me.

```PHP
if($fpermissions['canviewthreads'] != 0)
{
	// How many posts are there?
	if($datecutsql || $useronly || $prefixsql)
	{
		$query = $db->simple_select('threads', 'COUNT(tid) AS threads', "fid='{$fid}'{$useronly}{$visibleonly}{$datecutsql}{$prefixsql}", array('limit' => 1));
		$threadcount = $db->fetch_field($query, "threads");
	}
	else
	{
		$query = $db->simple_select("forums", "threads, unapprovedthreads, deletedthreads", "fid = '{$fid}'", array('limit' => 1));
		$forum_threads = $db->fetch_array($query);
		$threadcount = $forum_threads['threads'];
		if($ismod == true)
		{
			$threadcount += $forum_threads['unapprovedthreads'] + $forum_threads['deletedthreads'];
		}

		// If we have 0 threads double check there aren't any "moved" threads
		if($threadcount == 0)
		{
			$query = $db->simple_select('threads', 'COUNT(tid) AS threads', "fid='{$fid}'{$visibleonly}", array('limit' => 1));
			$threadcount = $db->fetch_field($query, "threads");
		}
	}
}
```

**Comment by Destroy666x** [comment]
> I would assume that is a fall-back case that fixed an issue before.

Yes, but does it do anything now? It says to double check moved threads but I see no relation with moved threads. Redirects seem to be counted

If it doesn't do anything, as I said I agree that the `if` condition should be changed and the optimised code left. Also the check should be removed then because a query is wasted.
But if it does something useful, why is it checked only for 0 threads?

**Comment by Sama34** [comment]
> Yes, but does it do anything now? It says to double check moved threads but I see no relation with moved threads.

I don't know. We would need to ask the one who implemented this code.

I'm assuming the counters were expected to fail even if not related to moved threads. So the fall-back was introduced at some point.

> Also the check should be removed then because a query is wasted for empty forums.

> But if it does something useful, why is it checked only for 0 threads?

It is better to run the query when there may be `0` threads than when there may be `9999` of them (less likely the counters would result on a `0` value).

I think modifying the first `if` check is the best, lets no mess with anything else.

**Comment by Sama34** [comment]
Just noticed this also happens with xThread filtering system. It is probably the same issue so any fix applied should be checked against it too. (xThread filtering pagination worked fine in 1.6, that is why.)

**Comment by Destroy666x** [comment]
> xThread filtering pagination worked fine in 1.6, that is why

So did multiple other plugins that stopped working after releasing 1.8. I don't recall fixing any of them in the core. Because that's not how it works, plugins are adapted to software updates, not the other way round.

> so any fix applied should be checked against it too

And if were going to do that, how would that work? From what I see the only 2 ways would be either checking something XThreads-specific in this conditional too: https://github.com/mybb/mybb/blob/feature/forumdisplay.php#L606 (and introducing plugin code to core isn't a good idea) or getting rid of the optimised forums query code.

**Comment by Sama34** [comment]
Introducing a fix that wouldn't fix something that shouldn't be broken is not a fix. That is what I meant, not to adapt the core for a third party plugin to work on it.

I have seem this in the core, and I'm against it too.

Anyways, just found the issues and yes, it is xThreads that needs updating so never-mind.

**Comment by effone** [comment]
1. All those redundant checks are not at all required. The query result itself going to be filtered as per the permissions.
2. Querying to `forums` table are completely wrong as that table doesn't hold prefixes. It just hold the counts, that too not perfect / with not enough info for us to use in this case.

The coder must have thought excess while coding this part. First query without condition suffice the purpose in every scenario.

**Comment by Sama34** [comment]
I will review this. But I can't find the option to add reviewers, can you add me so I can check it later?

**Comment by effone** [comment]
You must be finding the option 'reviewer' here in issues...
Requested review from @Sama34 at PR.
https://github.com/mybb/mybb/pull/3190#event-1611469368
