### ISSUE TITLE
Avay icon don't work properly at Forum team list

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1907]
I'm not sure if this is a bug, but in posts members &amp; staffs have icons: white - offline, yellow - away, green - online.

And at Forum team list only yellow and white showing. Is it ok or it is a bug?

Original thread: [Avay icon don't work properly at Forum team list](http://community.mybb.com/thread-168349.html)

**Comment by Sama34** [comment]
I didn't notice this was assigned already n.nU
