### ISSUE TITLE
Unnecessary code in functions_post.php

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1911]
https://github.com/mybb/mybb/blob/feature/inc/functions_post.php#L323

```PHP
		$post['useravatar'] = '';
		if(isset($mybb->user['showavatars']) && $mybb->user['showavatars'] != 0 || $mybb->user['uid'] == 0)
		{
			$useravatar = format_avatar($post['avatar'], $post['avatardimensions'], $mybb->settings['postmaxavatarsize']);
			eval("\$post['useravatar'] = \"".$templates->get("postbit_avatar")."\";");
		}
		else
		{
			$post['useravatar'] = '';
		}
```

**Comment by Deeses** [comment]
This still hasn't been fixed in  1.8.5? This is the easiest fix ever, delete the else.

Why isn't this fixed in real time?

**Comment by JN-Jones** [comment]
Because we're humans and this has the lowest existing priority. Also please stop commenting on every issue with not helpful comments...

**Comment by Deeses** [comment]
JN-Jones, yes but it would take less then 5 seconds. LITERALLY.

So what if it has a low priority? That shouldn't matter for something just so damn easy to fix.

**Comment by Stefan-ST** [comment]
@Deeses Feel free to create a pull request...
