### ISSUE TITLE
is_numeric check in Mysql update_query

### ISSUE THREAD

**Issue by zingaburga** [mybb/mybb#1933]
From inc/db_mysql(i).php

				if(is_numeric($value))
				{
					$query .= $comma."`".$field."`={$value}";
				}
				else
				{
					$query .= $comma."`".$field."`={$quote}{$value}{$quote}";
				}

This is only done in `update_query` and not anywhere else (even in Postgres/Sqlite drivers).  
It's problematic anyway, since is_numeric can return true for strings like "0x0", which can cause query errors.

I'm not in a convenient place to check the commit history for why the change was made, but I thought I'd just point it out anyway.

**Comment by zingaburga** [comment]
Also, I'm not sure if this is exactly reliable:

			if(isset($mybb->binary_fields[$table][$field]) && $mybb->binary_fields[$table][$field])
			{
				if($value[0] != 'X') // Not escaped?
				{
					$value = $this->escape_binary($value);
				}
				
				$query .= $comma."`".$field."`={$value}";
			}

If an escaped binary string just happens to start with an X, you can get weird results.

**Comment by euantorano** [comment]
The intention was to allow the use of fields such `BIT(1)` (for boolean values of 0 or 1). However, this is obviously problematic. I'm not sure what the best solution would begin this case.

**Comment by zingaburga** [comment]
Actually checking the datatype may be more appropriate (eg is_int).
Of course, it'd have to be done everywhere as well.

**Comment by euantorano** [comment]
Yes, checking the exact type would be far better, as I'm not sure whether floats work without being quoted either.

**Comment by Destroy666x** [comment]
Wouldn't something like `ctype_digit((string)$value)` be better to catch strings that are integers too, in case a plugin relied on that code in that way? Of course considering it should only catch integers, I'm not sure what it's supposed to do.

As for the 2nd issue:
> If an escaped binary string just happens to start with an X, you can get weird results.
Why?

**Comment by Sama34** [comment]
I think Zinga Burga meant that if the string happens to  start with `X` then , by looking at the code, it will not be escaped.

**Comment by RageSmirk** [comment]
So are you going to remove it? I already planned on writing my plugin to be compitable with this code.
Here is the thing: I wanted to do some optimizations on my database table, to convert varchar(40) 'ip' field to varbinary(16). Now looking at the code, I won't be able to use $db->insert_query with $db->escape_binary(my_inet_pton(get_ip())) since single quates would be doubled. However if I then inject the necessary information to $mybb->binary_fields array, the ordeal seems to pass...
Waiting your reply on how to do this right.

**Comment by zingaburga** [comment]
> Wouldn't something like ctype_digit((string)$value) be better to catch strings that are integers too, in case someone already relied on that code in that way? Of course considering it should only catch integers, I'm not sure what exactly it's supposed to do.

I can't see anyone relying on that specific behaviour, unless they're looking to generate database errors.  It doesn't make a difference for most cases anyway.

>  Waiting your reply on how to do this right.

If the MyBB devs just remove the check, you should be able to do it the way you specified without issue.  I.e.

	if(isset($mybb->binary_fields[$table][$field]) && $mybb->binary_fields[$table][$field])
	{
		$array[$field] = $this->escape_binary($value);
	}

As of now, the code _doesn't_ necessarily work if the IP happens to start with '58' (IPv6) or '88.' (IPv4).

If you need backwards compatibility with older MyBB, this is what I do:

	function xthreads_db_escape_binary($s) {
		global $db;
		if(isset($db->db_encoding)) { // hack for MyBB >= 1.6.12 to force it to not screw up our binary field
			$old_db_encoding = $db->db_encoding;
			$db->db_encoding = 'binary';
		}
		$ret = $db->escape_string($s);
		if(isset($old_db_encoding)) $db->db_encoding = $old_db_encoding;
		return '\''.$ret.'\'';
	}

**Comment by RageSmirk** [comment]
Why wouldn't it always start with X?
X'HEXHERE', that's how $this->escape_binary($value) works.

**Comment by zingaburga** [comment]
Oh I see what you mean - sorry I didn't read it correctly.
If the caller needs to always manually escape the binary fields, then it would make sense to completely remove the check (like in the pgsql driver), something like:

	if(isset($mybb->binary_fields[$table][$field]) && $mybb->binary_fields[$table][$field])
	{
		$array[$field] = $value;
	}
	else
	{
		$array[$field] = "'{$value}'";
	}

Makes more sense I suppose, since regular behaviour requires manual escaping anyway.
In which case, your code would still work.
