### ISSUE TITLE
Wrong awaitingactivation check

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1934]
https://github.com/mybb/mybb/blob/feature/global.php#L727
It doesn't make any sense because `$awaitingusers['time']` will always be smaller than tommorow's time, thus the 2 cache rebuild queries are executed on every page load.

**Comment by Destroy666x** [comment]
This doesn't look fully correct either: https://github.com/mybb/mybb/blob/feature/stats.php#L131 The setting says it's in hours and this is * 60860, which is ~16,9 hours. But I'm almost asleep now so I may be missing something.. I'll check it tommorow.

**Comment by Sama34** [comment]
You are correct. For some reason this was changed. https://github.com/mybb/mybb/commit/a5c99eec86d7c3a7ee6261b40145bb46d77f5032#diff-f73356294f1b60991e9aaabc76677d7bR136
