### ISSUE TITLE
ACP Smilies Mass Editor break all smilies on save.

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1953]
Version : myBB 1.8.4 - clean.
Subject : ACP Smilies Mass Editor break all smilies on save, by changing part of smillies ID's to html entities.

Reproduce bug :
- Go to smilies editor in ACP
- chose mass editing of smilies
- chose save smilies. (no need to edit anything just save)

Causes :
all characters like &lt;&gt; will be changed to html entities which breaks all smilies at once.

Original thread: [ACP Smilies Mass Editor break all smilies on save.](http://community.mybb.com/thread-169413.html)

**Comment by avril-gh** [comment]
wow, that was fast @Destroy666x 
i will try this fix and tell you soon if it worked.
