### ISSUE TITLE
Proposition : enhanced numeric option setting

### ISSUE THREAD

**Issue by crazycatdevs** [mybb/mybb#1959]
The `numeric` setting is good, but don't allow the use of the options.
I suggest to modifiy admin/modules/config/settings.php to allow a definition like:

``` php
$settings[] = array(
    'name' => 'my_numeric',
    'title' => 'a numeric field',
    'description' => 'a description',
    'optionscode' => 'numeric
min=3
max=99
step=3',
    'value' => '24'
);
```

The modification I suggest:

``` php
else if($type[0] == "numeric")
{
    $field_options = array('id' => $element_id);
    if (count($type)>1)
    {
        for($i=1; $i < count($type); $i++)
        {
            $optionsexp = explode("=", $type[$i]);
            $opt = trim($optionsexp);
            if (in_array($opt[0], array('min', 'max', 'step')))
            {
                $field_options[$opt[0]] = intval($opt[1]);
            }
        }
    }
    $setting_code = $form->generate_numeric_field($element_name, $setting['value'], $field_options);
}
```

**Comment by Supryk** [comment]
good idea
+ for you

**Comment by Sama34** [comment]
https://blog.isotoma.com/2012/03/html5-input-typenumber-and-decimalsfloats-in-chrome/

Step allows `any` as its value.

**Comment by Destroy666x** [comment]
Any progress @crazycatdevs?

**Comment by JN-Jones** [comment]
What feedback is required @Destroy666x ? Only the `any` value?

**Comment by Destroy666x** [comment]
> Note that existing settings could (should?) be update to use these new options, especially min (per page and similar settings).

+ `any` if we want it.

**Comment by JN-Jones** [comment]
`any` should be supported, especially with plugins in mind.
