### ISSUE TITLE
Editing problem in IE11

### ISSUE THREAD

**Issue by JoshHarmon** [mybb/mybb#1963]
Editing in Full Mode works incorrectly in IE11 when the post contains a hyperlinked image.

I managed to reproduce the problem in this forum (in the sandbox section).

Steps to reproduce:

1. Create a thread where the title post contains a hyperlinked image in the leading line and some text in the following lines. Sample code:

Code:
[img]http://www.metal-archives.com/images/5/4/4/544.jpg?4439[/img]

This is some basic text to edit

2. Try to edit the text line in Full Edit mode. Result = Fail (be it in plain code submode or in WYSIWYG submode)

In Quick Mode, editing works. If we delete the image (in Quick Mode), and then try to edit the remaining text in Full Mode, then it works. So the problem is somehow related to the presence of an image.

Actually, in my production forum I have the Quick Advanced Editor Plus plugin installed, in which environment the Quick Edit mode editing also becomes unsuccessful in the described scenario.

But it would be nice to at least resolve the basic problem, without the plugin interference.

TIA

Original thread: [Editing problem in IE11](http://community.mybb.com/thread-169733.html)

**Comment by JoshH99** [comment]
Have confirmed in IE11 on Windows 7 in the MyBB Testing section. Posting the thread is successful, and the line can be edited before you have posted the thread. Then, if you go to Full Edit after posting, you can edit the 2nd line in the editor, but the post will not be updated.

**Comment by Destroy666x** [comment]
It also applies to other tags like [hr]: http://community.mybb.com/thread-169491-post-1152449.html#pid1152449 and I think it may be fixed by SCEditor update in 1.8.5 (needs to be tested).
