### ISSUE TITLE
Using ||~|~|| in polls breaks poll

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#1964]
Of some odd reason MyBB uses ||~|~|| to separate poll answers. Therefore using ||~|~|| in poll answers can corrupt polls.

**Comment by Sama34** [comment]
What do you suggest? Serialization?

**Comment by Stefan-ST** [comment]
Serialization would be solution but it requires to update all existing polls. It may also be possible to escape the sequence as a solution until MyBB 2.0.

**Comment by Destroy666x** [comment]
Serialization would also break all plugins that get poll options by exploding the weird ||~|~||..

**Comment by Sama34** [comment]
What do you mean by escaping the sequence @Stefan-ST ?

**Comment by JN-Jones** [comment]
Eg `str_replace('||~||~||', '{escaped}', ...);` on saving and the other way around on loading. Where `{escaped}` should likely be something that can't be used in poll options (otherwise we'd have the same problem again).

**Comment by Deeses** [comment]
Hmm, wouldn't know a solution right now but what I'm going to do is rename that so nobody on my board can view this issue and do it on my fourm :+1:

**Comment by Krytic** [comment]
@JN-Jones couldn't you just prevent users from entering ||~||~|| in the poll options? Seems like an odd choice for someone to use in a poll unless they're actually *trying* to break it.

**Comment by Destroy666x** [comment]
@Krytic, yeah, that's what I also suggested in our private chatting place. It's not a perfect solution, but there's nothing better. And we can't fix current polls anyways.

Just submitting the fix.

**Comment by Sama34** [comment]
I agree with that solution.
