### ISSUE TITLE
Calendar - problem with mini calendar

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#1965]
According to the mini calendar on the right side the 22. march is a Monday but it is a Sunday.
![calender](https://cloud.githubusercontent.com/assets/544140/7188630/8a50c944-e479-11e4-8ce8-55b40a5d7c4a.png)

Also the link (») links to a week starting with Sunday although the first day of week is set to Monday.

**Comment by Destroy666x** [comment]
Whar are the reproduction steps? Looks correct on my testing forum:
<img src="http://i.imgur.com/AYyifWp.png" alt="" />

**Comment by Stefan-ST** [comment]
@Destroy666x You need to set "Start of Week" of the calendar to Monday (or probably anything but Sunday). Note it seams not to be reproducible every day probably depending on that setting.

**Comment by Destroy666x** [comment]
I see.
