### ISSUE TITLE
Problem with multiple recipients at PMs

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#1966]
Send a PM to multiple recipients and then have a look to the usernames of the recipients (see attached image).
Sometimes the names of the recipients are shown and sometimes not. I have also sent a PM on another board, where no username was shown at all but only N/A ("keine Angabe").....

Original thread: [Problem with multiple recipients at PMs](http://community.mybb.com/thread-168978.html)

**Comment by Destroy666x** [comment]
Don't forget about these 2 (query optimisation and PM search sorting by sender bug): http://community.mybb.com/thread-168978-post-1150102.html#pid1150102 or feel free to move them to other issues.

**Comment by JN-Jones** [comment]
@mybb/developers Can somebody look at this? There seem to be fixes available which should be considered and created a PR with them.

**Comment by Cu8eeeR** [comment]
@Matslom - can you please check this?

**Comment by Eldenroot** [comment]
MyBB team, still valid?
@effone @euantorano

**Comment by Sama34** [comment]
I'm unsure if this was ever fixed but I couldn't replicate in a live board using the last MyBB version.
![image](https://user-images.githubusercontent.com/1786584/50714985-d2f09400-102f-11e9-8252-23ab46662306.png)

**Comment by euantorano** [comment]
I’m not sure either, I seem to recall seeing a patch at some point? If it can’t be replicated on a test board or the community forums, we can probably close this.

**Comment by effone** [comment]
I have done this (or similar) patch already, but it was not this issue?
I am sure my patch got merged, it was a comma / space placing /parsing issue at frontend, select2...

**Comment by Eldenroot** [comment]
So what about queries mentioned above?

**Comment by Ben-MyBB** [comment]
I can't seem to replicate this so going to go ahead and close.
