### ISSUE TITLE
Feature request: Edit Timestamp

### ISSUE THREAD

**Issue by ITfee** [mybb/mybb#1967]
I think it would be a great feature, to have the possibility to change time and date of a MyBB post via ModCP rather that messing around in the SQL like this:
http://community.mybb.com/thread-110199-post-801934.html

**Comment by euantorano** [comment]
Hi, please suggest features on the forum rather than here. In any case, what is the specific use case for this feature? How often is it required?

**Comment by ITfee** [comment]
Since I think this is something that MyBB lacks, I thought this would be the better place to suggest.

Regarding your questions:
If you use MyBB as an intranet, it is a useful feature to change e.g. the date/time of notices about meetings or to put in news afterwards. That would be a big help for sorting and so on. In my use case this happens several times a week.

**Comment by Destroy666x** [comment]
> I thought this would be the better place to suggest.

It's not: https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md#suggesting-features

Also, I don't think it's useful on most forums, but feel free to suggest it on our forum. But I'd rather request a plugin, which has probably a bigger chance to be created.
