### ISSUE TITLE
Weird default user pruning task value

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1974]
It runs every minute at 2 o'clock for some reason: http://community.mybb.com/thread-170168-post-1155669.html#pid1155669

EDIT: also times should be removed from task description strings: http://community.mybb.com/thread-170168-post-1155678.html#pid1155678

**Comment by euantorano** [comment]
That's weird. Definitely is configured that way in the install: https://github.com/mybb/mybb/blob/feature/install/resources/tasks.xml#L115

Seems like it's been that way since before we even moved to GitHub.

**Comment by Stefan-ST** [comment]
I'm not sure whether we should update existing tasks. Users may have intentionally set different values.

**Comment by euantorano** [comment]
I wouldn't update them, as some users deliberately change them.
