### ISSUE TITLE
$this->delete_uids can be empty and throw SQL error

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1981]
As the title says, in some cases it can be emptied: https://github.com/mybb/mybb/blob/feature/inc/datahandlers/user.php#L1533 and there is no check for that, which results in this: http://community.mybb.com/thread-170462.html

**Comment by Sama34** [comment]
#1671

**Comment by Destroy666x** [comment]
Are you even serious? If yes, show which line exactly removed the check for possibly empty `$this->delete_uids` there. And to make it funnier, you were the one that wrote the buggy code, actually: https://github.com/mybb/mybb/commit/6492ab36d1d6eaae2018d9c55477bc5206a8bc6b

**Comment by Sama34** [comment]
https://github.com/mybb/mybb/commit/6492ab36d1d6eaae2018d9c55477bc5206a8bc6b#diff-d7a79d2018f59155db42272766f2f79bR1412

**Comment by Destroy666x** [comment]
What about that line? That's a guaranteed error in strict mode, not a proper check. Basically the same mistake as in here: https://github.com/mybb/mybb/issues/1831

**Comment by JN-Jones** [comment]
Guys, chill down. None of us noticed this before (not the one who wrote, not the ones who checked it and none of us who worked with that function). Also it's completly uninteressant who introduced the issue. A simple check should be added and that's it, no need to discuss anything here...
