### ISSUE TITLE
Custom profile field is deleting leading 0

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#1985]
When using a custom profile field for storing phone numbers, MyBB 1.8.4 is deleting leading zeros. For example, '0123555333' is becoming '123555333' after saving.

My custom profile field is configured as a textbox with no regex, and a maximal length of 0.

Original thread: [Custom profile field is deleting leading 0](http://community.mybb.com/thread-170561.html)

**Comment by PaulBender** [comment]
It only deletes leading zeros when it's an integer, before text zeros are kept.

**Comment by psde** [comment]
Thanks for pushing this from the forums. I think [this line](https://github.com/mybb/mybb/blob/d550186a2416acfeb62eb562ea7ad77fe7c0eccb/inc/db_mysqli.php#L895) seems like it could be responsible, but I do not have a deep understanding of the codebase.

**Comment by psde** [comment]
Similarly, if I try to format it as '+49123555333', MyBB will remove the leading '+'.

**Comment by Destroy666x** [comment]
Yeah, this is duplicate of https://github.com/mybb/mybb/issues/1933 similarly to http://community.mybb.com/thread-170288.html (and possibly many other fields).
