### ISSUE TITLE
Redirect problem with IDN after login

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#1988]
With an internationalized domain name the redirect after login redirects to a non existent page. For example when using the domain täst.de it redirects to t&amp;auml;st.de instead of the right url.

**Comment by Deeses** [comment]
I'm sure you can make an easy fix if you just look around for $mybb->setting['bburl'] via Notepad++

**Comment by Destroy666x** [comment]
It doesn't have anything to do with that setting, actually. The redirection URL is retrieved with JS from document's `href` attribute and there is apparently a problem with that (need to test it locally). That's another reason why the PHP `get_current_location()` solution is better as I said under another issue.

**Comment by Stefan-ST** [comment]
This code in member.php could cause the issue:
```php
redirect(htmlentities($mybb->input['url']), $lang->redirect_loggedin); 
```

**Comment by Destroy666x** [comment]
Ah yes, that would be it. Why was `htmlentities` used there?

**Comment by Stefan-ST** [comment]
@Destroy666x I have no idea and that line hasn't been changed for ages...
