### ISSUE TITLE
Deleting an event in 'editevent' without checking checkbox throws errors

### ISSUE THREAD

**Issue by psde** [mybb/mybb#2003]
When trying to delete an event from the edit event form without checking the checkbox, multiple errors are thrown:

    The name for the event is missing. Please enter an event name.
    The description for the event is missing. Please enter an event description.

All data fields (name, description, time) are also cleared.

Original thread: http://community.mybb.com/thread-168437.html

**Comment by psde** [comment]
The edit event pages uses two forms, which are both posting to calendar.php with action=do_editevent. But only the edit-form is posting the description, name and time, the delete-form does not. Therefore, these fields are empty when an error is detected.

I propose to remove the delete-form and replace it with a call to MyBB.deleteEvents($eid) instead.

**Comment by Destroy666x** [comment]
> I propose to remove the delete-form and replace it with a call to MyBB.deleteEvents($eid) instead.

That will make it inconsistent with `editpost.php`'s and `poll.php`'s delete forms though. They simply throw an error if the checkbox isn't checked. Same should be done here or all should be changed to another solution.

**Comment by psde** [comment]
> That will make it inconsistent with editpost.php's and poll.php's delete forms though.

Yes, that is true. So the form should use a different action, for example `do_eventdelete` and throw the relevant error. I am still concerned about introducing new language strings in a minor version. Is this something that is happening regularly?

I was also looking at the `calendar.php` source code and saw that there are no functions used. For example, checking the `$mybb->input['eid']` and checking calendar permissions is repeated for every action. Is it not desirable to use functions for these kind of repeated checks inside a file that is living in the root directory?

**Comment by Destroy666x** [comment]
> Is this something that is happening regularly?

Yes. Language changes are always reflected in docs: http://docs.mybb.com/versions/1.8.5/ Important modifications of language strings can be also easily found by using ACP -> Configuration -> Languages -> Edit with English functionality. So no worries about that.

> Is it not desirable to use functions for these kind of repeated checks inside a file that is living in the root directory?

It is, but some parts of MyBB are old and their quality is far from the best. `search.php` and `calendar.php` are probably the least optimised scripts.
