### ISSUE TITLE
Wrong theme shown as selected in ACP preferences

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2011]
Basically the same issue as https://github.com/mybb/mybb/issues/1590 Missed it earlier due to `Default` theme name.

EDIT: also, the global setting should have default value (otherwise wrong theme is shown there too) and `$file` is undefined.

**Comment by JN-Jones** [comment]
@Destroy666x You're assigned to this and added the in_progress label. Can we expect a PR for this anytime soon?
