### ISSUE TITLE
'Purge spammer ' Banned the user, removed his posts, but banned ME.

### ISSUE THREAD

**Issue by Deeses** [mybb/mybb#2013]
So I used this, https://rapidgrab.net/i/55d7f25c4a69.png and it banned him

But now I'm banned and can't do anything. 

"I'm sorry, but you are banned. You may not post, read threads, or access the forum. Please contact your forum administrator should you have any questions"

I went to ACP and it says I'm in the administration and moderation group like it should, no banned group.

So what the hell?

**Comment by Stefan-ST** [comment]
For support please use our forums: http://community.mybb.com/

**Comment by Deeses** [comment]
This isn't support, it's a bug.. 

I don't get why you closed this (facepalm)

**Comment by kawaii** [comment]
I've never seen this reported by anyone else. I just looked over the function which handles that feature and there's nothing in the code to suggest that behavior. This is a support issue - not a bug. If this were more prevalent and a widespread issue then you'd be correct but it's not and I personally use the purge spammer feature every day on my own 1.8* install with zero problems.

**Comment by Stefan-ST** [comment]
@Deeses Even if it was a bug this is not the right way to report it. Please read https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md

**Comment by Destroy666x** [comment]
Yep, I guess noone except you can reproduce it (me neither)...
