### ISSUE TITLE
Wrong Doc Blocks

### ISSUE THREAD

**Issue by ATofighi** [mybb/mybb#2026]
> There are several wrong doc blocks for functions. One example is the show_fields_from which returns an array and not a string. Also the "@param" block  is often wrong:

> http://manual.phpdoc.org/HTMLSmartyConve...m.pkg.html Wrote:
>> @param datatype &#36;var desc

> But we often ignore the "&#36;var" part which throws an error in several IDEs.

Original thread: [Wrong Doc Blocks](http://community.mybb.com/thread-171748.html)

**Comment by euantorano** [comment]
This has annoyed me for a long time, but fixing it as a very slow and tedious process. I tend to do it as I change other things :)

**Comment by JN-Jones** [comment]
I could try to fix at least the files in `inc` and `admin/inc`.But remember that the changed files package would get bigger because of this.
