### ISSUE TITLE
ACP link wrong at tend of upgrade.

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#2028]
At the end of the upgrade process the administrator is presented with a direcft link to the ACP index page.

The link is incorrect if the admin directory was renamed.

**Comment by Destroy666x** [comment]
It looks ok for me: https://github.com/mybb/mybb/blob/feature/install/upgrade.php#L637

**Comment by Sama34** [comment]
I see, it was wrong for me and I absolutely am using an renamed directory.

Will left open till I can trace it.

**Comment by Sama34** [comment]
Found it.

I was most likely being showed the Spanish language strings and did not noticed.
