### ISSUE TITLE
template render wrong

### ISSUE THREAD

**Issue by fxale** [mybb/mybb#2035]
The function cache($templates) in "inc/class_templates.php" in line 49 ignores the version field.
Thus rendering does not perform properly.

**Comment by Destroy666x** [comment]
Could you elaborate? Which version field do you mean? And in what way the rendering fails? Also, we'd be grateful if you reported bugs rather on our forum next time, thanks.

**Comment by JN-Jones** [comment]
I'd guess he means, that the cache caches the template but the cache isn't updated when the version field gets bumped. Though that's wrong as the cache is only "per page" and therefore the cache gets automatically updated.

**Comment by Destroy666x** [comment]
Yeah, the report looks invalid, I can't find any issues connected with templates' `version` - bumping it works fine as always. If you have more info, including reproduction steps, feel free to share. But as I said, it'd better if you do it on forums in 1.8 Bug Reports.

**Comment by fxale** [comment]
The problem was that the database had duplicate rows of templates for the same sid and title in different rows with different tid.
It is seen that errors occurred in previous versions and is reflected in this new version 1.8.5
I found this when I was adjusting the templates.
When I was editing a template, it is stored in a row and when is rendered from the other row.

**Comment by Sama34** [comment]
What happens if you revert the template back to its original state instead?

**Comment by Destroy666x** [comment]
> The problem was that the database had duplicate rows of templates for the same sid and title in different rows with different tid.

A problem indeed, but never seen that in the core. Were those custom templates added by a plugin? If yes, the plugin inserted them incorrectly. If not, which templates were affected and what were their versions?

**Comment by fxale** [comment]
<blockquote>
<p>
What happens if you revert the template back to its original state instead and then attempt to edit it normally?
</p></p>
Does it goes back to normal?
</p>
</blockquote>

I had to revert twice to return to its original state

<blockquote>
<p>
A problem indeed, but I've never seen that in the core. Were those custom templates added by a plugin? If yes, the plugin inserted them incorrectly. If not, which templates are/were affected and what are their version values?
</p>
</blockquote>

I give what I found in the database

![image](https://cloud.githubusercontent.com/assets/12943833/8270729/324b3ba0-17c6-11e5-8e4e-abbccfb76a51.png)

**Comment by Sama34** [comment]
Were there any errors when you updated your board?

**Comment by Destroy666x** [comment]
Are there any other duplicates of default templates except `forumdisplay_threadlist` and `global_boardclosed_warning`? Were they modified before upgrade? Do you perhaps have a backup to check whether they were duplicated before upgrading?

**Comment by fxale** [comment]
the oldest backup that I have is December 2013
the error already existed
in fact the timestamp is from 21/01/2013 19:34:14
the image shows all duplicate rows of table templates

![image](https://cloud.githubusercontent.com/assets/12943833/8272834/c35006e0-1829-11e5-8945-5b5b0db05f4f.png)


It is a very old bug apparently
perhaps be forgotten

**Comment by Destroy666x** [comment]
> perhaps be forgotten

I'd say so. Unless you (or anyone) has any idea how it may have been duplicated. Can't really do anything without knowing the source of problem, which may have already been fixed.

**Comment by Sama34** [comment]
I had experience this issue in the past but never took the time to debug it at all.

We can let this open some time to see if someone contribute valuable information.

**Comment by Destroy666x** [comment]
I think this can be safely closed, I haven't noticed any other support/bug thread about this yet. Might have been an issue in early 1.6.x.
