### ISSUE TITLE
Skype status icon broken

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#2042]
Template misc_imcenter_skype loads an image from http://mystatus.skype.com/ that doesn't exist anymore.

**Comment by JN-Jones** [comment]
Apparently they stopped supporting status images at all: https://support.skype.com/en/faq/FA605/how-do-i-set-up-the-skype-button-to-show-my-status-on-the-web-in-skype-for-windows-desktop

As we already have links for chat/call a user I'd vote for simply removing the image without any replacement. @Destroy666x @euantorano

**Comment by Cu8eR** [comment]
@JN-Jones - I agree
