### ISSUE TITLE
URL improvements for Gravatar

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2046]
As the topic title says, it could be changed in 2 lines. Also, `.jpg` extension should be either added or not added for consistency.

EDIT: not added it seems: http://community.mybb.com/thread-166477-post-1165982.html#pid1165982

**Comment by cronhound** [comment]
it's like, [two characters](https://github.com/lewd-sx/lewd.sx/commit/cfa5721bacd2cf836003ce0d18b24127652fa383) to make them load through SSL. 

I've never seen the point in making URLs protocol-less when you know that the https equivalent is available.

**Comment by Cu8eR** [comment]
For this issue just remove .jpg from line 2155?

@neko - your link is not working anymore, could you fix it?

**Comment by andrewjs18** [comment]
manual core file modifications have been posted to force gravatar over https by default: http://community.mybb.com/thread-187397-post-1201316.html#pid1201316

**Comment by Cu8eR** [comment]
@andrewjs18 - thx for info.
