### ISSUE TITLE
Hello World plugin fails on SQLite and most likely also pgsql

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2047]
Not good for an example plugin: http://community.mybb.com/thread-172178.html It should be compatible with our minimal requirements. I guess only the table creation query needs to be corrected,

**Comment by kawaii** [comment]
Isn't it about time you depreciated the Hello World plugin? I remember seeing a suggestion I think by Omar G to replace it with something a little more 2015...

**Comment by Sama34** [comment]
@kawaii it already has been replaced.

**Comment by JN-Jones** [comment]
Unassigned @Sama34 

@mybb/developers Can we have this fixed? I'm not sure whether we really should spend much time with the example plugin but ass we have it it should work.

**Comment by Stefan-ST** [comment]
It probably takes about 5 minutes at most to fix it. We should set a good example...

**Comment by euantorano** [comment]
At a quick glance, it looks like all that should be needed is:

- Different table creation code for different engines where `AUTO_INCREMENT` differs (and where `Enging=myisam` does't work) - https://github.com/mybb/mybb/blob/feature/inc/plugins/hello.php#L364
- Some weird stuff going on with template deletion - https://github.com/mybb/mybb/blob/feature/inc/plugins/hello.php#L404 - surely this can be simplified?
