### ISSUE TITLE
Remove HTML in parser

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#2050]
I think the HTML inside the parse would be better in templates.

**Comment by Destroy666x** [comment]
@PaulBender moved `[code]` and `[php]` here: https://github.com/mybb/mybb/pull/2025/files I'd also definitely move `[quote]` since I recall at least several complaints that its HTML can't be easily changed in themes. Maybe also `/me` and `/slap` since not everyone wants them in red font. Except them - I don't mind - the rest of MyCodes is quite standard.

**Comment by euantorano** [comment]
I agree with `[quote]`. Not sure about `/me` and `/slap` - we could simply use CSS classes to style them rather than manual style attributes and achieve the same result.

**Comment by kawaii** [comment]
It'd be really nice if we could have total access to all of the default built-in MyCodes without the need for core edits.

**Comment by JN-Jones** [comment]
IMHO @euantorano solutions seems the best.

**Comment by Sama34** [comment]
I can't add an additional attribute to an image unless I code a plugin to overwrite the default code.

**Comment by PaulBender** [comment]
I did what I could. The basic quote MyCode can't be moved without rewriting the quote parser. Same for all other MyCodes. I added a class to /me and /slap so they can be styled via CSS.

**Comment by Sama34** [comment]
I assume this can be considered done then? If the remaining issues are not feasible to fix.

**Comment by Destroy666x** [comment]
I'd say so

**Comment by PaulBender** [comment]
Yes, it's done.

**Comment by Destroy666x** [comment]
I just remembered that someone suggested adding classes to all BBCodes, which wouldn't be bad.

If not that, I'd change some tags to more semantic and HTML5-compatible solutions, e.g. the width/height attributes of `[img]`.
