### ISSUE TITLE
search.php doesn't check individual moderator permissions for tools

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2053]
As the title says. `forumdisplay.php` correctly checks permissions and separates templates for each tool, `search.php` yet again is incomplete and doesn't do it.

**Comment by Destroy666x** [comment]
This is a duplicate of https://github.com/mybb/mybb/issues/2350

**Comment by Cu8eR** [comment]
@Destroy666x - yes, and the milestone should be removed
