### ISSUE TITLE
Thread subjects FULLTEXT not applied.

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2056]
The following piece of code seems wrong:

```php
// Check if we need to create our fulltext index after changing the search mode
if($mybb->settings['searchtype'] != $mybb->input['upsetting']['searchtype'] && $mybb->input['upsetting']['searchtype'] == "fulltext")
{
	if(!$db->is_fulltext("posts") && $db->supports_fulltext_boolean("posts"))
	{
		$db->create_fulltext_index("posts", "message");
	}
	if(!$db->is_fulltext("posts") && $db->supports_fulltext("threads"))
	{
		$db->create_fulltext_index("threads", "subject");
	}
}
```

I had to manually set the FULLTEXT search for thread subjects because it wasn't being updated when modifying the setting.

Original thread: [Thread subjects FULLTEXT not applied.](http://community.mybb.com/thread-160369.html)

**Comment by JN-Jones** [comment]
As mentioned in the thread: I haven't checked whether the indexes are created or not but they are surely not dropped when the setting is changed back.

**Comment by Sama34** [comment]
It should use a language string instead and no allowing to rename the default directories IMO. Just like default template groups.

**Comment by Stefan-ST** [comment]
Why should it drop the indexes? They are part of the default installation process unless fulltext indexes are not supported at all. This code just adds them when they haven't been supported before.

**Comment by JN-Jones** [comment]
@mybb/developers Can we have some more opinion on this? @Destroy666x assigned himself after @Stefan-ST comment but I'd like to have a consens before we get a PR here.

**Comment by Stefan-ST** [comment]
Beside that, was anybody able to confirm the reported issue?

**Comment by euantorano** [comment]
I've not had a chance to look and confirm this. I'm away from home until the weekend, but will try to look then.

**Comment by Sama34** [comment]
If the setting is turned off the indexes shouldn't be dropped.

**Comment by euantorano** [comment]
Definitely agreed @Sama34. The indexes should be created on install, and (if they don't exist) when the setting is changed to full text. They should never be dropped.
