### ISSUE TITLE
Guests permissions to edit/delete posts/threads

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2058]
Hello, I'm trying to allow guests on the forums to edit their own posts and delete their threads.
When I visited the ACP -&gt; Users &amp; Groups -&gt; Groups -&gt; Guests -&gt; Forums &amp; Posts and I scrolled down, I noticed there were options for this and they were activated ( http://i.imgur.com/Fxg8VdA.png ) But for some reason when I visit the forum as a guest I don't see the delete/edit buttons in postbits for posts I made as a guest.

Original thread: [Guests permissions to edit/delete posts/threads](http://community.mybb.com/thread-163512.html)

**Comment by Destroy666x** [comment]
As it was said in the thread, ususable checkboxes should be deleted/hidden for guest group.
