### ISSUE TITLE
am suddenly getting PM messages from MyBB engine

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2060]
I have just upgraded from 1.6.5 to 1.8.1, and suddenly when a thread I had subscribed to gets a reply, instead of an email, MyBB now PMs me with the notification.  

Is this a bug?  
How can I fix this?  I can't find any related user setting in UserCP

Original thread: [am suddenly getting PM messages from MyBB engine](http://community.mybb.com/thread-162101.html)

**Comment by PaulBender** [comment]
Can anyone reproduce this?

I've upgraded a board from 1.6.9 to 1.8.7 and subscriptions were still being sent via email.

**Comment by Destroy666x** [comment]
I could reproduce it back then, I'll check now. Maybe something fixed it or it happens only under certain configuration.

**Comment by dequeues** [comment]
Did you manage to reproduce this? I can't seem to @Destroy666x

**Comment by Destroy666x** [comment]
Last time I checked everything was ok. But I can't remember whether it's dependent on some setting or whatever, if I even knew that. It most likely is, which makes it hard to reproduce.

**Comment by Destroy666x** [comment]
This may be related: http://community.mybb.com/thread-194633.html

**Comment by JN-Jones** [comment]
As this is upgrade related and it seems to be hard to reproduce I'm not sure whether there's anything we can properly do. @mybb/developers Probably rejecting this is the best instead of keeping it open for another year.

**Comment by euantorano** [comment]
If nobody's managed to reproduce it by now, I'd be inclined to agree.

**Comment by effone** [comment]
Closing this based on:
 - Its not confirmed
 - Its hard to reproduce
 - We haven't received such report again from any user in the last 3 years.

**Comment by Sama34** [comment]
I couldn't find anything in the code that may be causing this.
