### ISSUE TITLE
Renaming a stylesheet doesn't recache it

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2063]
I have a stylesheet named "color_darkblue", renamed it and it was cached with empty content. Resaving the stylesheet with the new name fixed it.

Original thread: [Renaming a stylesheet doesn't recache it](http://community.mybb.com/thread-165656.html)

**Comment by euantorano** [comment]
I'll take a look at this one at the weekend. I've done a fair bit of stuff with styles recently.
