### ISSUE TITLE
Inline moderation on classic mode.

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2071]
When the postbit is set to use the classic postbit template, selecting a post doesn't change the background color of the entire post element.

Code:
var post = element.parents('.post_content');

Should be:

Code:
var post = element.parents('.post');

Or a similar solution.

Original thread: [Inline moderation on classic mode.](http://community.mybb.com/thread-159925.html)

**Comment by Cu8eR** [comment]
OK, so use var post = element.parents('.post') should be added in these two places in .js ?
