### ISSUE TITLE
Last Post Issue

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2072]
For this bug if you use a custom moderator tool that moves the thread to another forum and also makes a reply, the last post data for the destination forum is not updated.  I noticed this after using a custom tool here.

Original thread: [Last Post Issue](http://community.mybb.com/thread-159141.html)

**Comment by Destroy666x** [comment]
More details:
- [ ] last post data is wrong if you approve a thread in a forum with instant moderation

And the 2nd bug also connected with moderation:
- [ ] if you merge 2 threads, the first post data is wrong in forumdisplay

**Comment by Stefan-ST** [comment]
#2339 fixes thie issue when approving a thread.

Right now I will can't reproduce the issue mentioned in the original bug report (moving and adding a post seams to work fine for me).
If I find the reason for the second bug I'll update the PR.

**Comment by Destroy666x** [comment]
Custom moderation bug was invalid from the beginning (last post bug was the culprit), but I'm 100% the merge one existed. Was it fixed somewhere else? I can't reproduce it now either, unless it has to be done in a specific order.
