### ISSUE TITLE
Rating an unapproved post

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2074]
I just noticed we can give reputation to an user from an unapproved post, and probably an soft deleted one as well.

IMO this shouldn't be the case. Even if I'm allowed to see the post.

Original thread: [Rating an unapproved post](http://community.mybb.com/thread-167600.html)

**Comment by Destroy666x** [comment]
This is still not fully valid.

This rejects rating if thread is not visible: https://github.com/Stefan-ST/mybb/commit/a87c157288122fa3f8c0c5e4175b43b76595b503#diff-375e34e50b906f65414e7b20eb43a20dR169

But the button still doesn't check that and still shows up for no reason: https://github.com/Stefan-ST/mybb/commit/7ef5b0198a14ea6dfcdab9f1da0dbb6d3ebdb811#diff-4139bceb91b5897c2a9cddc06430deacR336

**Comment by Stefan-ST** [comment]
@Destroy666x Nice catch. I've added another PR.
