### ISSUE TITLE
Dashboard quick access items lack permission checks.

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2075]
The side panel quick access items in the ACP lack permission checking.

For instance, if I cannot manage plugins I will see the link nonetheless.

Original thread: [Dashboard quick access items lack permission checks.](http://community.mybb.com/thread-169260.html)

**Comment by Cu8eR** [comment]
Isnt it fixed?

**Comment by PaulBender** [comment]
Yes, it was fixed in 1.8.6.
