### ISSUE TITLE
Front-end input manipulation FPD

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2079]
inc/class_captcha.php does not check input types which manipulation triggers a PHP error (Full Path Disclosure), wherever CAPTCHA is used.

One of many samples in inc/class_captcha.php:
https://github.com/mybb/mybb/blob/featur...#L293-L294

sendthread.php:
https://github.com/mybb/mybb/blob/featur...d.php#L152
https://github.com/mybb/mybb/blob/featur...d.php#L157
https://github.com/mybb/mybb/blob/featur...d.php#L209
https://github.com/mybb/mybb/blob/featur...#L215-L221
https://github.com/mybb/mybb/blob/featur...#L246-L250

showthread.php:
https://github.com/mybb/mybb/blob/featur...d.php#L989

Original thread: [Front-end input manipulation FPD](http://community.mybb.com/thread-169039.html)

**Comment by JN-Jones** [comment]
Note that there are more in that thread.

**Comment by Sama34** [comment]
Links are dead in this report.

**Comment by Sama34** [comment]
Wasn't this going to be fixed if #1527 was to be merged?

**Comment by JN-Jones** [comment]
Only the lines are wrong, shouldn't be too hard to find the correct ones ;)

#1527 will likely fix some (if not all) of these (if it gets merged) - but we would still need an issue for it and her we have it ;)

**Comment by Ben-MyBB** [comment]
related to https://github.com/mybb/mybb/pull/1527
