### ISSUE TITLE
"Only receive private messages from users on my Buddy List." ineffective when buddy l

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2080]
The option "Only receive private messages from users on my Buddy List." in thUser CP doesn't work when the buddy list is empty. It appears !empty(&#36;user['buddylist']) has been added in inc/datahandlers/pm.php for some reason but I don't know why.

Original thread: ["Only receive private messages from users on my Buddy List." ineffective when buddy l](http://community.mybb.com/thread-172367.html)

**Comment by tommm** [comment]
This is as intended; the option to only receive PMs from buddies should only apply when you're actually using the buddy list.

**Comment by Destroy666x** [comment]
Why? The option says "Only receive private messages from buddy list". It doesn't mention anywhere that you will still receive PMs if your buddy list is empty. It's also shown for everyone: https://github.com/mybb/mybb/blob/feature/usercp.php#L1114 If I was the user selecting that option without any buddies, it would be an unexpected behavior for me to still receive messages without admin ovverride. So I agree with @Stefan-ST .

**Comment by Devilshakerz** [comment]
The way this feature works should be at least described somewhere, however I agree that it's counter-intuitive anyway. It would be logical to assume that no messages will be received when the list is empty.

**Comment by tommm** [comment]
@Destroy666x showing the user only receives PMs from buddies wasn't in the original design. This may have been added later.

There are two parts to this feature; one is turning it on and adding at least one person to the buddy list for it to be effective. Otherwise an accidental click (or not knowing what the feature does) eliminates the possibility for the user receiving PMs at all (which shouldn't be intended).

**Comment by Sama34** [comment]
Thew only change in 1.8 regarding this shows that the 1.6 behaviors still persists.
Current:
https://github.com/mybb/mybb/blob/feature/inc/datahandlers/pm.php#L304-L307

1.6
https://github.com/mybb/mybb/blob/master/inc/datahandlers/pm.php#L294-L301

The description is wrong at most.

**Comment by JN-Jones** [comment]
@mybb/developers @mybb/management Seems like we need some discussion here. The possibilities are:

* Show a warning somewhere if the setting is used without any buddy (either on activating it or deleting the last buddy)
* Don't receive any pm if you have no buddy
* Keep it like it is

I'd prefer the first variant so the feature works as described (only buddies can send me a pm) but it remembers you if you don't have a buddy anymore.

**Comment by euantorano** [comment]
My vote would be for option 2 - `Don't receive any pm if you have no buddy`

**Comment by WildcardSearch** [comment]
> This is as intended; the option to only receive PMs from buddies should only apply when you're actually using the buddy list.

I agree with @tommm.

The `!empty($user['buddylist'])` is not included by mistake. I believe that it is there to prevent a user from clicking that checkbox erroneously who may or may not even understand the buddy list at all and find their incoming PMs disabled-- and most importantly, **they won't even know** that is has been done unless someone tells them.

To me if anything needs to be done it would be to add a note to the setting in User CP that the setting has no effect unless there is at least one buddy on the list.
