### ISSUE TITLE
UserDataHandler::clear_profile

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#2085]
https://github.com/mybb/mybb/issues/1820#issuecomment-115888589

`UserDataHandler::clear_profile` should remove the user avatar. This method is used by the Purge Spammer feature.

**Comment by Destroy666x** [comment]
+ the `substr()` may be not reliable as I mentioned there.

**Comment by Sama34** [comment]
Can you give some examples? `substr` as always been used.

MyBB always appends the time stamp so it should never fail. If the avatar was uploaded differently we can't not know that.

Ideally plugins should use a different value for `avatartype`.

**Comment by Destroy666x** [comment]
> If the avatar was uploaded differently we can't not know that. 

Yes, but we can remove only the `?dateline=XYZ` part at the end of string with a simple regex, which won't do anything if it doesn't exist unlike `substr()`, so I don't see why not use that instead. Again - no loss by doing that.

**Comment by Sama34** [comment]
No gain either. This has never failed and is not supposed to.

_If it ain't broke, don't fix it._

**Comment by JN-Jones** [comment]
The regex is safer. An easy example would be the merge system.

**Comment by Sama34** [comment]
Probably, but from what I can see only the vbulletin3 module imports avatars? The modules should import MyBB-friendly avatars anyways.

**Comment by JN-Jones** [comment]
Feel free to write the modules: https://github.com/mybb/merge-system/issues/140

Dylan tried to import avatars in the post but his code was so buggy that I've removed those codes in 1.8.3(?) and most of those boards will still have the old entries.

Is there any reason against the regex? If not simply change it as it's way more reliable and fail save.

**Comment by Destroy666x** [comment]
> Probably, but from what I can see only the vbulletin3 module imports avatars? The modules should import MyBB-friendly avatars anyways.

That doesn't mean that other modules in the future or custom merges made by other people will always have the `dateline` parameter. That's exactly why `substr()` with a predefined `-20` is unreliable. If we want to remove the `dateline` parameter, then only the `dateline` parameter should be removed, not 20 characters which may be random.

**Comment by Sama34** [comment]
Fair enough then. But my point stands that the MS should import mybb-frriendly avatars as should 3r party developers code mybb-friendly scripts.
