### ISSUE TITLE
Problem with multipage

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2092]
Hi,

1-Jump to page of multipage does not work in Moderator Logs(Mod CP).

2-The problem also exists in the upper multipage of Subscribed Threads(User CP) and probably in the upper multipage of Forum Subscriptions.

Original thread: [Problem with multipage](http://community.mybb.com/thread-168848.html)

**Comment by JN-Jones** [comment]
There are also other multipages mentioned in that thread.

**Comment by Destroy666x** [comment]
> There are also other multipages mentioned in that thread. 

And there might be even more multipages with nested `<form>`s, it needs to be checked.

**Comment by JordanMussi** [comment]
Same issue occurred in `private.php` fixed in #2782 for #2759.
