### ISSUE TITLE
contact form not stripping html code in emails

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2107]
Hi,

I use the default mybb contact form.  when a user submits a contact form and it emails me, it doesn't strip the &lt;br /&gt; from the email.  here's a recent email I was sent from the contact form:

E-mail: email@me.com
Forum profile: username
IP Address: 127.0.0.1
Message:
Hello,&lt;br /&gt;
&lt;br /&gt;
I just created a profile a few minutes ago and was wondering if i could change my username?&lt;br /&gt;
&lt;br /&gt;
Will i have to delete and then re-create?&lt;br /&gt;
&lt;br /&gt;
Thanks!&lt;br /&gt;
&lt;br /&gt;
Me

Original thread: [contact form not stripping html code in emails](http://community.mybb.com/thread-171904.html)

**Comment by Sama34** [comment]
Should probably use `postParser::text_parse_message` instead.

Thought I had commented this in that thread..
