### ISSUE TITLE
Subscribed thread is not showing as subscribed

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2111]
Search tells me no one else has reported this yet. This is happening on this board, and in mutiple threads/replies.
1. I subscribe to a thread.
2. I receive an email notification of a new reply.
3. I click the link to read the reply, and notice at the bottom there's a "subscribe to this thread" link.
4. I'm clearly logged in.

Expected behavior: that the board would know I was subscribed and offer an unsubscribe link.
Screenshot showing #3 &amp; 4.

[attachment=32561]

Original thread: [Subscribed thread is not showing as subscribed](http://community.mybb.com/thread-159910.html)

**Comment by JN-Jones** [comment]
> While the subscribe/unsubscribe link in the footer seems to work the radio buttons still don't work for me here.

**Comment by JN-Jones** [comment]
After looking through the code: The "Do not subscribe to this thread" option doesn't remove subscriptions, instead it acts as "Do not change the subscription type". IMHO it's bettter to simply change the language string instead of any codes which may cause more bugs.

Note that this only applies to the "New Reply" page, the "New Thread" page uses the same code blocks though.

Any thoughts @Destroy666x @euantorano ?

**Comment by Destroy666x** [comment]
I'd rather see the code corrected. "Do not change the subscription type" would be useless IMO. I think this should be the correct functionality:
- select a proper radio if there's a specific type of subscription
- remove the subscription if a person switches from the specific type of subsciption to "Do not subscribe to this thread"

**Comment by JN-Jones** [comment]
Unassigned myself as I'm not sure what the best solution would be here. @mybb/developers Any other thoughts here?
