### ISSUE TITLE
Inefficient thread moderation code - threads queried one by one

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2114]
As the title says:
https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php#L3650
https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php#L538
https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php#L3496
https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php#L388

All `tids`/`pids` are known so I'm not sure why a single query with a left join to the `forums` table + a while loop for results weren't used in the first place.

**Comment by Sama34** [comment]
The thread fetching probably, the forum fetching not as much. `get_forum` attemps to laod from the cache which should be trust-able enough. Specially for this kind of usage.

**Comment by JN-Jones** [comment]
Both, `get_thread` and `get_forum` have internal caches. While `get_thread` seems to query the thread once before it caches that thread, `get_forum` completly uses the cache. Probably faster to use something like
```php
$query = $db->simple_select('threads', '*', 'pid IN ('.implode("','", $tids).')');
while($thread = $db->fetch_array($query))
{
...
}
```
But tbh I don't think the `get_forum` call needs to be removed.

**Comment by Destroy666x** [comment]
Cache doesn't mean anything if you select threads from 100 different forums in `search.php`

**Comment by Destroy666x** [comment]
Yep, forgot that `get_forum()` doesn't run any query, only gets the info from cache
