### ISSUE TITLE
Inconsistent checks in db classes

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2115]
Most function get the query as parameter. While MySQL(i) and PgSQL simpy call the respictive functions then, SQLite always has "is_object" checks. Either all classes/function should get a proper check (&#36;query instanceof ...) or the checks should be removed.

Original thread: [Inconsistent checks in db classes](http://community.mybb.com/thread-171782.html)

**Comment by JN-Jones** [comment]
I'd vote for removing those checks as we don't check the types of parameters in other functions/classes too. @euantorano @Destroy666x

**Comment by euantorano** [comment]
I'd vote for removing them too.
