### ISSUE TITLE
closed threads

### ISSUE THREAD

**Issue by ATofighi** [mybb/mybb#2117]
Hi,
In closed threads, "New Reply" button don't change to "Thread Closed" button.

Jones:

> Imho it should be reverted to how it was in 1.6: If you can reply to a closed thread the "Closed" button should be shown but should link to the new reply page.

Original thread: [closed threads](http://community.mybb.com/thread-159466.html)

**Comment by JN-Jones** [comment]
As mentioned in that thread: It should be reverted to how it was in 1.6.x

**Comment by Cu8eR** [comment]
I agree

**Comment by wagey** [comment]
This would be nice to have back.

**Comment by MyBB-Andro** [comment]
Please someone look into this. Newly joined team members found it confusing very often and end up doing reopen.
