### ISSUE TITLE
Upgrade 1.6 -> 1.8 css3.css not inserted

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2124]
css3.css was not inserted into themes after updating from 1.6.15. I had to insert it by hand.

Original thread: [Upgrade 1.6 -> 1.8 css3.css not inserted](http://community.mybb.com/thread-159024.html)

**Comment by JN-Jones** [comment]
Though I never experienced this myself sometimes the display order isn't properly updated. I've a function somewhere which rebuilds that for all themes so I'll try to modify that and include it in the upgrade script.

**Comment by JN-Jones** [comment]
Removed myself as apparently that function has been hacked into some file which since then has been overwritten. Apart from that we should first test whether this issue is still present as there have been some changes to the theme system in the early 1.8 versions.

**Comment by euantorano** [comment]
Anybody still got a 1.6 board sitting around that could easily test this?

**Comment by JN-Jones** [comment]
I doubt that a fresh board would show this error. I've done quite a lot of updates back then with different database types and can't remember that I've seen this. Only a few boards seem to have this error at all.
