### ISSUE TITLE
reCaptcha not work if use SSL (HTTPS)

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2126]
reCaptcha not work if use SSL (HTTPS)

Solution:
in line 141 of class_captcha.php
PHP Code:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;this-&gt;server&nbsp;=&nbsp;"http://www.google.com/recaptcha/api";&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;this-&gt;secure_server&nbsp;=&nbsp;"https://www.google.com/recaptcha/api";&nbsp;

should be:
PHP Code:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;this-&gt;server&nbsp;=&nbsp;"//www.google.com/recaptcha/api";&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;this-&gt;secure_server&nbsp;=&nbsp;"//www.google.com/recaptcha/api";&nbsp;

Original thread: [reCaptcha not work if use SSL (HTTPS)](http://community.mybb.com/thread-161240.html)

**Comment by JN-Jones** [comment]
`$secure_server` should be removed.

**Comment by Nixtren** [comment]
I have fixed the problem, and also removed the $secure_server variable. Pull request:
https://github.com/mybb/mybb/pull/2148
