### ISSUE TITLE
Stylesheet order reset after importing a theme

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#2137]
The Stylesheet order is not being kept after a theme is imported.

https://github.com/mybb/mybb/blob/feature/admin/inc/functions_themes.php#L337

**Comment by WallBB** [comment]
Hi Stefan, 
Just wanted to know if this is going to be fixed in 1.8.15 ?

**Comment by euantorano** [comment]
There hasn’t been a patch created for this yet, so it won’t be in 1.8.15. We’ve frozen new commits for .15 at this time to prepare for release.

**Comment by WallBB** [comment]
Okay sure, can this be planned for 1.8.16 ?
