### ISSUE TITLE
Gravatar URL wrong

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2138]
For some reason the gravatar url ends with `.jpg` which causes a wrong redirect if the email isn't valid. Instead of
`http://www.gravatar.com/avatar/e9836f6afc1316cc1b58648ce499fa18?s=100&r=g&d=mm.jpg`
it should be
`http://www.gravatar.com/avatar/e9836f6afc1316cc1b58648ce499fa18?s=100&r=g&d=mm`

It doesn't matter if the email is valid, only if it's an invalid email.

**Comment by Destroy666x** [comment]
It's a triplicate though: http://community.mybb.com/thread-166477-post-1165982.html#pid1165982
