### ISSUE TITLE
Soft deleted threads and answers

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2139]
After soft deleting a thread the quick reply and the "New reply" button are still shown, however when I try to answer (either via Quick reply or when clicking on "New Reply") I get an error that the specified thread does not exist. I haven't checked the permissions here but either the buttons should be removed, I should be able to answer or I shouldn't see the thread. The current way is somehow wrong (I know the thread exists, I see the reply options but get an error).

Original thread: [Soft deleted threads and answers](http://community.mybb.com/thread-172302.html)

**Comment by JN-Jones** [comment]
Either the edit part should be removed, the buttons should be changed, the error message should be specified or the user should be able to answer. @Destroy666x and I are for the latest as that's also how closed threads are handled.

**Comment by effone** [comment]
Extends functionality of this:
https://github.com/mybb/mybb/issues/3149
