### ISSUE TITLE
forumteam display

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2140]
There has already been another discussion about this subject, and after some better observations I am sure now that the showteam.php module, which displays the members of forumteam groups, is buggy.

As it is now the showteam.php module will only work correctly when persons are member of one forumteam only, but it goes wrong when one person is member of two or more forumteams.

As an example I consider the testforum which I am using to develop a forum for a large (main) committee with several subcommittees. The testforum is limited in the number of members of the committees, in realty the committees will be far larger. The structure can be visualized as below:

All members of the main committee have this committee as their primary &amp; display usergroup. The main committee members who are also member of a subcommittee have this membership as an additional user group. When the forumteam is displayed, the composition of the main committe is displayed right with all 9 members with names displayed in green:

But that of the subcommittees not. As shown below for the 1st subcommittee the subcommittee members who are not member of the main committee (names in blue) are listed, but the (two) members who are also member of the main committee (names in green) are not listed:

Don't look at the text, this is Dutch, but you see that two of the six members are missing. Why this is becomes clear when you look at the source of showteam.php. Below the code snippet where users are assigned to a group.

PHP Code:
//&nbsp;Are&nbsp;they&nbsp;also&nbsp;in&nbsp;another&nbsp;group&nbsp;which&nbsp;is&nbsp;being&nbsp;shown&nbsp;on&nbsp;the&nbsp;list?if(&#36;user['displaygroup']&nbsp;!=&nbsp;0){&nbsp;&nbsp;&nbsp;&nbsp;&#36;group&nbsp;=&nbsp;&#36;user['displaygroup'];}else{&nbsp;&nbsp;&nbsp;&nbsp;&#36;group&nbsp;=&nbsp;&#36;user['usergroup'];}&nbsp;

You see that a user is assigned to either his displaygroup or, when this is not set, to his usergroup. The additional groups are not considered at all!
This is completely in contradiction with how, for example, user permissions are determined in function forum_permissions, see the code snippet below where the user's usergroups are gathered:

PHP Code:
&#36;gid&nbsp;=&nbsp;&#36;mybb-&gt;user['usergroup'];if(isset(&#36;mybb-&gt;user['additionalgroups'])){&nbsp;&nbsp;&nbsp;&nbsp;&#36;gid&nbsp;.=&nbsp;",".&#36;mybb-&gt;user['additionalgroups'];}&nbsp;

So here only the combination of usergroup and additional groups is considered. The display group is omitted, because this should be one of the additional groups!

So I decided to make an improved version of showteam.php. To start with, the query for selecting the users that are member of a forumteam group must be chaged, apart from the obvious errors that are in the original query at line 72. Originally this was:

PHP Code:
&#36;query&nbsp;=&nbsp;&#36;db-&gt;simple_select("users",&nbsp;"uid,&nbsp;username,&nbsp;displaygroup,&nbsp;usergroup,&nbsp;ignorelist,&nbsp;hideemail,&nbsp;receivepms,&nbsp;lastactive,&nbsp;lastvisit,&nbsp;invisible",&nbsp;"displaygroup&nbsp;IN&nbsp;(&#36;groups_in)&nbsp;OR&nbsp;(displaygroup='0'&nbsp;AND&nbsp;usergroup&nbsp;IN&nbsp;(&#36;groups_in))&nbsp;OR&nbsp;uid&nbsp;IN&nbsp;(&#36;users_in)",&nbsp;array('order_by'&nbsp;=&gt;&nbsp;'username'));&nbsp;

And this was changed into:

PHP Code:
&#36;where&nbsp;=&nbsp;"uid&nbsp;IN&nbsp;(&#36;users_in)&nbsp;OR&nbsp;usergroup&nbsp;IN&nbsp;(&#36;groups_in)";if&nbsp;(&#36;groups_in&nbsp;!=&nbsp;0){&nbsp;&nbsp;&nbsp;&nbsp;&#36;groups&nbsp;=&nbsp;explode(',',&#36;groups_in);&nbsp;&nbsp;&nbsp;&nbsp;foreach&nbsp;(&#36;groups&nbsp;as&nbsp;&#36;group)&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;where&nbsp;.=&nbsp;"&nbsp;OR&nbsp;{&#36;group}&nbsp;IN&nbsp;(additionalgroups)";&nbsp;&nbsp;&nbsp;&nbsp;}}&#36;query&nbsp;=&nbsp;&#36;db-&gt;simple_select("users",&nbsp;"uid,&nbsp;username,&nbsp;displaygroup,&nbsp;usergroup,&nbsp;additionalgroups,&nbsp;ignorelist,&nbsp;hideemail,&nbsp;receivepms,&nbsp;lastactive,&nbsp;lastvisit,&nbsp;invisible",&nbsp;&#36;where,&nbsp;array('order_by'&nbsp;=&gt;&nbsp;'username'));&nbsp;

In lines 73 - 110 (original code) the users found by this query are assigned to an array with forumteam users. This contains some errors and does not take the additional groups of users into account. I only give the replacement part for these lines below:

PHP Code:
while(&#36;user&nbsp;=&nbsp;&#36;db-&gt;fetch_array(&#36;query)){&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;If&nbsp;this&nbsp;user&nbsp;is&nbsp;a&nbsp;moderator&nbsp;&nbsp;&nbsp;&nbsp;if(isset(&#36;moderators[&#36;user['uid']]))&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;foreach(&#36;moderators[&#36;user['uid']]&nbsp;as&nbsp;&#36;forum)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(&#36;forum_permissions[&#36;forum['fid']]['canview']&nbsp;==&nbsp;1)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;forum_url&nbsp;=&nbsp;get_forum_link(&#36;forum['fid']);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;eval("&#092;&#36;forumlist&nbsp;.=&nbsp;&#092;"".&#36;templates-&gt;get("showteam_moderators_forum")."&#092;";");&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;forumlist&nbsp;.=&nbsp;&#36;lang-&gt;forum_hidden."&lt;br&nbsp;/";&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;user['forumlist']&nbsp;=&nbsp;&#36;forumlist;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;forumlist&nbsp;=&nbsp;'';&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;usergroups[6]['user_list'][&#36;user['uid']]&nbsp;=&nbsp;&#36;user;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Is&nbsp;this&nbsp;user&nbsp;also&nbsp;in&nbsp;other&nbsp;group(s)&nbsp;which&nbsp;is&nbsp;being&nbsp;shown&nbsp;on&nbsp;the&nbsp;list?&nbsp;&nbsp;&nbsp;&nbsp;&#36;groups&nbsp;=&nbsp;array();&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(&#36;user['usergroup']&nbsp;!=6)&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;groups[]&nbsp;=&nbsp;&#36;user['usergroup'];&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(&#36;user['additionalgroups'])&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;groups&nbsp;=&nbsp;array_merge(&#36;groups,explode(',',&#36;user['additionalgroups']));&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;foreach&nbsp;(&#36;groups&nbsp;as&nbsp;&#36;group)&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(&#36;group&nbsp;!=6&nbsp;&amp;&amp;&nbsp;&#36;usergroups[&#36;group])&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#36;usergroups[&#36;group]['user_list'][&#36;user['uid']]&nbsp;=&nbsp;&#36;user;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;}}&nbsp;

Last but not least there is one line that must be added to the language file global.lang.php:

PHP Code:
&#36;l['forum_hidden']&nbsp;=&nbsp;"(Hidden)";&nbsp;

This addition is needed because in the original version it went wrong when a user displayed the forum team and there was a moderator of a forum that is hidden for him. This is also corrected in the changes above.

When the forumteam is displayed with the new version of showteam.php, the output for the 1-st subcommitte looks like:

Which is the correct composition of this subcommittee, so with the two members of the main committee in green included.

I have solved it for my forum with a plugin, which in essence is the corrected version of showteam.php. But because there are several bugs in the present code I decided to present it here for implementing in the core of a future version of MyBB. I understant this will not be an urgent matter. :)

Original thread: [forumteam display](http://community.mybb.com/thread-166630.html)

**Comment by JN-Jones** [comment]
> So:
- Consider additional groups
- Show group leaders
- Use correct colors
- Check whether forum permissions are considered

Also it was suggested to have a switch between the old and new page. Not sure whether that's needed or possible but whoever fixes/changes this could take a look at it.

**Comment by JN-Jones** [comment]
Unassigned @Sama34 

Can someone at least look at the bug parts of this? @mybb/developers

**Comment by QuietSoul** [comment]
good work!!!
