### ISSUE TITLE
Task Manager does not work

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2147]
Do someone know why Task Manager not working after update from 1.6 to 1.8.5? 
i have file task.php in FTP, my task_image

Code:
&lt;img src="{&#36;mybb-&gt;settings['bburl']}/task.php" width="1" height="1" alt="" /&gt;

and footer

Code:
&lt;!-- The following piece of code allows MyBB to run scheduled tasks. DO NOT REMOVE --&gt;{&#36;task_image}&lt;!-- End task image code --&gt;

I no have automat backup, mass mail, removes ban 

please help! 
my forum: http://handsupowo.pl

Original thread: [Task Manager does not work](http://community.mybb.com/thread-172605.html)

**Comment by JN-Jones** [comment]
Cause:
> Only one task is run per page: https://github.com/mybb/mybb/blob/featur...sk.php#L31

>A few lines later an error is thrown if the file does not exist. However when the page is accessed the next time the same task is fetched, the same error is thrown and we're done again. 


Fix:
> Yeah, we should probably disable the task and send a warning mail to the administrator or something.

**Comment by Destroy666x** [comment]
The fix isn't complete - https://github.com/mybb/mybb/pull/2012 needs to be merged, otherwise emails sent from ACP will be empty.

**Comment by JN-Jones** [comment]
That doesn't mean this issue isn't fixed.. Also the mail is mainly helpful when sent from the frontend anyways. The main point is deactivating the task so other task are able to run.

**Comment by Destroy666x** [comment]
> That doesn't mean this issue isn't fixed

How doesn't it mean that? The lang strings shouldn't be empty at any time - it's partially broken and should be corrected, especially that the fix is very easy.

> Also the mail is mainly helpful when sent from the frontend anyways.

Mainly. But if for example a plugin runs a task at activation/installation, letting the admin know that something went wrong wouldn't hurt either.

**Comment by JN-Jones** [comment]
Empty emails aren't an issue specific to the task system - it's a seperate issue with a ticket and a PR and has absolutly nothing to do with this (apart that this adds one more place where it's triggered). Also there's no way we could fix that issue here (except adding a new `$lang->load` which would cause conflicts again). The issue with emails will be fixed after merging #2012 so there's no reason to keep this issue open.
