### ISSUE TITLE
RSS limit doesn't work in the generated URL - always 15

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2160]
No idea why noone noticed this obvious bug yet, but the last highlighted line doesn't make any sense:
https://github.com/mybb/mybb/blob/feature/misc.php#L842-44
It was added when fixing PHP warnings as I see, but I don't see any purpose of it..

And a bit nitpicky, but the limit desciptions says "Not recommended to be beyond 50." while the limit is hardcoded to be 50: https://github.com/mybb/mybb/blob/feature/syndication.php#L43 The description should make clear that you can't use higher numbers and this conditional: https://github.com/mybb/mybb/blob/feature/misc.php#L905-908 should also be corrected (+ `(int)` casting and `is_numeric()` check are redundant).

EDIT: and lastly, RSS is said to be default but Atom is used instead: https://github.com/mybb/mybb/blob/feature/misc.php#L890

**Comment by SvePu** [comment]
#2714
