### ISSUE TITLE
Contact Form Attempts to Send Mail as User's Address

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2162]
http://community.mybb.com/thread-173314.html

As stated in the above thread the contact form behaves really strangely.

It will attempt to spoof the mail in order to make it seem like the user sent it rather than simply sending from your forum's contact address and affixing relevant information about the user.

This is going to cause a 553 error with 90% of STMP servers which will take one look at this attempt at spoofing mail and say 'lol no'.

Original thread: [Contact Form Attempts to Send Mail as User's Address](http://community.mybb.com/thread-173328.html)

**Comment by Evenprime** [comment]
This problem would also be covered by Issue #257 which is about the same problem in this and other locations.

**Comment by Destroy666x** [comment]
Yep, this is a triplicate.
