### ISSUE TITLE
Invalid RE: regex

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2168]
Yet another problem with the `RE: ` code and post subjects. The regex is wrong because it doesn't catch only the beginning of the string with `^` and may deform words in the middle of the subject.
https://github.com/mybb/mybb/blob/feature/newreply.php#L791

So, for example, quoting a post with subject like `Sierra Madre: test` will result in invalid `RE: Sierra Madtest`

**Comment by Stefan-ST** [comment]
I could have fixed that with the other PR easily. :P

**Comment by Destroy666x** [comment]
Well, I'm always sent off with "it would be better to create another issue for this" even if a change requires one line modification, so..

**Comment by Stefan-ST** [comment]
Well, this one is really simple to fix and test. ;)

**Comment by JoshHarmon** [comment]
Here's a PR for it since no one's touched this, as far as I can tell.
