### ISSUE TITLE
How can i show a Pop for a user to fill profile field details, if the user has not filled it(in wordpress)

### ISSUE THREAD

**Issue by yogeshmanickam** [mybb/mybb#2170]
i want to show a POP UP with some time delay for the users who have not completed their profile details. In the POP up itself user can fill the details and complete it then save it.

Can this be done? (I'm using wordpress)

Thank you!! in advance :)

**Comment by Destroy666x** [comment]
This is not our support forum. Please ask here: http://community.mybb.com

**Comment by yogeshmanickam** [comment]
okay! thank you
