### ISSUE TITLE
Stopforumspam Reserved and Private IP ranges

### ISSUE THREAD

**Issue by stryderunknown** [mybb/mybb#2172]
This is in relation to the file of inc/stopforumspam.php

Currently a spammer ip isn't tested again Private or Reserved IP ranges which means if the IP is spoofed that either of those could attempt to be used to check the stopforumspam.com database.
This likely doesn't cause any errors but it will decrease available resources at the site for checking spammer IP,s and  will also unnecessarily use up a little bandwidth.

adding two filter inclusions will remove this problem, those filters are:
 FILTER_FLAG_NO_PRIV_RANGE & FILTER_FLAG_NO_RES_RANGE **

These filters Fail validation for the following:
Private IPv4 ranges: 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16.
Reserved IPv4 ranges: 0.0.0.0/8, 169.254.0.0/16, 192.0.2.0/24 and 224.0.0.0/4. 
*\* This flag does not apply to IPv6 addresses. 

Information on filters from: http://php.net/manual/en/filter.filters.flags.php 

The current conditional looks like this:

```
if(filter_var($email, FILTER_VALIDATE_EMAIL) && filter_var($ip_address, FILTER_VALIDATE_IP)) // Calls to the API with invalid email/ip formats cause issues
        {
```

It just needs editing to this:

```
if(filter_var($email, FILTER_VALIDATE_EMAIL) && filter_var($ip_address, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE)) // Calls to the API with invalid email/ip formats cause issues
        {
```

Credited Source: 
The Originally mention of the filter additions is in the comments of: 
http://php.net/manual/en/function.filter-var.php

**Comment by Destroy666x** [comment]
I don't see why not.

**Comment by JN-Jones** [comment]
@euantorano You wanted to look at this so #2174 was closed to allow you to create a new PR. Can you do that? :P Also there may be some changes related to the url validation changes in 1.8.8

**Comment by euantorano** [comment]
I'll see what I can do.
