### ISSUE TITLE
Join and minify JavaScript

### ISSUE THREAD

**Issue by ganchito55** [mybb/mybb#2180]
First of all thanks for that awesome forum CMS.

I have worked in web development from 2 years ago and join and minify JS is always one of the best options to improve the performance.

## How to make it
My proposal is join general.js and jquery.js (these two files are always loaded in every page) and minify all JS files.

I also think that we should create a release version with these changes and a development version with the complete JS files for improve editing.

**Comment by Destroy666x** [comment]
Please suggest things like that on our forum: https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md Thanks.
