### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by maruilian11** [mybb/mybb#2181]
would you please consider adding package.json so that we can add your lib on https://cdnjs.com.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5027

**Comment by JN-Jones** [comment]
@mybb/developers Not sure about this, can somebody please look at this so we can get it either done or closed?

**Comment by PeterDaveHello** [comment]
I don't think a php forum system would need a package.json

**Comment by euantorano** [comment]
I also don't think we need one.

**Comment by maruilian11** [comment]
sorry for not checking carefully.
