### ISSUE TITLE
SQL error with Binary pseudo charset

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#219]
If you choose "Binary pseudo charset" as the Table Encoding ~~during installation~~, you'll receive an SQL error.

```
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'binary' at line 9
```

```
CREATE TABLE mybb_adminlog ( uid int unsigned NOT NULL default '0', ipaddress varbinary(16) NOT NULL default '', dateline bigint(30) NOT NULL default '0', module varchar(50) NOT NULL default '', action varchar(50) NOT NULL default '', data text NOT NULL, KEY module (module, action) ) ENGINE=MyISAM CHARACTER SET binary COLLATE binary;
```

Is there any reasonable scenario where someone would need to use this?

**Comment by Destroy666x** [comment]
So, any idea how to fix it @mybb/developers ? Can't find any info about binary charset/collation except its existence in here: http://dev.mysql.com/doc/refman/5.5/en/charset-charsets.html So I doubt it's even usable, we should probably just remove it.

**Comment by JN-Jones** [comment]
It's usable but we'd need to add some checks especially for it - likely not only in the installer. I'm for removing

**Comment by PirataNervo** [comment]
From what I understand we'd need to check everywhere if it's binary that we're using and make it lower case in that case, otherwise just skip lowercasing. This is a lot of work.

**Comment by Destroy666x** [comment]
@JN-Jones , what kind of checks? For example, how would we fix the table insertion queries?

@PirataNervo , I meant fixing this issue with SQL errors, I doubt it has anything to do with lowercasing, does it?

**Comment by JN-Jones** [comment]
Just as a note: if we decide to support binary we also need to look into case sensitive things (like login, #349) as the other supported encodings are case insensitive.

**Comment by Destroy666x** [comment]
I tested this a week ago with the simpliest CREATE TABLE queries - none worked, always an error near 'binary' was thrown. So I still don't think it's a proper collation and we can just get rid of it.

**Comment by JN-Jones** [comment]
If noone wants to work on this I'll simply remove binary within the next days @mybb/developers

**Comment by JN-Jones** [comment]
Going to remove it later
