### ISSUE TITLE
Issue with user awaiting activation

### ISSUE THREAD

**Issue by eNvyArg** [mybb/mybb#2191]
When you create a new user from the ACP and select his primary group as **awaiting activation**, you can see in the forums, the red alert with the legend of **there is "x" amount of users waiting activation**, and after a link to activate them through the ACP.

If you, for any reasons, edit again the profile for this user and put his primary group as **registered**, the red alert keeps active, and if you go to the ACP through the link of the red alert, the ACP tells you **no users were find matching the specific search criteria**.

The only way to get ride of the red alert in the forums is editing one more time the user primary group to **awaiting activation** and after, activate the user directly from the link of the red alert.

I use 1.8.6 version.

Regards.

**Comment by JN-Jones** [comment]
Please report issues on our forum next time.

I can confirm that adding a user *to* the awaiting activation group recaches the counter but removing him from the group doesn't.

**Comment by eNvyArg** [comment]
Ok thanks jones.

**Comment by Destroy666x** [comment]
There are actually many places where updating the `awaitingactivation` cache update is missing (banning users, group promotions, etc.). Not sure to what extent we want to fix that, because there's a global `awaitingactivation` cache autoupdate each X minutes you choose in settings.
