### ISSUE TITLE
Poor INFORMATION_SCHEMA.TABLES querying performance in DB list_tables() and table_exists()

### ISSUE THREAD

**Issue by Devilshakerz** [mybb/mybb#2197]
The performance of querying the MySQL's `INFORMATION_SCHEMA.TABLES` metadata tables can be significantly reduced due to its poor optimization in MyBB's database wrapper classes `DB_MySQL` and `DB_MySQLi` (methods `list_tables()` and `table_exists()`).

Related to fixing #1913, introduced with PR https://github.com/mybb/mybb/pull/1973 into 1.8.6.

As seen in:
http://community.mybb.com/thread-178452.html
http://community.mybb.com/thread-179126.html
http://community.mybb.com/thread-179070.html

Additionally, https://github.com/mybb/mybb/pull/1973 breaks compatibility with MySQL < 5.0.2.

**Comment by Devilshakerz** [comment]
Proposed fix based on internal discussion: https://github.com/mybb/mybb/compare/feature...Devilshakerz:fix-2197 (needs testing)

**Comment by Cu8eR** [comment]
+1 thx for the fix!

**Comment by Destroy666x** [comment]
The fix looks and works good, except that the spaces in `if (...)`s don't match our development standards.
