### ISSUE TITLE
Reputation confirmation modal sometimes remains on the screen in 1.8.6

### ISSUE THREAD

**Issue by bsalamat** [mybb/mybb#2199]
If two (or more) reputations are given to posts on the same page (without navigating away or refreshing the page), the second reputation confirmation modal does not close and stays on the screen.
I have give more details on the forums: http://community.mybb.com/thread-178564.html

This is caused because in 1.8.6 the following lines are deleted from modal.close function in jquery.plugins.js:

@@ -70,9 +71,6 @@
     close: function() {
       this.unblock();
       this.hide();
-	  // Deletes the element (multi-modal feature: e.g. when you click on multiple report buttons, you will want to see different content for each)
-	  if (!this.options.keepelement)
-		this.$elm.remove();
       $(document).off('keydown.modal');
     },

**Comment by Destroy666x** [comment]
> close: function() {
this.unblock();
this.hide();

These lines are still there. I guess you meant:
```js
	  if (!this.options.keepelement)
		this.$elm.remove();
```
which were removed. Adding them back fixes the issue for me.

**Comment by Destroy666x** [comment]
`keepelement: false` should also be readded. https://github.com/mybb/mybb/commit/f6f9ed0c3b7bf170f02ef12d1fe5506e677d1237#diff-d69530cd715567ebc4532ae3159f29b1L449

That's why I was and am not a fan of modyfing 3rd party files directly. And if we are forced to do that, we should start wrapping modified code with comments like `/* MyBB modification start */` and `/* MyBB modification end */`

**Comment by JN-Jones** [comment]
IMHO we need to reorganize the handling of 3rd party js libraries/files. It's a pita to update them anyways (and as this issue shows I've overwritten something) as some are in a special folder, some not, some have a link included, some not etc.

**Comment by Stefan-ST** [comment]
The libraries in jquery.plugins.js are used on a lot of pages while SCEditor, Select2, jeditable and Validate are only used on a few pages where loading them separately make more sense. However changes to 3rd party files need to be more obvious; I think only Pirata knew about this one and the comment is inconspicuous between the other comments.

**Comment by bsalamat** [comment]
FYI, adding those lines back causes some issues with MyAlerts pop-up main menu. I don't know how important it is to not break the plugins, but I just wanted to let you know.

Overall, my experience with Kylefox modal jquery plugin has been pretty poor. Besides the issues with closing, not opening, appearing when it shouldn't, etc. that I have seen so far, it is horrendous on mobile devices. When the contents of modal is large and won't fit on a single page. The modal does not scroll and cannot be closed either.

I wonder if we want to consider a different modal.

**Comment by Destroy666x** [comment]
> I wonder if we want to consider a different modal.

Not in a minor version. I definitely agree it's not the best modal jQuery plugin, but we shouldn't cause compatibility problems because of that.

**Comment by martec** [comment]
i tested here to readd keepelement: false in 1.8.6, but for me not have effect.

**Comment by martec** [comment]
now make sense...
need put too keepelement function...
https://github.com/mybb/mybb/commit/f6f9ed0c3b7bf170f02ef12d1fe5506e677d1237#diff-d69530cd715567ebc4532ae3159f29b1L321

probably Pirata Nervo added too function below too

```if (!this.options.keepelement)
		this.$elm.remove();```

**Comment by ATofighi** [comment]
I'll add `keepelement` without editing `jquery-modal` plugin :)

**Comment by martec** [comment]
@ATofighi 

i tested here and work fine... thanks.
and something like too $('.noticemod').modal({ zIndex: 7, keepelement: true }); work fine, when need keepelement true due some reason.
