### ISSUE TITLE
Click and Hold erases thread prefix in 1.8.6

### ISSUE THREAD

**Issue by wizard974** [mybb/mybb#2203]
After upgrading mybb 1.8.5 to 1.8.6

Steps to reproduce :
 
1. Add a prefix to a thread title
2. Modify this title with click and hold functionnality
3. Refresh the page

The prefix disappears.

**Comment by Destroy666x** [comment]
I can confirm.

**Comment by Cu8eR** [comment]
@PaulBender would be nice to see in 1.8.7 because it is annoying
