### ISSUE TITLE
.htaccess <IfModule mod_filter.c> set wrong, no gzip for js

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2211]
Code:
&lt;IfModule mod_deflate.c&gt;
&nbsp;&nbsp;&nbsp;&nbsp;AddOutputFilterByType DEFLATE application/x-javascript text/css text/html text/xml
&lt;/IfModule&gt;
Is not working, js files are not gziped. I am not sure is it server depened, it is not working on my server.

Changing it to 

Code:
   &lt;IfModule mod_filter.c&gt;
        AddOutputFilterByType DEFLATE application/atom+xml &#92;
                                      application/javascript &#92;
                                      application/json &#92;
                                      application/rss+xml &#92;
                                      application/vnd.ms-fontobject &#92;
                                      application/x-font-ttf &#92;
                                      application/x-web-app-manifest+json &#92;
                                      application/xhtml+xml &#92;
                                      application/xml &#92;
                                      font/opentype &#92;
                                      image/svg+xml &#92;
                                      image/x-icon &#92;
                                      text/css &#92;
                                      text/html &#92;
                                      text/plain &#92;
                                      text/x-component &#92;
                                      text/xml
    &lt;/IfModule&gt;

Helped. Seems to be "application/javascript", not "application/x-javascript".

html5-boilerplate -- https://github.com/h5bp/html5-boilerplat.../.htaccess
Besides looking into headers you can check it here -- http://www.whatsmyip.org/http-compression-test/

Jquery and others js are too big to be downloaded notgziped for every user (without cache). It took me a while to figure out why my forum is slow comparing to other parts of site. I didn't thought that my root htaccess' mod_filter is overwritten here. Changing this speeds things a lot.

Original thread: [.htaccess <IfModule mod_filter.c> set wrong, no gzip for js](http://community.mybb.com/thread-165297.html)

**Comment by Destroy666x** [comment]
> Not exactly a bug, but we could add more MIMEs to the exemplary htaccess.txt, I guess

**Comment by Cu8eR** [comment]
`application/json \
                                     application/rss+xml \
                                     application/vnd.ms-fontobject \
                                     application/x-font-ttf \
                                     application/x-web-app-manifest+json \
                                     application/xhtml+xml \
                                     application/xml \
                                     font/opentype \
                                     image/svg+xml \
                                     image/x-icon \
                                     text/plain \
                                     text/x-component \
                                     `

What else to add? Do you have any specific request for this?

**Comment by Destroy666x** [comment]
The most common MIMEs. What you mentioned + possibly `application/x-javascript` (even though it's ahrdly used) should be enough.

**Comment by Cu8eR** [comment]
OK, thank you. I will create a PR today.
