### ISSUE TITLE
Font Size with numbers

### ISSUE THREAD

**Issue by JoshHarmon** [mybb/mybb#2217]
Currently we have 7 options at the editor toolbar for the font size:

xx-small

x-small

small

medium

large

x-large

xx-large

However, it seems to be possible to use font sizes with numbers in source edit mode. Eg.:

Code:
[size=5]Some text.[/size]
Which results in: Some text.
Problem is, while the MyBB parsing supports this when we click Preview or Post, the editor does not support it, and the size tag is removed after clicking Preview or switching to wysiwyg mode.

Another bizarre thing is that negative numbers are allowed in the size tag. Eg.:

Code:
[size=-5]Some text.[/size]
Which results in: Some text.

Worst of all, the text can even be made invisible when using values such as -10. Eg.:

Code:
[size=-10]Some text.[/size]
Which results in: Some text.

Original thread: [Font Size with numbers](http://community.mybb.com/thread-181241.html)

**Comment by Cu8eR** [comment]
I agree!

**Comment by Destroy666x** [comment]
Negative font sizes should be removed from the parser too:
https://github.com/mybb/mybb/blob/feature/inc/class_parser.php#L339
https://github.com/mybb/mybb/blob/feature/inc/class_parser.php#L709
because `pt` doesn't even accept negative values, not sure why the regex is accepting `-` in the first place.

**Comment by Destroy666x** [comment]
As for SCEditor, to fix numeric fonts, the size `html` function in our bbcode file should be something like:
```javascript
		html: function(token, attrs, content) {
			var pt = '', fontsize = attrs.defaultattr;
			
			if(!isNaN(fontsize)) {
				fontsize = parseInt(fontsize) + 10;
				
				if(fontsize < 10) {
					fontsize = 10;
					attrs.defaultattr = 0;
				} else if(fontsize > 50) {
					fontsize = 50;
					attrs.defaultattr = 40;
				}
				
				pt = 'pt';
			}
			
			return '<span data-scefontsize="' + attrs.defaultattr + '" style="font-size:' + fontsize + pt + ';">' + content + '</span>';
		}
```
if it should work similarly to parser and accept sizes from 0 to 40 only, after the parser will disallow negative sizes as mentioned above.

For full compatibility with `0`s
```javascript
			if(!size)
```
will;have to be changed to
```javascript
			if(size === 'undefined')
```

**Comment by martec** [comment]
@Destroy666x 

we can't use span tag.
if use span tag this bug will return https://github.com/mybb/mybb/issues/2228
https://github.com/mybb/mybb/pull/2229#r41813697

**Comment by martec** [comment]
need wait 2.0
solution for this appear that only in 2.0 of sceditor https://github.com/samclarke/SCEditor/issues/538

**Comment by JN-Jones** [comment]
So nothing we need to do here except updating SCE? @martec

**Comment by JN-Jones** [comment]
@mybb/developers I think we need to discuss here what exactly we want to support. @samclarke offered to create a BBCode which supports nummerical and text values using the font tag. Also pinging @Destroy666x as he already wrote some function above.
