### ISSUE TITLE
Report Bug

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2221]
I've tested this here and at my own forum and it happens on both.

Currently, the input box to enter a custom reason only appears when the other reason is selected from the drop down menu on the report button. If you open the report box on a thread and select a reason (not other) and then click off the box by clicking anywhere on the thread so it disappears and then click the report button again the input box to enter a custom reason for other will now show no matter which reason you select.

Original thread: [Report Bug](http://community.mybb.com/thread-183013.html)

**Comment by ATofighi** [comment]
Duplicated to https://github.com/mybb/mybb/issues/2199

**Comment by Destroy666x** [comment]
This is the same issue - old modal not closing properly, so marking this as duplicate.
