### ISSUE TITLE
wordfilter cannot replace strings with * in them

### ISSUE THREAD

**Issue by noxwyll** [mybb/mybb#2225]
If you set up a replace rule like this:
'c***_ck' => Toast
If a user then writes c**_*ck it will not be relaced as the \* will be treated as wildcard and it does not include itself.

**Comment by Destroy666x** [comment]
That's intended, the description in ACP states that only `A-Za-z0-9_` characters will be replaced. Not sure why, but it could be changed to all characters.

Also, please report issues on forum.

**Comment by Destroy666x** [comment]
@mybb/developers @mybb/sqa any opinion? If not, I'll change it to all characters.

**Comment by ATofighi** [comment]
It should be all characters.

**Comment by noxwyll** [comment]
I'd like to also mention that when a filter is created it is case sensitive. meaning it will only filter things if the case matches. 

The system for creating filters however is not sensitive.

This results in a filter like this Tango only filtering when it is written exactly like "Tango"
Mybb will prevent creating a filter that is written in other cases for example "tANGO"

As a result it is very easy to bypass and almost impossible to solve without editing the mybb code.

**Comment by Destroy666x** [comment]
The `i` flag should be added to the regex checker too then, because I don't think there's any reason for case sensitivity.

**Comment by noxwyll** [comment]
If you guys dont mind i got some more feedback regarding the filter.
Users commonly bypass it by using bb code inside of it. For example Sh[b][/b]it, Sh[b]i[/b]t

**Comment by Destroy666x** [comment]
Feel free to share

**Comment by antonpup** [comment]
Would it be possible to define Regular Expressions for words to replace? That way if there are variations of swear words, you can resolve them with one entry, as opposed to multiple.

Example: "`fuc[kк]`" => "`****`" Would replace both "`fuck`" and "`fucк`" (k is from Cyrillic). Instead of having two entries "`fuck`" => "`****`" and "`fucк`" => "`****`"

**Comment by Destroy666x** [comment]
Well, it would be possible, but I think they're supposed to be as simple as possible. You can currently achieve what you want with a MyCode.

**Comment by Sama34** [comment]
We could probably add a setting to allow administrators to threat the field as a regular expression instead. Not case sensitive `A-Za-z0-9_` characters should be used otherwise and by default.

This would mean you will need to figure a regex for `c*ck` by yourself.

**Comment by noxwyll** [comment]
Sounds like a very good idea.

**Comment by JN-Jones** [comment]
Ok, so the descision here is to add a new setting for this: Either the current behavior or a custom Regex? @mybb/developers

**Comment by Eldenroot** [comment]
Maybe we dont need any extra settings for that, just change to all characters and make it case insensitive

**Comment by Sama34** [comment]
I think it could be better to do what we mentioned early:
* Allow all characters by default.
* Make it case insensitive by default.
* Add a setting to treat the word replacement as a regular expression.

What do you think ?
