### ISSUE TITLE
SCEditor - Duplicate tags after re-election.

### ISSUE THREAD

**Issue by ATofighi** [mybb/mybb#2228]
Hi, 

For some time now users reporting to me bug in editor.  For example: if first select (ex. font-size), then again change this font - it not change BBCode, but adding next.

GIF presents: 

It's hard to do with so many modify tags on tapatalk for example...

Original thread: [SCEditor - Duplicate tags after re-election.](http://community.mybb.com/thread-184162.html)

**Comment by Destro-** [comment]
move to 1.8.8 ?
It is a very annoying bug and martec it have fixed this bug

**Comment by Destroy666x** [comment]
The fix isn't complete as you can see in the PR, it's priority is set to low (there are more important and annoying issues even concerning SCEditor) and the PR will mostly be remade as stated in the thread on forums.
