### ISSUE TITLE
Deprecate get_alt_bg()

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2231]
As it was mentioned somehwere else a long time ago but for some reason not added here, that funciton should be deprecated since it's not used anywhere and it doesn't make any sense (one background is always set).

Either that or we can fix it, but I see no point.

https://github.com/mybb/mybb/blob/feature/admin/inc/class_page.php#L775

**Comment by Sama34** [comment]
This shouldn't have been removed but deprecated.
