### ISSUE TITLE
MyBB logo on error page broken

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#2234]
The images is loaded from class_error.php?action=mybb_logo but there is apparently no such in the root directory.

**Comment by Destroy666x** [comment]
I'm quite sure this again allows the CSS injection: http://community.mybb.com/thread-172474.html

**Comment by Stefan-ST** [comment]
@Destroy666x basename() does indeed nothing against CSS injection. However SCRIPT_FILENAME is safe because it's the actual file executed by PHP and doesn't depend on the actual request.

**Comment by Destroy666x** [comment]
You're right, I mistook it with another `$_SERVER` variable, PHP named them awfully similarly..
