### ISSUE TITLE
Round corners in child tables inconsistent

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#2237]
![nopermission_css3_ori](https://cloud.githubusercontent.com/assets/544140/10563962/323a3e76-75a0-11e5-9ffd-90d43baa80c3.JPG)
As you can see the corners of the parent tables are correct. But both lower corners of thead in the child tables are rounded although they shouldn't be rounded.

**Comment by SvePu** [comment]
afa0aaf8dc8eb57f9004e20150c1f919f3078902
