### ISSUE TITLE
No smilies/post icons

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2256]
If all smilies are removed in ACP -> Configuration -> Smilies:
- [x] `misc.php?action=smilies` displays a weird table with no rows (it could show something like `There are currently no smilies available` instead), `misc.php?action=smilies&popup=true&editor=MyBBEditor&modal=1` modal too
- [x] SCEditor emoticon button is displayed, it could be hidden
- [x] post icons also are displayed when all of them are removed

**Comment by wagey** [comment]
I think this applies to Post Icons as well when they're all removed.

**Comment by Destroy666x** [comment]
Yeah, `$iconlist` is not checked

**Comment by wagey** [comment]
Thank you Paul.
