### ISSUE TITLE
Prefix - Staff Only = Uneditable

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2287]
Hello! We have a set of Thread Subject Prefixes that only staff can change. "Available To Groups" we have it only staff members can edit it.

However when a person without permission to Thread Prefixes tries to edit said post they will receive an error: "The selected prefix is invalid. Please select a valid prefix." and said user cannot update their post. 

We use these prefixes to mark something that only staff can mark the thread with. This is becoming an increasingly annoying issue to us, and I feel that it is a bug and not a feature.

Original thread: [Prefix - Staff Only = Uneditable](http://community.mybb.com/thread-187132.html)

**Comment by Destroy666x** [comment]
I guess checking if the prefix is changed on post update should be the fix. If it's ot, don't throw an error.

**Comment by Stefan-ST** [comment]
I can't reproduce this. The dropdown menu simply defaults to "No prefix" and removes the prefix when submitting.

**Comment by Destroy666x** [comment]
I don't know if anything was submitted in the meanwhile, but I'm sure I was able to reproduce it in 1.8.6. I'll check again.

**Comment by Destroy666x** [comment]
I can still reproduce it. More info about when it happens because OP didn't specify:
- if you quick edit a post with a disallowed prefix (full edit indeed deletes the prefix, which shouldn't happen either IMO)
- if you quick/full edit a post with a disallowed prefix in a forum which requires prefixes and you're not an admin - this part is most likely caused by: https://github.com/mybb/mybb/issues/2051

**Comment by Cu8eR** [comment]
Yes, I can confirm. Quite annoying

**Comment by Destroy666x** [comment]
Merging my old PR apparently reverted some newly introduced stuff, e.g. the `$previous_pid` conditional is missing here: https://github.com/mybb/mybb/blob/feature/inc/functions.php#L3545

**Comment by Stefan-ST** [comment]
You are right, I've missed that. Fixed: 6f15b20943534b1e1ed7f4ac2d4888477691db2e
