### ISSUE TITLE
Float number passed to mt_srand() on 32-bit systems

### ISSUE THREAD

**Issue by Devilshakerz** [mybb/mybb#2292]
The [`secure_seed_rng()`](https://github.com/mybb/mybb/blob/mybb_1806/inc/functions.php#L7659) function can generate values outside of signed integer range on 32-bit systems, returning a float value, which is then [passed to `mt_srand()`](https://github.com/mybb/mybb/blob/mybb_1806/inc/functions.php#L7748). This results in a PHP Warning being emitted.

Community discussion:
http://community.mybb.com/thread-187491.html

Changes to both `my_rand()` and `secure_seed_rng()` are recommended as in the discussion thread.

**Comment by frostschutz** [comment]
How about `return unpack('l', $output);` instead of `hexdec(substr(dechex(crc32(base64_encode(...`?

**Comment by Destroy666x** [comment]
`unpack('i', $output);` seems reasonable.

**Comment by frostschutz** [comment]
Doesn't work as well as I hoped, it only produces 32bit numbers even on 64bit machines after all. It seems I misunderstood the documentation...

**Comment by Stefan-ST** [comment]
Fixed with #2300
