### ISSUE TITLE
ACP - statistics page - Stats limit not working

### ISSUE THREAD

**Issue by Cu8eR** [mybb/mybb#2305]
Changing number of threads to be shown in Stats page does nothing. Always 15 threads are shown.

![acp-statistics_page](https://cloud.githubusercontent.com/assets/778890/12125248/9dd8b45e-b3ea-11e5-943b-08e9a5c037b7.png)

**Comment by Destroy666x** [comment]
Please report bugs on the forum first. And I don't see why a setting for the front-end statistic page should affect ACP's statistic page, unless you mean something else and the title is confusing.

**Comment by Cu8eR** [comment]
This setting should affect statistic page in board index in the footer, right?

**Comment by Destroy666x** [comment]
Yes, and it does. I don't see any problem on the front-end page.

Unless you mean the change isn't immediate, that may indeed happen because the cache needs to be updated before the setting takes effect.

**Comment by Cu8eR** [comment]
Then I am closing this. I am sorry about it, I was confused with "Statistics cache time" set to O.

**Comment by Destroy666x** [comment]
Well, this is actually a valid report, because in that case it would be good to update the cache on the setting page if the setting is changed.
