### ISSUE TITLE
[Question] Proxying images

### ISSUE THREAD

**Issue by ThePixelPony** [mybb/mybb#2307]
How would I go about proxying every user posted image to my image.php?href=url file?

It's breaking my SSL's lock in people's browsers.

I've solved the [img] tag with a custom one but avatars over http still persist.

**Comment by euantorano** [comment]
Hi,

Support requests should be made in the forum rather than on GitHub.

There is no built in support for image proxying in MyBB 1.x, but it will be available in 2.0 which is our future major release.
