### ISSUE TITLE
Custom avatar dimensions 

### ISSUE THREAD

**Issue by Scarsz** [mybb/mybb#2309]
First time contributing to MyBB, confused where to start as far as putting the idea out there. Please don't throw rocks at me.

Here's a feature request: to be able to set a custom avatar width and height for a group to be applied to it's users.

Configuration field for a group: http://i.imgur.com/aEYI20Z.png

Already working on this, will make a pull request in a day or so- saving the field to the database and stuff already works, just need to make it functional in the upload function file

**Comment by Destroy666x** [comment]
Thanks, but suggestions should be made here first: http://community.mybb.com/forum-158.html and get accepted by the team.

https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md

**Comment by Cu8eR** [comment]
Better to create a plugin for thís...
