### ISSUE TITLE
Not a good way to update counters

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2313]
As mentioned somewhere else, this shouldn't exist:
https://github.com/mybb/mybb/blob/feature/private.php#L54-L59

Counters seem to be correctly updated everywhere in the core, so it should be safe to remove without replacing it with anything more proper (e.g. recounting in the user cleanup task).

**Comment by euantorano** [comment]
This was mentioned on Slack IIRC. It should be safe to remove.
