### ISSUE TITLE
Data type-related PHP errors

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2316]
So I keep getting flooded with errors on my email but I cant seem to know what is causing these errors.
These are the current errors:

---

Type: 2
File: inc/functions.php (Line no. 4930)
Message
urlencode() expects parameter 1 to be string, array given

---

Type: 2
File: global.php (Line no. 46)
Message
Illegal offset type in isset or empty

I'm using MyBB 1.8.5 and PHP 5.6.11
Any help is appreciated.

Original thread: [Errors Flooding Me.](http://community.mybb.com/thread-173684.html)

**Comment by Destroy666x** [comment]
Possible fixes are mentioned here (the lines may be slightly wrong): http://community.mybb.com/thread-173684-post-1172263.html#pid1172263

**Comment by JN-Jones** [comment]
As PHP 7 has changed a few things (#2157, #2502) this may either be fixed already or should be fixed ASAP @mybb/developers

**Comment by hrubymar10** [comment]
`Warning [2] urlencode() expects parameter 1 to be string, array given - Line: 4964 - File: inc/functions.php PHP 7.0.15-1~dotdeb+8.1 (Linux)`

This bug is also on line **4964** in **inc/functions.php** .
Can someone please post here any workaround for this line? Should I add here some kind of variable type check? But what should I do, when given variable will be for example int?

Thank you

**Comment by Cu8eeeR** [comment]
I think this should be fixed together with #2743 to make MyBB fully compatible

@euantorano @Stefan-ST @Devilshakerz 

I would like to create a PR but my knowledge of php is not enough

**Comment by Ben-MyBB** [comment]
@euantorano @effone Anyone able to take a look at this?

**Comment by effone** [comment]
While we have already fixed some; can anyone trace any subjected instance? I can't find any ...
If no then this can be closed.
@mybb/developers @Eldenroot @AndreRl

**Comment by Eldenroot** [comment]
Last time when I wanted to create a PR for that I didnt find any of these. I think it was fixed by another commit or I am blind (my php skill is not great, but from my point of view there are not any of them).

**Comment by effone** [comment]
Majority of the identified code locations have been fixed by this PR:
https://github.com/mybb/mybb/pull/3343

This is being closed for further identification of such errors / warnings.
