### ISSUE TITLE
Signature Bug on Postbit?

### ISSUE THREAD

**Issue by jaydee9296** [mybb/mybb#2345]
As you can see, I'm using a custom theme and when I checked the templates the signature post is present even though I tried to switch to default theme using a local server in postbit templates. Then, I tried to use a signature image userbar for it to display on my forum posts but when Iooked at it there is no signature. Is this some kind of a bug or what?

![forum12](https://cloud.githubusercontent.com/assets/8472952/12909811/b3364256-cf3f-11e5-9c14-8ca014a98f7c.PNG)

**Comment by Stefan-ST** [comment]
Please use our forums for support requests: http://community.mybb.com/
