### ISSUE TITLE
Remove "Are You a Human" captcha

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#2351]
http://community.mybb.com/thread-188436.html
http://blog.areyouahuman.com/goodbye_playthru/

**Comment by labrocca** [comment]
Are you sure you guys didn't goof this?  Default MyBB captcha has stopped working.

**Comment by euantorano** [comment]
@labrocca Is it just not showing up, or is there some kind of error? I've not noticed any problems personally.

**Comment by labrocca** [comment]
On all my forums running 1.8.7 it doesn't show up.  Blank space.  Try it yourself on sportforum.net which is a pure 1.8 install with default templates and no plugins.  Didn't even notice that after last upgrade captcha stopped working and zero registrations on all my 1.8x sites. 

http://community.mybb.com/thread-188253.html

Someone else with same problem. I suspect most people use recaptcha.  

Unsure if this is a library issue but this 100% changed with the latest update.  I'm going through changes now to see if anything I can figure out and fix. If I do I will let you know but definitely it broke on latest update.

**Comment by kawaii** [comment]
@labrocca considered simply switching to Google's No CAPTCHA reCAPTCHA API? You'll get nice analytics and a significant decrease in unwanted registrations.

**Comment by labrocca** [comment]
I did use recaptcha but that's not the point.  A feature is broken. One that some people may not have noticed and are losing member registrations. Also this might effect plugins using default MyBB captcha which I haven't yet tested.

**Comment by euantorano** [comment]
Yep, it's definitely broken. Just tested on a local board. I'll try to see if I can work out the cause.

**Comment by labrocca** [comment]
Glad you confirmed. My job is done.  Have fun fixing.

**Comment by kawaii** [comment]
@labrocca @euantorano Are you guys sure? I just did exactly the same thing on 1.8.7 and it works perfectly.

![](https://i.imgur.com/6CQiLj7.png)

**Comment by euantorano** [comment]
It's possible my local install is broken, I'm setting up a fresh install to confirm it.

**Comment by labrocca** [comment]
Could be a discrepancy with the upgrade package.  So if a fresh install works then I suggest a close review of the upgrade package.

**Comment by euantorano** [comment]
Just tested on an upgraded board and it works for me there - https://www.mybbstuff.com/member.php

My local install is also working after having done a clean install with source files (rather than ones I've edited). Have you double checked that GD works at all @labrocca?

**Comment by labrocca** [comment]
Sites are at Dreamhost.  Everything worked fine on 5 MyBB sites hosted there up until 1.8.7 upgrade.  Three of those installs are default templates.  Sportforum is clean as hell with no plugins at all. The only change is the logo.  

http://www.sportforum.net/gdtest.php

Even if it worked on a fresh install for me that doesn't explain why it broke on upgrade.  And trust me...if it's broken for me it's broken for others. Some may not have noticed and possibly most use recaptcha for added spam prevention.

**Comment by Destroy666x** [comment]
Did you use AYAH before upgrading?

**Comment by labrocca** [comment]
I have always used default MyBB captcha for all my sites.  Going through the files now.  I suspect it's a template change that did this.

**Comment by Destroy666x** [comment]
The only template changes in https://github.com/mybb/mybb/pull/2352/files are for `member_register_regimage_ayah` and `post_captcha_ayah`. MyBB captcha doesn't use any of those. 

There's a known issue with this query: https://github.com/mybb/mybb/pull/2352/files#diff-b144ffcea33f436c5ae14b52bc18c047R48 in pgsql/SQLite, I don't see anything else that may have broken captcha in that PR. I don't se any other PR connected directly with captchas and merged into 1.8.7.

**Comment by labrocca** [comment]
Any changes in the database table?

**Comment by Destroy666x** [comment]
Not regarding captcha, except the one I linked and 2 lines below.

Also, make sure there's no PHP file that has BOM. You can use http://community.mybb.com/mods.php?action=view&pid=638 to quickly find files that have it.

**Comment by labrocca** [comment]
Tried BOM and also checked file verification. Which btw inc/functions.php does not validate even from the full package.

**Comment by Stefan-ST** [comment]
@labrocca Unfortunately I'm not able to reproduce your issue either. But it is probably not related to this ticket as it doesn't even touch the generation of the captcha.

btw:
>http://community.mybb.com/thread-188253.html

>Someone else with same problem. I suspect most people use recaptcha.

>Unsure if this is a library issue but this 100% changed with the latest update.

This thread was created before the release of 1.8.7. And it doesn't appear to be the same issue at all.
