### ISSUE TITLE
Per theme default avatar

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2363]
Make it possible to use something like `{theme}` for the default avatar as suggested here: http://community.mybb.com/thread-172906.html

**Comment by kawaii** [comment]
IMO theme needs to be parsed globally, it's really useful for forum owners with both a light and dark theme. The {lang} variable is also really nice although I don't use it as much.

**Comment by Destroy666x** [comment]
I'm not quite sure what you mean, but feel free to suggest it on the forum. `{lang}` is definitely connected with this issue since there are no lang string on the default avatar.

**Comment by kawaii** [comment]
I mean that it would be nice if we could use it in more places, it's a really nice feature. ^_^

**Comment by Destroy666x** [comment]
It is usable in smilies, group images/stars, attachment images, post icons and of course themes. Is there anything else except default avatar where it's missing?
