### ISSUE TITLE
ACP not using format_avatar() for formatting avatars

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2367]
As the title says and as mentioned here: https://github.com/mybb/mybb/pull/2364 Shouldn't be too hard too change, just the extraordinary scaling needs to be considered. Also `../` before avatars that use relative path, which could be added in `format_avatar()` if `IN_ADMINCP` is defined.

**Comment by JN-Jones** [comment]
@euantorano Maybe you could look at this as you're going to work on the acp avatars anyways?

**Comment by euantorano** [comment]
No problem, I'll have a look.
