### ISSUE TITLE
Incorrect user activity when action is unset

### ISSUE THREAD

**Issue by JordanMussi** [mybb/mybb#2371]
At the moment if a Moderator is viewing the Mod CP homepage, on the Who's Online page their location is shown as "Viewing Reported Posts" rather than "Viewing Moderator CP".

The fix is rather simple, change [functions_online.php#228-232](https://github.com/mybb/mybb/blob/mybb_1807/inc/functions_online.php#L228L232) from:

``` php
            if(!isset($parameters['action']))
            {
                $parameters['action'] = 0;
            }
```

to:

``` php
            if(!isset($parameters['action']))
            {
                $parameters['action'] = 0;
                $user_activity['activity'] = "modcp";
                break;
            }
```

**Comment by JordanMussi** [comment]
There might be other places where this sort of thing happens. I haven't checked though...

**Comment by JN-Jones** [comment]
Uhm @Cu8eR @dequeues @Destroy666x Any reason #2371 has been closed without any new PR/fix?

**Comment by Cu8eR** [comment]
@JN-Jones - my PR was not complete, feel free to fix this.
