### ISSUE TITLE
Report spam possible with PM/E-mail report medium

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2378]
You can send countless reports about the same user/post/reputation, the duplicate checks only work if ModCP reporting is enabled (proably because the report is saved to DB only then, haven't looked yet). I'm not sure why. It can be an annoyance if someone notices which medium is used and tries to abuse it.

**Comment by dequeues** [comment]
You're right. https://github.com/mybb/mybb/blob/fda43f3dc95421a50bf2f6eb0de0a92a10f1490b/inc/functions_modcp.php#L266-L293

I'm not sure a way to go around this though. We could add to `reportedcontent` and then update it when the PM is read (not entirely sure a concrete way). Not too sure about emails, though. Maybe a callback?

**Comment by Destroy666x** [comment]
>  and then update it when the PM is read (not entirely sure a concrete way). Not too sure about emails, though. Maybe a callback?

You mean `reportstatus`? I don't think updating that field is needed, normally you need to mark it as read manually too.

**Comment by dequeues** [comment]
That would work, with the MCP medium as of now, if a report gets marked as read then the content is enabled to reported again. I don't think that is much of an issue, though.

**Comment by Destroy666x** [comment]
Yeah, not a big deal since it'd affect only the reporting person.
