### ISSUE TITLE
my_date - no time for non-relative $format

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2382]
Not sure if this needs to be considered a bug, but posting it here, because to me it looks like one. 

This bug only occurs when not the relative time format, but the time format from settings is used. It might be possible, that this is not the case anywhere in the code, then it would be no bug, but dead code ^^

https://github.com/mybb/mybb/blob/feature/inc/functions.php#L482 Only today / yesterday is rendered, but no exact time. 

For relative time the exact time is added in case it is more than 12h ago https://github.com/mybb/mybb/blob/feature/inc/functions.php#L474

I traced it down to the commit, where the my_date function was adapted to support relative time at to me it looks like adding the time has been forgotten for non relative timestamps ... 

https://github.com/mybb/mybb/commit/508f7808085565ed77cc0aea3ad743fb60a4e192#diff-7fe6e55397c77ab9a0f5d57bc4cbe5b9L391

Original thread: [my_date - no relative time](http://community.mybb.com/thread-190208.html)

**Comment by Shade-** [comment]
If my interpretation is correct, this is intended. There are multiple places where relative time is not used, such as [L277](https://github.com/mybb/mybb/blob/feature/warnings.php#L277), [L657](https://github.com/mybb/mybb/blob/feature/warnings.php#L657) and [L669](https://github.com/mybb/mybb/blob/feature/warnings.php#L669); adding time automatically there would mean breaking all those places where timeformat is used contextually, doubling the time. I guess this behavior is intended. @mybb/developers

**Comment by PaulBender** [comment]
Looking at the code, it is intended; if the format isn't set to relative it simply formats the timestamp according to [PHP's date function](http://php.net/manual/en/function.date.php).

However it wouldn't hurt to add another format for non-relative times that include both the date and time with proper separator. I was looking at this possibility for the recent issues with the hover over relative times.
