### ISSUE TITLE
ACP language and button function error

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2385]
Here you see a deficiency.
user_banning.lang.php:  &#36; l [ 'search_user'] = 'User Search';

There admin/modules/user/banning.php code in the search button.
&#36; Buttons [] = &#36; form-&gt; generate_submit_butto's (&#36; lang-&gt; search_user, array ('name' =&gt; 'search'));
There's something wrong button, search entered user bans.

Original thread: [ACP language and button function error](http://community.mybb.com/thread-190249.html)

**Comment by Destroy666x** [comment]
Should be moved from config_banning lang file where it's useless

**Comment by xykul** [comment]
I think the search button in admin/modules/user/banning.php 611 line should be removed.
`$buttons[] = $form->generate_submit_button($lang->search_user, array('name' => 'search'));`

If you use this button, the user bans

**Comment by Destroy666x** [comment]
@xykul, are you sure? It just finds the user for me

**Comment by xykul** [comment]
Interesting, button user name english/admin/banning.lang.php: `$l['search_user'] = 'Search User';` Line Without bans, language line when doing search.

**Comment by Destroy666x** [comment]
I'm not sure if I understand, but it might ban if the button text is empty because for some reason the value is checked, `isset()` should be enough. It could actually be corrected too.

**Comment by xykul** [comment]
admin/modules/user/banning.php line 601 is changed as the following problem can be solved.
`$buttons[] = $form->generate_submit_button($lang->search_for_a_user, array('name' => 'search'));`
