### ISSUE TITLE
The #container in CSS default theme has a typo, causing cutting off problems

### ISSUE THREAD

**Issue by antonpup** [mybb/mybb#2388]
There is a typo in the default theme CSS for #container which causes the page to be cut off at certain window widths.
Example:
![Example](http://puu.sh/o3GeP/dc7f8c83f6.png)

Where the problem is:
![Problem](http://puu.sh/o3Gmo/a6bb8af102.png)

It's missing a `;` after `min-width: 990px`
Code should be:
```
text-align: left;
line-height: 1.4;
margin: 0;
min-width: 990px;
font-family: Tahoma, Verdana, Arial, Sans-Serif;
```

**Comment by Destroy666x** [comment]
https://github.com/mybb/mybb/blob/feature/install/resources/mybb_theme.xml#L39-L47? I don't really see any missing ; there. Make sure to report only issues that are available on clean MyBB forums. Also, please check: https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md#reporting-issues
