### ISSUE TITLE
SCEditor [img] code issues

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2391]
As reported here: https://github.com/mybb/mybb/pull/2390#issuecomment-205403645
- [ ] `align` should be supported but it isn't (thus it's removed - there's also another SCEditor issue about BBCodes stripping unknown attributes EDIT: https://github.com/mybb/mybb/issues/1674)
- [ ] 0 width/height should probably be disabled

**Comment by martec** [comment]
I can made PR of this issue. I will treat as different issue of #1674.
But i will made after mybb team accept this fix https://github.com/mybb/mybb/pull/2229 . I won't made other PR that will break another my PR. This is a waste of time to solve conflict issue (made rebase etc... It is very boring task.)

**Comment by Cu8eR** [comment]
@martec I agree, same issue for me with PRs. I cannot continue in my work without merging my PRs or PRs from others devs. It is a waste of time to rebase them and foolow new changes. Until that I cannot push fixes or change my PRs

**Comment by Cu8eR** [comment]
@martec - can you please make a PR with your fix?

**Comment by martec** [comment]
I will not made anything that will break another mine PR.

**Comment by JN-Jones** [comment]
@martec There doesn't seem to be any open PR of yours so can you add a PR for this now?
