### ISSUE TITLE
Option to hide location/status activity in profile page

### ISSUE THREAD

**Issue by JohOply** [mybb/mybb#2393]
Hi guys,

On my forum, I have private forums for staff. But anyone can view which topic admin is reading.
Could you add an option to hide to "simple" members the location/status of staff's members?

For instance:
- Hide location : true/false
- Bypass hiding location : true/false (allow staff's members to view everyone)

On the profile page, simply display "Online (@ TIME)" 

Thanks for reading :)

**Comment by Cu8eR** [comment]
GitHub is not a place where you can write your requests for features etc. For that purpose use MyBB forum!

**Comment by JordanMussi** [comment]
I think the functionality you are looking for is already in MyBB. Users don't see the names of threads for forums they can't read threads in and they also don't see forum names for forums they can't view.

**Comment by JohOply** [comment]
I just verified that and you are right! It's weird.. I just update in 1.8.7, maybe a little change

Thank you guy
