### ISSUE TITLE
captcha.php using slow CSPRNG

### ISSUE THREAD

**Issue by Devilshakerz** [mybb/mybb#2394]
[MyBB's CAPTCHA](https://github.com/mybb/mybb/blob/feature/captcha.php) uses [my_rand()](https://github.com/mybb/mybb/blob/mybb_1807/inc/functions.php#L7841), which became slow after recent refurbishment (it's being called 12113, 12227, or 13009 times) - PHP's `rand()` could be used instead.

**Comment by JoshHarmon** [comment]
@Devilshakerz If you'd be up to reviewing the fix on my fork, I'll open the PR if it's ready. Replaced all occurrences of my_rand in the file with rand.
