### ISSUE TITLE
Administrator Activation Registration Method fails

### ISSUE THREAD

**Issue by David263** [mybb/mybb#2395]
1. I installed MyBB on centos (Linux).
2. I created a forum and set its registration method to Administrator Activation.
3. I made sure I was logged **out**.
4. I clicked "Need to register?" on the home page.
5. I completed the registration form.
6. I was told I would receive an activation email (which I received but ignored).
7. After step 6 I was logged in as user "Betty Charlesba3jsneT", where "Betty Charles" was the user name I gave, and "ba3jsneT" was the password I gave.
8. I was able to view the forum posting index.
9. I was able to view an existing forum posting.

This appears to be a complete failure of the Administrator Activation method, along with other errors. It violates the security implied by "Administrator Activation".

I can't use MyBB like this. Did I set up something wrong?

**Comment by Ben-Conway** [comment]
Please ask for support at the community forums. http://community.mybb.com/forum-176.html

**Comment by Destroy666x** [comment]
But to answer it shortly here:

> Did I set up something wrong?

Yes.
