### ISSUE TITLE
"Notice: Undefined index: num_threads" when moving threads

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2419]
mybb_1807

Code:
Notice: Undefined index: num_threads in inc/class_moderation.php on line 2372
When moving threads with replies (other than topic starter)

Fix: add

Code:
if(!isset(&#36;user_counters[&#36;posters['uid']]['num_threads']))
{
    &#36;user_counters[&#36;posters['uid']]['num_threads'] = 0;
}

after line 2296

Original thread: ["Notice: Undefined index: num_threads" when moving threads](http://community.mybb.com/thread-193872.html)

**Comment by Destroy666x** [comment]
The fix is ok but an isset check would be better before the index is used in the update query - more optimal.

**Comment by JN-Jones** [comment]
@Stefan-ST This looks rather simple so could you fix this in 1.8.9?
