### ISSUE TITLE
Users.php error

### ISSUE THREAD

**Issue by Lukkez** [mybb/mybb#2420]
Hey, i got a error when browsing users, i just wanted to make some things, some screenshoots
![image](https://cloud.githubusercontent.com/assets/15003706/15903897/57df1f6e-2d85-11e6-8274-a2a7dc758979.png)
![image](https://cloud.githubusercontent.com/assets/15003706/15903920/6a04ab0a-2d85-11e6-9de3-3c3987027272.png)
The first is on main page, the 2nd is when i search users

**Comment by Destroy666x** [comment]
The report in invalid, the function exists in the core: https://github.com/mybb/mybb/blob/7c8092bf971d12b15b76af5fa725c00e1ce24f94/admin/inc/functions_view_manager.php#L664

Support questions should be asked on our forum.

**Comment by Lukkez** [comment]
So how to fix? I got that, is a problem because i can't change the groups of users

**Comment by Destroy666x** [comment]
> Support questions should be asked on our forum.

But, since I said the function exists and showed you where, the first logical step would be checking if it is there in your forum's files.
