### ISSUE TITLE
Installation fails on aggressive opcache settings

### ISSUE THREAD

**Issue by GeorgeLVP** [mybb/mybb#2422]
mydomain.com/install/index.php

![untitled1](https://cloud.githubusercontent.com/assets/15123289/16038088/67f12876-321b-11e6-9abc-8d28cab000e5.png)

PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by Ben-Conway** [comment]
Ensure your install directory exists. If it does open a topic on the community forums.
