### ISSUE TITLE
Admin interface issues on IPv6

### ISSUE THREAD

**Issue by cockroach** [mybb/mybb#2427]
The default settings do not appear to allow access to the admin interface via IPv6. Setting ADMIN_IP_SEGMENTS in admin/index.php to 0 fixes this.

It might make sense to either change the default value or modify the check in a way that makes it also accept IPv6 addresses.

**Comment by Destroy666x** [comment]
The report is partially invalid - it's already set to 0 by default: https://github.com/mybb/mybb/blob/feature/admin/index.php#L15

Would be nice to fix it for IPv6 though, I believe it has been discussed a long time ago.
