### ISSUE TITLE
My Alerts wysiwyg editor not shaded on alerts pop-up

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2441]
When you're on a page with the wysiwyg editor and click on "View Alerts", the alerts pop up and it gets highlighted, while the background becomes shaded (totally fine so far). but then the wysiwyg editor is not shaded, its still lighted.

Screenshot: http://image.prntscr.com/image/e715f667f90b41aeb22f752c2b2b9c44.png

Original thread: [My Alerts wysiwyg editor not shaded on alerts pop-up](http://community.mybb.com/thread-194899.html)

**Comment by Destroy666x** [comment]
Is this surely in the correct place?

**Comment by euantorano** [comment]
@Destroy666x I was talking about this on Slack last night. MyAlerts by default uses MyBB's built in modals. I tested on a near stock forum and the MyAlerts modal was given a `z-index` of 2, the mask was given 1, and the editor was given 3.

My test board is using the old approach of using `rel="modal"` rather than an `onclick` handler though, so I need to update the templates there to use `onclick` the same as the buddylist does in the standard theme. Once I've checked that, I can either confirm or close this issue.

**Comment by Destroy666x** [comment]
It'll definitely work with the same `onclick` because our wrapper function takes care of it: https://github.com/mybb/mybb/blob/feature/jscripts/general.js#L75. As for fixing the `rel` method, we could do it by extending it, but `MyBB.popupWindows()` should be used as standard by devs IMO.

**Comment by euantorano** [comment]
Alright, it's probably easiest to leave it as is then. I'd rather not go extending/patching third party stuff for 1.8.8.

**Comment by thelovelyone** [comment]
Why was this rejected so? @euantorano already provided a fix for it, editing the myalerts_headericon template and having the latests alert.php file installed on the server.

**Comment by Destroy666x** [comment]
Umm... You kind of answered yourself. This is not MyAlerts repository.

**Comment by thelovelyone** [comment]
Oh ok, why was it posted here anyway then. :P
