### ISSUE TITLE
MyBB not respecting https:// URLs of certain resources

### ISSUE THREAD

**Issue by Devilshakerz** [mybb/mybb#2443]
https://github.com/mybb/mybb/blob/mybb_1807/admin/modules/config/attachment_types.php#L322
https://github.com/mybb/mybb/blob/mybb_1807/admin/modules/config/post_icons.php#L468
https://github.com/mybb/mybb/blob/mybb_1807/admin/modules/config/smilies.php#L646
https://github.com/mybb/mybb/blob/mybb_1807/admin/modules/config/smilies.php#L729
https://github.com/mybb/mybb/blob/mybb_1807/admin/modules/user/users.php#L1485
https://github.com/mybb/mybb/blob/mybb_1807/usercp.php#L2245

Not covered by #1589:
https://github.com/mybb/mybb/blob/mybb_1807/inc/functions_serverstats.php#L215

**Comment by Sama34** [comment]
#1589 ?

**Comment by Destroy666x** [comment]
Yeah, I don't see the point of this PR while the `my_validate_url()` one seems to correct all of these. It'll only create conflicts.

**Comment by Devilshakerz** [comment]
Seems to be a duplicate, except ` inc/functions_serverstats.php` - I'll reduce the PR.
