### ISSUE TITLE
Mark All Reports bug

### ISSUE THREAD

**Issue by Ben-Conway** [mybb/mybb#2446]
From modcp.php/action=reports page, if we check the box for mark all reports and then remove the check for one individual report the mark all button doesnt get uncheked..

Steps to reproduce:
1. First report two or more posts
2. Click on the unread report notice to go to the reports page.
3. Now check the box for mark all. 
4. then from the list of reported posts, remove check for any one report
5. Now, the mark all check box remains checked and hitting the mark read button clears all reports, including the one unchecked in step 4.

Expected Behavior: when we remove check on any one individual report, the mark all button should get unchecked automatically

Original thread: [Mark All Reports bug](http://community.mybb.com/thread-195596.html)

**Comment by JordanMussi** [comment]
Fixed in #2461. :smiley:
