### ISSUE TITLE
Use a stylesheet for select2.css

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2450]
I suggest that rather than hardcoding the url to the select2.css in the templates that another stylesheet is added in the themes section of the ACP (rather like the thread_status.css or usercp.css). 

This will make it easier to provide matching select2.css, especially for those forums with a flat or black theme. I know that an import url can be added at the top of the css, but using a stylesheet in the theme is more consistent imo and helps separate concerns and avoids the issues around @import.

http://stackoverflow.com/questions/10036...use-import

Original thread: [Use a stylesheet for select2.css](http://community.mybb.com/thread-170230.html)

**Comment by Eric-Jackson** [comment]
Would this at all involve the ability to remove stylesheets? Regardless I'm glad this is getting looked at.

**Comment by Destroy666x** [comment]
Considering that stylesheets can't be updated and we update Select2, I don't think this will work.

**Comment by Sama34** [comment]
That is correct, MyBB doesn't update stylesheets so updating Select2 could be a pain in the future.

**Comment by Eric-Jackson** [comment]
Could the issue with updating stylesheets not be corrected? From here it seems that would solve a lot of other issues.

**Comment by Destroy666x** [comment]
If someone writes that feature and makes sure it doesn't collide with theme/user changes, then yes, it could. Feel free to.

**Comment by euantorano** [comment]
When did we last update the select2 CSS file, out of interest? Have we ever actually updated it in the 1.8 cycle so far?

**Comment by Stefan-ST** [comment]
It has been changed a few times: https://github.com/mybb/mybb/commits/feature/jscripts/select2/select2.css

**Comment by JN-Jones** [comment]
@mybb/management @mybb/developers Due to the reasons mentioned above (css updating isn't something we should add in 1.8 at this point) I'd like to reject this. Any other opinion?

**Comment by euantorano** [comment]
I agree, rejecting is the easiest thing to do.
