### ISSUE TITLE
Hash instead of the password at the "forgot my password"

### ISSUE THREAD

**Issue by I-n-d-e-r** [mybb/mybb#2456]
Hash instead of the password at the "forgot my password". I did not change in any way member.php file in the email displays the password hash added to the database instead of the decrypted password to login.

![zrzut ekranu z 2016-08-06 10-17-30](https://cloud.githubusercontent.com/assets/18102267/17455658/46507050-5bbf-11e6-9b56-50445066ef67.png)

**Comment by Destroy666x** [comment]
Looks like this https://github.com/mybb/mybb/pull/1850 still wasn't fully checked
