### ISSUE TITLE
Add option to set cookies with Secure flag

### ISSUE THREAD

**Issue by Devilshakerz** [mybb/mybb#2464]
Server: https://github.com/mybb/mybb/blob/mybb_1807/inc/functions.php#L1810
Client: https://github.com/mybb/mybb/blob/mybb_1807/jscripts/general.js#L483

as suggested in https://community.mybb.com/thread-198899.html

**Comment by andrewjs18** [comment]
I imagine this would cover this line as well?  https://github.com/mybb/mybb/blob/mybb_1807/inc/functions.php#L1856

I modified that line to read as:
```
$cookie .= "; Secure";
```

**Comment by Devilshakerz** [comment]
Yes, though cookies set with JavaScript wouldn't have this attribute.
The `Secure` flag would be added in similar fashion, depending on a setting.

**Comment by Devilshakerz** [comment]
The `headerinclude` template version was not updated for https://github.com/mybb/mybb/pull/2468/files#diff-05b404fc75b0e5bd6d57c79b667b44b8
