### ISSUE TITLE
: in url isn't handled correctly

### ISSUE THREAD

**Issue by CvH** [mybb/mybb#2467]
If I insert a link (some Wiki) `http://some.url/index.php?title=HOW_TO:Provide_Logfile` it don't recognize the full url - it stops at `:P` and inserts an emoticon.

the result after posting this url is
`http://some.url/index.php?title=HOW_TO[img]http://some.url/path/tongue.png[/img]rovide_Logfile`

**Comment by CvH** [comment]
sorry for the noise - probably an CKEditor problem

**Comment by euantorano** [comment]
PS: In the future, please report issues on the forum, which we will then later push to here once confirmed.

**Comment by CvH** [comment]
@euantorano 
CONTRIBUTING.md is sadly the best hidden thing at gh, pr templates would fix this ;) 
(will follow your guidelines next time)

**Comment by euantorano** [comment]
@CvH Yep, unfortunately. I wish there was a way to disable the reporting of issues, but still have issues that can be created via the API (which is how we do it).

The 2.0 repositories don't have any of these kind of rules - they operate more like a normal project as we don't have any legacy rules to hang on to ;)
