### ISSUE TITLE
 threads get marked as read by just visiting forum categories

### ISSUE THREAD

**Issue by kernschmelze** [mybb/mybb#2471]
There is a bug that gets threads marked as read by just visiting forum categories.
I hope it is acceptable to refer you to the forum thread discussing the bug to avoid redundant description of details.
https://community.mybb.com/thread-202223.html

I have written a fix. See the thread, please.
However I am new to Git(Hub).
Please don't be angry if I make any annoying mistake in the process to do the things necessary for a pull request.
Thank you for your understanding.

**Comment by Cu8eR** [comment]
It should be fixed in MyBB v1.8.8
https://github.com/mybb/mybb/issues/2167

Am I right?

**Comment by katosdev** [comment]
Unable to replicate this myself, @euantorano might be able to provide an insight here.

**Comment by katosdev** [comment]
Please refer to : https://github.com/mybb/mybb/pull/2169 as this should solve your issue.
You can apply this fix yourself, or update to 1.8.8 as @Cu8eR stated above.

**Comment by Cu8eR** [comment]
@PaulBender @Destroy666x and others - this is fixed in 1.8.8, it can be closed
