### ISSUE TITLE
Editing of announcements in ModCP doesn't work

### ISSUE THREAD

**Issue by ckoecher** [mybb/mybb#2496]
A few minutes ago I've tried to update an old announcement (starting date in 2007) in my forums via the ModCP. After submitting I've got the following error message:

> The starting date for the announcement is invalid.

If I replace the date by another one in present or future the error doesn't occur. But in this case the starting date will not be saved. Instead the timestamp seems to contain only the difference from now till the given date (e.g. if I set the date in 5 minutes it shows 1.1.1970 at 1:00 GMT).

Note, that this error only occurs in ModCP. Editing in AdminCP seems to work perfectly.
I could reproduce this error on both my live system and my local test environment. In both cases the forums run on an Apache server with PHP 7.0 and MyBB 1.8.8.

**Comment by JN-Jones** [comment]
Can confirm that editing announcements checks for the start date to be in the future which doesn't make sense on editing.

Anyways, please report issues on our forums next time as stated on our contributing file: https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md

**Comment by JN-Jones** [comment]
@mybb/developers @mybb/sqa Simply removing the check for the start date should be fine shouldn't it? Don't think there's any case where that would produce new issues.

**Comment by euantorano** [comment]
Off the top of my head, that should be fine.

**Comment by Cu8eeeR** [comment]
@JN-Jones - can you please push the FIX? Is it related to this issue? https://community.mybb.com/thread-205823.html

**Comment by JN-Jones** [comment]
I don't have a working fix here, it was just a potential fix I suggested.

**Comment by Ben-Conway** [comment]
Set as high priority as quite a few people have been complaining about this issue.
