### ISSUE TITLE
Signature preview saves the signature?

### ISSUE THREAD

**Issue by WhiteKitty00** [mybb/mybb#2509]
Just wanted to note, that upon clicking the 'Preview Signature' button, it saves the signature already, using MyBB 1.8.8 I've checked the source code, and the button code for the preview is like this:

```
<input type="submit" class="button" name="submit" value="Update Signature"/>
<input type="submit" class="button" name="preview" value="Preview Signature"/>
```

**Comment by JN-Jones** [comment]
This was introduced in #2347

Anyways, please report issues on our forums next time as stated on our contributing file: https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md
