### ISSUE TITLE
Last post not updated when approving the first post using inline mod tools

### ISSUE THREAD

**Issue by Shade-** [mybb/mybb#2516]
Last post data is not updated accordingly when you post a reply to an unapproved thread and subsequently approve the first post of the thread by using inline moderation tools.

### Steps to reproduce
- Post a thread and unapprove the thread;
- Post a reply to the unapproved thread;
- Approve the first post using inline moderation tools.

**Comment by Shade-** [comment]
This is related to https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php#L2468. approve_threads() does not update_last_post() while performing an update_forum_lastpost(). The solution would imply adding update_last_post() either to approve_threads() or above L2468. What do you think guys? @mybb/community-team

**Comment by Ben-Conway** [comment]
@euantorano https://github.com/mybb/mybb/issues/1392 wouldn't they of been related? This is the exact issue I brought up here: https://community.mybb.com/thread-187779.html

**Comment by euantorano** [comment]
Yep, seems linked to #2072 too - just hasn't been fixed properly yet unfortunately.

**Comment by Ben-Conway** [comment]
Since this has been present for a while now and hasn't been fixed in multiple PR's, can we set this as a high priority issue @euantorano ?

**Comment by euantorano** [comment]
Probably

**Comment by Shade-** [comment]
This happens also when posting to an unapproved thread and approving the whole thread. So I'd discard the option to add `update_last_post()` to `approve_posts()` and instead add it in `approve_threads()` to cover the two situations with the best optimization possible.

A more radical approach would be editing the postHandler to run `update_last_post()` even when a thread is unapproved, but if not updating the last poster when posting to unapproved threads is intentional, this is not required.
