### ISSUE TITLE
Invalid values used with operators expecting numbers raise E_WARNING on PHP 7.1

### ISSUE THREAD

**Issue by Devilshakerz** [mybb/mybb#2517]
https://github.com/mybb/mybb/blob/mybb_1808/inc/functions_calendar.php#L453-L461
https://github.com/mybb/mybb/blob/mybb_1808/calendar.php#L1536-L1545
`$offset` can be empty or non-numerical; more files can be affected.

http://php.net/manual/en/migration71.other-changes.php

**Comment by Shade-** [comment]
As far as I am concerned, timezone is stored in varchar() but should be int(). Casting as `(int)` should be fine.

**Comment by Stefan-ST** [comment]
Timezones are not integers. Float could work though.

**Comment by Shade-** [comment]
Ops, sorry that's right.

**Comment by JN-Jones** [comment]
There may definitely be other places where variables are passed to php functions which may throw a warning. Also related to another issue I've reported last week where the same happened

**Comment by Cu8eeeR** [comment]
I think this should be fixed in 1.8.9, because it would be better to avoid support threads on MyBB board about warnings due to php 7.1.

**Comment by Devilshakerz** [comment]
Numerical settings can have empty or invalid values: https://github.com/mybb/mybb/search?utf8=%E2%9C%93&q=gmdate+settings&type=Code

**Comment by Ben-Conway** [comment]
Good work @Devilshakerz we just need to get this tested now.
