### ISSUE TITLE
ModCP - Profileditor

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2541]
1. Code:http://www.xxx.info/modcp.php?action=finduser2. then search username with special character
3. then look for user
4. special character not perfect

idea?

Original thread: [ModCP - Profileditor](https://community.mybb.com/thread-179011.html)

**Comment by Cu8eeeR** [comment]
Is it a proper solution delete this lane in modcp.php? I am not sure about it (yeah, it fixes the issue but what about any side effect?)

$mybb->input[$field] = urlencode($mybb->get_input($field));

**Comment by WildcardSearch** [comment]
I agree with @Cu8eeeR, that line is causing the problem and is unnecessary.

**Comment by premiumcuyuz** [comment]
good job
