### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by Cu8eeeR** [mybb/mybb#2552]
Is there any reason not to add a favicon into the MyBB root folder? There is an error in the console (Google Chrome) about missing favicon. Not big deal but it should be included.

I created a PR, so it is up to you.

**Comment by Ben-Conway** [comment]
What do we think about this? @mybb/developers @JN-Jones ?

**Comment by Stefan-ST** [comment]
I don't see a reason for that. Yes, browsers try to access it but a missing favicon is no error. It's just a file users have to replace with their own.

**Comment by MattRogowski** [comment]
My only concern is that people never change it, and have the MyBB logo as their favicon forever.

Can we look at what other software does? Not just forums, but things like WordPress too.

**Comment by Cu8eeeR** [comment]
At least it will be an advertisement for MyBB software (browser bookmark). Anyway, it is a small cosmetic change. If you dont like it, just reject it :)

**Comment by Matslom** [comment]
If user replace favicon with their own, browser will not refresh this immediately. There will be another problem for users: "I replaced favicon with new but browser see the old one".

**Comment by Ben-Conway** [comment]
I think we should add one, like @Cu8eeeR said it is an advertisement for MyBB.

**Comment by Stefan-ST** [comment]
A tiny icon nobody recognizes isn't good advertisement...

**Comment by Ben-Conway** [comment]
I didn't say it was necessarily great advertisement, but it's still advertisement and we should be advertising as much as we can if we want to get more popular.

**Comment by Cu8eeeR** [comment]
Small advertisement is still better than nothing in my eyes.

**Comment by Devilshakerz** [comment]
Some projects ship an icon with the package, but if we included the main MyBB logo we would loose the distinction between new installations and the main site (we could go with some variation of it).
Also the resolution would need to be higher than the one present in the PR.

**Comment by WildcardSearch** [comment]
This is unnecessary in my opinion. It will create support work and has no value. Seeing no favicon at all reminds the admin to create and upload one.

**Comment by Ben-Conway** [comment]
Looks like I'm out numbered then..

**Comment by JN-Jones** [comment]
Wasn't this already discussed before 1.8? Anyway, also against it.
