### ISSUE TITLE
User bans do not auto-lift

### ISSUE THREAD

**Issue by ScottHarrisonDev** [mybb/mybb#2554]
MyBB Version: MyBB 1.8.7
PHP Version: 5.5.9-1ubuntu4.19
SQL Engine: MySQLi 5.6.19
Browser: Chrome 54.0.2840.98

**Steps to reproduce**
1. Go to */modcp.php?action=banning* and click 'Ban a User'
2. Find a user, enter a reason and set a date/time for 'Lift Ban After'
3. Submit the form and wait the specified amount of time.
4. Observe the user ban not auto-lifting

**Comment by Stefan-ST** [comment]
This is not the right place for support requests. Please use the community forums instead: https://community.mybb.com/

**Comment by ScottHarrisonDev** [comment]
It was my understanding that bug reports were supposed to be posted either here or on the forums? 

As per: https://community.mybb.com/announcement-22.html

**Comment by Ben-Conway** [comment]
Bug reports should be posted on the forums then they are confirmed and pushed to github by staff.

**Comment by ScottHarrisonDev** [comment]
Ok sure I'll report it there
