### ISSUE TITLE
PHP 7.1 compatibility - mail()

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2555]
Hi.

Description:
MyBB is unable to send any email. Returns blank page after registration/activation from ACP.
After removing @ from mail() function, we can see an error:
Code:Fatal error: mail(): Escaped command exceeds the allowed length of 2097152 bytes in /forum/inc/mailhandlers/php.php on line 69Problem is with additional parameters, even when we don't have any, we will see this error.
Mail without additional parameters is successfully sent.

Issue from PHPMailer repo

Tested with:
PHP 7.1.0RC1
MyBB 1.8.8

Original thread: [PHP 7.1 compatibility - mail()](https://community.mybb.com/thread-206431.html)

**Comment by Stefan-ST** [comment]
@euantorano Does this affect any non-RC version? According to the changelog it has been fixed in PHP 7.1 final: https://bugs.php.net/bug.php?id=73203

**Comment by euantorano** [comment]
I haven’t tested with a non-RC version yet, but had confirmed on RC1. I still need to install 7.1 final, but if it’s fixed we can close this.
