### ISSUE TITLE
Gravatar link updation

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2556]
Hi,

Currently Gravatar link under Change Avatar page is non https. It should be https enabled link.

Currently: http://en.gravatar.com

It should be: https://en.gravatar.com

Thanks

Original thread: [Gravatar link updation](https://community.mybb.com/thread-206458.html)

**Comment by JN-Jones** [comment]
Can somebody create a PR within one or two days please?

**Comment by euantorano** [comment]
I'll create a PR tomorrow if I don't get beaten to it.

**Comment by Ben-Conway** [comment]
Ah, beat me to it @MyBB-Andro ! Good work though, and keep contributing.
