### ISSUE TITLE
Disable edit by timestamp for admins also disables for moderators

### ISSUE THREAD

**Issue by Ben-Conway** [mybb/mybb#2558]
As the title says,

Under posting settings on the ACP:

Show 'edited by' Message for Administrators

Do you want to show edited by messages for posts created by administrators?

But disabling this option also disables the same for moderators. It should be either configurable which Group IDs can be disabled or disable only for administrators as the description says.

Thanks

Original thread: [Disable edit by timestamp for admins also disables for moderators]

EDIT: This is so that the setting description can be updated as the above is intentional behaviour.

(https://community.mybb.com/thread-206484.html)

**Comment by Ben-Conway** [comment]
Am I correct saying the above is intentional and the setting description should be updated? @JN-Jones ?

**Comment by JN-Jones** [comment]
Apparently it was changed at some point, would be good to recheck why that was done before changing anything else.

**Comment by Ben-Conway** [comment]
@mybb/developers any idea why?

**Comment by Ben-Conway** [comment]
@Cu8eeeR Could you take a look at this?

**Comment by Cu8eeeR** [comment]
@Ben-Conway - do you wanna just change description in ACP?

**Comment by Ben-Conway** [comment]
@Cu8eeeR Yes, it needs to be updating.

**Comment by Cu8eeeR** [comment]
@Ben-Conway - OK, I will take a look tommorow with my others PRs, is it OK or do we need this sooner for 1.8.9 release?
