### ISSUE TITLE
Empty index operator throws fatal error on PHP 7.1 when used on strings

### ISSUE THREAD

**Issue by Devilshakerz** [mybb/mybb#2560]
https://github.com/mybb/mybb/blob/mybb_1808/newreply.php#L732
https://github.com/mybb/mybb/blob/mybb_1808/newreply.php#L828

https://secure.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.empty-string-index-operator

**Comment by euantorano** [comment]
Should be an easy fix hopefully. Not sure why it was ever written like that.
