### ISSUE TITLE
Contact us System email log

### ISSUE THREAD

**Issue by Asandru** [mybb/mybb#2571]
Site: http://emucraft.com
**Error:**
> `The mail server does not understand the RCPT TO command. Reason: 550-"Your IP: 68.65.122.162 : Your domain gmail.com is not allowed in header 550 From"`

This happens when I use the contact us form.
My smtp settings are done correctly because users are receiving the activation link via email already, but using contact us form doesnt.

**Comment by euantorano** [comment]
Hi,

Please report issues on the forum, as explained in our [CONTRIBUTING.md file](https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md#reporting-issues)
