### ISSUE TITLE
COPPA Compliance

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#2576]
Even when set to "Deny" it still shows the COPPA Compliance &amp; Permission form link during registration.

This could be a bug or something that was just simply left out.

Original thread: [COPPA Compliance](https://community.mybb.com/thread-206683.html)

**Comment by andrewjs18** [comment]
also note that the URLs for the coppa site are dead in the admin cp & on the compliance page when registering.

the only decent link I've found to replace it with is a wiki page link: https://en.wikipedia.org/wiki/Children's_Online_Privacy_Protection_Act or... https://www.ftc.gov/tips-advice/business-center/privacy-and-security/children%27s-privacy

**Comment by wagey** [comment]
Thank you.

**Comment by MyBB-Andro** [comment]
> also note that the URLs for the coppa site are dead in the admin cp & on the compliance page when registering.

The link is working now. Just FYI..

**Comment by euantorano** [comment]
Related: https://community.mybb.com/thread-214276.html
