### ISSUE TITLE
SMTP mail error 554

### ISSUE THREAD

**Issue by stoffer123** [mybb/mybb#2578]
The mail server does not understand the RCPT TO command. Reason: 554 5.7.1 Recipient address rejected: Username admin@risingworld.dk and sender doesn't match

I understand my host needs a "from" mail inorder to send, and i cannot find the spot in inc/functions.php to edit it in...
i use SMTP
Anyone having a fix for this issue? i cant figure what im doing wrong.

**Comment by Matslom** [comment]
Hi, Please report issues on the forum, as explained in our [contributing guide ](https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md#reporting-issues)
