### ISSUE TITLE
File Verification and .txt files

### ISSUE THREAD

**Issue by nsuchy** [mybb/mybb#2580]
Hi there. I just figured I'd point out that some people choose to remove the .txt files that come in the MyBB zip file. You shouldn't tell me a .txt file is missing, I just figured I'd let you know :)

![screenshot 2016-12-23 at 10 05 41 pm](https://cloud.githubusercontent.com/assets/8227641/21464968/1c00698a-c95c-11e6-9d87-dbe4348e4a82.png)

**Comment by dequeues** [comment]
It should be in the `$ignore` array: https://github.com/mybb/mybb/blob/e30d9f84d67790f97a7fab8ecec4b18b095bb3ad/inc/functions.php#L7643
