### ISSUE TITLE
inline Moderation not work correct

### ISSUE THREAD

**Issue by Mx13Cyber** [mybb/mybb#2581]
HI
inline Moderation  is not work correct .
and Quote in posts and all of things is work with cookie in mybb 1.8.9
and i find why
in general.js in line 498 if we remove this line 
`secure: cookieSecureFlag,`
then its work correct

**Comment by euantorano** [comment]
Hi, this is a known issue in the 1.8.9 update, please see here: https://community.mybb.com/thread-206896.html

**Comment by dequeues** [comment]
https://github.com/mybb/mybb/pull/2579
