### ISSUE TITLE
Inline moderation issues

### ISSUE THREAD

**Issue by nsuchy** [mybb/mybb#2582]
Hi there. So I noticed the issue with inline moderation (yes I saw the thread: [https://community.mybb.com/thread-206896.html](url) and made the applicable core edits). This being said be sure to update file verification to not show an error in the next release.

![screenshot 2016-12-29 at 11 15 44 pm](https://cloud.githubusercontent.com/assets/8227641/21559582/dc99dbb2-ce1c-11e6-8700-1decd4ed1933.png)

**Comment by katosdev** [comment]
Hi!

We're aware of the issue, and as such our file verification will be updated to reflect this. IIRC @euantorano or @Devilshakerz are working on this.
Thank you for your contribution to the ongoing development of MyBB! :)

**Comment by Ben-Conway** [comment]
This shouldn't happen when we release 1.8.10 :)
