### ISSUE TITLE
Missing line break in New Thread post options

### ISSUE THREAD

**Issue by Ben-Conway** [mybb/mybb#2588]
Hello there
Is this a bug?
Or my mistake?

Original thread: [Is this a bug mistake?](https://community.mybb.com/thread-207157.html)

**Comment by Ben-Conway** [comment]
This doesn't happen on reply to a thread, this happens in create a new thread. Should be fixed in 1.8.10.

**Comment by Stefan-ST** [comment]
Great subject and description...

**Comment by Stefan-ST** [comment]
Thanks, @PaulBender

**Comment by Cu8eeeR** [comment]
@Ben-Conway - can you please add "fixed" tag?
