### ISSUE TITLE
Who Posted Sorting Links Redirect To New Page

### ISSUE THREAD

**Issue by Ben-Conway** [mybb/mybb#2590]
In forumdisplay.php when viewing the thread list and clicking the reply count link for the AJAX Who Posted modal...

...when clicking either sort link, the user is redirected to a page, empty except for the modal content:

Apologies if this is a duplicate, but I did search.

Original thread: [Who Posted Sorting Links Redirect To New Page](https://community.mybb.com/thread-206871.html)

**Comment by Ben-Conway** [comment]
My personal opinion would be to just remove the hyperlinks. It just displays the exact same information.

**Comment by WildcardSearch** [comment]
Unless someone else wants to handle it, I'll have the time tomorrow evening.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - feel free to push a PR :) 

I agree with @Ben-Conway

**Comment by Ben-Conway** [comment]
Thanks @WildcardSearch, good work! I'll keep an eye out for it :)

**Comment by WildcardSearch** [comment]
Done.
