### ISSUE TITLE
Custom profile field - Show on member profile - OFF is not working

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2591]
As title says - this settings for show/hide profile field on member profile is not working. The profile field is shown all the time.

Original thread: [Custom profile field - Show on member profile - OFF is not working](https://community.mybb.com/thread-207172.html)

**Comment by Cu8eeeR** [comment]
@Matslom - I see your PR, good job, can you push it to MyBB repository? I will try it and let you know

**Comment by Ben-Conway** [comment]
Good job @Matslom

**Comment by Cu8eeeR** [comment]
@Ben-Conway - can you please add "fixed" tag?
