### ISSUE TITLE
Problem Send PM - Member Profile

### ISSUE THREAD

**Issue by Matslom** [mybb/mybb#2594]
Hi guys,
today I was watching some profiles of users that are awaiting activation and the language variable of the link is empty. Users in awaiting activation in my forum can't receive/send PMs. Watching the PHP I saw that conditions that set the language and load the template are different, I think that this is the problem.

Original thread: [Problem Send PM - Member Profile](https://community.mybb.com/thread-206936.html)

**Comment by Matslom** [comment]
Also we can send PM's to user who is in group with disabled PM's. Is it desirable feature?
Lang issue also appears in header for user who have disabled PM's by group.
![image](https://cloud.githubusercontent.com/assets/4405492/21741141/bd8e9458-d4cd-11e6-9532-df94ea8bfc8b.png)

**Comment by Cu8eeeR** [comment]
> Also we can send PM's to user who is in group with disabled PM's. Is it desirable feature?

@Matslom - it is known issue, unfortunately not fixed. See this issue: https://github.com/mybb/mybb/issues/1834

It should be fixed together

**Comment by Ben-Conway** [comment]
I agree we should fix all the issues together. Can the developer who looks at this also take a look at https://github.com/mybb/mybb/issues/1834 ?
