### ISSUE TITLE
ForumDisplay: Who Posted Inoperable Without JavaScript

### ISSUE THREAD

**Issue by WildcardSearch** [mybb/mybb#2603]
If JavaScript is disabled, when viewing `forumdisplay.php`, the linked Replies column value is dead. The `href` attribute of the link points to `MyBB.whoPosted`.

A fallback should be introduced for a standard redirect.

See: #2590

**Comment by Shade-** [comment]
I can confirm this.

**Comment by WildcardSearch** [comment]
Apparently this goes back at least to 1.6.x (I just tested on 1.6.18).

**Comment by JordanMussi** [comment]
Fixed in #2772

**Comment by JordanMussi** [comment]
@euantorano This adds a new template as well - I've just noticed I haven't added it to the misc.php templatelist do you want to commit that directly?

**Comment by euantorano** [comment]
Thanks, and good catch. I'll add that in a minute.

**Comment by euantorano** [comment]
Fixed @JordanMussi
