### ISSUE TITLE
Deleting a forum and the recount link while using custom admin url,

### ISSUE THREAD

**Issue by nsuchy** [mybb/mybb#2606]
So I've discovered an issue present in MyBB 1.8.9. I moved all threads from one part of my site to another and was deleting the empty section. It gave me an alert telling me that ideally I should run the recount threads. It had a link to do so. That link was /index.php?module=tools-recount_rebuild rather than /mysecretadminurl//index.php?module=tools-recount_rebuild. This should be adjusted for the next release of MyBB 1.8.

**Comment by Ben-Conway** [comment]
I don't recall it coming up and telling you to do this off the top of my head.

**Comment by nsuchy** [comment]
See the related lang file line 102:
[https://github.com/mybb/mybb/blob/1912340401ec3d0e54449c980d861492ad1bc321/inc/languages/english/admin/forum_management.lang.php#L102](https://github.com/mybb/mybb/blob/1912340401ec3d0e54449c980d861492ad1bc321/inc/languages/english/admin/forum_management.lang.php#L102)

The issue is that there is no code for the actual admin URL. It's an easy fix, someone with access just needs to do it.

**Comment by PaulBender** [comment]
I can confirm the issue.

**Comment by Ben-Conway** [comment]
In future please report issues on the forum first and the team will push them to github once they are confirmed.
