### ISSUE TITLE
When viewing own profile via `uid=0`, the username isn't shown

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2610]
If you access `member.php?Action=profile` (with no UID) or `user-0.html` (when using search engine friendly URLs), you are taken to your own profile page. However, the current location will be `Viewing Profile`, without the name of the profile being viewed.

Original thread: [user-0 redirects to own profile](https://community.mybb.com/thread-207240.html)

**Comment by Broatcast** [comment]
Fixed the problem https://github.com/mybb/mybb/pull/2694
