### ISSUE TITLE
last post info is not updating properly

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#2612]
after the upgrade from 1.8.9 to 1.8.10, the last post info does not appear to be updating correctly on the forum index as well as when you click inside a forum category.  if you go inside the forum section where the post exists, it seems like it's updating correctly.

here's a few screenshots...

forum index view:

![215 jan 11](https://cloud.githubusercontent.com/assets/2748980/21849640/c7573fbc-d7d4-11e6-99e2-f0c766c5c10c.jpg)

category view:

![216 jan 11](https://cloud.githubusercontent.com/assets/2748980/21849645/cf4152d0-d7d4-11e6-941e-11a597fae374.jpg)

forum view:

![217 jan 11](https://cloud.githubusercontent.com/assets/2748980/21849647/d378a02e-d7d4-11e6-9fe2-9e5b71df9aba.jpg)

this issue is also present on these community forums as well..

Original thread: [last post info is not updating properly](https://community.mybb.com/thread-207323.html)

**Comment by Devilshakerz** [comment]
The `update_last_post()` call was removed in https://github.com/mybb/mybb/commit/674b11da258cb76b6a4b1072b243f29569b953d2#diff-7cc617e1e9d4b3ffa6409eb9329f6801L1234 (fixing https://github.com/mybb/mybb/issues/2516), and `update_forum_lastpost()` is fetching outdated information as a result.

**Comment by alexandergamster** [comment]
confirmed ....please solve this fast :D

**Comment by Its-Nasyr** [comment]
I hadn't realised this issue was even going on till I started looking online.
MyBB Blog: https://blog.mybb.com/2017/01/10/mybb-1-8-10-released-maintenance-release/
