### ISSUE TITLE
GO button in portal search not inline

### ISSUE THREAD

**Issue by SvePu** [mybb/mybb#2616]
The GO button in portal search should be in a line with the <input> textfield.

Now:
![mybb_portal_search_1](https://cloud.githubusercontent.com/assets/9826631/21938255/d8b6062a-d9ba-11e6-8c09-9cd5b553f935.PNG)

After fix:
![mybb_portal_search_2](https://cloud.githubusercontent.com/assets/9826631/21938269/e5f6c64e-d9ba-11e6-86b7-a7693745a348.PNG)

**Comment by SvePu** [comment]
#2617

**Comment by Shade-** [comment]
It seems like I can't reproduce the issue on a fresh 1.8.10 copy, even with the german word for "go". Can you please specify what version of MyBB are you using and the browser you are experiencing this with? Thank you.

**Comment by SvePu** [comment]
@Shade- The theme template wasn't edited since version 120. So issue is still in 1810.

It seems to be in any browser......some examples:

Opera (42.0) - Win10
![go_button_opera](https://cloud.githubusercontent.com/assets/9826631/22783328/9a08ca36-eecb-11e6-98cc-8193a7d5750f.PNG)

Firefox (51.0.1) - Win10
![go_button_firefox](https://cloud.githubusercontent.com/assets/9826631/22783353/b46b7e5a-eecb-11e6-955a-ab07b1b3ab52.PNG)

Safari - iOS
![go_button_safari](https://cloud.githubusercontent.com/assets/9826631/22783362/c16ea1d6-eecb-11e6-9ff5-822b0fbe3496.PNG)

**Comment by Shade-** [comment]
Since I cannot reproduce it on a Mac, I let someone else take care of this.

**Comment by Cu8eeeR** [comment]
I can confirm, win 10 google chrome. Button is below the input box
