### ISSUE TITLE
Always show "thread closed" info

### ISSUE THREAD

**Issue by matix931** [mybb/mybb#2628]
It is very useful for admins, to show that thread is closed even admin can replay in that thread.

Example solution:
showthread.php:641 (mybb 1.8.10)

```
if($forumpermissions['canpostreplys'] != 0 && $mybb->user['suspendposting'] != 1 && ($thread['closed'] != 1 || is_moderator($fid, "canpostclosedthreads")) && ($thread['uid'] == $mybb->user['uid'] || $forumpermissions['canonlyreplyownthreads'] != 1)) 
{
	eval("\$newreply = \"".$templates->get("showthread_newreply")."\";");
}
if($thread['closed'] == 1)
{
	eval("\$newreply_closed = \"".$templates->get("showthread_newreply_closed")."\";");
}
```

*new variable $newreply_closed

in template it should be placed like this:
`{$newreply}{$newreply_closed}`

**Comment by Cu8eeeR** [comment]
I agree, this needs to be changed to MyBB 1.6.x style

This was mentioned here:
https://github.com/mybb/mybb/issues/2117

**Comment by Cu8eeeR** [comment]
@Stefan-ST - is this piece of code usable? Or what is your idea how to solve this issue? Would be nice to share it
