### ISSUE TITLE
Quoting troubles after upgrade

### ISSUE THREAD

**Issue by alexalok** [mybb/mybb#2631]
After an upgrade from 1.8.5 to 1.8.10 quotes are not being shown if they include either nickname, pid or datetime. 
As a workaround, I reverted lines 854-855 of _class_parser.php_ 
```
eval("\$mycode_quote = \"".$templates->get("mycode_quote_post", 1, 0)."\";");
			return $mycode_quote;
```
to 
`return "<blockquote><cite>{$span}{$username} {$lang->wrote}{$linkback}</cite>{$message}</blockquote>\n";`
After this the problem is gone.

**Comment by Cu8eeeR** [comment]
Did you use the full package or just upgrade directly with changed files package from 1.8.5 to 1.8.10?

Btw - next time open a ticket on MyBB board, not here

**Comment by Stefan-ST** [comment]
Please use our forums for support: https://community.mybb.com/
