### ISSUE TITLE
Robots in between online user order according to activity

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2632]
Hi,

Username ascending orders robots first on index who's online section. While last activity ascending orders robots in between users which looks quite odd.

It should list robots either at first or last of the users according to activity. In between users confuses members as thinking robots as users.

Thanks

Original thread: [Robots in between online user order according to activity](https://community.mybb.com/thread-207265.html)

**Comment by Stefan-ST** [comment]
Related: On portal this broken completely still relying on $session->bots (which was removed years ago).
