### ISSUE TITLE
Redirect Issue with htaccess

### ISSUE THREAD

**Issue by CyberReflect** [mybb/mybb#2633]
It turns out I am facing a redirect issue with the current version (1.8.10). I tried getting help from my hosting providers but they weren't able to fix the problem and told me to report the issue instead. 

My **.htaccess** Settings are:

`#RewriteCond %{HTTP_HOST} !^www\.
#RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]

RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteCond %{HTTP_HOST} ^domain.com$ 
RewriteRule .* https://www.domain.com%{REQUEST_URI} [R,L]`

It works fine redirecting non-www to www over HTTPS but as soon as I add rule for www there's an infinite loop. For example the setting for both non-www and www would be:

`#RewriteCond %{HTTP_HOST} !^www\.
#RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]

RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteCond %{HTTP_HOST} ^domain.com$ [OR]
RewriteCond %{HTTP_HOST} ^www.domain.com$
RewriteRule .* https://www.warrior.pk%{REQUEST_URI} [R,L]`

Any suggestions to fix the problem?

**Comment by Stefan-ST** [comment]
This code is not even part of MyBB.

**Comment by katosdev** [comment]
Whilst this isn't even a part of MyBB and your host **Should** really have been able to have sorted this. (Seriously, it begs the question as to why they can't)

Can you not just use: 
```
# Make this rule the first rewrite rule in your .htaccess!
RewriteRule ^([^&]*)&(.*)$ https://creatorswave.com/$1?$2 [L,QSA,R=301]
```

And make sure that your settings in ACP reflect the www. domain.
and **not** the non-www version.
