### ISSUE TITLE
PHPGangsta/GoogleAuthenticator should be updated

### ISSUE THREAD

**Issue by JoshHarmon** [mybb/mybb#2635]
https://github.com/PHPGangsta/GoogleAuthenticator/commits/master

They've fixed a few issues, including a possible timing attack and non-strict comparison issue (https://github.com/PHPGangsta/GoogleAuthenticator/issues/24) since the file was last pulled into the core. They also now use far better RNG than the current version we're using.

New:
1. random_bytes() (PHP 7.0+)
2. mcrypt
3. openssl

Current:
1. array_rand(), a function that produces somewhat predictable output

**Comment by JoshHarmon** [comment]
I've made the change locally and am testing to see if it causes any problems. Currently, it seems to function fine but I haven't tested to see if there are any issues with upgrading the library with a user's secret already set.

**Comment by JoshHarmon** [comment]
Have tested the update in both directions:
- Set up with new version and reverted to old version
- Set up with old version and updated to new version

**Comment by euantorano** [comment]
Thanks @JoshHarmon. I'll need to set up some test environments with older PHP versions to ensure this doesn't cause any issues there.
