### ISSUE TITLE
Soft Delete Not Working

### ISSUE THREAD

**Issue by thunderclap82** [mybb/mybb#2637]
Issue was first noticed after upgrading to 1.8.10 though it could have started with 1.8.9. When soft deleting a post it is instead permanently deleted. Adding the code to global.css mentioned in the 1.8.9 update doesn't fix it, and the default theme is broken too. I've disabled all plugins to see if that resolved the issue but it didn't. I also did do a fresh install of 1.8.10 as a test and the problem is NOT present, so I think this has something to do with the update.

My original post in the forums is here: https://community.mybb.com/thread-207536.html

A short video highlighting the problem is here: https://community.mybb.com/thread-207536-post-1260343.html#pid1260343

**Comment by Ben-Conway** [comment]
Can you please report all bugs on the community forums.
