### ISSUE TITLE
Check if Column exist befor add, remove, modifie

### ISSUE THREAD

**Issue by Broatcast** [mybb/mybb#2639]
While in dev progress for a new plugin i found an old lost thread in the suggestion forum.
https://community.mybb.com/thread-162472.html

So in short i do this little modification for all db classes.

I think it's realy helpfull and will may prevent many code and ugly SQL Errors in the feature.

**Comment by Stefan-ST** [comment]
Please do not suggest feature on Github (https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md).
