### ISSUE TITLE
smtp fails with zoho.

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2644]
The smtp mailhandler does not support sending emails via zoho smtp server (smtp.zoho.com, on port 465 with ssl enabled). It fails on line 250 of the smtp mail handler script with the "&#36;this-&gt;send_data('.', '250');" call, with the server responding back with a 553 code instead of a 250 code.

Original thread: [smtp fails with zoho.](https://community.mybb.com/thread-207804.html)

**Comment by effone** [comment]
As much possible I have carried out digging for this it is appearing that zoho returns 553 relaying disallowed in following cases:
- host not registered in zoho db
- from ID & sender ID is different

This can take much time trying fixing but shall we try for a fix as we are switching to 3rd party mail library ...

Also a fix is mentioned somewhere which I don't know working or not, just for reference:

> I can't test this without a MyBB install, but if it uses the native PHP mail function, you may need to add the -f option to the mail() function call since you are using sendmail.. Note it is the 5th parameter (I wasted a day once thinking it that was 4th)
`mail('nobody@example.com', 'the subject', 'the message', null,
'-flocaluserr@thisdomain.com'); `

**Comment by euantorano** [comment]
I wouldn’t bother doing anything major to the mail handlers in 1.8. For 1.9 we’ll be using a library which should be a bit better.

**Comment by effone** [comment]
Setting it to `wontfix`.
