### ISSUE TITLE
Merge specific options when moderating with custom tools

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#265]
> When you moderating with the custom moderation tools and you are merging a thread you cannot select any specific options f.e. copy the thread.

Original report: http://dev.mybb.com/issues/1567
Reporter: Michael Malin
Status: Confirmed

**Comment by Destroy666x** [comment]
Closing since noone can reproduce (if anyone has more info feel free to bump). Cusrom moderator tools with merge + copy/move/whatever work fine, even when used outside of inline thread moderation (merge is skipped then).
