### ISSUE TITLE
Problems with username and german umlauts

### ISSUE THREAD

**Issue by Olli** [mybb/mybb#2650]
I'd tried to merge a VBulletin. The import stops with a duplicate entry error. There wars a username "Günter" ... and "Gunter" couldn't be importet.
The username field should be set on utf8_bin ... utf8_general_ci isn't appropriate for that because of mysqls own way to see the things.

**Comment by Stefan-ST** [comment]
We do not provide support here. Please use our Community Forums instead: https://community.mybb.com/

**Comment by Olli** [comment]
This wars no support but a bug report. The SQL schema must be adjusted for using utf8_bin.

**Comment by Stefan-ST** [comment]
This is not the right place to report bugs either (Please check https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md). Also this is an issue with the Merge System and not with MyBB.

**Comment by Olli** [comment]
No it's an issue with the default schema of MyBB. Thx for the hint with the bug reporting ... just another account in some forum :-(

**Comment by Stefan-ST** [comment]
We use utf8_general_ci intentionally because it's unlike utf8_bin case insensitive. It's considerably faster than using a case sensitive collation and LOWER() operations (#349). There is no issue unless you try to import data from different systems.
