### ISSUE TITLE
Wrong link to announcements in ModCP announcement list

### ISSUE THREAD

**Issue by SvePu** [mybb/mybb#2663]
The link in mod_cp announcement list should be linked to announcement itself ... momentary it goes to edit_announcement.

![issue_modcp_announcement_links](https://cloud.githubusercontent.com/assets/9826631/22863722/e847ac86-f145-11e6-8cea-ba15d253aff7.PNG)

**Comment by Shade-** [comment]
I'm not sure if this is really an issue. I feel like it has been built like this on purpose. What do you think @mybb/developers?

**Comment by Ben-MyBB** [comment]
I agree that it is an issue and should be fixed.

**Comment by SvePu** [comment]
@Matslom - I already added a PR with fix here #2664

**Comment by Matslom** [comment]
I don't know how I missed it...
