### ISSUE TITLE
Datacache stats doesn't update PHP 7.1.1

### ISSUE THREAD

**Issue by 036** [mybb/mybb#2665]
After upgrading to PHP 7.1.1 from PHP 5.6 the datacache for stats no longer updates. I've not checked the rest of the datacache or whether this happens on PHP 7.1.0. 

I can confirm this is related to PHP 7.1.1 as when I set nginx to load php-5-fpm adding a post updates the cache however when loading php-7-fpm the datacache does not update.

**Comment by Cu8eeeR** [comment]
@Devilshakerz

**Comment by Devilshakerz** [comment]
We weren't able to reproduce this so far.

Original report: https://community.mybb.com/thread-208293.html

**Comment by 036** [comment]
I'll try with a clean install on the same server to see if I encounter the same issue.

**Comment by Matslom** [comment]
I can't reproduce this on php 7.0 and 7.1.2.

**Comment by 036** [comment]
I've just upgraded to PHP 7.1.2 will update whether it makes any difference.

**Comment by euantorano** [comment]
Having debugged this through with @036 with debug, the issue is in the NewPoints plugin, which was passing the `/e` flag to `preg_replace`. This caused an error to be set on the error handler, preventing shutdown functions from running. Quite a pain to trace through and totally non-obvious.
