### ISSUE TITLE
Missing Plugin Hooks in the ACP

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2666]
As shown at line 1230 of the users modul in ACP, (Line 1230 in Crossreference) there are some plugin hooks missing in the code.

Currently i'am developing a plugin which exactly need hooks at this place, that's the reason why I found this (like I think, cool and funny, seems to be a forgotten one) ^^.

I think it's a very useful point for feature plugin developers if we include this hooks. I already make a fork with this change on Git. (the commit) All hooks are tested and working fine.

If some agree with this I will open a issue and will add a pull request with this code change.

(sry English is not my main language)

Original thread: [Missing Plugin Hooks in ACP Users Modul](https://community.mybb.com/thread-208322.html)

**Comment by Cu8eeeR** [comment]
@Broatcast - can you please push your PR with missing hooks (https://github.com/Broatcast/mybb/commit/38f063335101355d2e667a9edf56ee21adb23f0e)

Thanks!

**Comment by Broatcast** [comment]
Done #2674
