### ISSUE TITLE
User ratings not merging when account is merged

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#268]
> When two accounts are merged and they both left a rating on a thread, their rating will duplicate.  
> This is an example from [http://hackforums.net](http://hackforums.net)
> 
> ![](http://img.gmod.ws/SS-2011-03-30_14.27.44.png)
> 
> As you can see, the member got banned, and his account got merged.

Original report: http://dev.mybb.com/issues/1524
Reporter: Arnaud C.
Status: Confirmed

**Comment by JN-Jones** [comment]
Looks like this is valid from the code. @Sama34 or @mybb/developers shouldn't be too hard to fix this so can somebody look at this?

**Comment by WildcardSearch** [comment]
#2622 needs testing... any takers?

**Comment by WildcardSearch** [comment]
Feels good to help get a two-year-old issue closed. 🎉
