### ISSUE TITLE
Third party libraries need to be updated

### ISSUE THREAD

**Issue by Shade-** [mybb/mybb#2696]
This is a clean list of all the libraries which need to be updated to their latest version, or at least to the last version which does not break any existing MyBB functionality. Feel free to add others.

- [x] jQuery (1.11.3 –> 1.12.4)
- [x] CodeMirror (unknown –> 5.24.2)
- [x] jQuery Validation (1.14.0 –> 1.16.0)
- [x] jGrowl (1.4.3 –> 1.4.6)
- [x] jQuery modal (0.5.8 –> 0.8.0)
- [x] jQuery Impromptu (6.2.1 –> 6.2.3)
- [x] jQuery cookie (1.4.1 –> JavaScript Cookie 2.1.4)
- [x] Google Recaptcha #2699
- [x] jQuery UI (1.11.2 –> 1.12.1)

Select2 (3.5.3 –> 4.0.3) #2182 (waiting for author's fix of known issue)

**Comment by premiumcuyuz** [comment]
good work :)

**Comment by Cu8eeeR** [comment]
@Shade- please dont forget to include custom fixes which where applied for mybb needs (mainly css modifications)
