### ISSUE TITLE
Add new templates for hardcoded items

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2698]
Now we have {&#36;buddy_options}{&#36;ignore_options}{&#36;report_options} hardcoded. It would be nice to include them as separate templates for easier customisation.

Original thread: [Add new templates for hardcoded items](https://community.mybb.com/thread-207614.html)

**Comment by Shade-** [comment]
There are a lot of hardcoded things I would like to include in this issue's future PR. I will post a list in the near future.

**Comment by Cu8eeeR** [comment]
That would be great, for hardcoded items I use plugin (MyBB patches) so it is easier to backport them after updating to a newer MyBB version. I am looking forward! :)

**Comment by PaulBender** [comment]
If nobody objects, I'd like to move this issue to 1.9, since the Twig conversion fixed this issue.

**Comment by euantorano** [comment]
Sounds good to me!
