### ISSUE TITLE
update google recaptcha

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#2699]
google has rolled out their invisible recaptcha.  we should update the current recaptcha to the latest available from google.

https://www.google.com/recaptcha/intro/invisible.html

https://developers.google.com/recaptcha/...uto_render

Original thread: [update google recaptcha](https://community.mybb.com/thread-208934.html)

**Comment by Shade-** [comment]
Should we replace the old Google Captcha method, or add the invisible approach as an option? @mybb/developers

**Comment by kawaii** [comment]
@Shade- I would recommend adding it as an option, offers forum owners more flexibility.

**Comment by Cu8eeeR** [comment]
Would be better to have both methods. Will be the old Google Captcha supported or will be replaced soon by invisibile approach, dont you know?

**Comment by euantorano** [comment]
Add it as an option, for definite. Both styles are currently supported by Google, with no announced possibility of this changing any time soon as far as I know.

**Comment by nsuchy** [comment]
Just a note the developer link mentioned earlier in this thread is broken. However documentation for reCAPTCHA Invisible can be found at https://developers.google.com/recaptcha/docs/invisible

**Comment by nsuchy** [comment]
So the other day I looked into how this would need to be implemented. The recaptcha attributes would need to be added to the registration submission button since there isn't a check box.

**Comment by Shade-** [comment]
I have written down a preliminary version of this update, but for an unknown reason to me Google keeps on prompting me the visible reCAPTCHA. Please test it acknowledging it's a blindly written code.

Commit: https://github.com/mybb/mybb/pull/2697/commits/0321bac3ea8f4394ca902a63c96c0950e19e7d0e

**Comment by Cu8eeeR** [comment]
@Shade- any success? Fingers crossed!

**Comment by Shade-** [comment]
The code is there, it needs testing.

**Comment by Cu8eeeR** [comment]
@Shade- Is it working for you? Maybe I applied your changes in a wrong way but it is not working for me, I will let you know. Would be nice to have it in v1.8.13. What about others, MyBB team?

**Comment by Eldenroot** [comment]
This can be closed - added via https://github.com/mybb/mybb/issues/2696
