### ISSUE TITLE
Moving unapproved threads

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#270]
> Unapprove a thread with several posts, move it to another forum and then approve it. Then the counters will be wrong (e.g. negative). This may affect only PgSQL.

Original report: http://dev.mybb.com/issues/1439
Reporter: Stefan T.
Status: Confirmed

**Comment by PaulBender** [comment]
I cannot reproduce any counter issues with the latest code.

**Comment by JN-Jones** [comment]
Nothing wrong here so closing (tested with the newest github code and at all stages the counters were correct)
