### ISSUE TITLE
Custom Admin Theme Set Before Completed Login with 2FA

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2700]
Hi there. I realized a quick issue earlier today. If I login to my admin account where a custom theme is set, the CSS for that theme will load at the time the 2FA Prompt loads. If I enter an invalid code, my session is reset and I have to retype my username and password, then retry 2FA. However the difference is the login screen now shows my custom admin theme as it was never switched back to default. Was this intentional or is it a bug?

Original thread: [Custom Admin Theme Set Before Completed Login with 2FA](https://community.mybb.com/thread-208939.html)

**Comment by JordanMussi** [comment]
Fixed in #2783
