### ISSUE TITLE
Better description for Time between failed logins and Number of times to allow failed logins settings

### ISSUE THREAD

**Issue by cyof** [mybb/mybb#2709]
Using version 1.8.10.

The description in the software is:
> Number of times to allow failed logins
> The number of times to allow someone to attempt to login. Set to 0 to disable.
> 
> Time between failed logins
> The amount of time (in minutes) before someone can try to login again, after they have failed to login the first time. Used if value above is not 0.

These isn't as clear as what was stated in https://docs.mybb.com/1.6/Admin-CP-Board-Settings/. As shown below.
> Numeber of times to allow failed logins 
>     The number of failed logins allowed before they are locked out. Set to 0 to disable. 
> Time between failed logins 
>     The amount of time between a user can try to login again after having been locked out. 

The words locked out should be used in the description.

**Comment by Cu8eeeR** [comment]
Please, read https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md. Suggestions should be made here first: http://community.mybb.com/forum-158.html and get accepted by the team. Thank you.

**Comment by Cu8eeeR** [comment]
@euantorano - this can be closed, right? If I understand correctly there is a small "issue" with 1.6 old docs
