### ISSUE TITLE
ACP menu not sorting

### ISSUE THREAD

**Issue by Broatcast** [mybb/mybb#2710]
Found that the submenu creation in ACP is designed for plugin devs to adding own menu entry's in the spaces between of exist entry's. Good to see at the choosed numbers for the core menu entrys like here:
https://crossreference.mybb.de/admin/modules/tools/module_meta.php.source.html

But the add_menu_items function missed to sort them before generating the output for the sidemenu:
https://crossreference.mybb.de/nav.html?admin/inc/class_page.php.source.html#l1106

Original thread: https://community.mybb.com/thread-209422.html

**Comment by Shade-** [comment]
Please, read https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md. Suggestions should be made here first: http://community.mybb.com/forum-158.html and get accepted by the team. Thank you.

**Comment by Broatcast** [comment]
Sry for the premature pr ... missed that Azareal is not a team member
