### ISSUE TITLE
Editor Video button Placeholder class incorrect.

### ISSUE THREAD

**Issue by MyBB-Andro** [mybb/mybb#2712]
Editor Video button Placeholder class incorrect. It is clickable currently, to match up with image/url options on editor it should be unclickable and only comes in a lighter shade.

Discussion has been done [in this thread](https://community.mybb.com/thread-208749-post-1269124.html#pid1269124) and SCEditor replied with the fix.

**Comment by Shade-** [comment]
Please, read https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md. Suggestions should be made here first: http://community.mybb.com/forum-158.html and get accepted by the team. Thank you.

**Comment by Cu8eeeR** [comment]
@MyBB-Andro - would be better to wait for final v2.0 release of SCeditor, this "reverse" engineering is not the best way :(

**Comment by Shade-** [comment]
I tend to agree with @Cu8eeeR on this. SCEditor-related issues should be updated once 2.0 is released. Also, this poses serious problems with maintaining the library through future updates.

If there are no objections I'd reject the PR and add this to #2542.

**Comment by MyBB-Andro** [comment]
Sure @Shade- , no problems at all. Feel free to.😃
