### ISSUE TITLE
Empty submit allowed on forms

### ISSUE THREAD

**Issue by FaithInMotion** [mybb/mybb#2721]
I don't know if it is site wide, but I do know that at least the "Forgot Password" can be submitted empty. This is causing an influx in "can't send mail with mail() function" errors in the admin cp. Does this not also open up the site to brute force vulnerability?

**Comment by Shade-** [comment]
Hi, please read https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md. Suggestions and feedbacks towards eventual bugs should be made here first: http://community.mybb.com/forum-158.html and get accepted by the team after meaningful and constructive discussion. Thank you.

**Comment by FaithInMotion** [comment]
I thought that's what Github was for.

**Comment by euantorano** [comment]
As our contributing guide says, issues should be reported on the forums. That's not the case for 2.0, but for 1.8 we stick by the old (sometimes confusing) rules.
