### ISSUE TITLE
"Select all" don't work in Forum and Posts / Attachments

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2723]
Hello,

I want to select all my attachments from a specific search, in Admin CP / Forum &amp; POsts / Attachments / Find Attachments. I have hundreds...

But when I press the "select all" button (the first square from top), no attachments are selected. Even the manual selection with click on the first post and Shift + click on last post, didn't work. 

I have the last Mybb update.

It is a bug or is something wrong with me? I don't want to manually select 300 atachments...

System: Win 8.1 / Chrome

Original thread: ["Select all" don't work in Forum and Posts / Attachments](https://community.mybb.com/thread-209616.html)

**Comment by JordanMussi** [comment]
Looks like the Javascript was never written for this... 😮

**Comment by JordanMussi** [comment]
Technically this duplicates #2110.
