### ISSUE TITLE
Replace features deprecated in PHP 7.2

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#2743]
- `create_function()`
- `each()` (3rd party only)
- `assert()` with string argument (3rd party only)

https://wiki.php.net/rfc/deprecations_php_7_2

**Comment by skmedix** [comment]
* ```create_function()``` - 14
  * ```/admin/inc/functions_themes.php```
    * [functions_themes.php#L423](https://github.com/mybb/mybb/blob/feature/admin/inc/functions_themes.php#L423)
  * ```/admin/modules/config/languages.php```
    * [languages.php#L348](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L348)
    * [languages.php#L352](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L352)
    * [languages.php#L561](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L561)
    * [languages.php#L562](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L562)
    * [languages.php#L566](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L566)
    * [languages.php#L567](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L567)
    * [languages.php#L598](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L598)
    * [languages.php#L602](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L602)
    * [languages.php#L621](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L621)
    * [languages.php#L625](https://github.com/mybb/mybb/blob/feature/admin/modules/config/languages.php#L625)
  * ```/inc/functions.php```
    * [functions.php#L5686](https://github.com/mybb/mybb/blob/feature/inc/functions.php#L5686)
    * [functions.php#L5687](https://github.com/mybb/mybb/blob/feature/inc/functions.php#L5687)
    * [functions.php#L6479](https://github.com/mybb/mybb/blob/feature/inc/functions.php#L6479)
---
* ```each()``` - 4
  * ```/inc/3rdparty/diff/Diff/Engine/Native.php```
    * [Native.php#L200](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L200)
    * [Native.php#L208](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L208)
  * ```/inc/3rdparty/diff/Diff/String.php```
    * [String.php#L75](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/String.php#L75)
    * [String.php#L92](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/String.php#L92)
---
* ```assert()``` - 17
  * ```/inc/3rdparty/diff/Diff/Engine/Native.php```
    * [Native.php#L103](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L103)
    * [Native.php#L104](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L104)
    * [Native.php#L203](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L203)
    * [Native.php#L210](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L210)
    * [Native.php#L218](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L218)
    * [Native.php#L256](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L256)
    * [Native.php#L340](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L340)
    * [Native.php#L361](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L361)
    * [Native.php#L393](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L393)
    * [Native.php#L397](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L397)
    * [Native.php#L418](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L418)
    * [Native.php#L434](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L434)
    * [Native.php#L438](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Native.php#L438)
  * ```/inc/3rdparty/diff/Diff/Engine/Shell.php```
    * [Shell.php#L90](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Engine/Shell.php#L90)
  * ```/inc/3rdparty/diff/Diff/Mapped.php```
    * [Mapped.php#L39](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Mapped.php#L39)
    * [Mapped.php#L40](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/Mapped.php#L40)
  * ```/inc/3rdparty/diff/Diff/ThreeWay.php```
    * [ThreeWay.php#L99](https://github.com/mybb/mybb/blob/feature/inc/3rdparty/diff/Diff/ThreeWay.php#L99)

**Comment by dvz** [comment]
The `Diff` update pulled in #2797 contains code which assertions might fail. We can use patches that were recently applied to the library in WordPress: https://core.trac.wordpress.org/ticket/41526
