### ISSUE TITLE
Broken attachment name

### ISSUE THREAD

**Issue by PirataNervo** [mybb/mybb#2751]
![screenshot](https://cloud.githubusercontent.com/assets/1008807/26453457/aee43624-415b-11e7-9207-ae6ee8c06b7a.png)

The problem is in global.lang.php:
`$l['rel_time'] = "<span title=\"{5}{6}\">{1}{2} {3} {4}</span>";`

This is used in the my_date function which is used by functions_post.php to get $attachdate which is then placed in the title property of the hyperlink in template `postbit_attachments_attachment`

**Comment by PirataNervo** [comment]
Pull request: https://github.com/mybb/mybb/pull/2752

Not sure if you guys want this as it seems to revert your addition.

**Comment by euantorano** [comment]
It would probably be better to change the code to prevent it breaking the HTML, rather than stepping back the change to add the title in my opinion.

**Comment by Cu8eeeR** [comment]
I agree with @euantorano

**Comment by PirataNervo** [comment]
That's really up to you guys, I just provided a Pull Request for my temporary fix :) People didn't really like seeing attachment names like that!

**Comment by uzbugg** [comment]
I am sorry I just have done this, but here you can find another solution, possibly the easiest one...  --> https://github.com/mybb/mybb/pull/2758 .

**Comment by ErikThiart** [comment]
When will this be fixed, or what can I do in the meantime? It breaks the attachments as well as the last posted by date next to the threads.

**Comment by euantorano** [comment]
@ErikThiart You can try the patch here: https://github.com/mybb/mybb/commit/0041042190d5148703c63a8f4d2c595cf09f4c9a

I haven't yet had time to test @uzbugg's PR.

**Comment by ErikThiart** [comment]
Thanks for the reply. This might be slightly out of scope, Doing these changes I fcked up somewhere along the way messing with the functions file.

Now when I try to login to the Admin CP (2 factor enabled) it keeps saying the Authenticator code is wrong. Is there a way to access the admin CP bypassing the 2 factor authentication? 

I have full access to the server, DB and files.

**Comment by euantorano** [comment]
In the `mybb_adminoptions` table in the DB, empty the `authsecret` and `recovery_codes` columns for your `uid` and that should fix it.

**Comment by ErikThiart** [comment]
My god! I will ship wine to your front door all the way from South Africa!

Thank you my good sir!

**Comment by djmojacar** [comment]
A manual fix is to open 
/inc/languages/english/admin/global.lang.php
and change the line reading
`$l['rel_time_changedbydavid_realonebelow'] = "<span title='{5}{6}'>{1}{2} {3} {4}</span>";`
to
`$l['rel_time'] = "{1}{2} {3} {4}";`

**Comment by ErikThiart** [comment]
I seem to have the same problem in the threads. The last post time:

less than 1 minute ago">Last Post by PersonX

**Comment by ErikThiart** [comment]
https://i.imgur.com/bHroiJC.png 

^Thid is my issue the last by now shows a date if it is yesterday.
