### ISSUE TITLE
$sourcemode causes page to scroll to editor textarea when set to true via usercp.

### ISSUE THREAD

**Issue by floofytsuna** [mybb/mybb#2754]
When a user sets the option to show the MybbEditor in source mode by default ($sourcemode = "MyBBEditor.sourceMode(true);";) any page using it will scroll until the editor is in view. This causes issues on certain pages since the top of the page is not visible by default.

Checked in 1.8.11 on a test instance.

**Comment by martec** [comment]
already fixed https://github.com/samclarke/SCEditor/issues/456
need wait release of sceditor 2.0.
Or use another editor.
