### ISSUE TITLE
Go To in private.php doesn't work

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#2759]
If you have a lot of private messages and you see pages like "1-2-3-4-5-....-finalpage-go to" when you click on go to and write any number to there it simply doesn't work. Giving the page you searched couldnt be found error. Same function works in forumdisplay where there are a lot of pages and you can go to any page via go to button. But in private messages it doesn't work. 

I would appreciate if someone can try to reproduce this in their own forum. I couldn't try it in here, mybb community forums since I don't have that much private messages.

Original thread: [Go To in private.php doesn't work](https://community.mybb.com/thread-210824.html)

**Comment by JordanMussi** [comment]
Fixed in #2782
