### ISSUE TITLE
Registered group bugs out when they have "can view deletion notices" and cant see new posts.

### ISSUE THREAD

**Issue by RussianRonin** [mybb/mybb#2767]
As I said above, the registered group bugs out when they have "can view deletion notices" and cant see new posts because I think the deleted posts count and will only count towards the max post count in that thread. It is a bit hard to explain. But if "can view deletion notices" is off, the count of posts is correct because they cannot see deleted posts anymore and can see the latest post.

**Comment by JordanMussi** [comment]
@RussianRonin I've tried to reproduce the error that you described but not been successful.

Please could you provide some more details:
- what do you mean by "bugs out"? Are there any error messages?
- what do you mean by "cant see new posts"? Which setting have you turned off and where (forum permissions or group permissions) - there is only the option to disallow viewing threads but not disallow viewing posts.

**Comment by JordanMussi** [comment]
Related to #1565 #2500

**Comment by RussianRonin** [comment]
As a forum admin, the page count is incorrect for some very long threads. Ex.
http://i.imgur.com/KsFZGoQ.png
but if you click on 53, there are more pages in the actual thread than are shown in the thread list.
http://i.imgur.com/iMEYkbV.png

I think they are both related to how deleted notices are counted vs post count and how many pages exist.

I think this relates to how many deleted posts there are in a thread. The forum thread list page count does not take into account the deleted posts when calculating the number.

I will have to get more info later about the view deletion notices issue.

**Comment by Suraf** [comment]
Interesting, I've checked and so far I haven't seen related issues.

**Comment by JordanMussi** [comment]
@RussianRonin thank you for your report! I can confirm this is an issue. #2500 didn't change multipage links generation. Fixed in #2779.
