### ISSUE TITLE
Showthread.php - add a new plugin hook before postbits

### ISSUE THREAD

**Issue by Cu8eeeR** [mybb/mybb#2787]
https://community.mybb.com/thread-210749.html

**Comment by euantorano** [comment]
Any thoughts @mybb/developers @mybb/sqa? I'm the only one who responded to the original thread, so just wanting to check others are happy to add this hook.

**Comment by Suraf** [comment]
I support this idea.

**Comment by tommm** [comment]
This looks like the plugin hook wants to be added to manipulate the `$pids` in the query?

Apologies if this is misinterpreted, but if the `$pids` are manipulated, wouldn't the pagination that is processed above this block of code be (potentially) incorrect?

I guess I'm wondering _why_ there would be a need to manipulate the posts that are being returned for the page, when you've got very powerful hooks in `build_postbit`.

**Comment by euantorano** [comment]
I would guess that's the intention, yes. I hadn't realised the pagination was built before this hook, so that could be problematic.

An example of problems this would solve would certainly help understand the use case.

**Comment by tommm** [comment]
I don't think a plugin hook to manipulate getting the posts for the page is needed.

If the goal is to query _which_ posts are loaded on the page, hooking into the `postbit` hooks and adding `$pids` to the global scope in the hook function will return the string of PIDs used in the query, which can then be just to gather any additional data needed for posts.

More visibility on the usage case would be good.

**Comment by SvePu** [comment]
With this hook you could catch e.g.: all $uids of a thread page....so you could save up some db queries.

**Comment by tommm** [comment]
@SvePu that can already be done easily in `postbit` hooks without any queries. The proposed hook, it seems, wouldn't help this situation.

**Comment by SvePu** [comment]
@tommm how you can fetch all unique $uids of a single thread page in an array with the postbit hook??

**Comment by tommm** [comment]
@SvePu https://gist.github.com/tommm/874ac136e8d04faa9c3da0e68e046a8e

**Comment by Cu8eeeR** [comment]
OK guys, so do we reject this?

**Comment by euantorano** [comment]
I think so, yeah. ANy other thoughts @mybb/developers?

**Comment by tommm** [comment]
I personally can't see a reason for it. Unnecessary hooks slow the software down, and this is a key point in the code where you don't want to do that.

**Comment by Cu8eeeR** [comment]
I am closing then :)
