### ISSUE TITLE
No activation email

### ISSUE THREAD

**Issue by XakepSDK** [mybb/mybb#2800]
Registration method set to: send email verification
No email after registration.
In AdminCP i see block with "Awaiting users X".
MyBB 1.8.12

**Comment by Stefan-ST** [comment]
We do not provide support on this bug tracker. Please use our forums instead: https://community.mybb.com/

**Comment by XakepSDK** [comment]
Is this bug tracker? Forum sends an email, but activation emails aren't sent.

**Comment by kawaii** [comment]
@XakepSDK you need to post your issue here: https://community.mybb.com/forum-157.html

:slightly_smiling_face:
