### ISSUE TITLE
I can't set to 0 to disable some feature in AdminCP

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#2801]
I think there is a bug in Admin CP -&gt; 

Maximum Number of Poll Options (Home » Board Settings » Posting)
The maximum number of options for polls that users can post. Set to 0 to disable the limitation.

But the minimum in textarea is 2, I can't write 0 to disable:

And also in Maximum Attachments Per Post (Home » Board Settings » Attachments)
The maximum number of attachments a user is allowed to upload per post. Set to 0 to disable.

Original thread: [I can't set to 0 to disable some feature in AdminCP](https://community.mybb.com/thread-211715.html)

**Comment by Cu8eeeR** [comment]
@JN-Jones and others MyBB devs - it is related to this one - https://github.com/mybb/mybb/issues/1766

**Comment by Eldenroot** [comment]
MyBB dev team, is possible to have a fix in MyBB 1.8.13? There are 3 issues related to that bug, I would like to fix it but I dont how. Really annoying, breaks many features in ACP :( Thank you guys!

@euantorano @PaulBender @Shade- @dvz and other, keep good work!

**Comment by imteerachotj** [comment]
I found this issues. Can't set 0  to disable some feature.

**Comment by Eldenroot** [comment]
Yes, we know... quite annoying issue, still not fixed. I hope this will be fixed in v1.9 alongs with the ACP rewrite. Be patient please :)
