### ISSUE TITLE
If there's a quote in excerpt for pm_subscription, new date code causes an issue

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2802]
If user gets private message notification for a message, starting with quote, they see something like this:

Quote:...
Here is an excerpt of the message:
------------------------------------------
Username (who get quoted): (&lt;span title="19-07-2017, 15:21"&gt;1 minute ago&lt;/span&gt;)
--
Quoted message
------------------------------------------

To view the thread, you can go to the following URL:
...

Original thread: [If there's a quote in excerpt for pm_subscription, new date code causes an issue](https://community.mybb.com/thread-211828.html)

**Comment by PaulBender** [comment]
Added a fix for this issue in #2753
