### ISSUE TITLE
Admin Panel (config-banning) has ban adding below the ban list

### ISSUE THREAD

**Issue by nsuchy** [mybb/mybb#2803]
The panel to add a ban is below the ban list - this is an issue for forums with huge ban lists and should be changed. If MyBB agrees with the change - say so on this issue and I'll do a PR.

**Comment by Cu8eeeR** [comment]
+1, would be nice to change all panels (moved them to topú - in ACP -> Users and Posts -> BAN tab

**Comment by Cu8eeeR** [comment]
@nsuchy - can you push your PR?

**Comment by nsuchy** [comment]
@Cu8eeeR Hi there - sorry about the delays -other projects were taking priority - when do you need this done by?

**Comment by Cu8eeeR** [comment]
@nsuchy - IDK when MyBB dev team wanna release v1.8.13 so better sooner than later, nice improvement :)

**Comment by nsuchy** [comment]
See: https://github.com/mybb/mybb/milestone/18 for how close the next update is. That being said I'll try to get this done some time in the next few days.

**Comment by euantorano** [comment]
Milestones aren't very accurate due to the way we currenty use them - when we complete a release (eg: when we release .12), all other issues then get assigned to the next release even if they might not make it.

Basically: take milestons with a pinch of salt 😉

**Comment by nsuchy** [comment]
The affected file is https://github.com/mybb/mybb/blob/feature/admin/modules/user/banning.php - edits to it should resolve this issue. I'm putting this here for MyBB's reference https://github.com/mybb/mybb/blob/feature/admin/modules/user/banning.php

**Comment by Cu8eeeR** [comment]
@nsuchy - Yes, we all know that. Feel free to edit and send your PR into feature branch.

**Comment by Cu8eeeR** [comment]
@nsuchy - do you plan to submit a PR? thank you!

**Comment by nsuchy** [comment]
@Cu8eeeR Sorry things have been really busy and now I have other PRs I'm working on. Did you want to work on this issue?

**Comment by SoftwaysAndre** [comment]
Wouldn't it make sense to put the "Ban User" button within the panel and then move it above the ban list?

**Comment by Cu8eeeR** [comment]
@SoftwaysAndre - it would be nice to move the table with banned users/IPs/Usernames etc below the "Ban a...." part.
