### ISSUE TITLE
Forum Description Color

### ISSUE THREAD

**Issue by PrilA3** [mybb/mybb#2810]
When I first used 1.6 I was able to add a forum description and add it with color 
(eg description) Testing <font color="red">Something</font> but now when I try add color, I get 403 once I "save forum settings"... Is there another way to add color? I have tried the <span color...> but doesn't work either.

Thanks

**Comment by Stefan-ST** [comment]
We do not provide support here. Please use the community forums instead: https://community.mybb.com/

Thank you.
