### ISSUE TITLE
Issue with thread's post count

### ISSUE THREAD

**Issue by Shade-** [mybb/mybb#2815]
The Problem
Post count in thread doesn't consider deleted posts if permission "can view deletation notice" is active for normal users and guests.

Steps to Reproduce
Edit forum permission of a forum for registered usergroups and check the input Can view deletion notices? in tab "Editing". Then create a thread in that forum e post some replies. Then delete the first reply and check the thread with both admin and registered users. With admin account you'll see all the post. With registered users you can't see the last post or others if there are many deleted posts.

Original thread: [Issue with thread's post count](https://community.mybb.com/thread-210189.html)

**Comment by Shade-** [comment]
## Steps to reproduce
- post a thread X;
- enable "Can see deletion notice?" permission to usergroup Y;
- set 10 as default's post per page setting;
- post 10 replies to thread X. The multipage selector appears;
- delete 1 reply, not the last one;
- see the thread with an user in usergroup Y. He should see the deletion notice and the multipage, however he does not see the multipage and the last reply cannot be seen unless he manually appends `?page=2` to the URL.

This happens because the page count is calculated upon thread's replies, which are obtained accounting for user's permissions with get_thread(), excluding replies he can't see (deleted/unapproved). The count is updated for moderators only who can see the multipage correctly.

**Comment by JordanMussi** [comment]
Related to #1565 #2767
