### ISSUE TITLE
Bad comment marker in CSS

### ISSUE THREAD

**Issue by 5050** [mybb/mybb#2820]
In admin/styles/default/main.css, at lines 991 and 1033 there are php-like comments (starts with //) that are invalid in CSS.

> // Scroll fix for Opera 

must be replaced by 

> /* Scroll fix for Opera */

**Comment by Devilshakerz** [comment]
https://github.com/mybb/mybb/blob/mybb_1812/admin/styles/default/main.css#L991
https://github.com/mybb/mybb/blob/mybb_1812/admin/styles/default/main.css#L1033
