### ISSUE TITLE
Error reported on avatar upload

### ISSUE THREAD

**Issue by 5050** [mybb/mybb#2831]
Our board reports a few errors per week like this :

> Your copy of MyBB running on xxxxx (http://xxxxx) has experienced an error. Details of the error include:
> 
> Type: 2
> File: inc/functions_upload.php (Line no. 160)
> Message
> opendir(./uploads/avatars): failed to open dir: Operation not permitted

I solved them by replacing in file inc/functions_upload.php, line 160
`$dir = opendir($avatarpath);`
by 
`$dir = opendir(realpath($avatarpath));`

I'm not sure if it is the best way to correct it, but it seems to work.

**Comment by Shade-** [comment]
Please, read https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md. Suggestions should be made here first: http://community.mybb.com/forum-158.html and get accepted by the team. Thank you.
