### ISSUE TITLE
redirect forums do not work

### ISSUE THREAD

**Issue by xensor** [mybb/mybb#2834]
redirect forums do not work.

when i try to make one, i get database error or it can't link to another url. 

https://s.nimbus.everhelper.me/share/1090860/8bs43wq1y5ngmzc7fw01

error #2:

https://s.nimbus.everhelper.me/share/1090864/brpxvl9en56evegw60l2

This is the latest version of mybb on a localhost. This didn't start until 1.8.12.

I been getting these type of errors lately with some plugins to as well. 

Wampp for localhost with latest 5.6 php

**Comment by Shade-** [comment]
Please, read https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md. Suggestions should be made here first: http://community.mybb.com/forum-158.html and get accepted by the team. You already opened a thread there, please wait till a Team member confirms the issue. Thank you.
