### ISSUE TITLE
Broken settings

### ISSUE THREAD

**Issue by HCStrike** [mybb/mybb#2841]
Hello,

For some reason I have some broken settings in my ACP, I have tried reinstalling my forums but that didnt change anything. Here is an example of the settings http://prntscr.com/gks443

Thanks

**Comment by euantorano** [comment]
Hi,

Please see the [CONTRIBUTING](https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md) file - support is offered via the [MyBB community forum](https://community.mybb.com) rather than here, so please create a thread there.
