### ISSUE TITLE
Drafts Incorrectly Counted Toward Total Post Count In Statistics

### ISSUE THREAD

**Issue by WildcardSearch** [mybb/mybb#2842]
I noticed that in my forum today's top poster (which is shown in stats.php page) has absurdly high number of post (52)

When I check this guy's posts I see only 11 posts in last 24 hours.
Any idea what causes that info to mess up?

Original thread: [Saving as Draft considered as posting in stats](https://community.mybb.com/thread-212952.html)

**Comment by WildcardSearch** [comment]
Steps to reproduce:
- visit: https://community.mybb.com/stats.php and note the amount of posts for Today's Top Poster
- create as many drafts as it takes to inflate your post count for the day past the current top poster

This will reveal that saved drafts count toward total post count in Today's Top Poster.

**Comment by PaulBender** [comment]
Can confirm, also unapproved/soft deleted posts are counted as well.

**Comment by WildcardSearch** [comment]
@mybb/developers anyone see a reason this can't be merged. Looks good to me.
