### ISSUE TITLE
Impossible To Allow Unlimited Maximum Avatar Upload Size

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#2844]
The description reads, 

Quote:Maximum file size (in kilobytes) of uploaded avatars. Set to 0 to disable the limitation.

but setting the input to zero results in an error message on submit that informs you,

Quote:Please select a value that is no less than 1.

Steps to reproduce:

Go to ACP » Board Settings » Profile Options

Set "Max Uploaded Avatar Size" to 0 (you will have to type it in as the GUI will not let you go below 1)

Click "Save Settings" submit button

Original thread: [Impossible To Allow Unlimited Maximum Avatar Upload Size](https://community.mybb.com/thread-212989.html)

**Comment by Cu8eeeR** [comment]
Related https://github.com/mybb/mybb/issues/2801
