### ISSUE TITLE
Show Forum Internal Error

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2853]
Are mybb forums limited in the amount of forums?
URL: https://community.mybb.com/forumdisplay....4294967296

Original thread: [Show Thread Internal Error](https://community.mybb.com/thread-213277.html)

**Comment by Eldenroot** [comment]
one more: https://community.mybb.com/thread-213277-post-1285441.html#pid1285441

**Comment by PaulBender** [comment]
That issue has already been fixed with my PR.

**Comment by Eldenroot** [comment]
@PaulBender - my bad, I didnt check your PR, I am sorry, good job!
