### ISSUE TITLE
MyBB Calendar PHP Error

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2854]
I wasn't aware there was a year called 0000 :-/ :-/ :-/ 
URL: https://community.mybb.com/calendar.php?...8888999999

Original thread: [MyBB Calendar PHP Error](https://community.mybb.com/thread-213280.html)

**Comment by PaulBender** [comment]
I believe I fixed this issue in #2835 (the calendar won't go back before January 1901 now).

**Comment by euantorano** [comment]
@PaulBender Does that patch also fix the second issue mentioned in the thread relating to an execution timeout?

**Comment by PaulBender** [comment]
No, that still exists.

**Comment by nsuchy** [comment]
@PaulBender Has the full file path disclosure issue been addressed?
![screen shot 2017-10-01 at 5 23 31 pm](https://user-images.githubusercontent.com/8227641/31102716-60781616-a7a1-11e7-8142-cbf887e68be3.png)
