### ISSUE TITLE
member.php "Awaiting Activation Error"

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2866]
Sorry English.

When a member moves to "Awaiting Activation" group.

This member is in the user control panel when "Recent Activation Email" is clicked.

Will not be able to activate the member account

Because, mybb_awaitingactivation table, this user type value is null.

member.php, line 1402: 
PHP Code:&#36;query&nbsp;=&nbsp;&#36;db-&gt;simple_select("awaitingactivation",&nbsp;"*",&nbsp;"uid='".&#36;user['uid']."'&nbsp;AND&nbsp;(type='r'&nbsp;OR&nbsp;type='e'&nbsp;OR&nbsp;type='b')");&nbsp;

to correct

member.php, line 1531: 
PHP Code:&#36;uid&nbsp;=&nbsp;&#36;user['uid'];&nbsp;
this code after

PHP Code:if(!&#36;user['type'])&nbsp;{&#36;user['type']&nbsp;=&nbsp;"r";}&nbsp;

I hope I made myself clear

Original thread: [member.php "Awaiting Activation Error"](https://community.mybb.com/thread-213410.html)

**Comment by Eldenroot** [comment]
OK, mentioned fix works for me, if anything I can pull a PR :)

**Comment by euantorano** [comment]
Might be best to fix the admin CP to actually fill that column with the correct value I think.

**Comment by ozanakkaya** [comment]
Admin cp does not have. Because, "do_resendactivation" adding a new row to mybb_awaitingactivation table.

And
$cache->update_awaitingactivation(); ???

**Comment by Shade-** [comment]
I haven't looked at it, but we can add it. `$cache->update_awaitingactivation()` updates the cache by reading from the database, it does not update the database itself if that's what you asked.

**Comment by ozanakkaya** [comment]
What if the wrong address is waiting for activation??

**Comment by effone** [comment]
That is to be taken care by admin. If admin is worried about storing valid mails he should not set registration to 'Administrator Activation' at the first place. But thats a different issue. Our current situation is about manually moving a user to Awaiting Activation group (though I have no clue why anyone will want to move an activated member to awaiting).

**Comment by Sama34** [comment]
The user activation process should be the same as the set option in settings.

**Comment by Ben-MyBB** [comment]
PR wasn't linked to this issue but I can't replicate this after #3204
