### ISSUE TITLE
Unknown error occurred returned for several error() calls in warnings.php

### ISSUE THREAD

**Issue by JordanMussi** [mybb/mybb#2881]
Several error messages are using language strings from `datahandler_warnings` but that language file is not loaded in the `warnings.php` context, thus causing `null` to be passed to `error()` which falls back to `An unknown error has occurred`.

The fix is a simple `$lang->load("datahandler_warnings");` underneath the current `$lang->load("warnings");`. However I thought it be best to discuss if the language strings should be copied to the `warnings` language file instead? It might be unexpected the datahandler language file being loaded outside the datahandler so should probably be avoided.

There may be more instances of this sort of use of datahandler language string use around other parts of the codebase.

**Comment by euantorano** [comment]
Duplicating language strings is kind of annoying IMO, so I'd just load the data handler warnings instead of making life more difficult for translators.

**Comment by JordanMussi** [comment]
There is one other place where datahandler language strings have been used:
https://github.com/mybb/mybb/blob/efce2244b3fe3980f48617d363b744c5a3631a35/usercp.php#L261-L265
This section of code was introduced in 32c55f6e342d95ddcadf0a30d960a33f3f0c28b1 fixing [Issue 2077](http://web.archive.org/web/20131109093242/http://dev.mybb.com/issues/2077).

This is a weird one because the expression would never evaluate to true as the language string isn't loaded. Having done some testing, what it was supposed to avoid doesn't actually happen without the block so it could be removed. For now I've modified the block so that it resets the option to the value stored in the DB.
