### ISSUE TITLE
1264 - Out of range value for column 'pid' at row 1

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2884]
Code:Query:
INSERT INTO mybb_forums (`name`,`description`,`linkto`,`type`,`pid`,`parentlist`,`disporder`,`active`,`open`,`allowhtml`,`allowmycode`,`allowsmilies`,`allowimgcode`,`allowvideocode`,`allowpicons`,`allowtratings`,`usepostcounts`,`usethreadcounts`,`requireprefix`,`password`,`showinjump`,`style`,`overridestyle`,`rulestype`,`rulestitle`,`rules`,`deletedthreads`,`deletedposts`,`defaultdatecut`,`defaultsortby`,`defaultsortorder`,`icon`) VALUES ('test','','','c',-1,'','1','1','1','0','1','1','1','1','1','1','1','1','0','','1','0','0','0','','','0','0','0','','','folder.png')
Please contact the MyBB Group for technical support.
Occurs when trying to copy forum with forum type set to category

Fresh install with https://community.mybb.com/mods.php?action=view&amp;pid=930 this them and https://community.mybb.com/mods.php?action=view&amp;pid=916 this plugin 

plz help

Original thread: [1264 - Out of range value for column 'pid' at row 1](https://community.mybb.com/thread-213662.html)

**Comment by dvz** [comment]
Related: https://community.mybb.com/thread-53709-post-389000.html#pid389000

**Comment by JordanMussi** [comment]
I think this can be closed as it was duplicated by #3938 which has been fixed.
