### ISSUE TITLE
PGSQL, SQLite Database Classes Do Not Abide By DB_Base Interface

### ISSUE THREAD

**Issue by WildcardSearch** [mybb/mybb#2885]
In `session::create_session()` `DB_Base::replace_query()` is used with two extra parameters that only affect the PGSQL database class.

https://github.com/mybb/mybb/blob/bf6e33fdfd2d93c4c696023f1f69cb9ae8024177/inc/class_session.php#L526

The definition in `db_base.php`:

https://github.com/mybb/mybb/blob/bf6e33fdfd2d93c4c696023f1f69cb9ae8024177/inc/db_base.php#L352

There are many other places in which `replace_query` is used with three to four arguments rather than the two parameters specific in `DB_Base`.

The best course of action, imo would be to edit the existing definition to include the optional parameters and edit all of the database class wrappers to include the optional arguments in their definitions.

If that course of action is agreed upon, I am happy to create the pull request.

**Comment by euantorano** [comment]
Yes, that would be my preferred action too.
