### ISSUE TITLE
Extra unnecessary WHERE in 1813 Upgrade Script

### ISSUE THREAD

**Issue by mohammadg** [mybb/mybb#2901]
For the update script for 1813, upgrade41.php:

```
$db->update_query("moderatorlog", array(
  "action" => $db->escape_string($stripped),
), "WHERE tid = '".$row['tid']."'");
```

WHERE should not be provided to `$db->update_query` in argument 3?
Causes SQL syntax error (using MariaDB 10.2.10).

Example of broken query (duplicate WHERE):
`UPDATE mybb_moderatorlog SETaction='Thread Deleted Permanently: I\'m leaving.' WHERE WHERE tid = '7958'`

I managed to fix the issue locally and finish the upgrade script without any issues myself.

**Comment by WildcardSearch** [comment]
Good catch!

**Comment by bositman** [comment]
This is STILL there if you download the 1.8.13 changed files from Mybb 
https://mybb.com/versions/1.8.13/ 
Please fix this ASAP.

**Comment by euantorano** [comment]
Hi, were aware of this but are waiting for somebody to be available to upload the changes packages.
