### ISSUE TITLE
ratethread.php - unnecessary code

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2903]
Hi!

What is the purpose of this duplicate?

https://github.com/mybb/mybb/blob/featur...hp#L51-L62

Original thread: [ratethread.php - unnecessary code](https://community.mybb.com/thread-214050.html)

**Comment by JordanMussi** [comment]
(Link was broken in process of copying to GitHub) https://github.com/mybb/mybb/blob/efce2244b3fe3980f48617d363b744c5a3631a35/ratethread.php#L51-L62

**Comment by JordanMussi** [comment]
Closed in #2904.
