### ISSUE TITLE
php 7.1.x errors - admin/modules/users.php

### ISSUE THREAD

**Issue by Eldenroot** [mybb/mybb#2905]
After updating to v1.8.13 (from v1.8.12; php 7.1.x) I get these php errors in ACP -> User & Groups -> Edit user -> Profile - these errors are shown below the setting. I use custom profile fields.

After discussion with @euantorano over Discord, he found that there is an issue on lane #4046 (admin/modules/users.php) - it creates an array, then overwrites it with an empty array.

I am enclosing image:
![phperror](https://user-images.githubusercontent.com/778890/32700048-7c40a032-c7bf-11e7-82be-7cc312285ae4.png)

**Comment by euantorano** [comment]
https://github.com/mybb/mybb/blob/feature/admin/modules/user/users.php#L4046 - Array access of a variable not yet defined (defined [here](https://github.com/mybb/mybb/blob/feature/admin/modules/user/users.php#L4048)).

That whole block looks suspect - it writes to an array, then assigns an empty array to the variable, losing the old content.
