### ISSUE TITLE
Signature Permissions Bug

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2913]
Example bug.

Member in 2 groups:
1. Registered
2. Custom (type 4)

Registered is set with canusesig=1 and canusesigxposts=250
Custom group is set canusesig=0 and canusesigxposts=0

Member is added to the custom group.  They are able to add a signature even if their post count is under 250.  This is because &#36;groupzerogreater (class_core.php) has the canusesigxposts but not the canusesig permissions.

Logic grabs the canusesig as 1 and the canusesigxposts as 0.  It should grab the canusesigxposts permission where it get the canusesig. Or at least the lowest number if greater than 0.  

Best of luck fixing.

Original thread: [Signature Permissions Bug](https://community.mybb.com/thread-214294.html)

**Comment by kawaii** [comment]
I have confirmed this issue on MyBB 1.8.13.
