### ISSUE TITLE
Inline Moderation Select All

### ISSUE THREAD

**Issue by labrocca** [mybb/mybb#2915]
While using Inline Moderation (version 1.8.12) the "select all results" doesn't actually work.  Tried on 3 installs including a near default version.

Can someone else confirm.  Example use would be to view more than one page of results for threads then try to close them all by either clicking the "Select all XXX results in this search." option.  Then open or close the threads.  For me it's not working at all on any site I tested. May require further testing but I can't bother with it now.

Bug does exist.

**Comment by kawaii** [comment]
I've confirmed this issue on 1.8.13. Find a user with more than two pages of search results when using finduserthreads, check the 'select all' inline moderation option and then the option to select ALL of the results from all pages in the query. Then, in the inline moderation action dropdown menu, select the option to close the threads. The success message will trigger but when you are returned to the search view no action will have actually been taken on any of the threads in the selection.

**Comment by euantorano** [comment]
Some further information/steps to reproduce the issue: https://community.mybb.com/thread-214320-post-1289833.html#pid1289833

**Comment by fluxtion** [comment]
Seems a bit more involved than my previous fixes so I'll be going with this one.
