### ISSUE TITLE
Add a Dependency Injection Container

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2920]
The current MyBB code uses tightly coupled code and global variables for instances of classes. This leads to repetitive `global $mybb` lines and makes it difficult to mock and test individual components.

With a Dependency Injection Container, all services would be defined in the DI, allowing them to be easily swapped out and mocked. It would also make it easy to extend instances of classes (such as replacing the core `$mybb` instance with an extended `MyCustomMyBBCore` instance that adds additional methods) from within plugins.

## Choosing a DI

There are multiple DI libraries for PHP, all with similar features and approaches. As far as I see it, there are the following well known libraries to choose from that meet our requirements:

- [Pimple](https://pimple.symfony.com/) - a simple DI container, no support for automatic resolution of dependencies. Does not conform to PSR-11.
- [PHP-DI](http://php-di.org/) - a slightly more complex DI container with support for automatic resolution of dependencies based upon constructor type hints. Conforms to PSR-11.
- [Container by the League of Extraordinary packages](http://container.thephpleague.com/) - a simple but powerful DI container that conforms with PSR-11.
- [Laravel's Container](https://github.com/illuminate/container) - the core container from the Laravel framework. Documentation is only available as part of the Laravel documentation, [found here](https://laravel.com/docs/5.5/container). Conforms to PSR-11.
- [Symfony's DependencyInjection Component](https://github.com/symfony/dependency-injection) - the core container from the Symfony framework. Documentation is only available as part of the Symfony documentation, [found here](https://symfony.com/doc/current/components/dependency_injection.html). Conforms to PSR-11.

## Choice of library

Ideally we'd choose a library sooner rather than later, and preferrably it would be one that conforms to PSR-11 (which would make it easier to swap out in the future due to it following a defined interface).

**Comment by JordanMussi** [comment]
It might also be good to consider the Laravel [Service Container](https://laravel.com/docs/master/container) ([PSR-11 compliant](https://laravel.com/docs/5.5/container#psr-11)). As 2.0 is using Laravel, it makes sense that we use Laravel components where we can since the idea behind 1.10 is to phase in components which 2.0 will use.

**Comment by 036** [comment]
I agree that if we're ever looking to move to Laravel in the future it would be wise to use the Laravel service container.

**Comment by euantorano** [comment]
Yeah, I think the Laravel Container is probably where we're headed. I'm going to open a PR tonight to add it hopefully, then can update my SMTP PR to make use of it.

**Comment by 036** [comment]
A note on this we need to find the best way of handling where the classes are going to be bound to the container while bearing in mind plugin developers may also want to bind classes to the container.

I propose something similar to Laravels service providers or having a directory of providers that get bound to container on runtime however I'm not sure how feasible that is.

**Comment by euantorano** [comment]
One thing I definitely don't want is to have everything registered in a file like `global.php`. I haven't yet thought about how we're going to do it, but will start thinking about it as we work on rewriting the ACP.

**Comment by euantorano** [comment]
This is implemented in 1.9 already.
