### ISSUE TITLE
Can't upgrade from mybb 1.8.13

### ISSUE THREAD

**Issue by RikoDEV** [mybb/mybb#2924]
The update wizard does not have an update option for mybb 1.8.13

![upgrade](https://user-images.githubusercontent.com/18230443/33337893-b3e5313a-d474-11e7-89c1-7794c4776317.PNG)

![upgrade2](https://user-images.githubusercontent.com/18230443/33337960-eb1320e0-d474-11e7-99d8-2243bf0d1be8.PNG)

**Comment by kawaii** [comment]
Are you sure that your forum is actually 1.8.13? It's possible that you did not upgrade correctly from 1.8.12 previously. Can you paste line 24 of `inc/class_core.php` here please?

**Comment by RikoDEV** [comment]
I overwritten old files with update files.
public $version_code = 1814;

**Comment by dvz** [comment]
If you have MyBB 1.8.13 already installed, there is no need to run the upgrade script for 1.8.14 - only files need to be overwritten (the _Changed Files_ package can be used).

**Comment by RikoDEV** [comment]
I created a new test forum on localhost, I used hanged Files package and still have the same problem.

**Comment by metonator** [comment]
Read the message above. **You don't need** to run update script.

**Comment by RikoDEV** [comment]
Solved

**Comment by Eldenroot** [comment]
I can confirm, anyway I didn't know about that so I selected 1.8.12. Everything seems to be fine.
