### ISSUE TITLE
ACP User Group Save Error

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2929]
mybb vers : 1.8.14
error string : Fatal error: Call to undefined function array_column() in /home/homeer/public_html/forum/admin/modules/user/groups.php on line 977
error url : http://sitename.com/admin/index.php?module=user-groups&amp;action=edit&amp;gid=4

save and url change result :

Original thread: [ACP User Group Save Error](https://community.mybb.com/thread-214528.html)

**Comment by euantorano** [comment]
This bug is caused by the use of [`array_column`](http://php.net/manual/en/function.array-column.php) which is only available in PHP >= 5.5.0: https://github.com/mybb/mybb/blob/feature/admin/modules/user/groups.php#L977

It's also uses on line `747`: https://github.com/mybb/mybb/commit/b018d3e90752caf5546e588844552f3fea788e4f#diff-ae3e55d69ec857aaacae92249064aa57R747

**Comment by kawaii** [comment]
- [x] Confirmed that the issue only affects anyone running PHP < 5.5.0
- [x] Confirmed that @euantorano's provided patch resolves the issue for people using PHP < 5.5.0

Looks good, this can be merged. :slightly_smiling_face:
