### ISSUE TITLE
Deleting a large number of users in ACP

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#293]
> I have had this issue from at least 1.6.3 on.
> 
> I search users in the ACP and return the results as a table. (This is usually done when I have a list of users I want to get rid of.) I return more than about 500 results (haven't found the exact figure at which this happens, but it seems to be a little over 500). Then I select the "check all" box to select them all. Then I select "Delete User(s)" from the drop down box at the foot of the page. Then hit "Go".
> 
> The page then returns to the user list without deleting the users and reports: "Sorry, but you did not select any users. Please select some users and try again."
> 
> I have reproduced this error on several different installations of v1.6.7.

Original report: http://dev.mybb.com/issues/1998
Reporter: John Swoggy
Status: New

**Comment by Naththo** [comment]
Can't reproduce.

**Comment by Destroy666x** [comment]
Me neither, tested with over 1000 accounts on one page and it worked, so rejecting.
