### ISSUE TITLE
Cannot install 1814 on PHP 7.2.0

### ISSUE THREAD

**Issue by kawaii** [mybb/mybb#2931]
MyBB 1.8.14 will fail to install when executed using PHP 7.2.0.

The following error message is presented to the user upon attempting the theme insertion stage of the installation procedure:

![image](https://user-images.githubusercontent.com/12242877/33688201-7d41daa2-dad2-11e7-8dbc-01338f75bb19.png)

**Comment by dvz** [comment]
https://github.com/mybb/mybb/issues/2927
