### ISSUE TITLE
Upgrading from 1.8.12 to 1.8.14 isn't working

### ISSUE THREAD

**Issue by greencopper** [mybb/mybb#2936]
I haven't got time to register on the forum and this is a bug report.

I have just followed the guide in order to upgrade from version 1.8.12 to 1.8.14. Since this is a full upgrade I downloaded all the files and copied the files over (overwrite) the old ones. Afterwards MyBB isn't working and I am getting the following very unhelpful message:

```
MyBB Internal: One or more warnings occurred. Please contact your administrator for assistance.
```
And:

```
MyBB has experienced an internal error and cannot continue.

Please contact the MyBB Group for technical support.
```
Some debugging info would be useful. I have checked the PHP logs as well, but since this is an internal MyBB error, nothing gets into the logs.

**Comment by euantorano** [comment]
You need to turn on error reporting in the ACP. `ACP > Configuration > Server and Optimization Options > Use Error Handling  = On; Error Logging Medium  = Log errors; Error Type Medium  = Warnings and Errors; Error Logging Location  = ./error.log`.

This will create an `error.log` file in the root directory (eg: next to `index.php`, `forumdisplay.php`, `showthread.php`, etc.) that will contain more detailed error information to track the problem down.

**Comment by greencopper** [comment]
Thanks, I did that and got the following strange message:

```
<error>
	<dateline>1513036132</dateline>
	<script></script>
	<line>0</line>
	<type>42</type>
	<friendly_type>MyBB Error</friendly_type>
	<message>Your board has not yet been upgraded. Please do so before attempting to browse it.</message>
</error>
```

**Comment by greencopper** [comment]
I found this which solved the issue, I wish that would be displayed as the error message. I have wasted so much time finding this.

https://community.mybb.com/thread-89418.html

**Comment by greencopper** [comment]
The documentation doesn't mention running this after over writing the old files, should this not be mentioned?
