### ISSUE TITLE
Only show sensitive errors to admins by default

### ISSUE THREAD

**Issue by 036** [mybb/mybb#2962]
At the moment MyBB will show almost all errors including SQL errors to the end user regardless of status. On forums I've run in the past I've always modified the error handler to only show the sensitive DB errors to the administrator group.

**Comment by fluxtion** [comment]
@036 Does this mean you already have the code to do it? If you're not planning to do a PR based on this and you give me an example of how you're implementing it, I don't mind putting it into the main code.

**Comment by 036** [comment]
@fluxtion I have the code ready but wanted to confirm everyone agreed before creating a PR

**Comment by JordanMussi** [comment]
I would agree with this. Here's some quick thoughts I've had:

I would expect there to be a generic whoops error message for normal users when an error does happen? Also for the board not installed error and database connection errors (plus others I haven't thought of) you won't be able to determine if you are showing to an admin, so these would be shown to everyone.

Make sure it respects the `$mybb->dev_mode` option (shows errors to everyone if true).

**Comment by fluxtion** [comment]
@036 In that case, I strongly agree with this addition. I would custom mod this myself too and think it should be a secure default instead. :)

**Comment by effone** [comment]
@036 any status on the pr? You can place it anyway for us to see how it goes good and subsequent possible merge...

**Comment by demtor** [comment]
If nobody is working on it, I could throw something (waiting for a confirm before), I find it useful. A new setting that give the possibility to enable/disable silent errors, where if enabled, instead of an error will be shown a custom error message. In addition, every type of error (silent or not) will have a custom ID which can be sent to the administrator to check it in the logs.

I was also thinking to integrate a log viewer (of the error_log file), together with the other logs on Tools & Maintenance. I have a neat idea on how to make it, and could be useful in order to filter logs by type, ID, etc. Waiting for a confirm also for that.

**Comment by effone** [comment]
We always encourage people to contribute. Your PR is most welcome.
Please bear in mind that this is targeted to be implement in 1.9

**Comment by euantorano** [comment]
I've been looking into this, I think it's something we could fix in 1.8 without too many changes.

Currently, if the `Error Logging Medium` is `None` (as it is by default), then error details are shown. The only way to hide the error details, is to change `Error Logging Medium` to any other value. This then runs the peeker to show the `Error Type Medium` setting. The `Error Type Medium` setting can then be changed to `Hide Errors and Warnings`.

In my opinion, we should always show the `Error Type Medium` setting, and default that setting to `Hide Errors and Warnings`, unless we detect the hostname at install is `localhost`.

It might also be a good idea to look at re-phrasing the actual error page - it currently says:

> Please contact the MyBB Group for technical support.

This leads to us receiving email to `contact@` fairly often, which just gives me more work (I try to respond to all emails).

The MyBB Group text should only show for admins, and normal users should be advised to contact the site admins.

**Comment by JordanMussi** [comment]
I've just come across an annoying problem with this, for example if `lock` exists for example or any of the other early messages the user hasn't been authenticated yet.

https://github.com/mybb/mybb/blob/1326eea040ef2637ac58c92512f9b6f7dd7696bb/inc/init.php#L107-L110


![image](https://user-images.githubusercontent.com/2552068/84809028-70137280-b001-11ea-81e1-138010c0f112.png)

So you are faced with the frustrating problem of not being even able to login via Admin CP to change error output medium (advanced user can use `settings.php` but this is still sub optimal).

Perhaps some errors should be shown regardless?
