### ISSUE TITLE
Last Post by - Broken

### ISSUE THREAD

**Issue by ErikThiart** [mybb/mybb#2964]
Every time there is a new update my theme breaks.

This is my issue:
[https://i.imgur.com/eLWWrlC.png](url)

![](https://i.imgur.com/eLWWrlC.png)

**Comment by Shade-** [comment]
Please read: https://community.mybb.com/thread-213964-post-1288154.html#pid1288154

GitHub is used to report bugs, not to request support. Next time, please use the community forums, thank you.
