### ISSUE TITLE
Login Form pops up at bottom of page

### ISSUE THREAD

**Issue by halojoy** [mybb/mybb#2967]
In 1.8.14 and 1.8.13 there seems to be a bug.
The login form pops up at very left bottom of page.
So, I have gone back to 1.8.12 ... which works correct.

Normally Login Form pops up in very center of page

I wait for 1.8.15 before I update again from 1.8.12

**Comment by Shade-** [comment]
Please read https://community.mybb.com/thread-213964-post-1288154.html#pid1288154. No need to wait for 1.8.15, just update your stylesheets :)
