### ISSUE TITLE
Reputation Wordwrap

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2970]
https://community.mybb.com/reputation.php?uid=21114

I left Euan T a reputation that was a single long word and it extends the page so that you can't see the whole page anymore.  Buttons for delete, report and other elements become off-page.  

Sorry for the spammy reputation but this is what members do to screw up a reputation page.

In reputation.php a solution would be to add wordrap() function to the &#36;reputation_vote['comments'] as so:

PHP Code:  &nbsp;    &nbsp;&#36;reputation_vote['comments']&nbsp;=&nbsp;&#36;parser-&gt;parse_message(&#36;reputation_vote['comments'],&nbsp;&#36;reputation_parser);  &nbsp;    &nbsp;&#36;reputation_vote['comments']&nbsp;=&nbsp;wordwrap(&#36;reputation_vote['comments'],&nbsp;100,&nbsp;"&lt;br&nbsp;/&gt;&#092;n",&nbsp;true);&nbsp;

Original thread: [Reputation Wordwrap](https://community.mybb.com/thread-215151.html)

**Comment by Eldenroot** [comment]
OK, so do you prefer CSS or php fix? I am a little bit confused, because css fix seems to be better but could bring a lot of issues during updating (due to adding new css). @euantorano
