### ISSUE TITLE
Attached Images Not Showing to Any Member

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#2974]
Hello all,

Fresh install of 1.8 today,  all great except image attachments do not show.

They seem to upload fine, I only started with mybb today so I'm very green, so forgive this if it is a silly question.  All users have permission to download images. 

Can't screenshot it, but if I hover over the 'broken link' image I get the correct file name and size shown.

[attachment=39831]

I have checked the permissions on the upload folder which all seems okay.
[attachment=39832]

Tried JPG and PNG (only formats I have allowed), tried a hard refresh as well as other devices but the same issue occurs.  After test uploads the attachment space increments in the stats page of the admin panel, however in my uploads folder there doesn't seem to be anything there beyond what I image was attachment 3.

The tell-tale upload % bar in Chrome increments as the file is being uploaded, so it must be going 'somewhere'.  Changing the theme has no impact. 

Any pointers most welcome!

Andy

Original thread: [Attached Images Not Showing to Any Member](https://community.mybb.com/thread-215173.html)

**Comment by euantorano** [comment]
I asked the user the following questions:

- Is GZip enabled in ACP - no
- What's in your `.htaccess` file - very simple, nothing to cause attachment issues:

```<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>```

I also tried on the forum in question. I uploaded the following image (uploaded exactly the same below):

![2017-12-31 19 56 51](https://user-images.githubusercontent.com/748913/34630831-a8ea60b6-f265-11e7-9a85-42259e9e0a2e.jpg)

The result was an invalid attachment file when viewed live on the board, as shown below:

<img width="1552" alt="screen shot 2018-01-05 at 22 14 20" src="https://user-images.githubusercontent.com/748913/34630872-d349f0ec-f265-11e7-9c30-5c04a4080298.png">

The thumbnail and `.attach` file in the actual filesystem are correct and can be opened with a standard image viewer once downloaded via FTP.

This isn't the first time I've seen a report of this: https://community.mybb.com/thread-171301-post-1287196.html#pid1287196

It was assumed the above was caused by my MyAlerts plugin, but the forum this ne report comes from doesn't have MyAlerts installed/enabled.

**Comment by SoftwaysAndre** [comment]
Works fine on the latest version of MyBB. Tried it myself. Turned out to be an issue with one of the user's plugins.

**Comment by euantorano** [comment]
See this post by .m.: https://community.mybb.com/thread-215173-post-1294391.html#pid1294391

The issue was a plugin file having a BOM/white space character at the start.

**Comment by abubasil70** [comment]
I have the same nightmare tonight, i was putting display:none here and there to remove some details but it affects the image in the attachments ..
