### ISSUE TITLE
Add plugin hook to format_name()

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#2977]
Add a new plugin hook at https://github.com/mybb/mybb/blob/mybb_1814/inc/functions.php#L3075 so the username format can be further modified basing on available information.

**Comment by tommm** [comment]
Should formatting the username be this dynamic? What are the use cases?

**Comment by dvz** [comment]
E.g. adding labels depending on account-specific conditions (unfortunately the user ID is not passed to this function, but this hook at least allows to look up data by username).

**Comment by tommm** [comment]
`format_name` is called repeatedly in `build_postbit`, and depending on the user's posts per page setting, possibly up to 50 times (and more, if the users browsing this thread is turned on). A badly coded plugin could effect performance.

You have much more flexibility on this by amending the label to the user's username variable in the `build_postbit` function instead, where plugin hooks already exist.

The only use case outside of this are singular areas, such as User CP & WOL, where existing hooks could also be utilised.

I personally don't think adding a hook into a well used function (a rare place for a hook to be in the code as well) is an answer.

**Comment by WildcardSearch** [comment]
I have to agree with @tommm, this seems like it would be more (potentially) harmful than good.

**Comment by dvz** [comment]
> A badly coded plugin could effect performance.
Yes, but that's IMO outside of our scope; I can see a reason against if the unused hook causes performance issues, or could be placed somewhere better - there are more areas where usernames are displayed, including third party plugins.

**Comment by tommm** [comment]
Adding a plugin hook that could lead to performance degradation is within our scope though. Even if it's unused it is still called. Do we effect the 99% of installs that won't use that plugin?

There are even more places where usernames are displayed _without_ `format_name`. Whacking a plugin hook into a well-used function, I don't believe, is an answer to a specific plugin problem.

**Comment by tommm** [comment]
(The plugin can always use Pluginlibrary to modify core code to add this hook).

**Comment by dvz** [comment]
>Whacking a plugin hook into a well-used function, I don't believe, is an answer to a specific plugin problem.

It wouldn't be a core PR if the intent was to use it in a single plugin.

The impact of empty hooks on performance seems negligible even in functions like `format_name()`, so extendibility and how far we intend to go with it appears to be the main issue.

**Comment by WildcardSearch** [comment]
If this isn't intended to make a single plugin possible/easier (as I assumed from the conversation prior to your last post) then what is it that you hope to accomplish here? Your earlier reply of "adding labels" wasn't clear to me.

**Comment by dvz** [comment]
There is a plugin that would benefit from it, as described earlier - it wouldn't be a suggestion for the core if there was no possible use for any other extension that deals with username formatting.

**Comment by kawaii** [comment]
I'd be happy to see this PR merged, there have been a number of times when trying to modify the output of usernames globally in MyBB that I've wished for such a hook to be added, as opposed to other hacky ways that modify a number of templates to do it instead.

**Comment by WildcardSearch** [comment]
You make compelling arguments, but I can't get past this:

> There are even more places where usernames are displayed _without_ `format_name.` Whacking a plugin hook into a well-used function, I don't believe, is an answer to a specific plugin problem.

**Comment by euantorano** [comment]
I feel that this should have been discussed before a PR was opened, but it's a bit late for that now in any case.

I do wonder what kind of use case this has, as has been mentioned before. What can you achieve with this new hook that you can't achieve with display group formatting that isn't going to be terribly unoptomised? If there was a clear explanation and example use case, I think the argument would go much easier.

**Comment by dvz** [comment]
> What can you achieve with this new hook that you can't achieve with display group formatting that isn't going to be terribly unoptomised?

Group display style cannot be mixed, so it's not possible to append labels like country flags or ranking status using it; if the usernames are cached, no additional data needs to be fetched per call to this function.

**Comment by euantorano** [comment]
Ok, that's a good enough argument for me. ANy other thoughts @mybb/developers or can we merge?

**Comment by tommm** [comment]
> if the usernames are cached, no additional data needs to be fetched per call to this function

Curious; is it worth caching formatted usernames (as we do in `format_avatar`)? I mean the function could be called multiple times per page for the same user; is it going to differ that often? (Obviously the plugin can manipulate the output as per the PR).

**Comment by euantorano** [comment]
Might be worth investigating @tommm, but perhaps in a different issue/PR?

**Comment by tommm** [comment]
Considering this issue/PR was a bit cavalier anyway, perhaps it's worth expanding the scope of improving `format_name` within it now we've had a bit of a discussion about it?

**Comment by dvz** [comment]
Execution time of the old code vs new, after applying changes described in https://github.com/mybb/mybb/pull/2978#issuecomment-356324893 and adding a cache check (`static` variable):

- `~1.05` with random usernames
- `~1.7` with random usernames and the new hook (unassigned)
- `~0.4` with a static username

**Comment by euantorano** [comment]
That sounds alright to me, mind updating the PR with those fixes @dvz?
