### ISSUE TITLE
ReCaptcha v1 support being dropped

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#2986]
Google is dropping support for Recaptcha v1 so we should likely remove this for .16

**Comment by buildist** [comment]
any update? Saw this on my registration page the other day, not sure if it fails open or closed but I've also been seeing more spam bots than usual. https://imgur.com/a/1pBZR

They're already running an experiment where a percentage of v1 requests result in that message, and the old API will be disabled completely in March.

**Comment by Shade-** [comment]
Hi, reCaptcha v2 is already supported by MyBB. You need to create a new pair of keys for the new version (on Google’s side), and change MyBB’s settings to “reCaptcha invisible”.

**Comment by nsuchy** [comment]
I would like to do a pull request to solve this issue. Could someone give me a breakdown of what needs to be done. So far I've done the following (not yet pushed to GitHub),

- Removed old recaptcha's support in inc/class_captcha.php
- Removed the type from the settings.xml
- I know I need to add a line to the upgrade script to remove the setting from the database

What else should I do?

**Comment by nsuchy** [comment]
I noticed that in `admin/modules/config/settings.php` on line 934, it checked for captcha types 2 and 4, old recaptcha and no captcha, in my code I've adjusted to types 4 and 5 so the invisible google nocaptcha also gets checked if there is not a public and private key.

**Comment by JordanMussi** [comment]
> What else should I do?

@nsuchy could you also submit a separate PR which gives a deprecation warning notice on the Admin CP dashboard if the board is running the old recaptcha. This PR would be included in the previous version to the main PR in order to give administrators advanced notice of the removal.

**Comment by nsuchy** [comment]
@JordanMussi Sure thing, I'll try to get something ready shortly :)

**Comment by Ben-MyBB** [comment]
Just seen: https://community.mybb.com/thread-216508.html 

Looks like we need to address this in .16.

**Comment by nsuchy** [comment]
@Ben-MyBB It's possible it was the 24 hour brown out period they discussed.

**Comment by effone** [comment]
@JordanMussi Is the depreciation warning notice PR still required? Then I will create one ...

**Comment by Sama34** [comment]
I think only a warning message about the removal will be enough.

But I think users should be notified by a blog post instead.

**Comment by nsuchy** [comment]
@Sama34 From what I understand Google turned off v1. Please see: https://developers.google.com/recaptcha/docs/faq there is not a need for a graceful warning anymore as the v1 API is completely disabled now.

**Comment by effone** [comment]
@Sama34 That should suffice requirement and is a real handy idea.

**Comment by euantorano** [comment]
Ok, we’ll draft a blog post that’s separate to the release post then.

**Comment by Ben-MyBB** [comment]
I can draft the post tonight.

**Comment by effone** [comment]
@Ben-MyBB The blog post will combine #3153 ?

**Comment by Ben-MyBB** [comment]
Makes sense to include both.
