### ISSUE TITLE
MyBB CSS editor converts ../../../ (etc.) into ../

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#299]
> I found this the other day, when I edited my global.css file using the MyBB advanced editor. A lot of url() statements were of the form ../../../images/night/tcat.png for example, and they were all changed to ../images/night/tcat.png upon saving. I didn't think this was a big deal, and the site still worked in all the web browsers I tested.
> 
> However, the server started generating a lot of error logs, and they were all reporting that the file "cache/themes/theme32/images/night/tcat.png" could not be found (with various images). So apparently there are some browsers out there that will try to load CSS URLs relative to the actual CSS file's position in the tree.
> 
> I've solved the problem for now by having absolute URLs, but maybe this is a bug?

Original report: http://dev.mybb.com/issues/1973
Reporter: Adrian Hayter
Status: New

**Comment by JN-Jones** [comment]
Apparently this is intended: https://github.com/mybb/mybb/blob/feature/admin/inc/functions_themes.php#L535-L538
`unfix_css_url` removes `../../../` from all stylesheets if they're edited. Probably some backwards compatibility form 1.2/1.4? Or probably someone tried to be smart and fix urls which are relative to the admin directory?

**Comment by JN-Jones** [comment]
@mybb/developers @mybb/sqa I would propose to simply remove the function above as there's no apparent reason for that (or maybe @tommm as the longest member knows something) and I don't see a reason to keep it.

**Comment by Devilshakerz** [comment]
To my knowledge the current mechanism works correctly.
When the CSS file is saved in the `cache/themes/` directory all paths are converted to be relative to that location, and they are removed when pasting the raw cache file in the ACP.

**Comment by JN-Jones** [comment]
You shouldn't paste the raw cache file in the ACP. And the current mechanism doesn't work if you have your images in a directory which is at least the levels above the forum (which may happen) so it's more a bug than a feature IMHO.

**Comment by Devilshakerz** [comment]
> You shouldn't paste the raw cache file in the ACP.

I'm usually working on cache files and save it in the ACP to make MyBB update the version in the database once it's done - I suspect more people are using this bug as a feature, so it might break compatibility.

**Comment by JN-Jones** [comment]
What does the rest think? I've still the opinion that this is more a bug than a feature and would vote for removing it. Otherwise we should simply close this but we shouldn't keep it open for years...

**Comment by Eric-Jackson** [comment]
I'd vote for removing this. It caused me trouble when I first started working with MyBB, I'm sure others have had issues as well.

**Comment by JN-Jones** [comment]
Any more opinions?

**Comment by euantorano** [comment]
I'd be happy with removing it, so long as existing themes will continue to work as before both when using the cache and when not (such as if the folder isn't writable).

**Comment by WildcardSearch** [comment]
I'm confused. The way I am understanding it the original report was that when editing the stylesheet URLs were altered. If so, that should mean that `unfix_css_urls` needs to be called.

Am I missing something?

**Comment by Shade-** [comment]
It is called: https://github.com/mybb/mybb/blob/88fb8783c02b900bbff5da4fd055fcbc8b8c010f/admin/modules/style/themes.php#L2316

I tend to agree with @Devilshakerz as this has been on for so long it has become a feature, as it's easier to copy and paste cached stylesheets edited through browser's consoles than to manually search for the CSS rule to edit.

**Comment by effone** [comment]
.... so... finally?
remove? don't remove?

**Comment by Eric-Jackson** [comment]
Still much prefer removing it. Most users aren't going to be pasting in cached stylesheet contents edited through the browser (Using it as a feature), they're going to be editing it directly and wondering why their CSS is changing.
