### ISSUE TITLE
Search - keyword contains a umlaut - also non-umlaut keywords are found

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#300]
> Description:  
> When searching for a keyword (e.g. hölle) which contains a german umlaut (ä,ö,ü) the search result contains not only entries which contains the keyword you're looking for but also entries which contain a similar word where the umlaut is replaced by a normal letter (a,o,u), e.g. holle.
> 
> Steps to reproduce:  
> - Create a new Thread which contains the word 'Hölle'  
> - Create a new Thread which contains the word 'Holle'  
> - go to the search  
> - search for 'Hölle'  
> - search for 'Holle'
> 
> Expected:  
> - Search#1:   
> -- the search result contains Thread#1  
> -- the search result doesn't contain Thread#2  
> - Search#2  
> -- the search result doesn't contain Thread#1  
> -- the search result contains Thread#2
> 
> Actual:  
> - Search#1:   
> -- the search result contains Thread#1  
> -- the search result contains Thread#2  
> - Search#2  
> -- the search result contains Thread#1  
> -- the search result contains Thread#2
> 
> Additional Infos:  
> I was able to reproduce this not only on my forum but also on various other forums including the official german mybb board (mybboard.de) so I don't think that this is an issue with my settings.

Original report: http://dev.mybb.com/issues/1962
Reporter: Berni B.
Status: Confirmed

**Comment by JN-Jones** [comment]
Yeah, seems to be a mysql issue/behavior. Probably something for the docs, but nothing we can do about it. The only "solution" I've found is telling mysql to use a specific collation for that query but that will likely cause other issues. Marking as won't fix.
