### ISSUE TITLE
send_pm() and signatures

### ISSUE THREAD

**Issue by labrocca** [mybb/mybb#3014]
Please remove the default signature = 0 for the send_pm() function.

It is a great function but by disallowing signatures here you can't have a useful signature for staff or site bots when providing warnings or other automated pms.

**Comment by euantorano** [comment]
For reference the line is here: https://github.com/mybb/mybb/blob/f7b8a16d6774a98c16f5c21acfd23fe52270c525/inc/functions.php#L8586

**Comment by Eldenroot** [comment]
I agree. So only remove this line of code, or do you wanna adjust even something more?

**Comment by labrocca** [comment]
I think just removing it should be fine.  Plugins can still use $pm options to set signature to 0. And doesn't the datahandler set signature to a default if it's not set?  My issue was this being hard coded in.
