### ISSUE TITLE
Performance Optimization for the function replace_query 

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#302]
> replace_query() does a loop which is not necessary...
> 
> here is an optimized version of db_pgsql.php:
> 
>  @@ -1223,15 +1230,12 @@ } else { - $query = $this->write_query("SELECT {$main_field} FROM {$this->table_prefix}{$table}"); - - while($column = $this->fetch_array($query)) + $search_bit = "{$main_field} = '".$replacements[$main_field]."'"; + $query = $this->write_query("SELECT COUNT(".$main_field.") as count FROM {$this->table_prefix}{$table} WHERE {$search_bit} LIMIT 1"); + + if($this->fetch_field($query, "count") >= 1) { - if($column[$main_field] == $replacements[$main_field]) - { - $update = true; - break; - } + $update = true; } }

Original report: http://dev.mybb.com/issues/2174
Reporter: Can Özdemir
Status: New

**Comment by JN-Jones** [comment]
Code from above a bit more readable:
```php
} else {
- $query = $this->write_query("SELECT {$main_field} FROM {$this->table_prefix}{$table}");
 -
 - while($column = $this->fetch_array($query))
 + $search_bit = "{$main_field} = '".$replacements[$main_field]."'";
 + $query = $this->write_query("SELECT COUNT(".$main_field.") as count FROM {$this->table_prefix}{$table} WHERE {$search_bit} LIMIT 1");
 +
 + if($this->fetch_field($query, "count") >= 1) {
 - if($column[$main_field] == $replacements[$main_field])
 - {
 - $update = true;
 - break;
 - }
 + $update = true; }
 }
```

The current code really looks quite ugly. Especially since we handle array fields with one query but if we have a single field we use a loop which doesn't make much sense to me. I'm also not sure whether we need to replace the loop with the code above as it doubles the code we use for array without the foreach there. From a quick look the following function does the same and is a lot easier to follow:
```php
	function replace_query($table, $replacements=array(), $default_field="", $insert_id=true)
	{
		global $mybb;
		if($default_field == "")
		{
			$query = $this->write_query("SELECT column_name FROM information_schema.constraint_column_usage WHERE table_name = '{$this->table_prefix}{$table}' and constraint_name = '{$this->table_prefix}{$table}_pkey' LIMIT 1");
			$main_field = $this->fetch_field($query, 'column_name');
		}
		else
		{
			$main_field = $default_field;
		}
		$update = false;
		$search_bit = array();

		if(!is_array($main_field))
		{
			$main_field = array($main_field);
		}

		foreach($main_field as $field)
		{
			if(isset($mybb->binary_fields[$table][$field]) && $mybb->binary_fields[$table][$field])
			{
				$search_bit[] = "{$field} = ".$replacements[$field];
			}
			else
			{
				$search_bit[] = "{$field} = ".$this->quote_val($replacements[$field]);
			}
		}
		$search_bit = implode(" AND ", $search_bit);
		$query = $this->write_query("SELECT COUNT(".$main_field[0].") as count FROM {$this->table_prefix}{$table} WHERE {$search_bit} LIMIT 1");
		if($this->fetch_field($query, "count") == 1)
		{
			$update = true;
		}

		if($update === true)
		{
			return $this->update_query($table, $replacements, "{$main_field}=".$this->quote_val($replacements[$main_field]));
		}
		else
		{
			return $this->insert_query($table, $replacements, $insert_id);
		}
	}
```

@mybb/developers @mybb/sqa Anything I'm missing? Or maybe there's another even better solution? Otherwise I'll create a PR with that replacement
