### ISSUE TITLE
editpost.php - Delete post checkbox and settings.

### ISSUE THREAD

**Issue by xerotic** [mybb/mybb#3020]
EDIT: Read my replies to this before commenting as I changed the code I used and I don't want to edit out my earlier work.
-
MyBB has two settings when editing group permissions:
1.) Can delete own posts?
2.) Can delete own threads?

If _Can delete own posts?_ is checked (and _Can delete own threads?_ is NOT) then the top delete box will appear even though it will give error_no_permission if you attempt to delete a thread OP.

This is an issue with editpost.php. When displaying the page it should be checked if the post in question is the first post in a thread before displaying the deletebox.

Current code:
```
$deletebox = '';
// Can we delete posts?
if($post['visible'] != -1 && (is_moderator($fid, "candeleteposts") || $forumpermissions['candeleteposts'] == 1 && $mybb->user['uid'] == $post['uid']))
{
    eval("\$deletebox = \"".$templates->get("editpost_delete")."\";");
}
```

Fix code:
```
$query = $db->simple_select("posts", "pid", "tid='{$tid}'", array("limit" => 1, "order_by" => "dateline", "order_dir" => "asc"));
$firstcheck = $db->fetch_array($query);
if($firstcheck['pid'] == $pid)
{
    $firstpost = 1;
}
else
{
    $firstpost = 0;
}
	
$deletebox = '';

if($firstpost) {
	if($post['visible'] != -1 && (is_moderator($fid, "candeletethreads") || $forumpermissions['candeletethreads'] == 1 && $mybb->user['uid'] == $post['uid']))
	{
		eval("\$deletebox = \"".$templates->get("editpost_delete")."\";");
	}
} else {
	// Can we delete posts?
	if($post['visible'] != -1 && (is_moderator($fid, "candeleteposts") || $forumpermissions['candeleteposts'] == 1 && $mybb->user['uid'] == $post['uid']))
	{
		eval("\$deletebox = \"".$templates->get("editpost_delete")."\";");
	}
}
```

The method used is what editpost.php uses elsewhere when actually submitting a delete post (or thread) request.

Thanks.

**Comment by xerotic** [comment]
Better yet to save the query, use this instead:
```
if($thread['firstpost'] == $pid) {
	if($post['visible'] != -1 && (is_moderator($fid, "candeletethreads") || $forumpermissions['candeletethreads'] == 1 && $mybb->user['uid'] == $post['uid']))
	{
		eval("\$deletebox = \"".$templates->get("editpost_delete")."\";");
	}
} else {
	// Can we delete posts?
	if($post['visible'] != -1 && (is_moderator($fid, "candeleteposts") || $forumpermissions['candeleteposts'] == 1 && $mybb->user['uid'] == $post['uid']))
	{
		eval("\$deletebox = \"".$templates->get("editpost_delete")."\";");
	}
}
```

Much better.

**Comment by xerotic** [comment]
Looking through it now... should MyBB ever use this query?
```
$query = $db->simple_select("posts", "pid", "tid='{$tid}'", array("limit" => 1, "order_by" => "dateline", "order_dir" => "asc"));
$firstcheck = $db->fetch_array($query);
if($firstcheck['pid'] == $pid)
{
	$firstpost = 1;
}
else
{
	$firstpost = 0;
}
```

Why not just use:
```
if($thread['firstpost'] == $pid)
```

Check Lines 258-271 and Lines 385-399.
Can't the query be taken out for the simplified if statement?

**Comment by labrocca** [comment]
Agreed there are wasted queries for firstpost when $thread already has the data from the top of the editpost.php file.  

And I prefer the usage like this:

$firstpost = ($thread['firstpost'] == $pid) ? 1 : 0;

**Comment by euantorano** [comment]
Confirmed, we’ll look at this for 1.8.16.

**Comment by Eldenroot** [comment]
@labrocca - can you create a PR? Thank you!

**Comment by effone** [comment]
First of all, if it is about displaying the delete checkbox at the first place then is it helpful try fixing the editpost.php? the checkbox display depends on showthread.php, isn't it?

Secondly, $firstpost can not be assigned at line no, 40 as @labrocca said, as $thead is getting assigned at line 59. It should be somewhere near line 66, after the invalid check.

Third, the whole system malfunctioned for me. No matter whatever permission I assign to whatever group. It always ignored the settings. Even with or without the provided fix for deletebox. What the big part I am missing?

**Comment by Ben-MyBB** [comment]
@xerotic
