### ISSUE TITLE
Suggestion to add the limit for thread views.

### ISSUE THREAD

**Issue by RikoDEV** [mybb/mybb#3025]
Currently, topic views are increasing each time the page is reloaded. I suggests adding a limit so one user can increase the number of topic views only once.

**Comment by Azareal** [comment]
The problem with this is that you would need a views table which holds the userID (or IP) of the viewer and the topic which was viewed. This is a lot more expensive than just a simple increment.

Most likely the IP, as the vast majority of topic views would be from guests rather than members.

**Comment by labrocca** [comment]
This should be closed as it's not feasible.

**Comment by euantorano** [comment]
Agreed, closed.
