### ISSUE TITLE
Code Parser

### ISSUE THREAD

**Issue by kawaii** [mybb/mybb#3027]
Code:[code]This is bad parser.[/code]

Above is example of a bug.  Posting it here so you can see it in action. Staff can edit my post to view the mycode used.

btw, this wasn't a bug in 1.6x.

Original thread: [Code Parser](https://community.mybb.com/thread-215901.html)

**Comment by JordanMussi** [comment]
For reference

**Raw MyCode**
```
[code][code]This is bad parser.[/code][/code]
```

**Parsed by MyBB parser**
![image](https://user-images.githubusercontent.com/2552068/36208989-6b1045b6-1192-11e8-837b-5c3738fa5236.png)


**Parsed by SCEditor**
![image](https://user-images.githubusercontent.com/2552068/36208935-4760a4f8-1192-11e8-87ed-fd3565040889.png)
