### ISSUE TITLE
Function insert_id() not working in db_pgsql.php

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#303]
> The function insert_id() is completely dysfunctional.
> 
> Here is a working implementation:
> 
>  /** * Return the last id number of inserted data. * * @return int The id number. */ function insert_id() { $query = $this->query("SELECT lastval() as mylastval"); $field = $this->fetch_field($query, 'mylastval'); return $field; }

Original report: http://dev.mybb.com/issues/2171
Reporter: Can Özdemir
Status: New

**Comment by JN-Jones** [comment]
That function has been modified since this issue was first submitted - from a quick look the modified one seems good, can someone confirm?

**Comment by willhartman** [comment]
Looks and works fine for me, my limited product knowledge aside.

Perhaps a better approach would be to use a RETURNING statement to set a property for the insert_id() method to return?

**Comment by Destroy666x** [comment]
I can confirm that this commit fixed it: https://github.com/mybb/mybb/commit/b568b844cf5d94e95d9e3b379fd37e8fae89cf16
