### ISSUE TITLE
Usercp2.php removal

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3034]
In 1.9 we should remove the usercp2.php and look to merge this into one since the file doesn't do a huge amount and tidy things up a little bit.

**Comment by effone** [comment]
Well, here is the PR.
Tested so far working fine ...
Unfortunately messed and mixed up with my other PR and reverted commit. Is it okay or I have to create fresh?
Also suggest required changes.

**Comment by euantorano** [comment]
I’m not sure what the best option for hooks is. I’d say we should keep the names the same, and add a comment explaining why they’re called that.

**Comment by effone** [comment]
@euantorano  Alright I will do the necessary reverts.

Just another point, if we keep the old hooks there is an open hook in usercp2.php
`$plugins->run_hooks("usercp2_start");` which I have ommitted as `$plugins->run_hooks("usercp_start");` is already in place. But there is no `$plugins->run_hooks("usercp2_end");`
This start hook of usercp2 is pointless and can be omitted. But if I omit that the issue remains same as any plugin using the hook `$plugins->run_hooks("usercp2_start");` will break.

Decision?

**Comment by euantorano** [comment]
I doubt any plugins use usercp2_start (I could be wrong though). We might be able to get away with not including it.

**Comment by PaulBender** [comment]
If we're keeping this issue for 1.9, then the hooks should be renamed.

**Comment by effone** [comment]
Commit: [Hook names retained](https://github.com/mybb/mybb/pull/3093/commits/cb8ba63dc406add625759f50271e608b202a1271)

If we are going to rename hooks at all; its not a big job, but a matter to decide. Let me know and I will revert my last commit, if required.

**Comment by effone** [comment]
Are we gonna merge this or waiting for 1.9?
I have a messed up fork of MyBB (no idea how some commit happened directly to feature while I was playing with VSCode) and this is preventing me to make a freah fork as well as making new PR. So I need to delete and refork.
Still not much familiar with GitHub, I guess ...

**Comment by euantorano** [comment]
A change like this would be best for 1.9 in my opinion.

**Comment by effone** [comment]
@euantorano with due honor to your view this is not gonna impact much in extend as you can see only 6 links to be fixed in theme.xml removing '2' and thats all. Even if people not comfortable or not ready to modify links we can suggest them with 2 lines of htaccess code and that will handle all routing from usercp2 to usercp. The frontend impact is neglegable wrt the ongoing / upcoming changes.

**Comment by effone** [comment]
Another solution is to keep a dummy usercp2 with a code like following:
```
$redirecturl = str_replace('usercp2', 'usercp', $_SERVER[REQUEST_URI]");
redirect($redirecturl);
```

**Comment by euantorano** [comment]
Yes, that would work. And yes, we're keeping the old hooks as of now.
