### ISSUE TITLE
Online Today Pagination

### ISSUE THREAD

**Issue by labrocca** [mybb/mybb#3040]
If you have more than 1000 users online today the function my_number_format() in online.php changes the $todaycount with a comma. Then it gets passed to the multipage function and that breaks it.  

I suggest you fix this by ensuring any multipage variables have $mybb->settings['thousandssep'] and $mybb->settings['decpoint'] removed but short term fix is to correct the online.php code.  I just added a $todaycounted variable that is now passed to multipage without the comma.

This is of course a Big Board only problem as you would need 1000+ members to have been online that day.

**Comment by labrocca** [comment]
An easier short-term fix.

Move the multipage to the line before the my_number_format.

	$multipage = multipage($todaycount, $perpage, $page, "online.php?action=today");

	$todaycount = my_number_format($todaycount);
	$invis_count = my_number_format($invis_count);

Works perfect that way too and much easier fix.

**Comment by euantorano** [comment]
Good catch, thanks for reporting. I've added the necessary labels to this issue and hopefully we'll get it patched soon.
