### ISSUE TITLE
Empty Post Error Bug

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3044]
Thanks to one of my members who finally tracked down an occasional bug.  

To replicate:
https://community.mybb.com/newreply.php?...rocessed=1

As you can see the error says "Can not upload file - Too large for php post_max_size directive. Please press the back button."

When in fact it's that the &#36;post var is empty.

From newreply.php, editpost.php, and newthread.php

Code:if((empty(&#36;_POST) &amp;&amp; empty(&#36;_FILES)) &amp;&amp; &#36;mybb-&gt;get_input('processed', MyBB::INPUT_INT) == 1)
{
&nbsp;&nbsp;&nbsp;&nbsp;error(&#36;lang-&gt;error_cannot_upload_php_post);
}
So the error says it's too large but actually it's just empty. This confuses members.  

This appears to happen when you refresh the page btw.  So the &#36;post data might empty out and reload the page with that error.

The error should be corrected so it's not confusing people.

I recommend something slightly more generic like:

"There has been an error due to your post data being empty. Possibly cause is a browser page refresh or direct access to this page. We recommend you press your browser back button and begin again."

In any case the existing error is wrong and confuses people into thinking your site is the problem with some pseudo php error that didn't happen.

Honestly, got reports of this for years. :)

Original thread: [Empty Post Error Bug](https://community.mybb.com/thread-216073.html)

**Comment by Eldenroot** [comment]
OK, so just change the lang string?!

**Comment by labrocca** [comment]
Yes, 

$lang->error_cannot_upload_php_post

Should technically be something like:

$lang->error_empty_post_input

Saying:  "There has been an error due to your post data being empty. Possibly cause is a browser page refresh or direct access to this page. We recommend you press the browser back button and begin again."

**Comment by Eldenroot** [comment]
@labrocca - PR sent, if anything let me know :)
