### ISSUE TITLE
File Verification can wrongly parse mybb.com responses

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#3058]
The ACP's _File Verification_ currently loads expected file checksums by [splitting data with newline character](https://github.com/mybb/mybb/blob/mybb_1815/admin/modules/tools/file_verification.php#L39), which can result in incorrect interpretation, e.g. when the response contains an error page's HTML instead.

**Comment by effone** [comment]
This is not because of splitting data with newline character. The problem is usage of `fetch_remote_file()` which gathers garbage error page code if the remote file is missing resulting never triggering the condition `empty($file[0])`.
