### ISSUE TITLE
Embedded videos no longer play after upgrading to 1.8.15

### ISSUE THREAD

**Issue by Shade-** [mybb/mybb#3066]
After upgrading our forum software from MyBB 1.8.14 to 1.8.15, a couple of members noticed that embedded YouTube videos were no longer playable, and displayed an error message when the play arrow was clicked.
 
Digging around a bit, I was able to resolve this problem by moving lines 500 to 509 of inc/class_parser.php to just prior to the call to &#36;this-&gt;mycode_auto_url on line 453 of the same file. I am not very familiar with the MyBB code, so this may have unintended consequences, but so far everything seems to be OK. Have tested on a vanilla install and confirmed the same problem with same solution.

Emphasising my lack of familiarity with the code, here's (kind of roughly/vaguely and potentially imprecisely) why I think this solution works: the code to convert the video BBCode into an embedded video - the moved lines - expects a bare URL, whereas the code to auto-generate a link out of a bare URL - &#36;this-&gt;mycode_auto_url - converts bare URLs to links. Shifting the former code so that it occurs prior to the latter code makes sure a bare URL is passed as expected.

Original thread: [Embedded videos no longer play after upgrading to 1.8.15](https://community.mybb.com/thread-216380.html)

**Comment by SimurgTR** [comment]
thanks for solving this problem.

**Comment by euantorano** [comment]
This is the same issue we had with images being broken just before release. IMO the auto link should be ran after everything else.
