### ISSUE TITLE
Default Thread subscription mode in admin CP

### ISSUE THREAD

**Issue by WallBB** [mybb/mybb#3071]
Hi MyBB Team, I found an issue in 1.8.15 version of MyBB.

I will try to explain the issue, suppose a user selected default thread subscription mode to "Instant PM Subscription Mode" via usercp. But if you go to Admin Panel and see user settings, it shows Do Not Subscribe. Also the "Instant PM Subscription Mode" is not shown there in Admin CP > Users and Groups > Edit User > Account Settings.

Regards
WallBB

![subscription](https://user-images.githubusercontent.com/18086627/37562730-5828bb2e-2a95-11e8-9af0-3f03f4d9a637.png)

**Comment by PaulBender** [comment]
Can confirm
