### ISSUE TITLE
html not being stripped in admin cp

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#3073]
there's a few spots in the admin cp that are not stripping html.  the 2 posted below are in the mail settings, there may be more that I haven't seen yet..

![screenshot 2018-03-18 15 24 48](https://user-images.githubusercontent.com/2748980/37570461-84c292d2-2ac6-11e8-929e-a60a0152242c.jpg)
![screenshot 2018-03-18 15 25 05](https://user-images.githubusercontent.com/2748980/37570462-84ee4058-2ac6-11e8-8c39-3cd5c7e98139.jpg)

**Comment by JordanMussi** [comment]
This is caused by `htmlspecialchars_uni` added here https://github.com/mybb/mybb/commit/a607821ffb46e1d3c1accfa5f415f78bafef038c#diff-d8ba16aa014c15e1fde4896a00d88005R1520

**Comment by euantorano** [comment]
Indeed @JordanMussi. We should revert that patch.

**Comment by JordanMussi** [comment]
I'm not sure about reverting it - perhaps using `nl2br` and allowing some basic MyCode (url, b, u, i) would be better? I can't think of any other HTML markup that would be strictly needed in a setting description...

**Comment by casimirodocelta** [comment]
the option of massive emails does not work well, it does not send to all the registered ones of the forum only to the half. It also does not work when you want to send users with 0 messages or topics sent to users with messages. summarizing the mass email option does not work

**Comment by Sama34** [comment]
We should leave it for title and revert it for descriptions imo.
