### ISSUE TITLE
missing LICENSE file in 1815

### ISSUE THREAD

**Issue by joneum** [mybb/mybb#3077]
Hey all,
i missing the LICENSE File in 1815.

mybb-mybb_1815 # ls
admin                   forumdisplay.php        misc.php                ratethread.php          syndication.php
announcements.php       global.php              modcp.php               readme.md               task.php
archive                 images                  moderation.php          report.php              uploads
attachment.php          inc                     newreply.php            reputation.php          usercp.php
cache                   index.php               newthread.php           rss.php                 usercp2.php
calendar.php            install                 online.php              search.php              warnings.php
captcha.php             jscripts                polls.php               sendthread.php          xmlhttp.php
contact.php             managegroup.php         portal.php              showteam.php
css.php                 member.php              printthread.php         showthread.php
editpost.php            memberlist.php          private.php             stats.php

**Comment by effone** [comment]
Whats this issue? I can't get it ...

**Comment by Shade-** [comment]
Hi, the LICENSE file is present at the time of writing.
