### ISSUE TITLE
Incorrectly santizes (youtube) video urls.

### ISSUE THREAD

**Issue by Kasi-R** [mybb/mybb#3085]
BBCode in post-bits gets incorrectly translated (tested with YouTube), Example:
`[video=youtube]https://www.youtube.com/watch?v=dX3k_QDnzHE[/video]`

gets translated to (notice the `"&quot; target"` appended to the end of the url):
`<iframe width="560" height="315" src="//www.youtube.com/embed/dX3k_QDnzHE&quot; target" frameborder="0" allowfullscreen=""></iframe>`

I managed to get a temp fix this by removing santization through commenting out the following line.
https://github.com/mybb/mybb/blob/0ff8ffd56923c7524b8c0d0b5618247db557008c/inc/class_parser.php#L1459

**Comment by Shade-** [comment]
Hi, this has been already reported and fixed: #3066.
