### ISSUE TITLE
Memberlist searching case sensitive with PostrgreSQL

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#309]
> In PostgreSQL the LIKE keyword is case sensitive. Because of this the letters or search function becomes case sensitive. As far as I know the only way to fix this is to wrap both sides of the WHERE/LIKE clause with upper/lower.
> 
> On a side note a category for starting with a symbol might be handy.

Original report: http://dev.mybb.com/issues/2104
Reporter: Braden Obrzut
Status: New

**Comment by JN-Jones** [comment]
There also seems to be a possibilty using the collation: http://stackoverflow.com/questions/2876789/how-can-i-search-case-insensitive-in-a-column-using-like-wildcard

I don't have my PgSQL board available atm so can't test it but if that's a possibility I'd prefer using that over lowercasing every single like query in PgSQL. @mybb/developers
