### ISSUE TITLE
inside of post, not showing color but show[color= rgba(0, 0, 0, 0.87)]

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3090]
[color=rgba(0, 0, 0, 0.87)]QB HOUSE TOKYO Midtown East

[color=rgba(0, 0, 0, 0.87)]So good!!!!!![/color][/color]

[color=rgba(0, 0, 0, 0.87)](but showed here! ! [/color]
[color=rgba(0, 0, 0, 0.87)]Look at my screenshot. )[/color]

Original thread: [inside of post, not showing color but show[color= rgba(0, 0, 0, 0.87)]](https://community.mybb.com/thread-216612.html)

**Comment by effone** [comment]
@euantorano as you have asked in the main thread, no, our parser only handles text and 3 or 6 digit hex codes as of now. 

While trying to extend the options in the regex I have noticed that the parser is picking the variables from the code in a different way. Probably it targets the pattern and picks (.....) [text in first brackets] and hence I can't use first bracket inside the logic. For example if I use `(rgb|hsl)a?` inside pattern to catch rgb(a) or hsl(a) values it comes out something as:
`<span style="color: rgba(0, 0, 0, 0.87);" class="mycode_color">rgb</span>`
notice it replaced the text which is to be colored and picked up the value after `(` as second parameter ($2).

**Comment by martec** [comment]
https://github.com/mybb/mybb/issues/4231 related?

**Comment by euantorano** [comment]
@martec yes. I’ll close this issue.
