### ISSUE TITLE
PM Search & Hard Limit

### ISSUE THREAD

**Issue by labrocca** [mybb/mybb#3097]
Please add the search hard limit to PM searches.  Need I say more?

**Comment by Shade-** [comment]
Sorry for the late reply, what is your suggestion exactly? Sorry for my ignorance.

**Comment by labrocca** [comment]
search.php respects a hardlimit setting to limit queries.  Example is on my site I have it to 500 results.  On my forum some members can have 20,000 PMs and many do.  A PM search with 12,000 results errors on the site because it doesn't have any limits set.

Setting is searchhardlimit. 

"Hard Limit for Maximum Search Results
Enter the maximum amount of results to be processed. Set to 0 to disable. On larger boards (more than 1 million posts) this should be set to No more than 1000."

So if adjustments can be made so that the query in private.php used the setting that would be great.
