### ISSUE TITLE
Total Posts count incorrect

### ISSUE THREAD

**Issue by WallBB** [mybb/mybb#3098]
Hi MyBB Team, I found an issue related to total posts count in 1.8.15 version of MyBB.

I will try to explain the issue in member profile page of MyBB, suppose before creating users statistics are below -
Total Posts - 2 and Total Threads - 1
Now suppose a user is creating a new thread in any forum. After creating thread, 
Total Posts - 3 and Total Threads - 2

This is incorrect and Total Thread Count should not be added in Total Post count. 

Regards
WallBB

**Comment by kawaii** [comment]
I believe that this is intentional and that a thread also counts as a post (because, technically, it is a post).

@euantorano do you have any input on this?

**Comment by WallBB** [comment]
@kawaii I agree that thread name is actually first post but then it doesn't make sense if we are showing same number in Total posts and Total Threads. Threads should actually be renamed to Total Start Post or Total First Post in that case.

**Comment by effone** [comment]
Nevermind but as @kawaii said first post in a thread is a post itself. In my opinion the statistics are correct.
Thread is nothing but a container of several posts.
Just imagine the scenario considering threads as directories and posts are files within it. You will get a clear picture that how the stats are correct.

**Comment by euantorano** [comment]
I’d also say this is intended behaviour. The first post in a thread is still a post.

**Comment by WallBB** [comment]
I would again like to post my answer 
"I agree that thread name is actually first post but then it doesn't make sense if we are showing same number in Total posts and Total Threads. Threads should actually be renamed to Total Start Post or Total First Post in that case."

Anyways this issue can be Ignored/closed/rejected if more people don't agree with this :)

**Comment by effone** [comment]
@WallBB Thread name is not actually first post. Thread is a container that holds first post and its subsequent related reply posts. Thread is not a post, thread is a space to hold the post. When we name a thread the first post just inherits the same name - thats the point from where this confusion arrived.

**Comment by WallBB** [comment]
Hey @effone , 
I understand this but I should have written this more clearly :)
To understand what I have said, think in this way -
There is a new forum with 0 content i.e. in user profile we will see 0 threads and 0 posts, also in forum stats you will see 0 threads and 0 posts. Now we know thread is nothing but just first post but this is not known to a third party or an entity outside MyBB. Now I will give an example that will explain where this will go wrong.
Suppose an advertiser visits new forum and sees 1 Thread and 1 Post (which gives an impression of total content as 2) but in reality that is only 1 Post and thread is just a data structure that holds all posts or container as you said. This will make advertiser feel that the forum owner is duping advertisers by showing incorrect stats and it will be difficult to tell advertiser in technical terms and they might not understand.

I hope I was able to explain what is the reason behind creating the issue. 

Regards
Peter

**Comment by effone** [comment]
> Now we know thread is nothing but just first post
This is wrong statement. Thread can't be empty. So, when we create a thread we actually make a post and the post takes place inside a thread. The thread and the first post shares the **same name**. Having same name doesn't make them same. Thread is a container, post is a content.

**Comment by WallBB** [comment]
@effone, please read my previous post and pardon me for the comment that I posted in response to kawai

> I agree that thread d is actually first post 
This is wrong but read the above post I posted in response to you.

**Comment by effone** [comment]
Look at the following image and count:
![Thread and Post](https://image.ibb.co/diLgMc/Untitled_1.png)

When you create a thread you actually create 2 things: a thread and a post in it with same name. A blank thread doesn't exist.

**Comment by WallBB** [comment]
I will close this, no need for me to argue :)
