### ISSUE TITLE
Awayreason and MySQL errors

### ISSUE THREAD

**Issue by labrocca** [mybb/mybb#3112]
MyBB doesn't check that awayreason isn't more than the 200 character limit as the column in users table is varchar(200). This creates an error.log entry for that query and displays it on the site if error reporting is on.

I was able to replicate at MyBB.com as well.  

"1406 - Data too long for column 'awayreason' at row 1"

Should be an easy fix in the datahandlers/user.php where it's cut-off with my_substr() at 200 characters.

**Comment by effone** [comment]
Do you think its a good idea to silently slice the trail of user input away?
Or I should try placing a validation and force user to restrict input within 200 chars?

**Comment by euantorano** [comment]
I would cut the length and add a warning on the page. Can’t you also set a max length on the input field HTML?

**Comment by labrocca** [comment]
Same exact issue with the template usercp_usergroups_joingroup and the "reason".  Suggest adding a maxlength of 250 to the template.
