### ISSUE TITLE
Default Language conflitc with Group Join Request

### ISSUE THREAD

**Issue by Walter-Correa** [mybb/mybb#3113]
I found the following problem:
My Default board language is Portuguese - Brazil, but if a user is using the Default language in your User CP and he is the leader of a group, when I send a join request he receives the email in the English language. It only resolves when the user directly selects Portuguese - Brazil as their language.

Note: With the other emails working normally, this problem only happens when it is a Join Request.

**Comment by Walter-Correa** [comment]
Maybe the problem is at usercp.php: $lang->set_language($leader['language']), when it detects the language of the leader before sending the email with the request to join the group.

**Comment by Walter-Correa** [comment]
I found the reason: 
usercp.php

When the language is configured again:
Line 3190: `$lang->set_language($mybb->$leader['language']);
$lang->load("messages"); `

Line 3200: `$lang->set_language($mybb->user['language']);
$lang->load("messages");`


Maybe because the language is already set at the beginning of the file.

**Comment by effone** [comment]
@Walter-Correa Feel free to open a PR

**Comment by Shade-** [comment]
Removing these pieces of code might solve the issue in your particular case, but turns messages sent to all leaders into the board's default language. A real solution would be adapting `set_language()` to use the board's default language instead of "english" as it does at the moment.

**Comment by Walter-Correa** [comment]
Thank you @Shade- for the Pull Request!
Your changes have resolved the problem, because when a user configures their language to Default, in the database, the "language" field is blank (null).
The only problem that is happening now is the moment of the confirmation of sending the request to join the group:
The message box that says the message was sent correctly, below appears: "Click here if you do not want to wait any longer.". If the leader language is the same as mine, the phrase: "Click here if you do not want to wait any longer." appears in the correct language, but if the language of the leader is English and my Portuguese, the phrase appears in English.

**Comment by Shade-** [comment]
Quite odd. [This line](https://github.com/mybb/mybb/blob/2e6c0eb4a10ed6fd3fa2ee4ebbbe11c972e341c8/usercp.php#L3201) should reset the language back to your preferred one.

**Comment by Walter-Correa** [comment]
For the confirmation message in the box this line work, but for the phrase("Click here if you do not want to wait any longer.") not:

Maybe [this line](https://github.com/mybb/mybb/blob/2e6c0eb4a10ed6fd3fa2ee4ebbbe11c972e341c8/usercp.php#L3205) is the problem.

**Comment by Shade-** [comment]
Nope, because the line I posted above resets the language for everything that's loaded afterwards. Are you sure your language pack includes the "Click here if you do not want to wait any longer" string? It's codename is `click_no_wait`.

**Comment by Walter-Correa** [comment]
Yes, because when the group leader have the same language(português) the "Click here if you do not want to wait any longer" appears translated: http://prntscr.com/j59dqt

...but if the language of the leader is English and my Portuguese, the phrase appears in English.
