### ISSUE TITLE
XSS and $mybb->input in Templates

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3124]
I'd like to point out that MyBB templates should never use &#36;mybb-&gt;input directly in the templates. This creates a situation where the data is not sanitized on the page.  This opens up XSS where links to the page could insert malicious code including javascript to execute on the site including things like login popups which may mimic site login popup and then steal the credentials.

XSS is low-risk but still a risk and it's not the best practice to use unsanitized user input anywhere.  But MyBB does this in a number of the default/master templates.  

Most of the time the &#36;mybb-&gt;input is used in case there is an error in form submission and the data remains in the form.  That's convenient for the member but it's a risk as well.  I suggest that MyBB does a template search and see which templates do this in order to decide if they want to sanitize the input or just remove the convenience.  

Please review asap.

Original thread: [XSS and $mybb->input in Templates](https://community.mybb.com/thread-216966.html)

**Comment by effone** [comment]
Line numbers of mybb_theme.xml where occurrences found:
5282, 6861, 6868, 6912, 6918, 6924, 6930, 6936, 6953, 6969, 7150, 7201, 7905, 7909, 7913, 8159, 8161, 8167, 8179, 8639, 10292, 10916, 10921 (2), 10925, 10948, 14075, 14079, 14083

**Comment by euantorano** [comment]
I think it might be better for clarity to stop using $mybb->input in templates entirely. Introducing variables for each one makes it easier to determine that things are cleaned properly.
