### ISSUE TITLE
Custom MyCode broke after upgrading to 1.8.15

### ISSUE THREAD

**Issue by soliddanii** [mybb/mybb#3129]
As you know video and image parsing broke. I copied the latest inc/class_parser.php and that fixed that issue, but my custom mycode (that is a modifyed img mycode) is still broken. It works if  I test it in the ACP but doesn't work on the post display.

MyCode Regular Expresion: 
`\[img( width=[0-9]*)?( height=[0-9]*)?( alt=["'][^\[\]"']+["'])?\]([^\[\]]+)\[\/img\]`

MyCode Replacement: 
`<img src="$4"$1$2$3></img>`

Test: 
`[img alt='Megumin']https://images4.alphacoders.com/721/thumb-1920-721593.png[/img]`

Result: 
`﻿<img src="https://images4.alphacoders.com/721/thumb-1920-721593.png" alt='Megumin'></img>`

Working as intended.
What is shown in the actual post: 
![Image](https://i.imgur.com/4dn1JnA.png)

As I said, it worked in 1.8.14 (and im using the latest class_parser.php, the one that fixed the videos)

Thank you.

**Comment by euantorano** [comment]
We're aware of some issues with the parser and we have a few open issues/PRs relating to them. They should be patched in 1.8.16 which we hope to release pretty soon.

- https://github.com/mybb/mybb/issues/3103
- https://github.com/mybb/mybb/pull/3127
- https://github.com/mybb/mybb/pull/3106

**Comment by labrocca** [comment]
#3127 should fix the custom mycode problem for OP.
