### ISSUE TITLE
Nested links still possible for multiline [url] tags

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3150]
The merged PR #3127 attempted amongst other things to eliminate the possibility of the parser outputting nested links. Unfortunately, it seems to have missed one case: certain "url" tags that span multiple lines.

For example, this two-line "url" tag:

Code:[url=http://example1.com]http://example2.com
[/url]
currently results in nested links (a link to example2 being nested in a link to example1).

It looks to me that the fix is simply to add to the regexes in mycode_auto_url() an "s" modifier on top of the existing "i" and "u" modifiers (so that the initial part of the regexes matching HTML links detects HTML links that run over multiple lines).

Original thread: [Nested links still possible for multiline [url] tags](https://community.mybb.com/thread-217156.html)

**Comment by lairdshaw** [comment]
Argh, sorry for the commit on two branches - I'm still learning the git(hub) system and making my fair share of mistakes.
