### ISSUE TITLE
Thread's prefix doesn't exist on index page in lastpost

### ISSUE THREAD

**Issue by Poftorek** [mybb/mybb#3152]
Hi

Please add the possibility that we can see **prefix on index page** with lastpost thread name, i know that plugin exists https://community.mybb.com/mods.php?action=view&pid=749 but in the next version it would be fine to add this

**Comment by effone** [comment]
Please post your suggestions at community forums for opinions before pushing it to Github.
https://community.mybb.com/forum-158.html
