### ISSUE TITLE
Closed vs. Locked

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3164]
Not a big issue, just something odd came to notice.
Some places it is "Closed Thread" some places it is "Locked Thread".
We should choose either of two and stick with it. Isn't it?

Note: Majority is with implementing "**Closed Thread**" everywhere.
[Original Thread](https://community.mybb.com/thread-216704.html)

**Comment by Suraf** [comment]
Consistency is the key to success. At least from a website I visited, but IMO, "**Closed Thread**" is what I'd go for.

**Comment by Ben-MyBB** [comment]
I'd also agree with Closed Thread.
