### ISSUE TITLE
memberlist_search doesn't check for referral option disabled or enabled

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3176]
In my forum referral system is deactivated, but still in memberlist.php it's possible to search users by "number of referrals"

Original thread: [memberlist_search doesn't check for referral option disabled or enabled](https://community.mybb.com/thread-214046.html)

**Comment by Ben-MyBB** [comment]
This should be a relatively easy fix I think.

**Comment by effone** [comment]
Are we talking about "Sort by: members referred" ?

**Comment by Eldenroot** [comment]
Yes, in memberlist when you wanna search there is an option which doesnt follow your setting for referral system
