### ISSUE TITLE
Moving to mybb2

### ISSUE THREAD

**Issue by essteffan** [mybb/mybb#3183]
Hi Guys.

I so that there is a mybb2 which is based on Laravel (which btw i love it) and i was wonder what is the plan for that? when should it be stable or moving to?

Best regards

**Comment by kawaii** [comment]
MyBB 2.0 has been formally placed 'on hold' whist we refocus our efforts on developing and releasing MyBB 1.9 and 1.10. You can find more information detailed in the threads I've linked below:

https://community.mybb.com/thread-215212.html
https://community.mybb.com/thread-215211.html

**Comment by Eldenroot** [comment]
Next time use MyBB community board for these type of questions... please close this.
