### ISSUE TITLE
Avatar dimension separator consistency

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3192]
hi
Loading avatar gives error on 2 pages(admin panel and user panel.)

I upload .jpg image upload not error.

png image upload error :(

please help me

screen shoot
http://i.hizliresim.com/X9BqXo.png

Ups helpp

Fixed
source : 

Original thread: [png image avatar upload error](https://community.mybb.com/thread-206235.html)

**Comment by effone** [comment]
We should use one format and stick to that. Alternately we can think of accepting both the formats (| and x) for every case. Just check the existence of separator and split accordingly.
Also we need to explore the possibility to validate the input while updating settings from ACP.
And we can extend this to consider default is a valid setting format not found.

**Comment by Suraf** [comment]
Using both would be fine, shouldn't be no problem identifying either one. Although to think of it, the x format seems to be more used (globally or not just to MyBB).

**Comment by Sama34** [comment]
I will add two input elements instead of one, one for width and the second for height, and add the necessary code for plugin developers to make use of it. I will probably use the `|` (pipe) as the separator and update current settings during the upgrade.

**Comment by Eldenroot** [comment]
@Sama34 - yes "pipe" character would be the best

**Comment by effone** [comment]
There are only 4 settings to handle:
Maximum Avatar Dimensions in Posts : `postmaxavatarsize`
Default Avatar Dimensions : `useravatardims`
Maximum Avatar Dimensions : `maxavatardims`
Maximum Display Avatar Dimensions : `memberlistmaxavatarsize`

However I can see neutralization attempt already in place to accept both formats:
`$avatardimensions = str_replace('x', '|', my_strtolower($mybb->settings['postmaxavatarsize']));`

**Comment by Eldenroot** [comment]
@effone - great, I agree!
