### ISSUE TITLE
Move Contact fields to Custom Profile Fields

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#3203]
https://community.mybb.com/thread-214204.html

Move the contact fields from their current hardcoded database fields to Custom Profile Fields that Admins can Add/Edit/Delete with ease.

**Comment by justinsoltesz** [comment]
Columns for fid4, fid5, and fid6 need to be added to `mybb_userfields` on install (in `install/resources/mybb_db_tables.php`) to account for the default contact fields. There's currently an error when new users register or are created:

![screenshot_from_2018-08-06_23-55-54](https://user-images.githubusercontent.com/544942/43790311-3af794f6-9a40-11e8-96cb-505bf9e5d180.png)

**Comment by Shade-** [comment]
I guess this can be closed now?
