### ISSUE TITLE
Arithmetic with strings can cause PHP Warning in polls.php on PHP >= 7.1

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3228]
I wanted to update a poll but I got the following error:

Quote:Warning [2] A non-numeric value encountered - Line: 694 - File: polls.php PHP 7.1.17 (Linux)

File: Function/polls.php
Line: 694
errorHandler-&gt;error

This is on line 694 of polls.php:

PHP Code:&#36;numvotes&nbsp;=&nbsp;&#36;numvotes&nbsp;+&nbsp;&#36;votes[&#36;i];&nbsp;
Thanks in advance!

Original thread: [Poll](https://community.mybb.com/thread-217800.html)

**Comment by Eldenroot** [comment]
Would be nice to fix this for MyBB v 1.8.16 to make MyBB fully compatible with php 7.1/2

**Comment by AndreRl** [comment]
As it seems to be counting votes wouldn't using the following tag suffice:

`(int)`

for both $numvotes & $votes? I've managed to fix this locally by doing so with no further issues.

**Comment by Eldenroot** [comment]
PR would be welcomed :)

**Comment by euantorano** [comment]
Yeah, I think that will be fine @AndreRl but I haven't had time to test locally.

**Comment by effone** [comment]
https://github.com/mybb/mybb/pull/3231
