### ISSUE TITLE
PHP 7.2 error.

### ISSUE THREAD

**Issue by 0xC1A551C** [mybb/mybb#3230]
Why does mybb recommend php5.5 still when it is outdated by years now? I am running php 7.2 & have received these errors.

![image](https://user-images.githubusercontent.com/36227001/40821561-7d7d6b1a-651c-11e8-8517-797cdc23f97a.png)

**Comment by euantorano** [comment]
We still recommend PHP 5 due to there still being small bugs such as this one with PHP 7. Once we know these kinds of issues are ironed out, PHP 7 will be the recommended version.

**Comment by euantorano** [comment]
Also, this issue is in the staff page plugin you’re using, though I believe we’ve merged another patch already to move where THIS_SCRIPT is defined.
