### ISSUE TITLE
SQL Error when opening the moderator panel

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3232]
The error below occurs when a moderator (primary group moderator) want to open the moderator-panel.
MyBB Version: 1.8.6
PHP Version: 5.5.9-1ubuntu4.14
SQL Engine: PostgreSQL 9.3.10
active plugins: Email Admin-Created User (1.0) Favicon (1.6.1) MyCode: [spoiler] (1.2)
inactive plugins: First Post Only (1.2)

MyBB SQL Error

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
    0 - ERROR: operator does not exist: ! smallint LINE 7: WHERE (t.fid &lt;&gt; 0 AND t.fid IN (0,'3')) OR (!l.fid) ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. 
Query:
    SELECT l.*, u.username, u.usergroup, u.displaygroup, t.subject AS tsubject, f.name AS fname, p.subject AS psubject FROM mybb_moderatorlog l LEFT JOIN mybb_users u ON (u.uid=l.uid) LEFT JOIN mybb_threads t ON (t.tid=l.tid) LEFT JOIN mybb_forums f ON (f.fid=l.fid) LEFT JOIN mybb_posts p ON (p.pid=l.pid) WHERE (t.fid &lt;&gt; 0 AND t.fid IN (0,'3')) OR (!l.fid) ORDER BY l.dateline DESC LIMIT 5

Original thread: [SQL Error when opening the moderator panel](https://community.mybb.com/thread-187731.html)

**Comment by euantorano** [comment]
Was fixed here: https://github.com/mybb/mybb/pull/2965
