### ISSUE TITLE
.prop('checked') doesn't trigger change events

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#3241]
Checking a checkbox with `.prop('checked')` doesn't trigger the `change` event, making it difficult to detect state changes when features like "select all" are used.

Example: https://github.com/mybb/mybb/blob/mybb_1815/jscripts/inline_moderation.js#L240

This can be fixed by triggering the event manually with `.change()`.

**Comment by effone** [comment]
`prop()` is not meant to trigger change event. It is basically to get or set the state. The line you are pointing at is exactly doing that, its not a trigger.

Any issue if you can describe with reproduction steps will be appreciated.

**Comment by WildcardSearch** [comment]
Just chain `.change()` onto the `prop()` call. Or maybe that is what you meant all the time...

**Comment by dvz** [comment]
Yes, evoking `.change()` on top of these calls would allow custom JS to perform actions when rows are selected by MyBB functions (currently necessary for overriding checkbox styling).

**Comment by WildcardSearch** [comment]
Agreed. I can see where that would be helpful.

**Comment by dvz** [comment]
The non-moderator functionality also needs to be changed: https://github.com/mybb/mybb/blob/mybb_1817/jscripts/general.js#L21-L31
