### ISSUE TITLE
Autofill Disable in Installer

### ISSUE THREAD

**Issue by Azareal** [mybb/mybb#3246]
There's a little problem in the installer, or at the very least, in my case with it on `localhost`.
Basically, the browser will attempt to autofill the Admin PIN, database fields, etc. with my password for localhost.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password#Allowing_autocomplete
You might want to disable auto-complete for these fields.

**Comment by AndreRl** [comment]
Next time please suggest it on the forum and wait for it to be pushed to GitHub, if necessary :). Although I'm unsure if I agree with this. It doesn't exactly cause a problem.

**Comment by WildcardSearch** [comment]
Having those fields autofill is extremely useful when setting up multiple installations for testing purposes. I feel that this is a non-issue.

**Comment by Eldenroot** [comment]
I dont think that this is a bug, you can configure your web browser to not remember "fields" and do not use "autofill" on specified urls.

**Comment by WildcardSearch** [comment]
This is expected behavior. If any @mybb/designers or @mybb/developers wish to reopen this issue, they may.

I'm going to close it for now.
