### ISSUE TITLE
Bad word filter

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3262]
Hello,
Simple problem, perhaps somebody can help me?

I have a word that I want to be censored on my forum. So I add the word in admin CP -&gt; configurations -&gt; Word Filters.

I add a word "whatever123" and it exchange into "space". So when somebody writes it it will change into an empty space.

So, when somebody types a message
"
Hi everybody,
My name is whatever123
I am a guy
Bye
"

It will be visible as:

"
Hi everybody,
My name is  
I am a guy
Bye
"

BUT!
When somebody types a message:
My name iswhatever123
OR
My name is whatever123I
OR
My name is whatever123Iam

The word "whatever123" will stay there. How can I get rid off it when its surrounded by other letters/words?
I thought I could add it to filter in the following way "#whatever123" or "%whatever123", but it doesnt work.

Any advice would be highly appreciated!
King regards!

Original thread: [Bad word filter](https://community.mybb.com/thread-218066.html)

**Comment by effone** [comment]
Note:

1. If you try to filter `stone` with `metal` it works fine (spaces surrounded).
2. If you try to filter `stone*` with `metal` the word 'stone' will not be replaced until a character other than space is appended. For example 'stoner' will be replaced perfectly. The behavior should not be like that. The filter should occur with or without character appended.
3. Currently it is considering '*' as a single character. So to filter out 'stoneman' or 'stoneboy' you need to place the target word as 'stone***'. which is again wrong. Single character should be represented by '?' and '*' should be representing 0 or more characters.

**Comment by WildcardSearch** [comment]
>  Single character should be represented by ? and * should be representing 0 or more characters.

Totally agree. That is the accepted usage in all other cases that I'm aware of.

**Comment by euantorano** [comment]
Yep, agreed @WildcardSearch  and @effone - that would make the most sense to me for definite.

**Comment by Azareal** [comment]
It all seems a little complex, I don't know if you do it already (my memory is a little blurry on this feature), but maybe a checkbox in the UI for the thing for running it as a regex and just doing a simple sub-string replace or something?

**Comment by Sick1G** [comment]
I want to include one more thing, people tend to abuse character filter via link format. for example:

www.badworld.com 
http/s://badworld.com 

so they can do the following to mess with the filters:
[url=badword.com]badword[/url]

Word filter is not parsing links, unfortunately.
