### ISSUE TITLE
using github is indirectly supporting fascism

### ISSUE THREAD

**Issue by milkpepsi** [mybb/mybb#3269]
As many of you propably know, github got bought by microsoft.
Yet there is many to say about microsoft, but I believe it's important to have current events in mind, and how the struggle for free software can be linked with those of others.

That's how resisting becomes more powerfull, when the opressed give visability to each others struggle and take action of solidary.

Microsoft is currently supporting ICE.
Take on that matter also a look at this:
https://boingboing.net/2018/06/20/godwins-law-suspended.html
(myself haven't really made any research on that sybject)

This is a call for directAction in solidarity with anyone being effected by the fascist activities conducted by the US agency ICE.

Since being here on github, we can start to use this proprietary plattform instead of sharing code, colaborating on code and being constructive about coding to use it to exclusivly share informations about microsoft supporting fascism, what it has to do with ones own use of this plattform and deconstructing fascist ideology.

Also start writing issues about this into any other software projects you empathise with
and encourage people to do the same.

Thought their is potential of making a trend out of this, that could damage the trademark github and microsoft and raises more awareness about ICE within the coder scene.

Maybe someone could come up with a much better writing then this one, incl. some more research and possibilities that can be taken to resist ICE in specific or racism in general.

Please STOP using Github, we should not promote the use of it by honest software developers and should switch to free and ethical alternatives such as gitlab and friends

thank you!

**Comment by Eldenroot** [comment]
Please report this spammer to GitHub, hilarious...

**Comment by euantorano** [comment]
Microsoft haven't yet actually purchased GitHub, the sale is dependant upon regulators. The people currently controlling GitHub are the same people who controlled GitHub before.

In addition, Microsoft's [original blog post about working with ICE](https://blogs.msdn.microsoft.com/azuregov/2018/01/24/federal-agencies-continue-to-advance-capabilities-with-azure-government/) was recently updated:

> In response to questions we want to be clear: Microsoft is not working with U.S. Immigration and Customs Enforcement or U.S. Customs and Border Protection on any projects related to separating children from their families at the border, and contrary to some speculation, we are not aware of Azure or Azure services being used for this purpose. As a company, Microsoft is dismayed by the forcible separation of children from their families at the border. Family unification has been a fundamental tenet of American policy and law since the end of World War II. As a company Microsoft has worked for over 20 years to combine technology with the rule of law to ensure that children who are refugees and immigrants can remain with their parents. We need to continue to build on this noble tradition rather than change course now. We urge the administration to change its policy and Congress to pass legislation ensuring children are no longer separated from their families. 

We have investigated mirroring the MyBB repository to GitLab, but the "MyBB" username is currently in use on GitLab.com by an inactive user account and we can't get hold of it until the user has been inactive for another couple of months.
