### ISSUE TITLE
PHP 7 multipage issue

### ISSUE THREAD

**Issue by chack1172** [mybb/mybb#3276]
Today I was debugging stuff on my forum and I found an issue with multipage. The issue happens in some pages that uses multipage. The issue happens if you specify a big number for page because in many pages there aren't conditions that check if specified page is greater then max page.
This is an example:
https://community.mybb.com/memberlist.php?page=999999999999999999
Many admin pages and some forum page are affected by this. It is a low bug but it should be fixed.

**Comment by SvePu** [comment]
#3277 Fixes #3276 -PHP 7 multipage issue

**Comment by Azareal** [comment]
I vaguely recall this being a problem many years ago before PHP7, but I can't put my finger on it, might be older than you think.

**Comment by Azareal** [comment]
Also, this issue exposes a bigger issue. MyBB shouldn't be exposing the queries that it's running like that.

**Comment by euantorano** [comment]
Please see this existing issue: https://github.com/mybb/mybb/issues/2888

Rewriting every single query in the core is a monumental task, though it is one we plan to take eventually with 1.10 or another future feature release. 

For now it may be best to change the default setting to not show SQL queries in error messages.

**Comment by chack1172** [comment]
So we shouldn't fix it for now? I was just working on it.

**Comment by euantorano** [comment]
I’m not opposed to fixing it for now, but the 1.8.16 merge window is closed, so this will have to wait until 1.8.17.

I also think we should change the error pages to only show SQL errors to super administrators.

**Comment by chack1172** [comment]
As I said, I was already fixing it before opening the issue. I'm going to create a new pull request because I finished it. You can merge it in next versions if you want.

**Comment by WildcardSearch** [comment]
I agree with @euantorano that we should only show **the query** for SQL errors to admins. No issue telling the user that there has been an SQL error, though.
