### ISSUE TITLE
PHP 7.1+ Debug

### ISSUE THREAD

**Issue by phaze1G** [mybb/mybb#3280]
This happens to everyone who uses Lock plugin for newspoints with PHP above 5.6
Error code

https://i.imgur.com/9pnp5Wf.png
https://i.imgur.com/ID04K8G.png

The code:

https://pastebin.com/kxcnGdB2

**Comment by effone** [comment]
This is incompatibility in the code of a plugin and not in MyBB core files.
Suggest you to contact plugin author or seek help in your already created support thread.
https://community.mybb.com/thread-218254.html

This is closed.
