### ISSUE TITLE
Unable to view or add attachments if new post was saved as draft before posting

### ISSUE THREAD

**Issue by uzbugg** [mybb/mybb#3287]
Hello,

this seems like a weird attachment issue in the latest mybb version, probably something related to user permissions. 

- Mybb version: 1.8.15 
- PHP version: 5.6.30
- SQL engine: MySQLi 10.1.21
- Browser: firefox (62.0b2)  & chrome (unknown version)

**What is actually happening:**
This bug occurs when a standard user is creating a post with attachments (images, files) and decides to save it as a draft. Later when he wants to finish up the post, all goes fine but it's not possible to view the attachments in post preview, when new attachments is added, it's not visible in the preview as well. Also when attachments are clicked, the following error message is returned: "The specified attachment does not exist."

Administrators or moderators are able to view the already uploaded attachment so it does exists.

**How to reproduce:**

(do not do the steps bellow as admin or mod, use a standard registered user)

1. create a new thread
2. insert some text
3. upload and insert some attachment(s)  (preview the post so that you see they are there)
4. save as draft
5. open draft
6. preview post (attachments are missing)
   - user can't view attachments
   - administrators can view attachments
   - not possible to add new attachments to the post (won't show up in the preview)

After the post has been made, attachments are shown in the thread. It's just a little bit annoying for users because they can not be sure that their attachments are there or not.  

-- uzbugg

**Comment by effone** [comment]
I can confirm this issue.

However request you to please post issues in Community Forums first from next time. We track the issues from there and push only legitimate ones.
