### ISSUE TITLE
Slack and IFTTT both believe the RSS/Atom feed URLs are invalid

### ISSUE THREAD

**Issue by megashub** [mybb/mybb#3288]
Slack and IFTTT both believe the RSS/Atom feed URLs are invalid

Examples:
![image](https://user-images.githubusercontent.com/2977043/41994845-a0211f20-7a04-11e8-8451-dd84480392a0.png)
![image](https://user-images.githubusercontent.com/2977043/41994867-b56f3268-7a04-11e8-9d04-d76e01b81b8b.png)

**Comment by euantorano** [comment]
Have you tried clicking the `visit the help page` link in the first image? I guess they require the URL to have an extension like `.xml` which is a shoddy way to validate a feed... You could solve that with a rewrite rule in your web server though.

**Comment by megashub** [comment]
Hmmm... like this, you mean?

![image](https://user-images.githubusercontent.com/2977043/41995860-f68e8200-7a07-11e8-875e-89d6cca7fd6e.png)

**Comment by megashub** [comment]
the help page linkes to a W3C validation tool. This is the result:

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fthefoundationcollective.ihostfull.com%2Fforum%2Fsyndication.php%3Ffid%3D3%26limit%3D15

**Comment by euantorano** [comment]
I was meaning the one in the screenshot with the green background - at the bottom there is a link that says `for feed URL requirements, visit the help page` - where does that link go?

**Comment by euantorano** [comment]
I was meaning the one in the screenshot with the green background - at the bottom there is a link that says `for feed URL requirements, visit the help page` - where does that link go?

**Comment by megashub** [comment]
https://help.ifttt.com/hc/en-us/articles/115010396768-My-RSS-feed-is-not-working-correctly

**Comment by euantorano** [comment]
Ah,

It looks like your site is responding with a page that isn’t valid and that requires JS to work. Do you use anything like CloudFlare in front of your site?

**Comment by megashub** [comment]
Not my site. I'm just a user of it. When you browse to the URL, it presents the feed just fine. It's when something that doesn't use a web browser hits it, that it can't negotiate the javascript.

**Comment by megashub** [comment]
Here's the URL, in case you'd like to play with it directly: 

http://thefoundationcollective.ihostfull.com/forum/misc.php?action=syndication

**Comment by yuliu** [comment]
MyBB's https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fcommunity.mybb.com%2Fsyndication.php%3Flimit%3D15+

OP's https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fthefoundationcollective.ihostfull.com%2Fforum%2Fsyndication.php%3Flimit%3D15


```
>curl http://thefoundationcollective.ihostfull.com/forum/syndication.php?limit=15
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

It seems that the server that the forum is served http://thefoundationcollective.ihostfull.com/forum/ forbids some accesses. That means it doesn't a MyBB issue actually. OP may look into HTTP server's configuration to loosen some checks or whitelist relevant sites/services. @megashub
