### ISSUE TITLE
Issue with Thread Prefix 

### ISSUE THREAD

**Issue by WallBB** [mybb/mybb#3289]
Hi Team,
I see an issue in MyBB 1.8.15 series related to Thread Prefix.

Description
Basically when I set a display style to thread prefix, on showthread page the thread title shows the "Prefix" and it doesn't show the display style.

I can see the "Display Style" field on forumdisplay pages and nav(on showthread) as well.

Regards
WallBB

**Comment by effone** [comment]
Create a thread in Community Forums. NEVER make direct issues here.
