### ISSUE TITLE
Issue with Thread Prefix

### ISSUE THREAD

**Issue by AndreRl** [mybb/mybb#3291]
Hi Team,
I see an issue in MyBB 1.8.15 series related to Thread Prefix.

Description

Basically when I set a display style to thread prefix, on showthread page the thread title shows the "Prefix" and it doesn't show the display style.

I can see the "Display Style" field on forumdisplay pages and nav(on showthread) as well.

Regards
WallBB

Original thread: [Issue with Thread Prefix](https://community.mybb.com/thread-218356.html)

**Comment by effone** [comment]
>but that essentially renders the the Prefix setting useless in ACP
Which setting?

The first suggestion is much acceptable IMO.

**Comment by AndreRl** [comment]
There would be no use for "Prefix" setting in ACP if we depend on `{$thread['displayprefix']}` (uses "Display Style setting in ACP) instead of `{$thread['threadprefix']}`.  The only thing `{$thread['threadprefix']}` would be used for is the New Thread Prefix drop-down menu I believe. @effone

**Comment by effone** [comment]
Agreed with you @AndreRl 
This appears to be intended behavior. Those who want the output that way as the issue indicates they can just modify the templates as per you suggested in your post. There is nothing to do in our part.

Opinions? @mybb/developers

**Comment by Eldenroot** [comment]
I agree guys, this should be changed. The thread prefix should be displayed everywhere in the same way if we use CSS style for that, not only for some places...

**Comment by euantorano** [comment]
The configured style should be used everywhere, apart from pages like archive mode or the print thread mode.

**Comment by Eldenroot** [comment]
I am thinking about this one - what about to display thread prefixes in ACP as they look like in frontend (apply set CSS) Something like in usergroups ACP setting page where it is displayed.

![image](https://user-images.githubusercontent.com/778890/49165589-d5294980-f331-11e8-811f-fe6520eb0536.png)

**Comment by euantorano** [comment]
Yes, the style should be used in the ACP too ideally.
