### ISSUE TITLE
Strange comma after upgrade and usergroup title not showing

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3309]
Hello!

After upgrading to the latest MyBB version , i' having some small issues that i would like to make you present.

On who's online,there is a comma :

[attachment=40541]

And i can't see the user tiltes under their usernames,the titles are active in ACP:

[attachment=40542]

If i find more issues,i will report.

Thanks for the update.

Original thread: [Strange comma after upgrade and usergroup title not showing](https://community.mybb.com/thread-218429.html)

**Comment by effone** [comment]
Fixed by this PR:
https://github.com/mybb/mybb/pull/3300

**Comment by ErikThiart** [comment]
What is the fix, I cannot find it.

**Comment by effone** [comment]
> What is the fix, I cannot find it.

https://github.com/mybb/mybb/pull/3300/files

**Comment by ErikThiart** [comment]
Sweet, thank you!
