### ISSUE TITLE
Usergroup permission for being invisible

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3327]
Usergroup settings to implement for allowing users to set themselves as invisible.

Original thread:
https://community.mybb.com/thread-217188.html

**Comment by dvz** [comment]
I'd put it into the same bag as private message preview in ACP (regardless of whether they're going to be called _private_) - MyBB shouldn't encourage curtailing privacy.

**Comment by effone** [comment]
Agree with you @dvz but it seems users want it, hence it is here.
We can anytime reject it for good reason. Specially after GDPR

**Comment by linguisten** [comment]
Is GDPR compliance or privacy of people using mybb your problem? That's the admins' responsibility. Let those who install and run the thing decide whether they use the setting or not.

**Comment by effone** [comment]
Provision for the same is my problem. There should not be any option in core to impact on user privacy.

**Comment by effone** [comment]
So, are we doing this? @mybb/developers

**Comment by Azareal** [comment]
Well, everyone has their pet feature, I'm just wondering whether it really provides much value, if every possible permission was added, you'd end up with vB3 where who's online has like five permissions. Depends on whether you think it's actually valuable.

**Comment by Eldenroot** [comment]
I like it, I use task for make all users visible, so it could be really useful. Small but useful feature

**Comment by AndreRl** [comment]
Reading the comments above I'm split on this. It is a useful feature to have but why would this be implemented and not a preview message permission (assuming this has been suggested as dvz mentioned it)? Forums are meant from engagement, so on that basis both of them should be denied and kept out of the core.

**Comment by Sama34** [comment]
Please do not ignore that regardless of globalization the MyBB product is aimed to a more extended marked that just the EU.

We can't just force specific user's status display behaviors , we can, however, add a setting.

Even if this permission setting is added or not I agree a global switch for this feature is the least.

> why would this be implemented and not a preview message permission

Regarding private messages the problem is the title itself, as "private" should remain, well, private.

**Comment by Ben-MyBB** [comment]
I'm working on this and should have a PR incoming in a few days.
