### ISSUE TITLE
Video MyCode Bug

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3344]
Today Continue testing the Pre-Relase 1.8.17 

Video Test:

Video Erros in MyBB Presales 1.8.17

Liveleak
Display the URL but not the video
[Video: https://www.liveleak.com/view?t=xv9I_1531462966]

Metacafe Video
Not Display video

Veoh Video, 
Note: Flash Player Must be Installed

With Fash Player installed not display video

1. Test OnLine
2. Test on Community

Original thread: [Video Bug Pre-Release 1.8.17](https://community.mybb.com/thread-218685.html)

**Comment by Diego-Pino** [comment]
Hi Euan T, Thanks for the support.
Please consider removing the Veoh Video, because  Flash Player Must be Installed. 
is just a suggestion!
