### ISSUE TITLE
Short array syntax in showteam.php causes Parse error on PHP < 5.4

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#3347]
https://github.com/mybb/mybb/blob/mybb_1817/showteam.php#L282

introduced in https://github.com/mybb/mybb/pull/3217/files#diff-344951ef7d00619345342e5b65ec37e5R282

**Comment by effone** [comment]
Less than 5.4? Ok.
That was my PR and I still don't get the issue...

**Comment by euantorano** [comment]
We have to still support PHP 5.2 with MyBB 1.8 unfortunately, so we can’t use the new syntax.

**Comment by euantorano** [comment]
Yes, we have to define arrays using `array()` instead of `[]`.

**Comment by Eldenroot** [comment]
We need MyBB v1.9.0 soon, because maintaining support for php <7.0 is a pure evil. 😈

**Comment by dvz** [comment]
>Maybe MyBB 1.9.0 should require minimum php 7.1 (or even better 7.2)

discussion continued at https://community.mybb.com/thread-195675-post-1309612.html#pid1309612
