### ISSUE TITLE
I have problem in mybb 1.8.15 in video player

### ISSUE THREAD

**Issue by earab** [mybb/mybb#3362]
I have problem in mybb 1.8.15 in video player

Example :

[http://www.info3rb.com/showthread.php?tid=323](url)

video youtube

**Comment by effone** [comment]
Issue not defined in details or no reproduction steps provided.
Linked page is RTL and doesn't have embedded video.

Suggest you to upgrade to latest MyBB version and check if your unknown problem gets fixed.
This is closed.
