### ISSUE TITLE
web updater

### ISSUE THREAD

**Issue by terrar** [mybb/mybb#3377]
Is mybb planning a webupdater in the foreseeable future?
Great would of course be a function with the plugins previously tested for suitability.
That works pretty well on Nextcloud.

**Comment by effone** [comment]
Feature requests should come through [Development Forums](https://community.mybb.com/forum-161.html).

**Comment by dvz** [comment]
Possibly _foreseeable_, but not necessarily _near_ future; there are many things we'll need to improve in the codebase and organization to be able to run it safely and securely (we might get into these details in a Blog post soon).
