### ISSUE TITLE
unable to add images to register questions

### ISSUE THREAD

**Issue by aasjpvm** [mybb/mybb#3383]
After mybb 1815 release, the security questions enable to add html, I use it to add images in the questions, if it was by security reasons, will be a good feature to add bbcode support instead of html, to support the image questions:

Before 1815:
![screenshot_10](https://user-images.githubusercontent.com/13684669/43850170-d0c47eb0-9afc-11e8-862a-c5df437a70b6.png)

After 1815:
![screenshot_8](https://user-images.githubusercontent.com/13684669/43850088-a3ae3db2-9afc-11e8-9f5c-e3ffc31ce470.png)

The code added was:
![screenshot_11](https://user-images.githubusercontent.com/13684669/43850272-1c1d5d0a-9afd-11e8-9de4-2051b8ef9ffb.png)

**Comment by Eldenroot** [comment]
It is not a regression at all... it is safer right now after this change... anyway I see your point, maybe we can find another way.

**Comment by aasjpvm** [comment]
The easiest way that I see is to add a parser to render bbcode like with the normal post, it permit more dynamic in this option, like add images, different font type/size/position/weight. 
I can collaborate making that change and posting here if you want, it add the same properties that I need without resting the security that was added with the version change mentioned.

**Comment by Eldenroot** [comment]
Feel free to open a pull request

**Comment by euantorano** [comment]
Using the parser would probably be the best option, the other option would be [`my_strip_tags`](https://github.com/mybb/mybb/blob/acde34debf3a5a9cc97a4a8f69fc5a6c91534a7d/inc/functions.php).

**Comment by Eldenroot** [comment]
@aasjpvm - will you open a PR with fix?

**Comment by Eldenroot** [comment]
We can use this regular expression:
`(?i)<(?!img|/img).*?>`

to replace all html and keep img tag
`html.replaceAll('(?i)<(?!img|/img).*?>', '');`

**Comment by MinusPL** [comment]
https://i.imgur.com/bQyvFcW.png
Seems to be working with parser. Most likely it would be nice to add few settings to ACP to let people choose what kind of parsing in questions should be possible tough, @euantorano what do you think? Add few settings for parser in registration form or just make this options constant and don't let people change them?

**Comment by euantorano** [comment]
I'd probably just hard code it. We don't need to support every option:

- No support for `/me` (obviously)
- No support for HTML
- No highlight
- Probably no bad word filtering since only admins can use it?

**Comment by MinusPL** [comment]
Yeah, I actually allowed all mycodes and img ones, still considering is video code is actually needed but most likely not. But for people when it is merged it would be nice to say exactly what they can use and what not in questions. For now I'll update my code with things I actually did and maybe soon create pull request.

**Comment by laietechie** [comment]
As previously mentioned, only admins can write security questions, why do we need to forbid html? If going with BB Code, why do we need to limit any tags at all?

**Comment by MinusPL** [comment]
Consider iframe as security problem. If you add source from unknow place and it uses something weird, then you also have this on your registration form. But that's my point of view, and that's why I actually tried attaching here parser.

**Comment by euantorano** [comment]
The reason for limiting the ones I listed are:

- `/me`: No user logged in on register (obviously), so the code can't be used
- HTML: We blocked HTML which caused this issue in the first place
- Highlight: Only used for search results
- Bad word filtering: Only admins can manage security questions. If they wish to cuss/swear, then they probably don't have a beadwork filter in place for it

@MinusPL video code probably isn't needed, but there might be somebody out there with a question like `Name the character at 1:32 in the below video` or something I guess...

**Comment by MinusPL** [comment]
Then I'll enable it, but looking how it would be parsed, It could completely destroy any spacing in register form, but I'll test it ;)

I'll also allow smilies, when we are giving people a way to actually customize more questions then smilies are needed :D

**Comment by dvz** [comment]
> As previously mentioned, only admins can write security questions, why do we need to forbid html? If going with BB Code, why do we need to limit any tags at all?

see https://community.mybb.com/thread-219334-post-1312214.html#pid1312214; I'd consider HTML parsing for security questions controversial too as some might interpret that simply as a feature. Adding elements like `<iframe>`s might make sense in some cases as well.

IMO MyCode as a replacement sounds good.

**Comment by MinusPL** [comment]
Also I ran to another issue - simply security questions might require more space in database now - considering that with MyCodes they could become pretty "big" in terms of text data I ran twice to an error saying that my question is too big.
