### ISSUE TITLE
grammar issue in upgrade script

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#3393]
the word 'in' needs to be added here:

Welcome to the installation wizard for MyBB 1.8.18. MyBB has detected it is already configured this directory.

so it reads like so:

Welcome to the installation wizard for MyBB 1.8.18. MyBB has detected it is already configured in this directory.

**Comment by Eldenroot** [comment]
I think there is no need to open a new PR, can be fixed in one commit together with 1.8.18 release. What do you think?
