### ISSUE TITLE
New plugin hook in User CP

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3403]
Hi everyone!

I have been creating some new theme for my forum. I have some issues with all "Threads" related things in account summary in UCP.

I wanted to add some new features to threadlist like I have in forumdisplay and that's the moment I realized that in UCP there are no threads hooks.

Nothing at all. You can use usercp_start or usercp_end, but it isn't going to do well with changing or adding anything in threadlist because of how it is all created. Original MyBB script recreates $threadcache and that makes it impossible to change anything. Also I cheked forumdisplay to see if it's the same in here, but there hooks for changing individual threads is present.

Maybe it would be a good idea to add these hooks to UCP too?
There are displayed threadlists too, and some people might want to use plugins to make them look the same as in forumdisplay.

For now I can do overcomplicated things to do the same thing, but adding threads hooks to UCP would make it much easier and faster to work.

Original thread: https://community.mybb.com/thread-219282.html

**Comment by Eldenroot** [comment]
What will be the best place to add this hook?

**Comment by MinusPL** [comment]
There are few places - Thread subscriptions and Latest threads in UCP. Exactly I think it should be similar to how it is placed in forumdisplay.php right below foreach loop for $subscriptions and $threadcache maybe?
That way it would allow modifying each thread like in thread lists in forumdisplay.

**Comment by Eldenroot** [comment]
@minuspl will you push a PR with fix? If not let me know via MyBB community board - PM
