### ISSUE TITLE
/install/resources/settings.xml file in the update package and install package unfortunately does not automatically translate (1.8.18)

### ISSUE THREAD

**Issue by SimurgTR** [mybb/mybb#3411]
Hello, the /install/resources/settings.xml file in the update package and install package unfortunately does not automatically translate the language.I had to manually translate this file later, how to fix it that problem?

**Comment by SimurgTR** [comment]
Hi,

I found a solution for myself.  inc/languages/english (- turkish or another language)/admin/config_settings.lang.php
I added the missing language lines in the file, and made the translation. I solved the problem this way.`
[config_settings.lang.zip](https://github.com/mybb/mybb/files/2315563/config_settings.lang.zip)

`

**Comment by MinusPL** [comment]
I think this can be closed - it's not a bug, but a way that MyBB works. If you want to have your own language updated you need to get updated language pack from authors of translation.
As far as I know MyBB does not provide any other language than english by itself.

**Comment by SimurgTR** [comment]
Hi @MinusPL ,

This issue did not have any previous version updates. The forum language was automatically changing according to what was select.

**Comment by MinusPL** [comment]
Hmm it didn't update english files too?

**Comment by SimurgTR** [comment]
@MinusPL 
I Briefly summarize this problem, 

**Old Version:** After upgrading from MyBB 1.8.16 too MyBB 1.8.17, the general forum settings for the forum are in Turkish or another language.

**New Versiyon:** After upgrading from MyBB 1.8.17 too MyBB 1.8.18 the general forum settings for the forum are in English

Admin CP language Turkish or another language, Board Language Turkish or another language and General Forum Settings page is English

**Comment by MinusPL** [comment]
Maybe some lines changed their names or something, that's the only thing I can think of right now. Because for me it looks like change in language files that your turkish ones did not have at the moment.

**Comment by Eldenroot** [comment]
You have to modify your language files according to the latest changes in the English one
