### ISSUE TITLE
Last Active shown for hidden users

### ISSUE THREAD

**Issue by AndreRl** [mybb/mybb#3417]
Users who have set "Hide me from the Who's Online list" to "Yes" will have their Last Visit information set to "(Hidden)". This is the correct behaviour. The same behaviour is no longer displayed when that said user is on someone's buddy list - their Last Visit information will be displayed.

**Comment by Eldenroot** [comment]
I think it is expected behaviour. Friends will see your status, thats why you have them in a friendlist, or not?

**Comment by Eldenroot** [comment]
It is same as for enable/disable PMs. It doesnt apply to friends

**Comment by Azareal** [comment]
Expected or unexpected, I don't think it's particularly clear to users what the buddylist really even means and what it does.

**Comment by Eldenroot** [comment]
We can adjust the lang file, same as we did for PMs

**Comment by euantorano** [comment]
Or maybe we could extend the setting to have 3 options:

- Don't show as offline
- Show as offline to everyone except buddies
- Show as offline to everyone

**Comment by Azareal** [comment]
Something to probably keep in mind is that in IMs being invisible means to be invisible to everyone including friends, users may come in with the same expectations they get from those.

**Comment by chack1172** [comment]
I agree with @euantorano we should add an option to allow friends to see their status.
