### ISSUE TITLE
Thread and posts should not be hidden from the OP when approval is required!

### ISSUE THREAD

**Issue by bravepuzzle** [mybb/mybb#3419]
When creating a new thread or post that is not approved, no one but mods/admins can view it.

That is wrong and not intuitive at all. It should allow for the person who created that post / thread to also view it. It just doesn't make any sense, why does it have to be hidden for even the person who made it.

That causes the person who created the thread to:

1. Think it was not created/published thus trying to post it multiple times
2. There is a yellow warning while writing the thread and another after submitting it which apparently no one reads. The warnings are fine in my opinion but they do not help with the fact the post is not displayed.
3. And last but not least after its posted there is no trace of it, see GIF at the bottom.

The proper behavior should be to still allow the creator of the post / thread be taken back to it once posted, just like a regular post and allow the creator of it, to still view/read it, with a message at the footer of the post saying the message is still waiting for approval and won't be viewed by other users until then.

![example](https://i.imgur.com/aOSRo4X.gif)

Thanks for the amazing forum!

**Comment by euantorano** [comment]
I agree the current approach doesn't make much sense and is a bad user experience. We should probably fix it, but not sure if that will be something we should aim at 1.8 or 1.9. Thoughts @mybb/developers?

**Comment by chack1172** [comment]
Yeah it should be fixed but I think it's better to fix it in 1.9

**Comment by effone** [comment]
I also agree with the raised point. Currently if a thread goes under approval OP has no clue about what just happened and why it is posted and vanished instantly.
I have even noticed cases several times that confused OP recreated the same thread over and over.
Proposed behavior makes much sense.

**Comment by PaulBender** [comment]
Yes, it should be fixed.

**Comment by bravepuzzle** [comment]
I will agree with @effone on that. And glad it wasn't just me feeling this was so off.

**Comment by Admixing** [comment]
I'm backing this 100%, a notice at the top would be ideal so that if something changes the user can still edit prior to being approved. I've had this issue on the MyBB forums when posting as thread for an Extend item, I make changes and want to update it but need to wait till it's been approved.

**Comment by Eldenroot** [comment]
Yes, super annoying. We can change it for 1.8, because many forum use this feature and this could be a small but really useful addition :)

**Comment by WildcardSearch** [comment]
Totally agree with @bravepuzzle and @effone here. This should be changed.

**Comment by Ben-MyBB** [comment]
Definitely should be changed in 1.9 I say.

**Comment by avril-gh** [comment]
agree, but why not in 1.8.19 ?

**Comment by euantorano** [comment]
The only reason I wondered whether to target 1.9 is that I wish to keep new templates or template edits to a minimum in 1.8. It would be nice to get into 1.8 if possible, it should be simple - we just have to make sure the new template(s) get ported to 1.9 too.

**Comment by dvz** [comment]
> I wish to keep new templates or template edits to a minimum in 1.8

Would it actually require significant template edits?
There can be many queries to modify, but making it visible on forum and thread view probably would be fine even if the content is not available e.g. in search.

**Comment by euantorano** [comment]
It shouldn't, it might just need a change to `show thread` to add a notice to the top/bottom. The `forumdisplay` would just display the same as it does for admins and mods I imagine.

**Comment by WildcardSearch** [comment]
Agreed. Minor template changes only, I'd think.

**Comment by effone** [comment]
I'll come up with a PR. Soon.

**Comment by Eldenroot** [comment]
@effone - great! I will test it when will be available :) Thx!

**Comment by effone** [comment]
Seems like there is a redundant template `postbit_deleted` alongwith related CSS declarations as well as js (`Thread.showDeletedPost()`) which can be easily replaced with another existing template `postbit_ignored` minimizing repetition. I am; however; not changing anything for now and just going to reuse  `postbit_ignored` and associated css / js. The code can be optimized (removing redundant template, css, js) in 1.9, is that ok?

**Comment by euantorano** [comment]
Sounds good to me!

**Comment by Sama34** [comment]
I have to say I'm glad somebody actually fixed this, thank you!
