### ISSUE TITLE
Remove archive mode

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3427]
The archive mode in 1.8 is mostly redundant and is built with hardcoded HTML. It can simply be removed for 1.9.

To remove:

- [x] `inc/functions_archive.php`
- [x] `inc/languages/english/archive.lang.php`
- [x] `archive/`
- [x] archive related settings
- [x] archive related permissions

This shouldn't have any effect elsewhere in the code, unless there are some re

**Comment by Azareal** [comment]
https://community.mybb.com/thread-218251-post-1312919.html#pid1312919
As it's relevant to this issue, I'll link to a related discussion on the forums which still seems to be ongoing..

**Comment by labrocca** [comment]
You have my vote for removal.  Calendar too while you're removing useless features.

**Comment by chack1172** [comment]
Yeah, we should remove it in 1.9. If no one is already working on it, I can do it.

**Comment by Sama34** [comment]
Wouldn't it be better to deprecate `build_archive_link()` instead of totally removing it ?
