### ISSUE TITLE
All smilies should be shown on the full list

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3429]
Now I only have access to the clickable smilies.  The "get more" link works, but only shows the clickables, not the other 100 or so smilies that are shown as installed on the admin panel.

In posts, the extended smilies do show and can be used - they just do not display on the Get More page.

Is anyone else having this problem?

Original thread: [Smilies issue with 1.8.18 upgrade](https://community.mybb.com/thread-219507.html)

**Comment by dvz** [comment]
reverts https://github.com/mybb/mybb/issues/3237
