### ISSUE TITLE
ACP settings search option - hardcoded only for english language.

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3430]
myBB version :
1.8.18

Issue :
search  in ACPs configuration tab is "hardcoded" to always use english language, independently from language chosed by administrator. Therefore search does not find anything when administrator use different language than english.

Steps to reproduce :
1. Goto ACP
2. Change ACP language to anything but english.
3. Click "configuration" tab at top of page or go to admin/index.php?module=config-settings
4. Insert non english word in search textbox and click search.
5. Obviously nothing will be found.

Details :
admin\modules\config\settings.php at line 1147 perform search by query on DB data which is in english.
It should rather create an array of translated data and search this instead. (or similar ideas)

Original thread: [ACP settings search option - hardcoded only for english language.](https://community.mybb.com/thread-219527.html)

**Comment by avril-gh** [comment]
ok since i opened this issue, let i'll fix it.
Heres the fix #3435

**Comment by avril-gh** [comment]
sorry, has to close #3435 due to i pushed it from wrong branch.
Pushed fix branch here #3438 , now its ok.
