### ISSUE TITLE
avater directory not reachable for upload

### ISSUE THREAD

**Issue by 5050** [mybb/mybb#3442]
Hi,
Our forum generated many notifications for issues with this message :
```
Your copy of MyBB running on XXX Forums (http://XXX) has experienced an error. Details of the error include:
---
Type: 2
File: inc/functions_upload.php (Line no. 160)
Message
opendir(): open_basedir restriction in effect. File(./uploads/avatars) is not within the allowed path(s): ([i]/var/XXX/[/i])
```

I solved them by changing line 160 in inc/functions_upload.php from
` $dir = opendir($avatarpath); `
by 
` $dir = opendir(realpath($avatarpath)); `

I'll not open a pull request because I have no certitude at all this is the best solution, or even the correct one.

Best regards, thanks for myBB project

**Comment by AndreRl** [comment]
By the looks of it this is more to do with your PHP settings then MyBB.

**Comment by 5050** [comment]
Can you tell more ?

**Comment by Ben-MyBB** [comment]
Yes, open_basedir restriction is the issue.

**Comment by 5050** [comment]
- If it is a php setting mistake, can you tell more because we do not see which.

- If open_basedir is the problem, can you explain why the relative path fails but the full path works fine ?
BTW I confirm that ./uploads/avatars is inside the open_basedir tree, like all other directory used by the forum.

**Comment by WildcardSearch** [comment]
@5050 if you need support, please post on the community forums.
