### ISSUE TITLE
PHP Tags

### ISSUE THREAD

**Issue by kikizon** [mybb/mybb#3447]
Hi, I today I upgrade mybb from 1.8.18 to 1.8.19

And I see a weird bug, I think this is a bug of myBB 

When I use PHP tags

[php]
some code[] "string ex";
[/php]

Thiis is the output:
"<?php"
some code[] "string ex";

Tags adds "<?php"

Can someone helpme with this? 

PS: Sorry by my bad E
![screenshot_6](https://user-images.githubusercontent.com/11791503/45582836-fbcbfe00-b873-11e8-8ae4-cde1c342cde9.png)

EDIT:

I Fix that with this

```
if($added_open_tag)
{
    $code = preg_replace("#<code><span style=\"color: \#([a-fA-F0-9]{0,6})\">&lt;\?php( |&nbsp;)(<br />?)#", "<code><span style=\"color: #$1\">", $code);
}
```

**Comment by MinusPL** [comment]
it seems that regex here added opening tag of php file just because it is php code, but considering that people would like to show some code without tags It's better this way.
Can you make PR for this?

**Comment by Eldenroot** [comment]
@minuspl please feel free to open a new pull request with fix. I will test it

**Comment by MinusPL** [comment]
Well I tried to somehow recreate this issue, but no luck so far... Every single time php MyCode works as it should. Also in parser there's nothing that adds <?php tag, but still digging deeper to be 100% sure.

**Comment by Ben-MyBB** [comment]
I have tried to replicate this and also no luck as mentioned above so going to go ahead and close this.
