### ISSUE TITLE
Edit time limit in editpost.php not respected

### ISSUE THREAD

**Issue by mikegron** [mybb/mybb#3452]
The edit time limit for post does not seem to be respected.

I tracked down the issue in the `editpost.php` file and it seems we are not using the proper object to retrieve the setting, and the validation is bypassed:

```
// Edit time limit
$time = TIME_NOW;
if($mybb->usergroup['edittimelimit'] != 0 && $post['dateline'] < ($time-($mybb->usergroup['edittimelimit']*60)))
{
	$lang->edit_time_limit = $lang->sprintf($lang->edit_time_limit, $mybb->usergroup['edittimelimit']);
	error($lang->edit_time_limit);
}
```

I changed `$mybb->usergroup` to `$mybb->settings` and now it work:
```
// Edit time limit
$time = TIME_NOW;
$edittimelimit = $mybb->settings['edittimelimit'];
if($edittimelimit != 0 && $post['dateline'] < ($time-($edittimelimit * 60)))
{
	$lang->edit_time_limit = $lang->sprintf($lang->edit_time_limit, $edittimelimit);
	error($lang->edit_time_limit);
}
```

Is this expected?
I also noticed that the quick reply feature also completely bypasses this validation so I removed it from my templates.

**Comment by linguisten** [comment]
yes, edit time limit is a group setting

**Comment by mikegron** [comment]
Oh, I didn't notice that at first. There is the same setting in Board settings > Posting though, but this one is not used anymore ?

**Comment by Ben-MyBB** [comment]
@mikegron What version are you running? I certainly don't have that option in Board Settings -> Posting.

**Comment by PaulBender** [comment]
There used to be a board setting in the past, but it was removed in favor of a usergroup setting in 1.8.

**Comment by mikegron** [comment]
1.8.17 but it's an old server that was upgraded multiple times so that might be it.
