### ISSUE TITLE
Problem with action=event in calendar.php

### ISSUE THREAD

**Issue by kuba2915** [mybb/mybb#3455]
**myBB Version**
myBB 1.8.19 11-09-2018

**issue** 
Calendar not working properly in iframe, ublock blocking any interaction with events in any calendar because EasyPrivacy using filter `?action=event&`, and ublock blocking this sites because in link is `action=event.` changing action, or event to anything else, solves the problem.

Is any chance to confirm that and rename it in master code?

**Comment by euantorano** [comment]
Renaming isn’t as easy as you’d think - doing so would break any existing links in search engines and forum posts.

**Comment by kuba2915** [comment]
Okay, but this case should only affect calendar.php, and nothing else. Am I wrong?

**Comment by euantorano** [comment]
It would affect all links to any calendar events that people have posted in threads, or sent to others on other sites, or indexed in search engines.

**Comment by Eldenroot** [comment]
First of all report issues on MyBB board, not here on GitHub.
