### ISSUE TITLE
Accented char in mybb_theme_colors.xml breaks default theme

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3456]
Hello,

From years now, I translate mybb into french (installation included).

Since v1.8.0 a new functionnality was implemented : colors templates for default theme with the file /install/resources/mybb_themes_color.xml.
I translated the color themes names into french. So "Crepuscule" became "Crépucule". That file was created on february 2015 and never changed nor problematic.

But, since v1.8.16, this file causes an issue.
When editing theme settings, now I get the error "&#36;l['error_invalid_color']" defined in /admin/styles.lang.php, so I was unable to save anything.

Comparing "/admin/modules/style/themes.php" between 1.8.15 and 1.8.16, I see you restrict the stylesheets names to only alphanumeric characters in v1.8.16 and later!
Lines 1095 to 1107.
PHP Code:foreach(&#36;colors&nbsp;as&nbsp;&#36;color)    &nbsp;{   &nbsp;&#36;color&nbsp;=&nbsp;trim(&#36;color);   &nbsp;if(preg_match('/^[a-z0-9]+={1}[a-z0-9]+&#36;/i',&nbsp;&#36;color))    &nbsp;{          &nbsp;&#36;color&nbsp;=&nbsp;explode("=",&nbsp;&#36;color);          &nbsp;&#36;properties['colors'][&#36;color[0]]&nbsp;=&nbsp;&#36;color[1];   &nbsp;}   &nbsp;else   &nbsp;{         &nbsp;&#36;errors[]&nbsp;=&nbsp;&#36;lang-&gt;sprintf(&#36;lang-&gt;error_invalid_color,&nbsp;&#36;color);   &nbsp;}  &nbsp;}&nbsp;
So, now it's impossible made any changes in default theme. That'a pity!
If I change mybb_theme_colors.xml with new one without accented char, the error remains.
Rebuilding default_theme cache does not correct anything.

I tried to change 'é' to 'e' in database (mybb_themes and mybb_datacache), but doing this breaks completely the default theme ! The CSS are lost and now the error is :

Code:Warning [2] Invalid argument supplied for foreach() - Line: 1361
File: ...&#92;admin&#92;modules&#92;style&#92;themes.php PHP 5.6.12 (WINNT)
File     Line     Function
D:&#92;xampp&#92;htdocs&#92;mybb_test&#92;admin&#92;modules&#92;style&#92;themes.php     1361     errorHandler-&gt;error
D:&#92;xampp&#92;htdocs&#92;mybb_test&#92;admin&#92;index.php     821     require!
I can't understand why you changed this! Why a stylesheet name should not have accented chars?... I don't know who had the idea to change suddenly this behaviour, but my question is :
How can I correct this on a running mybb &gt;= 1.8.6 ?
I need to inform my members on how to correct without loosing all.

Note : I wrote a little script (see attachment) inspired from install index.php to re-execute the function insert_templates(). After uploaded the file in /install directory et replaced mybb_theme_colors.xml file, it seems working, but are there a best and/or light way to restore default theme functionnality after replaced mybb_theme_colors.xml file?

Thanks for answer.
[attachment=40848]

Original thread: [Accented char in mybb_theme_colors.xml breaks default theme](https://community.mybb.com/thread-219792.html)

**Comment by effone** [comment]
We restricted characters in color naming to handle a very old issue:
https://github.com/mybb/mybb/issues/2094

**Comment by Sama34** [comment]
I think restriction on characters should be minimal and only on required characters (i.e: `=`)

All other characters should be allowed unless the documentation says otherwise (we can't disable characters and use a bland error message expecting users to guess the reasoning).

**Comment by lairdshaw** [comment]
Do you think then that the alternative regex that @Eldenroot and I came up with in PR #4315 needs to be even more permissive? If so, how do you think it should be modified?

**Comment by Sama34** [comment]
@lairdshaw I actually kept that tab open for testing after publishing my comment. Your ReGex seems to be enough, yes.

**Comment by lairdshaw** [comment]
OK, good. We could probably permit a few other characters such as dash or tilde if you think that's worth it, but I don't think we'd want to be too much more permissive around symbols in particular and any other characters more generally.

**Comment by Sama34** [comment]
Might be worth it, but for me is OK.

**Comment by Eldenroot** [comment]
I dont think so - we should not permit dash/tilde... We can also update the description (lang file).
