### ISSUE TITLE
css.php - multiple queries

### ISSUE THREAD

**Issue by woostarUK** [mybb/mybb#3467]
Apologies if this is in the wrong place. This is a request to enhance css.php

Many (like myself) choose to not pre-cache stylesheets as a file (for various reasons), but unfortunately this can require a dozen extra MySQL queries. When it only requires 1.

Can this:
```
<link type="text/css" rel="stylesheet" href="https://domain.com/css.php?stylesheet=32" />
<link type="text/css" rel="stylesheet" href="https://domain.com/css.php?stylesheet=38" />
<link type="text/css" rel="stylesheet" href="https://domain.com/css.php?stylesheet=17" />
```
Be changed to this:
```
<link type="text/css" rel="stylesheet" 
href="https://domain.com/css.php?stylesheet=32,38,17&lastmod=1539446075" />
```
Please.

**Comment by euantorano** [comment]
It may be worth assigning this to 1.9, since we're making theme system changes there anyway. I've assigned it to 1.8 for now until we discuss that possibility.

**Comment by Azareal** [comment]
What reasons do you have for not pre-caching them?

**Comment by woostarUK** [comment]
I notice this is scheduled for 1.8.20. Before it gets released the database query needs altering slightly (updated here: https://github.com/mybb/mybb/issues/3482 ).
