### ISSUE TITLE
Can't get activated

### ISSUE THREAD

**Issue by RobDonovan** [mybb/mybb#3475]
Sorry to leave this here, but it's the only place I can possibly get in contact with anyone to do with mybb.

I registered an account on mybb.com 2 days ago, and it said it sent me an email to verify my account, but I never receive the email.

I've tried the "Resend Activation Code" but still I don't get anything. (Yes, I've checked my Spam/Junk folder). I know you have the correct email, as I've checked it in my userCP.

I don't have any other problems with that email address, so it must be something wrong on mybb side.

To make it even worse, there is no way that I could find to contact or ask for any help, as the only thing all posts/info told me was to post in the forums... which I can't, because I'm not verified. 

Can anyone here help? As it is either a bug with mybb code or their servers/email.

Thanks, Rob.

**Comment by euantorano** [comment]
Could you please send an email to “contact at MyBB dot com” with the username and email you used to sign up? I can then manually activate your account for you.

**Comment by euantorano** [comment]
@dvz you’ve been working on the web site lately, it may be a good idea to add some details of the contact email address and alternative ways to contact us (eg: Twitter) other than just the forums.
