### ISSUE TITLE
Admin cant see embeded Videos 

### ISSUE THREAD

**Issue by chaesbueb** [mybb/mybb#3481]
Hi,

My users had struggled to embed youtube Videos. I found out that when I logged out and read the Forum as a Guest, I could see the embedded videos. I found out on the mybb Forum from another User, that he had same-ish problems and he solved it with the DVZ Secure Plugin. After installing it and setting it up, now my Users can see embedded Videos which is awesome.

But for me as an Admin, I still can't see it. I just see the code and the youtube link.

Bonus problem: When reading the Forum via Smartphone, the youtube Videos cant be shown it says: "Plug in not supported...."

Appreciate any Help a lot!

**Comment by tnadzieja** [comment]
Sounds like a plugin problem, not a MyBB problem.

"But for me as an Admin, I still can't see it. I just see the code and the youtube link."
I would suggest you check mybb_users database for 'showvideos' and make sure your option matches other users.

**Comment by Eldenroot** [comment]
I am sorry but I cannot reproduce this issue. Please check your UCP and enable videos in posts.
