### ISSUE TITLE
Add 'exact' option to memberlist username search

### ISSUE THREAD

**Issue by kawaii** [mybb/mybb#3483]
Currently the memberlist has advanced search options to search for a username 'beginning with' or 'containing' a string. I'd like to suggest we also add an 'exact' option. On large forums with thousands of members it can be very difficult to find certain users when it's searching in a regular expression style.

**Comment by Eldenroot** [comment]
Moreover add a support - search in custom profile fields would be great...

**Comment by effone** [comment]
@Eldenroot for the 'search in custom profile fields' feature it requires quite of efforts, as:
- The form fields need to be generated dynamically based on input types.
- There are permissions in place that to honor while searching.
- The data gets saved in a separate table, needs JOIN in query.

Its better to have another issue created seeking the feature with separate expected PR.

**Comment by euantorano** [comment]
Depending on how difficult those tasks are, it may be best to leave until 1.9.

**Comment by Eldenroot** [comment]
I agree with you guys, it was just my idea and useful feature. ;)
