### ISSUE TITLE
Missing Moderation Notices

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3486]
I remember previously stumbling across this issue myself but I do not know why I never actually pushed to get a solution for it. After reading [How To?] Notifications to moderators about unapproved posts I was once again reminded that MyBB does not give notice of all moderation notices.

As it stands all posts, threads and attachments that need moderator approval are not being notified with a moderation notice like you would get for reported content.

This solution from 2011 does work (I just tested it) however I am not sure how up to par the coding is and haven't actually looked at it hard enough. I'm also TERRIBLE at trying to maneuver or work GitHub so I figured I would post this here for someone else that may be able to actually do pull requests and changes and what not that are necessary.

I do believe this should have always been standard/core MyBB, after all if it is in the moderation queue it should be notified to all moderators or those with Mod CP access.

Original thread: [Missing Moderation Notices](https://community.mybb.com/thread-220422.html)

**Comment by Eldenroot** [comment]
There is a working plugin for this (http://doylecc.altervista.org/bb/downloads.php?dlid=20&cat=1), but this should be added into MyBB core.

**Comment by yuliu** [comment]
In v1.9, the moderation queue notice is also missing.

I'd like to submit a PR later. Should a new issue to be created for better tracking or only just reference this one?

**Comment by euantorano** [comment]
For 1.9, issues don’t matter so much right now. 

The reason we like separate issues per PR is related to writing release notes - we assign issues to the 1.8/1.9 label and add a milestone, so that when we release a version we can easily link to a list of fixed issues. 

As 1.9 is a much bigger release, the release notes are going to be done manually in all likelihood so issues can be mixed.
