### ISSUE TITLE
Memberlist search by username will not work with usernames containing special characters

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3492]
When searching the memberlist by suername, the username is ran through `htmlspecialchars_uni()` before being used in the search query. This means that any search for a user like `1&2` will fail as the query will be something like:

```sql
SELECT * FROM mybb_users WHERE username LIKE '%1&amp;2%';
```

https://github.com/mybb/mybb/blob/d776df51f8f0af98e970ed19a4d3315c7eaa6960/memberlist.php#L199-L216

The `$username_like_query` should probably just be `$db->escape_string($mybb->get_input('214'))` (I'm not sure whether it should trim the query - that's debatable and ties in to #3088).

**Comment by effone** [comment]
If you are talking about trimming the username search criteria I am against it. Reason being, currently if you search ` tor` (with a space before) you will get 'administrator' & 'actuator' in result dishonoring the appended space. IMO it should not catch those names, instead should show those names with a 'tor' having space before, like: 'Euan Torano' or 'Burning Torpedo'. - if you get what I mean ...

**Comment by euantorano** [comment]
Yes, I completely agree. If the user includes a space, we shouldn't just ignore it.

**Comment by effone** [comment]
The username `1&2` is invalid at the first place. Is it required to be fixed?

![snap](https://image.ibb.co/iLTSVA/Untitled-2.png)

**Comment by effone** [comment]
Is this still an issue or we can close it?
