### ISSUE TITLE
Thread prefixes - use style in ACP

### ISSUE THREAD

**Issue by Eldenroot** [mybb/mybb#3508]
Same as for usergroups we should use styles for thread prefixes in ACP too.

https://github.com/mybb/mybb/issues/3291#issuecomment-442525541

**Comment by Sama34** [comment]
Sounds nice, has been requested before. But it will only work for forums that don't use external CSS classes.

**Comment by Eldenroot** [comment]
And? We use same approach for usergroups... why not to extend it?

**Comment by Sama34** [comment]
Sure, I'm not saying the contrary, if you want to send a PR I will review it for you.

**Comment by Sama34** [comment]
Oh, ok, if you were suggesting to do it in the same PR I apologize, I might have confused myself.
