### ISSUE TITLE
Reputation is lost on account merge

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3509]
Related to #2020, was decided that a separate PR would be good in #3405.

**Comment by Ben-MyBB** [comment]
@JordanMussi 👀

**Comment by JordanMussi** [comment]
Hehe I'm already working on it @Ben-MyBB!

This was how I spotted the referrals issue :wink:

**Comment by rajat315315** [comment]
Although, I have reviewed the reputation merging code which seems fairly robust, the only possibility of reputation lost seems to be when the 2 users to be merged have upvoted each other's posts/comments. In that case, double counting of reputation is avoided.
I have created a PR which resolves a major BUG in reputation merging, which might have caused almost all merges untill now to be incorrect.
