### ISSUE TITLE
Cannot navigate beyond page 1 in ModCP - Warning Log

### ISSUE THREAD

**Issue by panayotb** [mybb/mybb#3511]
Clicking on page 2 or the "Next" button does not do anything.

**Comment by Eldenroot** [comment]
First of all report bugs on MyBB board, not here on GitHub. 

Moreover this issue will be fixed in MyBB 1.8.20

**Comment by euantorano** [comment]
Please see Pull Request #3505 which fixes this issue and is already merged to be part of the next release.
