### ISSUE TITLE
Forum Team Link should be available globally

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3512]
As this link is a special member listing link just like memberlist link, independent to anything related to index.php - this should be available globally and placed in headerinclude.

**Comment by euantorano** [comment]
Should be in headerinclude and/or the footer.

**Comment by effone** [comment]
Right, I stated header as the memberlist link is also there. But not a problem as the variable is available globally. This will be useful for those who like all the member listing links grouped (memberlist, teamlist, buddy list, who's online), may be in a dropdown under members menu.

Making a PR placing the link in footer.
