### ISSUE TITLE
Forum home - who's online error

### ISSUE THREAD

**Issue by justinsoltesz** [mybb/mybb#3518]
The following error appears on the forum home (`index.php`) when the who's online list is enabled. Error does not appear if the who's online list is disabled on the forum home page.

![image](https://user-images.githubusercontent.com/544942/49462116-4601b300-f7c3-11e8-94a0-880543d8a8a6.png)

There are no apparent errors on the who's online page itself (`online.php`)

**Comment by rajat315315** [comment]
which branch should I look it in?

**Comment by euantorano** [comment]
I believe this is already resolved, closing this issue.
