### ISSUE TITLE
Invisible Recaptcha - PW Reset Error

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3520]
A member has tried to reset his PW, but couldn't get past the email stage as it flags up "Please complete Recaptcha", but the Recaptcha doesn't appear

I was able to replicate and to solve I simply switched from Invisible Recaptcha to the normal Recaptcha

So I think there is an issue with Invisible Recaptcha on the reset PW page

Original thread: [Invisible Recaptcha - PW Reset Error](https://community.mybb.com/thread-220033.html)

**Comment by meetdilip** [comment]
I had this issue with the admin login page. I was blocked from admin login for around 24 hours. And when I tried sometime back, I got the error first and in the second attempt, I was through. I checked and found out that I am using reCAPTCHA v3 and had set Invisible CAPTCHA for registration.
