### ISSUE TITLE
ft_min_word_len query every search

### ISSUE THREAD

**Issue by labrocca** [mybb/mybb#3526]
I'm doing some custom edits in search and found a line is called in the functions_search.php inside the function perform_search_mysql_ft().  

This is the code:

> // Attempt to determine minimum word length from MySQL for fulltext searches
> 	$query = $db->query("SHOW VARIABLES LIKE 'ft_min_word_len';");
> 	$min_length = $db->fetch_field($query, 'Value');
> 	if(is_numeric($min_length))
> 	{
> 		$mybb->settings['minsearchword'] = $min_length;
> 	}
> 	// Otherwise, could not fetch - default back to MySQL fulltext default setting
> 	else
> 	{
> 		$mybb->settings['minsearchword'] = 4;
> 	}

That one query isn't really needed imho and there are better ways to deal with ft_min_word_len setting than a query each time the function is run.  

Consider an alteration where it just uses the setting. Maybe during install of MyBB you ensure that the setting is the minimum value.

Every query saved is nice.

**Comment by labrocca** [comment]
And actually if you look over the code it's weird because let's say I want to set my min character word to 5, it won't let me because it will hard-code to 4.  

You guys literally hard-code set the setting in the function.  :(

I had to look at it carefully to realize WTF was happening.

**Comment by euantorano** [comment]
I've tagged this as a bug. It won't be fixed in 1.8.20 because I want to release that sooner rather than later, but once we get the 1.8.21 milestone created we'll probably assign it to that.

**Comment by euantorano** [comment]
Yeah, I think that is the best way.
