### ISSUE TITLE
Modern password hashing

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#3530]
Use [`\Illuminate\Hashing`](https://github.com/laravel/framework/tree/5.7/src/Illuminate/Hashing) and extensions for modern password hashing.

Codebase:
- modify `create_password()`, `verify_user_password()` wrapper functions to use MyBB's extension of `\Illuminate\Hashing\HashManager`,
- implement `bcrypt` password hashing (`Illuminate\Hashing\BcryptHasher`) as default,
- create `MybbHasher` hashing driver to handle old hashes,
- modify `verify_user_password()` to allow plugins overwrite parameters (e.g. to decrypt values before checking),
- modify `LoginDataHandler::complete_login()` to upgrade algorithm and parameters to default on the fly.

Database:
- extend `mybb_users.password` column length,
- add `mybb_users.password_algorithm` column for algorithm identification.

Defer to 1.9-compatible version of [DVZ Hash](https://community.mybb.com/mods.php?action=view&pid=976) for algorithm wrapping and encryption with intent to implement in subsequent branches; set `argon2id` as default algorithm once PHP 7.3 is required.

**Comment by euantorano** [comment]
Note that a `password_algorithm` column may not be needed. If using PHP's standard `password_*` functions, there is [`password_get_info()`](http://php.net/manual/en/function.password-get-info.php) to resolve the algorithm and cost used for a given password. Assuming a core MyBB install of 1.8, the existing password will never start with `$` (as the password is a base64 representation of an MD5 hash) so if it doesn't start with that, then it's an old MD5 hash.

**Comment by dvz** [comment]
That's worth considering too, but we'll be dealing with a mix of functions that support `password_get_info()` and those that do not (mainly the old `mybb` and the wrapped `mybb_bcrypt`), which is why I went with an explicit column for now so that everything can be previewed and manipulated more easily (extensibility for custom algorithms aside).
With this scheme we can clear the additional field partially or entirely when the algorithm metadata is stored in the main string.

**Comment by effone** [comment]
Why this is in 1.9? This can be designed in backward compatible way to update existing hashes to be modern. This should be part of 1.8.

@euantorano the check can be more bullet proof. Salt field will be blank. I can modify the function a way that if the native `password_verify()` fails it will check further with old MD5 method alongwith presence of salt in DB. If it matches it will update the new hash cleaning salt and log the user in. This can be so smooth that user will notice nothing. The update will be once per user.

There is no problem having this in 1.8. Then in 1.9 we can use Illuminate.

**Comment by euantorano** [comment]
@dvz fair enough, makes sense to include a column then.

@effone the main reason for waiting until 1.9 is that PHP's `password_hash()` and associated functions are only available in PHP >= 5.5 and the [`password_compat`](https://github.com/ircmaxell/password_compat) library needs PHP >= 5.3.7. MyBB 1.8 needs to support all the way back to PHP 5.2.

I suppose we could select the best available algorithm based upon available functions, but then we could be maintaining 3 or 4 different password hashing schemes and all the associated support requests that would cause.

1.9 should't be too far away, and there's already @dvz's plugin for 1.8 to update the hashing, so I think leaving it until 1.9 makes sense.

**Comment by Katarn** [comment]
Will this be compatible with passwords of users who have already logged in to the forum and who have not yet logged in - after the forum has been converted from another (via Merge System)?

In other words, I'm interested in whether absolutely all users can log in without problems on a forum that was converted from another, for example, IPB4.

**Comment by dvz** [comment]
The Merge System supplies a [plugin](https://github.com/mybb/merge-system/blob/feature/loginconvert.php) to verify passwords using third party algorithms, and then to convert them to the MyBB format. It may need some minor changes for 1.9 compatibility, but no major problems are expected (and passwords would still be verified and converted for users who haven't logged in).

MyBB itself will continue to support the old (≤ 1.8) algorithm and convert old password to the new algorithm.

**Comment by cronlabspl** [comment]
> using third party algorithms

@dvz really? You want to send password ( regardless hashed / unhashed ) out-of script ( MyBB ) to some 3rd party plugin? What if author of this plugin decides to push some malicioius change that will, say, redirect incoming stream to some DB to store for later use?

That can happen.
