### ISSUE TITLE
Admin panel "show forum" button no work correctly with https

### ISSUE THREAD

**Issue by arv187** [mybb/mybb#3535]
Hi, after many attempts I give up, there is an error whereby the button does not add the last slash to the url and redirects to http, not https

More details here, in question 2 (Q2):
https://community.mybb.com/thread-220478-post-1317980.html#pid1317980
Final note here:
https://community.mybb.com/thread-220478-post-1318901.html#pid1318901

My cookies are configured in admin panel such `.argavirtual` and folder `/mybb/`
Site address: `https://foro.argavirtual.com/mybb` (admin panel say: DO NOT include the bar (/) at the end.)

I try too this in a blank .htaccess (host/mybb/.htaccess): 

> effone said in discord:
> 
> ```
> RewriteEngine On
> RewriteCond %{HTTPS} off
> RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
> ```

But I receive a error always, even if I erase the cookies and the cache:
(Firefox)
> The page is not redirecting properly
> An error has occurred connecting to foro.argavirtual.com.
> This problem is sometimes caused by disabling or rejecting the reception of cookies.

(Chrome)
This page does not work The page foro.argavirtual.com has redirected you too many times.
Delete cookies
ERR_TOO_MANY_REDIRECTS

If the "View forum" button included the final slash there would be no problem.

**Comment by labrocca** [comment]
If you use a subdomain then try the cookie as "foro.argavirtual.com".

Also looks like your forum is here:
http://foro.argavirtual.com/mybb/

And I think your htaccess is bad which is the real problem. 

This is not a MYBB bug. Just a configuration problem on your end.

**Comment by arv187** [comment]
effone a mybb member team, said me that .htaccess and is same that I found in google.
About subdomain in details of site admin panel say: start your domain with "." to cover all subdomains.

I will try with full url, but then forum help is bad.

**Comment by arv187** [comment]
@labrocca tankyou for you help, now I can't login.

**Comment by effone** [comment]
This is related to browser cache / cookies / .htaccess as stated before as well.
I'd seriously like to look at your `.htaccess`

There is no problem with MyBB regarding this issue. I am closing this. This can be further taken up through Support Forums / Discord Channel.

**Comment by arv187** [comment]
Sure? I have this issue since 10-31-2018 and not help

**Comment by arv187** [comment]
Ever is my fault or my configuration, but I configure forum following instructions.

**Comment by Eldenroot** [comment]
I have no issue with SSL... it is configuration related issue

**Comment by arv187** [comment]
I followed the instructions, saying that it is something of configuration and putting the problem on me does not help.

https://community.mybb.com/thread-220478-post-1321559.html#pid1321559

**Comment by arv187** [comment]
> 
> 
> I have no issue with SSL... it is configuration related issue

https://community.mybb.com/thread-220478-post-1321559.html#pid1321559

**Comment by arv187** [comment]
The problem is only that fucking button, the rest works correctly, so stop blaming me and help me really.

**Comment by Eldenroot** [comment]
Do not be rude kid. This button works fine for me, so blame yourself...

**Comment by effone** [comment]
I can understand your frustration but I have demonstrated you your site link is working for me with or without trailing `/`.
The other fact is if you try to access your site with `https://` it is not obeying the protocol and getting redirected to insecure `http://`. There IS some config issue. And once again, most likely its your `.htaccess`.

Please stop the discussion here.
