### ISSUE TITLE
Member Profiles have Send Email link

### ISSUE THREAD

**Issue by labrocca** [mybb/mybb#3538]
Line 2194 is an IF statement which creates the $sendemail template on profiles.  It does not have the $mybb->usergroup['cansendemail'] variable as part of it.  It should be added so that on profiles the link to email the member is removed.

**Comment by PaulBender** [comment]
Can confirm, PM templete needs it too.

**Comment by effone** [comment]
There are many things like that throughout MyBB. I have an exhaustive list, few main points are posted already:
https://community.mybb.com/thread-221021.html

**Comment by effone** [comment]
Also, if you are viewing your own profile you will see send email link.
Why on earth a person will send mail to himself?

**Comment by Eldenroot** [comment]
@effone I agree, would be nice to fix them. QoL changes are always welcome!

**Comment by euantorano** [comment]
@effone WOuld you mind opening another issue(s) for those? Makes it easier to track that way 😄

**Comment by Eldenroot** [comment]
1. "Subscribe to this thread" - appears for logged in users, but not for guests. Fine. But "Subscribe to this forum" appears for all; however clicking on it as a guest will show 'No permission' page. - **AGREE**
2. "Ban this user in MCP / ACP" appears in every member's profile even if they are already banned. That can be removed or changed for already banned members to "Modify Ban / Unban". - **AGREE**
3. "Open Buddy List" appear for those who don't have buddies. - **I am not sure about this, maybe better to leave it as it is for consistency.**
4. "Mark All Forums Read" appears even if there is not a single unread post. - **AGREE**
5. "Show Forum Team" link appears in Memberlist even if the Forum Team listing page is disabled. - **AGREE**
6. Find all posts / Find all threads in profile even when there is no post / thread made by user. Same for reputation details link. Same for Reputation report of Reputation-less user. - **I am not sure about this, maybe better to leave it as it is for consistency.**
7. Empty forum shows thread filter and all good thread controls along with postbit frame.
8. Showthread-> Moderator Tools : "Open/Close Thread" and "Stick/Unstick Thread" should be specific as per state like "Approve/Unapprove". - **AGREE**
9. Postbit/member profile - display PM/EMAIL etc buttons for own post is redundant - **AGREE**
