### ISSUE TITLE
User promoted from a Custom usergroup (via Forum Management) is not displayed as...

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#354]
> Scenario: in MyBB v. 1.6.11, when a user is promoted via **Forum Management** ->**Moderator** a **CUSTOM** usergroup, **Primary User Group** is NOT changed automatically to Moderators usergroup, even if the user has the rights to moderate the selected forum.
> 
> Instead, if this user is member of **Registered** usergroup (no custom one), **Primary User Group** IS changed automatically in Moderators usergroup.
> 
> Reported here: [[[http://community.mybb.com/thread-148312.html](http://community.mybb.com/thread-148312.html)]]

Original report: http://dev.mybb.com/issues/2283
Reporter: Flavius Popa
Status: New

**Comment by JN-Jones** [comment]
While I can confirm that this is valid we should discuss how we want to solve this. It's ok to overwrite the primary usergroup as long as it's the registered group but I don't think that overwriting custom usergroups is the best idea. Instead the moderator group should either set as secondary group or the custom group should be moved to secondary groups.
