### ISSUE TITLE
Configure PHPStan as part of MyBB 1.9's CI

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3551]
[PHPStan](https://github.com/phpstan/phpstan) is a static analysis tool for PHP that can help catch common errors in code.

We should add it as part of our CI pipeline in MyBB 1.9 to catch obvious errors.

We should likely only target the `inc/src` and `tests` folders, but it's worth trying it on the full codebase first to see how bad it actually is...

**Comment by ks129** [comment]
Created PR for this

**Comment by euantorano** [comment]
Great, thanks. I will review it tonight!

**Comment by Ben-MyBB** [comment]
@euantorano can this one be closed with #3750

**Comment by euantorano** [comment]
Yeah, closed.
