### ISSUE TITLE
Typo when a thread is waiting for approval

### ISSUE THREAD

**Issue by woostarUK** [mybb/mybb#3553]
1.8.20 beta

Typo: "and aiting Moderation: 1 unapproved thread."

Narrowed down the error to rogue code on line 783 - global.php
`$moderation_queue = substr_replace($moderation_queue, ' '.$lang->and.' ', strrpos($moderation_queue, $lang->comma), strlen($lang->comma));`

Where do dev's prefer beta testing reports to be posted. Here, or https://community.mybb.com/thread-221648-post-1322856.html ?

**Comment by Eldenroot** [comment]
Thank you for your report!

**Comment by Eldenroot** [comment]
I can reproduce, here is the picture
![image](https://user-images.githubusercontent.com/778890/51801313-45721f80-223c-11e9-8aec-83e107576faa.png)

**Comment by effone** [comment]
@Eldenroot 
Can you please replace these 2 lines in global.php near line 762:
```
    $moderation_queue = $lang->sprintf($lang->mod_notice, implode($lang->comma, $moderation_queue));
    $moderation_queue = substr_replace($moderation_queue, ' '.$lang->and.' ', strrpos($moderation_queue, $lang->comma), strlen($lang->comma));
```
with these 3:
```
    $moderation_queue_last = array_pop($moderation_queue);
    $moderation_queue = empty($moderation_queue) ? $moderation_queue_last : implode($lang->comma, $moderation_queue).' '.$lang->and.' '.$moderation_queue_last;
    $moderation_queue = $lang->sprintf($lang->mod_notice, $moderation_queue);
```
and check if the issue gets fixed?

I can't do testing or PR right now for some reasons ...
