### ISSUE TITLE
Missing captcha v2 in "error_nopermission"

### ISSUE THREAD

**Issue by send-your-nudes** [mybb/mybb#3560]
Okay,

This is the third time I'm posting and I'm sorry that I haven't looked through all places.

This should be a final missing captcha place. Error template for not logged in users.

**Comment by Eldenroot** [comment]
Hmm, quite interesting - someone used this "weak" spot and tried to guess the password (I use my own code for logging unsuccessful login attempts). 66 tries :D

**Comment by Sick1G** [comment]
@PaulBender can you revisit this?

**Comment by PaulBender** [comment]
Yes, I'll look at this over the weekend.

**Comment by Eldenroot** [comment]
Is there any workaround?

**Comment by euantorano** [comment]
There is no patch for this yet, it'll be solved in 1.8.22.

**Comment by Sick1G** [comment]
Guys, I think you misunderstood this. This is **NOT** for captcha v3, this is for captcha v2 missing the **3rd** template "Error template for not logged in users." Because I previously reported 2 other templates

**Comment by euantorano** [comment]
I understood what you meant, just haven’t had a PR yet.

**Comment by PaulBender** [comment]
I've looked into this and I'm not sure if it could be fixed. You can add a CAPTCHA to the page but there isn't a way to validate it.
