### ISSUE TITLE
Request can't be found in the container for 1.9

### ISSUE THREAD

**Issue by xaoseric** [mybb/mybb#3562]
Basically, what the title says, it seems that the "request" class can't be found.

`Fatal error: Uncaught ReflectionException: Class request does not exist in C:\xampp\htdocs\mybb-1.9\inc\vendor\illuminate\container\Container.php:779 Stack trace: #0 C:\xampp\htdocs\mybb-1.9\inc\vendor\illuminate\container\Container.php(779): ReflectionClass->__construct('request') #1 C:\xampp\htdocs\mybb-1.9\inc\vendor\illuminate\container\Container.php(658): Illuminate\Container\Container->build('request') #2 C:\xampp\htdocs\mybb-1.9\inc\vendor\illuminate\container\Container.php(609): Illuminate\Container\Container->resolve('request', Array) #3 C:\xampp\htdocs\mybb-1.9\inc\src\Application.php(437): Illuminate\Container\Container->make('request', Array) #4 C:\xampp\htdocs\mybb-1.9\inc\src\functions.php(23): MyBB\Application->make('request', Array) #5 C:\xampp\htdocs\mybb-1.9\admin\admin.php(15): MyBB\app('request') #6 {main} thrown in C:\xampp\htdocs\mybb-1.9\inc\vendor\illuminate\container\Container.php on line 779`

**Comment by euantorano** [comment]
Which page were you trying to access when you got this?
