### ISSUE TITLE
Not receiving email with activation code

### ISSUE THREAD

**Issue by eirikh1996** [mybb/mybb#3563]
I've been trying to activate my account (eirikh1996) on the MyBB community forum. However, when requesting account activation email to be sent to my email address I receive NO email. Have tried multiple times, and haven't received a single email with an activation link

**Comment by effone** [comment]
Have you checked spam / junk folder?

**Comment by euantorano** [comment]
Please email me euantor-at-mybb.com with your username and email address and I will manually activate your account after work tonight.
