### ISSUE TITLE
Mybb 1.9 Demo Sign Up Page <abbr> tag issue on password label

### ISSUE THREAD

**Issue by Holyphoenix** [mybb/mybb#3564]
As you can see in the image, the abbr tag isn't really doing anything but displaying and making the sign up page look bad.  This is on Justin's demo site here: https://mybb.jsoltesz.com/mybb-1.9/
![image](https://user-images.githubusercontent.com/3467817/51916508-0f9b7b00-23a3-11e9-838f-fbf757e6dc97.png)

**Comment by kawaii** [comment]
Thanks for the report, I'll let @justinsoltesz know!

**Comment by justinsoltesz** [comment]
This has been fixed and the demo board has been updated
