### ISSUE TITLE
Enhancement: Remove double confirmation of upload

### ISSUE THREAD

**Issue by woostarUK** [mybb/mybb#3566]
When attaching files to a post/thread, MyBB (currently) requires files to be confirmed twice (once when pressing the Confirm/Submit/Choose button on the dialog box, and then again by pressing the 'Add Attachment' button).

The 'Add Attachment' button is redundant. Can Ajax be used to attach the file once the confirmed (Confirm/Submit/Choose) and dialog box closes?

**Comment by Ben-MyBB** [comment]
I agree with this, it is a low priority enhancement but definitely worth while making.

**Comment by Eldenroot** [comment]
@zygzagZ

**Comment by zygzagZ** [comment]
Do you mean that after clicking "Choose files", selecting attachments and accepting the modal window it should automagically send them without waiting for "Add Attachment" button? There is distinct behaviour based on whether you want to add or update attachment, should they be merged?
![pic rel](https://i.imgur.com/2QAeqfR.png)

**Comment by woostarUK** [comment]
@zygzagZ - IMHO the 'Add Attachment' can be removed. The attachment should upload straight after clicking 'Open' (on your screenshot). 

Since you have already double confirmed by selecting the file and clicking Open, there is no need for a third confirmation (Add Attachment).

Upload Process:
1. Click 'Choose Files'
2. Select file
3. Click 'Open'

**Comment by Eldenroot** [comment]
@woostarUK - I agree! The attachment should be uploaded automatically after selecting the files, not need to click on "Add attachment" button

**Comment by effone** [comment]
Add attachment will be there as a fallback to no-js.
But we can definitely trigger upload by js on input change.
