### ISSUE TITLE
Requirements Check Error 1.9

### ISSUE THREAD

**Issue by ks129** [mybb/mybb#3568]
If you install MyBB 1.9 in Requirements Check stage, every time first try show this error:

> Error
The MyBB Requirements check failed due to the reasons below. MyBB installation cannot continue because you did not meet the MyBB requirements. Please correct the errors below and try again:
The configuration file (inc/config.default.php) could not be renamed. Please manually rename the config.default.php file to config.php to allow it to be written to or contact MyBB Support.

I tried this 2 time and every time this file is renamed.

**Comment by euantorano** [comment]
This code hasn’t changed at all in 1.9, but may have received changes in 1.8 that haven’t been copied across yet.
