### ISSUE TITLE
MyBB 1.9 Error after installing

### ISSUE THREAD

**Issue by ks129** [mybb/mybb#3569]
After I installed MyBB 1.9 to my website, Google Chrome show message:

> Host domain cannot process this request at this time.

In error_log:

> [30-Jan-2019 16:43:20 UTC] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in domain/mybbdev/inc/class_plugins.php on line 52

**Comment by euantorano** [comment]
Which version of PHP are you using? You need a recent version, at least PHP 7.1.
