### ISSUE TITLE
Mass Mail problem

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#357]
> As descrived here [http://community.mybb.com/thread-139200-page-2.html](http://community.mybb.com/thread-139200-page-2.html) there is a problem with mass mail.  
> It always stays at 0% and repeats the sending of the first 20 users every 15 minutes, tried with email only text and only html.  
> I

Original report: http://dev.mybb.com/issues/2279
Reporter: Max T.
Status: New

**Comment by JN-Jones** [comment]
@mybb/sqa I have never experienced this myself and most support request about mass mail are related to other issues so not sure whether this is a valid bug. Can somebody confirm this or otherwise close it?

**Comment by Shade-** [comment]
I have never experienced this and being a fairly old issue it should have already been patched. I'd close this. @mybb/developers
