### ISSUE TITLE
Mybb 1.8.19 Attachment Upload Error

### ISSUE THREAD

**Issue by ozanakkaya** [mybb/mybb#3570]
Hi,
I'm opening a new thread. add attachment and click send thread button. 

Loading attachment. But when the thread is sent, there is no supplement.

I have a new forum. I have the same problem again.

Thanks.

**Comment by ozanakkaya** [comment]
I couldn't tell?

**Comment by tedem** [comment]
I have tested on 1.8.19; couldn't see a problem 😕

**Comment by Eldenroot** [comment]
Same here, no issue so far.

**Comment by ozanakkaya** [comment]
> I have tested on 1.8.19, couldn't see a problem

would you write a link for me to test?

**Comment by tedem** [comment]
No live links.

![acp](https://user-images.githubusercontent.com/45723359/52722284-59e44500-2fbc-11e9-9711-907ef697a3e0.png)

![test](https://user-images.githubusercontent.com/45723359/52721988-d591c200-2fbb-11e9-89a0-ad48e8e158c9.png)

**Comment by Eldenroot** [comment]
This can be closed if no more steps how to reproduce would be provided.
