### ISSUE TITLE
bug Resend email activation

### ISSUE THREAD

**Issue by firstboy000** [mybb/mybb#3572]
query of do_resendActivation in member.php line 1515 should change to...
```
$query = $db->query("
		SELECT u.uid, u.username, u.usergroup, u.email, a.code, a.type, a.validated
		FROM ".TABLE_PREFIX."users u
		LEFT JOIN ".TABLE_PREFIX."awaitingactivation a ON (a.uid=u.uid AND (a.type='r' OR a.type='b'))
		WHERE u.email='".$db->escape_string($mybb->get_input('email'))."'
	");
```
"just put ```a.type='r' OR a.type='b'``` in parentheses"

what happened:
by change register type from both to email verify, some users that registered before it, has type 'b' and activated field has value '1'
in query of line 1515 in member.php return many records that are type'b' and activated'1'!!!
if we put parentheses, the condition will be correct.

**Comment by Eldenroot** [comment]
Maybe related issue, it displays all the time
![image](https://user-images.githubusercontent.com/778890/52532355-11aaf580-2d24-11e9-9a69-d8751da2a545.png)

**Comment by Ben-MyBB** [comment]
@mybb/developers @mybb/sqa Can anyone confirm?

**Comment by Ben-MyBB** [comment]
@Sama34 Can you take a quick look? The fix is included in the post.
