### ISSUE TITLE
MyBB 1.9 Install page

### ISSUE THREAD

**Issue by LogicPlague** [mybb/mybb#3573]
Can we update the looks of the install page? It reminds me of the 1.8 installer's GUI, and if we are getting new looks to MyBB we should also get a new look to the install page.

**Comment by euantorano** [comment]
Would probably make sense. I've not looked at the code behind the layout or anything of the installer in a while.

**Comment by Sick1G** [comment]
Would be nice to have it ajaxified and minikalist like woltlab or ips 😁

**Comment by effone** [comment]
Sounds exciting!!!

**Comment by euantorano** [comment]
The plan is to have a CLI based installer in the future too. I plan to start work on the CLI tool in 1.9, but don't know if we'll get the installer part done then.

**Comment by dvz** [comment]
Tracking in #3712
