### ISSUE TITLE
Parser auto link breaks `ftp://` protocol URLs

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3575]
For example, 

```ftp://example.com/```

gets converted by `mycode_auto_url_callback()` to 

```ftp.example.com/```

which `mycode_parse_url()` links to 

```http://ftp.example.com/```

Original thread: https://community.mybb.com/thread-222021.html

**Comment by kawaii** [comment]
Confirmed this behaviour on 1.8.20.

**Comment by kawaii** [comment]
Hmm, so the provided patch does indeed fix the FTP URLs, and other kinds of URLs still parse as intended. This is probably safe to merge if someone else can also test and validate.

**Comment by euantorano** [comment]
I seem to remember giving this a quick try out the PR myself a while back and also confirming it worked. I'll test again today.
