### ISSUE TITLE
Threads Awaiting Moderation text overflow and no BBCode parsing

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3578]
The `Threads Awaiting Moderation` part of the Mod CP (`modcp.php?action=modqueue&type=threads`) needs some CSS modification to prevent text overflowing the width of the container. The text also isn't being parsed as BBCode:

<img width="1205" alt="screenshot 2019-02-23 at 09 34 47" src="https://user-images.githubusercontent.com/748913/53284586-48cecd00-374e-11e9-91cd-037dc562f6df.png">

**Comment by euantorano** [comment]
Note that this also applies to posts awaiting approval.

**Comment by dvz** [comment]
No parsing might have been a feature - full source would show all links hidden with modified font color, etc.

**Comment by dragonexpert** [comment]
I think it is better with full source rather than what it actually looks like parsed.  There is another issue I can see that relates to awaiting moderation, but I'll make a new thread on the forum.  It is a one line to fix.

**Comment by effone** [comment]
Source view is a part of moderation, for like identifying hidden spam links ...
I guess `word-break` is the only issue to be addressed here.

**Comment by euantorano** [comment]
Ok, I can easily revert the parsing commit.

**Comment by euantorano** [comment]
Reverted changes for parsing, the PR only fixes the word wrapping now.
