### ISSUE TITLE
Ranged events do not show in the calendar

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#358]
> Ranged events wont show in the calendar if the start and end time of the original interval don't fall within the searched scope for the events.
> 
> When I create an event on 1-1-2013 which re-occurs every year it is only shown in the calendar of 2013 not in subsequent years. I suspect all events which are ranged with a start time earlier then the asked end time should be considdered.

Original report: http://dev.mybb.com/issues/2276
Reporter: Jelke van Hoorn
Status: New

**Comment by Destroy666x** [comment]
Ranged events seem to be ok, but repetitive not. The issue for that was duplicated: https://github.com/mybb/mybb/issues/2099 but there's one more valid one so I'll close this.
