### ISSUE TITLE
1.8.20 Editor Center issue

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3588]
Reproduction steps:
In message editor, center your text.

Preview your post OR send your message.

Notice that your text isn't centered anymore.

If you write align=center yourself, it works. If you use button for it, it doesn't.

Original thread: [1.8.20 Editor Center issue](https://community.mybb.com/thread-222153.html)

**Comment by martec** [comment]
ps. this doesn't hapeen with firefox.

**Comment by martec** [comment]
maybe the sceditor doesn't full compatible with jquery 3.
maybe need update sceditor to 2.1 and to do changes like that smf did.
h ttps://github.com/SimpleMachines/SMF2.1/commit/6b12e2ec747cd51fb5f1bdc9c50c8cbacbd79b44#diff-c962f66d2fef87254e2ffaf9b1f07e1c

or change mybb default editor to bbcode editor like mybb 1.6. complicated for us to offer support to abandoned libraries or practically no support for bbcode plugin like tinymce and ckeditor .
for me if want wysiwyg editor, so use extension, like phpbb.

**Comment by MinusPL** [comment]
It seems that SCEditor itself has this bug. It's not related to MyBB (I spent about 1,5 hour searching what could possibly create this issue).

For now I tried to rewrite align in other way, tried to remove all MyBB BBCodes. Nothing changed. Even SCEditor built-in bbcodes are not able to change centered text into [center]text[/center] code. (Yes, this is standard alignment bbcode, and yes it technically works for MyBB too). So it seems that it is required to update SCEditor to version 2.0 or higher or change editor to other one. Also I'd like to point that adding any custom bbcodes that require some custom processing is really hard with SCEditor.

**Comment by euantorano** [comment]
We’re planning on upgrading SCEditor to the latest version in 1.8.21, along with upgrading jQuery to the latest version. 

We can’t really change editors in a minor point release.

**Comment by MinusPL** [comment]
Yeah it won't be a good idea to change editor to other one. I'll continue to look where this issue has originated. It's weird that only centering doesn't work. And as I noted in my previous comment - SCEditor 1.5.2 is working properly as standalone thing, but when used in MyBB centering suddenly stops working.

**Comment by effone** [comment]
Apparently this issue has been introduced in v.1.5.2 where a function for getting WYSIWYG editors HTML value started cloning the code.

file: "jquery.sceditor.bbcode.js" line 2145 to 2151.
```
				var $tmp = $('<div>')
					.appendTo(document.body)
					.append($($wysiwygBody[0].childNodes).clone());

				dom.fixNesting($tmp[0]);

				html = $tmp.html();
```

Earlier it was using the raw code:

```
html = $wysiwygBody.html();
```

So if we use:
```

				if (filter !== false && pluginManager.hasHandler('toSource')) {
					html = pluginManager.callOnlyFirst('toSource', html, $wysiwygBody);
				}
```
in place of:
```

				if (filter !== false && pluginManager.hasHandler('toSource')) {
					html = pluginManager.callOnlyFirst('toSource', html, $tmp);
				}
```
Issue gets resolved.

May be author @samclarke can put some light.
