### ISSUE TITLE
Plugin system should allow hooks with multiple arguments

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3594]
The current plugin system allows you to pass a single argument to `run_hooks`. This leads to workarounds such as the following pseudo code:

```php
$args = [
'file' => &$file,
'line' => &$line,
];

$plugins->run_hooks('foo', $args);
```

I propose that we adapt `run_hooks` to be a variadic function that takes multiple arguments. We can then dispatch hooks using `call_user_func_array()` when there is more than 1 argument.

**Comment by euantorano** [comment]
Actually, I wonder if variadic functions can take arguments by ref in PHP. Based upon a quick test, it doesn't seem to be possible (eg: the syntax `... &$args` is invalid).

**Comment by veryard** [comment]
Hello,

I've tried to have a crack at this while retaining the functionality of the old methods here's what I have come up with.
/inc/class_plugins.php
`/**
	 * Returns the correct arguements (To work with older versions)
	 * @param array $arguments The argument for the hook that is run
	 * @return array The arguments for the hook.
	 */
	private function return_arguements($arguements = array())
	{
		if(count($arguements) == 1) {
			return $arguements[0];
		}

		return $arguements;
	}

	/**
	 * Run the hooks that have plugins.
	 *
	 * @param string $hook      The name of the hook that is run.
	 * @param mixed $arguments The argument for the hook that is run.
	 * @return mixed The arguments for the hook.
	 */
	function run_hooks($hook, &...$arguements) 
	{
		
		if(!isset($this->hooks[$hook]) || !is_array($this->hooks[$hook]))
		{
			if($hook == 'myalerts_activate') {
				return $arguements;
			}
			return $this->return_arguements($arguements);
		}

		$this->current_hook = $hook;
		ksort($this->hooks[$hook]);

		foreach($this->hooks[$hook] as $priority => $hooks) {
			if(is_array($hooks)) {
				foreach($hooks as $key => $hook) {
					if($hook['file']) {
						require_once $hook['file'];
					}
					if(array_key_exists('class_method', $hook))
					{
						
						$return_args = call_user_func_array($hook['class_method'], $arguements);
					}
					else
					{
						$func = $hook['function'];
						$return_args = call_user_func_array($func, $arguements);
					}

					if($return_args)
					{
						$arguements = $return_args;
					}
				}
			}
		}
		
		$this->current_hook = '';	
		return $this->return_arguements($arguements);
	}`

And to test, I created a dummy hook and tested a call against it.
`$plugins->add_hook('run_hooks_test', 'test_hook_func');

$greeting = 'hello';
$age = 50;
$plugins->run_hooks('run_hooks_test', $greeting, $age);

function test_hook_func($greeting, $age)
{
	echo $greeting . ', you are: ' . $age. ' years old';
}`

![image](https://user-images.githubusercontent.com/3941758/64077249-f70c8e00-cd00-11e9-8353-a3d303fc5b55.png)

**Comment by euantorano** [comment]
Check my closed PR which took a similar approach: https://github.com/mybb/mybb/pull/3595 - I also made some other changes

That original PR was closed due to conflicts, but I plan to open a new one this weekend or this week at the latest 😄

**Comment by veryard** [comment]
Ah my bad.

Thanks :)
