### ISSUE TITLE
class_stopforumspamchecker.php uses old API call url

### ISSUE THREAD

**Issue by VBGAMER45** [mybb/mybb#3604]
inc/class_stopforumspamchecker.php

Find All:
http://www.stopforumspam.com/api

Replace:
http://api.stopforumspam.org/api

Quote

    API queries are running at ~200ms globally, and they're geographically load balanced (thanks to @sucurilabs) to the closest API node but only if you use http://api.stopforumspam.org. API calls to http://www.stopforumspam.com will be a little slower, and they have no global fault tolerance.
Source : https://twitter.com/StopForumSpam/status/1104875246648213506

Check out
https://www.stopforumspam.com/usage

**Comment by euantorano** [comment]
Good catch, should be easy to fix. I’ll open a PR tonight.

**Comment by Eldenroot** [comment]
Or I can, I have a dayoff

**Comment by euantorano** [comment]
Sure, I won’t complain ;)
