### ISSUE TITLE
Change Usergroup & Hidden Theme Interfering

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3611]
FORUM VERSION: 1.8.19

Found this problem on another board I administrate, replicated this on a test board to see if this was an issue elsewhere.

If a theme is available to x usergroup(s) only and a user has this theme selected when you go to change their usergroup to anything that that particular theme is not available to you get the error:
Quote:The following errors were encountered:The style you selected is invalid. Please select a valid style.

If I manually change the users theme selected to a theme available to all usergroups then the error does not occur when attempting to change usergroup.

Not sure if this is intended feature but may confuse others that come across this issue as the error message is not particularly descriptive ('style' does not = 'theme' in the ACP and took me a few days to figure out the relation and solve this myself).

Original thread: [Change Usergroup & Hidden Theme Interfering](https://community.mybb.com/thread-220518.html)

**Comment by effone** [comment]
This is related:
If you force a new theme to all users which was actually admin only the theme permission remains as is but get forced to all members without problem. 
Now everytime you edit anything of any non admin account you will get invalid style error message, unless you change the applied theme to the account from forced theme to default.

Need opinion on how to handle this.

**Comment by effone** [comment]
Or may skip the validation if the form submitted style matches with already set style of the account.

@euantorano opinion?

**Comment by euantorano** [comment]
I’ll have to look at this tonight to understand the problem, remind me if you don’t hear anything please.

**Comment by effone** [comment]
Ping @euantorano 
2 approaches proposed and the decision pending at your end..

**Comment by euantorano** [comment]
Sorry, I’ve been busy with work. I’ll look tonight and respond here.

**Comment by effone** [comment]
mmmm... may be both?
