### ISSUE TITLE
Clear select2

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3613]
On member list and other pages, there is select2 for searching a user. However, after I filter a certain user, there is no option to clear the select2 and "unfilter".

Original thread: [Clear select2](https://community.mybb.com/thread-221231.html)

**Comment by effone** [comment]
We may drop secect2 eventually. The in-house replacement is ready just to wait for a spot to push in

**Comment by Ben-MyBB** [comment]
It would still be worth fixing if select2 doesn't get replaced until 1.9, imo
