### ISSUE TITLE
PHP 7 compatibility - functions_calendar.php

### ISSUE THREAD

**Issue by woostarUK** [mybb/mybb#3625]
Can someone confirm this is an error with PHP 7.2

Warning [2] count(): Parameter must be an array or an object that implements Countable - Line: 133 - File: inc/functions_calendar.php PHP 7.2.16 (Linux)

I may be wrong, but PHP 7.2 changed the way it handles the count function when variables are empty. 

I know @count() suppresses errors to screen, but my log file is getting filled.

If this is confirmed, can !empty() be added to line 133.

Proposed:
`if((!empty($events_cache["$day-$calendar_month-$calendar_year"])) && @count($events_cache["$day-$calendar_month-$calendar_year"]) > 0)`

**Comment by woostarUK** [comment]
I've not really used GitHub for anything else (other than MyBB). I tried a pull request. Did it work?

**Comment by WildcardSearch** [comment]
This seems reasonable. I'll take a look at the PR.

**Comment by dvz** [comment]
@woostarUK looks like the 2nd PR was created in a forked repository instead of this one
