### ISSUE TITLE
Admin Edit User - Missing external URL

### ISSUE THREAD

**Issue by woostarUK** [mybb/mybb#3627]
When you edit a user in admin, the avatar doesn't have the correct image path when using a CDN.

Location:
Overview and Avatar Tabs
/admin/index.php?module=user-users&action=edit&uid=1

I'm looking around line 979 admin/modules/user/users.php to add format_avatar();

Any pointers? (I'm not great at reverse engineering)

**Comment by woostarUK** [comment]
Hacked this together so my admin works, but sure someone with coding experience will do better:
https://github.com/woostarUK/mybb/blob/woostarUK-patch-1/admin/modules/user/users.php#L979-L1017

**Comment by Eldenroot** [comment]
Please push a PR with your fix into master branch
