### ISSUE TITLE
Enhancement: Add $plugins->run_hooks('global_templatelist');

### ISSUE THREAD

**Issue by woostarUK** [mybb/mybb#3628]
Please, can a hook be added on line 461 global.php

```
$templatelist .= ",header_menu_calendar,header_menu_memberlist,global_dst_detection,header_quicksearch,smilie";
$plugins->run_hooks('global_templatelist', $templatelist);
$templates->cache($db->escape_string($templatelist));
```

**Comment by euantorano** [comment]
You can already add to the template list with the `global_start` hook:

```php
global $mybb, $templatelist, $templates;
if (isset($templatelist)) {
	$templatelist .= ',';
}
$templatelist .= 'myalerts_headericon,myalerts_modal,myalerts_popup_row,myalerts_alert_row_no_alerts,myalerts_js_popup';
```

Example from here: https://github.com/MyBBStuff/MyAlerts/blob/master/inc/plugins/myalerts.php#L692

Adding a hook like this in a minor point release could get confusing for users where some new plugins use the hook and then need to target 1.8.22+, which would cause a bunch of support requests.

I'm not normally opposed to new hooks, but this one wouldn't help you do much that you can't already (except perhaps remove items from the template list, but I don't see a need for that?).

**Comment by WildcardSearch** [comment]
You don't even have to use a hook to add templates to the list:

https://github.com/WildcardSearch/MentionMe/blob/ce0dd9a71c2c0f4716ed7901e3996598f22f60a1/Upload/inc/plugins/MentionMe/forum.php#L210-L238

As you can see above, if you initialize from function scope and make `$templatelist` global, you can insert your extra templates when the plugin file is originally `require`'d.

**Comment by woostarUK** [comment]
Ahhhhhhhh. Thank you! I'm still getting used to MyBB coding style. Totally overlooked line 462 that allows you to add templates before (rather than after) the main global template list.
https://github.com/mybb/mybb/blob/feature/global.php#L462

It would be handy to deregister templates but I can wait til 1.9/Twig to do that :)

Thanks guys.
