### ISSUE TITLE
Enhancement: reCAPTCHA v3

### ISSUE THREAD

**Issue by woostarUK** [mybb/mybb#3630]
Request:
Can Google reCAPTCHA v3 be integrated, please?

**Comment by skmedix** [comment]
#3560

**Comment by woostarUK** [comment]
Ahh. Thank you. I did have a look be searched reCAPTCHA, not captcha 🤦‍♂️

**Comment by Eldenroot** [comment]
@n-thumann - arent you interested? :)

**Comment by Eldenroot** [comment]
MyBB dev - maybe we should make a decision and integrate this one sooner or later, SPAM bots are not good and they are smarter and smarter.

**Comment by PaulBender** [comment]
Probably worth adding

**Comment by euantorano** [comment]
Yes, and shouldn’t be too difficult.

**Comment by Sama34** [comment]
If I understand correctly  v3 can be used to monitor different user inputs, like posts or private messages, from both guests and members.

Since we only use captcha for guests that would mean our implementation will be limited to them, is that correct?

**Comment by Eldenroot** [comment]
If I understood correctly, yes I think so.

**Comment by Eldenroot** [comment]
As i see recaptha V3 was added to phpBB right now - https://github.com/phpbb/phpbb/commit/a43cdbac54bb9f681fe9ce8e773de7c3866d9ea4

**Comment by euantorano** [comment]
Yes, it makes sense to implement it so I'm not surprised to see them doing so.

**Comment by yuliu** [comment]
Don't know if this is an issue related to v3: https://community.mybb.com/thread-227752.html .

OP in the thread said:

Hi there,

I'm getting reports that users are receiving the error "Please solve the reCAPTCHA to verify that you're not a robot." when trying to reset their passwords after I upgraded the CAPTCHA system to Google's new Invisible reCAPTCHA. The registration page works fine.

I searched Google and found this thread and checked my templates to see if they had the name="submit" fix, which they do.

Does anyone have any other ideas? Much appreciated!

Ed.

**Comment by Eldenroot** [comment]
There are PRs for this issue with password reset, not?

**Comment by yuliu** [comment]
> There are PRs for this issue with password reset, not?

Seems related to v3. There's [another report in Discord](https://discordapp.com/channels/215876847634743296/215877079911104522/710633336766332929) and the user seems to be using the latest v3.

I haven't used reCaptcha/noCaptcha. Is there any problem with them (should be v2/v1?)?

**Comment by Eldenroot** [comment]
@PaulBender - please can you check the latest report from @yuliu 2 posts aboveM THX!
