### ISSUE TITLE
browse plugin page in admin cp is not parsing special characters correctly

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#3642]
in the browse plugin page in the admin cp, mybb is not parsing special characters correctly.

to duplicate, visit this page in your admin cp: https://yoursite.com/admin/index.php?mod...ion=browse

![2019-04-26 16_23_38](https://user-images.githubusercontent.com/2748980/56834663-07d36180-6840-11e9-90bc-81264949da48.png)

this is what it should look like:

Thank You/Like System+MyAlerts &amp; Tapatalk support

Original thread: [browse plugin page in admin cp is not parsing special characters correctly](https://community.mybb.com/thread-222826.html)

**Comment by euantorano** [comment]
Looking at this, it seems like the easiest way to fix this may be at the mybb.com level rather than in the MyBB software. I'll investigate this further.

**Comment by dvz** [comment]
Resolved at `mybb.com`.
