### ISSUE TITLE
SQL Error on Post Update With Removed Attachment

### ISSUE THREAD

**Issue by kawaii** [mybb/mybb#3656]
```
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
0 - ERROR: invalid input syntax for integer: "" LINE 3: WHERE aid='' ^
Query:
DELETE FROM mybb_attachments WHERE aid=''
```
Software:
- MyBB 1.8.20
- PostgreSQL 11.2

Steps to reproduce issue:
- Add an attachment to a post and publish the post
- Edit the post, remove the attachment and save the updated post

**Comment by euantorano** [comment]
Seems this was caused by our changes to use AJAX to handle attachments, which means when we come to call `remove_attachment()` in `editpost.php` on submitting the form, the attachment is actually already deleted. I'm adding a check for the query returning 0 rows to handle this.
