### ISSUE TITLE
Incorrect "continue" usage in Delayed Moderation Task

### ISSUE THREAD

**Issue by aasjpvm** [mybb/mybb#3665]
PHP marc as warning the continue statement in the lines 112, 172, 178
The solution I applied for this was set a flag variable and replace that continue with break and validate on switch exit if flag are true execute continue to exclude the delete_query statement like actually

https://github.com/mybb/mybb/blob/96f00ab3c1769440557004fc8b3728e0f57281b2/inc/tasks/delayedmoderation.php#L112
https://github.com/mybb/mybb/blob/96f00ab3c1769440557004fc8b3728e0f57281b2/inc/tasks/delayedmoderation.php#L172
https://github.com/mybb/mybb/blob/96f00ab3c1769440557004fc8b3728e0f57281b2/inc/tasks/delayedmoderation.php#L178

**Comment by Eldenroot** [comment]
Feel free to open a PR with a fix.

**Comment by aasjpvm** [comment]
Sorry @Eldenroot I don't know how to do it, I not use much github, but today I see that it will be fixed in  1.8.22
