### ISSUE TITLE
Membership List(s): Last Visit / Active time may be incorrect

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3669]
The Last Visit / Last Active time may be incorrect and shown as "1 minute ago" for users who have registered but then never logged in.

MyBB Version 1.8.20 
PHP Version 7.1.28
SQL Engine MySQLi 5.6.43

Suggested fixes:
In users.php
at line 3583
// $user['view']['lastactive'] = my_date('relative', $user['lastactive']); (LFG) 04-16-2019
 if($user['lastactive'])
{
$user['view']['lastactive'] = my_date('relative', $user['lastactive']);
}
else
{
$user['view']['lastactive'] = $lang-&gt;never;
}
In memberlist.php
at line 486
if($user['invisible'] == 1 &amp;&amp; $mybb-&gt;usergroup['canviewwolinvis'] != 1 &amp;&amp; $user['uid'] != $mybb-&gt;user['uid'])
 {
 $user['lastvisit'] = $lang-&gt;lastvisit_never;

 if($user['lastvisit'])
 {
 // We have had at least some active time, hide it instead
 $user['lastvisit'] = $lang-&gt;lastvisit_hidden;
 }
 }
 else
 {
 if($user['lastvisit'])
 {
 $user['lastvisit'] = my_date('relative', $user['lastactive']);
 }
 else
 {
 $user['lastvisit'] = $lang-&gt;lastvisit_never;
 }
 }

Original thread: [Membership List(s): Last Visit / Active time may be incorrect](https://community.mybb.com/thread-222691.html)

**Comment by effone** [comment]
I don't know how this happens at the first place as the issue only triggers when the `lastactive` and / or `lastvisit` field is empty. However; those fields get filled immediately after creation of user with `regdate` value.

But, as this somehow has encountered (don't know how) I can just address this using the nearest available value.

Well, I'd like to mention here with another issue. If you create a user from ACP, as stated above the `lastactive` and `lastvisit` fields get filled which is completely wrong as the user is not visited at all.

**Comment by effone** [comment]
And this looks completely wrong to me:
https://github.com/mybb/mybb/blob/feature/memberlist.php#L490

You are overriding the value with `Never` lang.
After that you are checking if its set (its obviously set, you just set it, no matter what it was before) then overriding with `Hidden` lang. So, never never happens.
