### ISSUE TITLE
Editing posts with JS disabled to manage attachments

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3675]
There are some issues when editing posts with JS disabled and trying to manage attachments. First, the code refers to an input called `submit`, which never appears on the page as far as I can tell (it's called `submitbutton` instead):

```php
	if(!isset($mybb->input['submit']))
	{
		$mybb->input['action'] = "editpost";
	}
```

This means that if you disable JS and try to remove an attachment, you simply get redirected to the thread without the attachment being removed.

**Comment by euantorano** [comment]
I'm wondering if this has ever worked at all. Looking at the code, we're looking for the attachment ID to be set, and the attachment action. Without JS, I'm not sure how we would be setting both at the same time when clicking the "remove" button for a given attachment.

Looking at the blame, this particular block of code hasn't been touched for 5 years: https://github.com/mybb/mybb/blame/feature/editpost.php#L229

Any chance you could try editing a post to remove an attachment with JS disabled on an older MyBB version @kawaii?

IMO, it would make sense to make the attachment management rows into separate forms rather than being part of the main form, but I'm not sure how much stuff this will break...

I'm tempted to postpone this to 1.8.22 as it's looking like it might be a bit of a headache.

**Comment by effone** [comment]
I want to look into in too, may be I can come up with a solution.
So, postponing it to 1.8.22 is a good idea. No point making an attempt that actually doesn't solve the root issue.

**Comment by euantorano** [comment]
That would be great @effone. 

I agree, I will change the milestone. 

It might be good to have a look around the rest of the software and find any other bits broken with JS disabled.
