### ISSUE TITLE
SQL Error When Viewing Unread PMs

### ISSUE THREAD

**Issue by kawaii** [mybb/mybb#3676]
```
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
0 - ERROR: column "0" does not exist LINE 5: WHERE pm.folder='1' AND pm.uid='1' AND pm.status="0" ^
Query:
SELECT pm.*, fu.username AS fromusername, tu.username as tousername FROM mybb_privatemessages pm LEFT JOIN mybb_users fu ON (fu.uid=pm.fromid) LEFT JOIN mybb_users tu ON (tu.uid=pm.toid) WHERE pm.folder='1' AND pm.uid='1' AND pm.status="0" ORDER BY pm.dateline desc LIMIT 20 OFFSET 0
```
When using MyBB 1.8.20 and PostgreSQL 11.3, the following error is thrown when attempting to view the 'Unread' folder of your private messages. I will also note #3666 as a similar issue, interesting that for such a core function this problem had seemingly not been found already.

**Comment by dvz** [comment]
https://github.com/mybb/mybb/blame/mybb_1820/private.php#L2249 via https://github.com/mybb/mybb/pull/3515

**Comment by euantorano** [comment]
This is an easy fix, I’ll make a PR tonight.
