### ISSUE TITLE
"Additional Contact Information" should be reworked.

### ISSUE THREAD

**Issue by send-your-nudes** [mybb/mybb#3695]
The problem is that some of the fields are old and need upgrading

1. Google Hangouts will be discontinued around 2020.
2. Yahoo Messenger is discontinued
3. ICQ is an old school along with Skype.

Now how to improve it:
Like kawaii or someone mentioned new standards are coming.
Maybe include fields such as:
Instagram, Facebook, Discord, Steam, Whatsapp, Viber, or anything you see as appropriate.

I think this shouldn' take much of the time.

**Comment by Eldenroot** [comment]
All suggestion and bug reports should be placed on MyBB community board, not here.

@euantorano please close this one.

**Comment by euantorano** [comment]
The plan is that there won’t be any built in contact fields, there will instead be some pre-set custom profile fields for contact fields. I believe this might already be implemented in 1.9.

**Comment by euantorano** [comment]
@eldenroot we’re not too bothered about forcing people to use the forums anymore, so long as people don’t start using GitHub to post support questions that just confuse things.

**Comment by Sick1G** [comment]
This is related to 1.8, if so, can we have it removed then?

PS: For me, posting enhancements looks way clearer here somehow.

**Comment by effone** [comment]
I have seen discussions before that additional contact informations will be removed altogether to make use with custom profile fields; however I'd prefer an additional contact module which will be validated through Oauth before adding the field to profile. This data can further be used for core social login feature.

**Comment by Sick1G** [comment]
Would that be for 1.8?

**Comment by effone** [comment]
Ofcourse its possible even for 1.8 but I doubt such huge feature will be allowed in 1.8 branch.
..... or, will be accepted at all.

**Comment by euantorano** [comment]
I’d definitely prefer a big change like that for 1.9 rather than 1.8
