### ISSUE TITLE
Case sensitivity in English (Mark forum read)

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3702]
There is an irregular case sensitivity in language "English (American)".

forumdisplay.lang.php &gt; markforum_read:
"Mark this forum read"

global.lang.php &gt; bottomlinks_markread:
"Mark All Forums Read"

Better keep pervasive lower case to harmonise.
Maybe there are more case sensitivity issues on other lang-records worth to seek out.

[ExiTuS]

Original thread: [Case sensitivity in English (Mark forum read)](https://community.mybb.com/thread-223334.html)

**Comment by Eldenroot** [comment]
It is not a bug, there are a lot of places where case sensitivity should be changed and normalized. Lets discuss what way to choose and then I can create a PR to fix all of these.
