### ISSUE TITLE
Missing files in mybb_1821.tar.gz

### ISSUE THREAD

**Issue by joneum** [mybb/mybb#3717]
Pls restore the /inc/settings.php and /inc/config.default.php in mybb_1821.tar.gz

**Comment by effone** [comment]
Please download the latest build. Read the note before you download.
https://github.com/mybb/mybb/releases
https://mybb.com/download/

**Comment by joneum** [comment]
the 2 files are not in the current tar.gz

**Comment by dvz** [comment]
GH-provided archives for `mybb_1821` were not corrected, but try the ones from this tag: https://github.com/mybb/mybb/releases/tag/mybb_1821pl1
