### ISSUE TITLE
Change video default link value "http://" to placeholder

### ISSUE THREAD

**Issue by MinusPL** [mybb/mybb#3721]
I think that default value "http://" for links in video dropdown in editor is making some problems, because when we copy link with http already in it will add another one in front of original link and break it.

It would be better to change in dropdown value to placeholder with same value. This way we still have information that this is field for links, but we don't get duplicated http protocol in front of our link.

**Comment by Eldenroot** [comment]
+1

**Comment by WildcardSearch** [comment]
@MinusPL 

I'm against using the placeholder for this, as the intended purpose is to provide instructions for acceptable input, ***not*** to show something irrelevant to the process.

If you want to replace the `placeholder` attribute, replace it with `paste URL here` or something that fits the purpose of that attribute.

**Comment by MinusPL** [comment]
@WildcardSearch your idea seems good.
But to make things clearer we should also change then other things like: adding image or link.
In both cases it uses placeholder with only "http://".

You're right that placeholder is to show some kind of instructions or example data that is not actually set to the fiield as it's value.

**Comment by WildcardSearch** [comment]
@MinusPL I agree, other inputs will need to be fixed, but for this one issue, lets just make it right and we can create separate issue(s) to fix any others that are wrong.

**Comment by MinusPL** [comment]
Seems good 👍
