### ISSUE TITLE
Plugins hooks in forum display

### ISSUE THREAD

**Issue by chack1172** [mybb/mybb#3724]
I think I new hook should be added in forumdisplay.php after the $threadcache and $tids are defined.
This will help making only one new query to the database if extra data is needed for a plugin.
Otherwise they should run one extra query for each thread displayed.

**Comment by Eldenroot** [comment]
@chack1172 - could you please open a PR for that?

**Comment by veryard** [comment]
I'm not 100% sure if this is correct, a bit more detail would help, if someone can check see if this is okay.

Thanks

**Comment by PaulBender** [comment]
Since this issue has come up, there is one hook I want to add to forumdisplay.php, just above the eval for $threadslist. I'm making a PR for that right now.

**Comment by Eldenroot** [comment]
@veryard where is your PR? If you have any issues, let me know and I will help you

**Comment by Eldenroot** [comment]
@PaulBender and @chack1172 - are you willing to create a PR for the first part of this issue? Thank you

**Comment by veryard** [comment]
@Eldenroot Looks like I made a commit to my fork rather than a PR.

https://github.com/veryard/mybb/commit/149d4329cdc5631ee319a12a8efb09692aad788e
