### ISSUE TITLE
Incorrect Password in MyBB 1.9

### ISSUE THREAD

**Issue by ks129** [mybb/mybb#3732]
After installing MyBB 1.9, I can't login into Admin account. This say in front-end and in back-end of forum: Incorrect Password. But I know exactly, what I added to password and I installed one more time, but same thing.

**Comment by dvz** [comment]
This may be related: https://github.com/mybb/mybb/pull/3705

**Comment by ks129** [comment]
Sorry, now fixed. GitHub download didn't downloaded all files and because this I can't access. Now fixed and may be closed.
