### ISSUE TITLE
Private messsages not shown after moving them into the "Inbox" folder

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#3733]
I see  there's been a change in the private message folders since version 1820 with commit [# 8e26c5b](https://github.com/mybb/mybb/commit/8e26c5bbe69ae736fe6044021bf212da6f8fd88f#diff-3dc0b085bc730d898e3b650e05355834) which reads:

> // Old folder structure. Need to update
> // Since MyBB 1.8.20 fid[0] represents 'Inbox' and fid[1] represents 'Unread'

It seems it's a feature update that would be allowing more functions on private message, but I quite don't get the idea. However, there will be a problem of showing private messages if they've been moved into the "Inbox" folder. Although neither the template nor the script denies a user to do so, the `private.php` script surely denies users from visiting their "Inbox" folder whose ID is 0:

`$folder = !$fid ? 1 : $fid;`

The only way for them to get back these moved messages is to search their messages with some string sequences in the messages subjects, if they could remember any.

I don't get the clear idea of making the "Inbox" folder kind of obsolete. Just having an ID for the "Inbox" folder and read messages still reside in a folder with ID=1, the "Unread" folder. I'm not sure if I make this issue clear, I do has this problem in my MyBB installation. Also, without knowing the purpose of doing so, I really can't patch the code.

It's my first time contributing to MyBB :)

**Comment by Eldenroot** [comment]
I can reproduce :(

**Comment by Eldenroot** [comment]
@effone ah, another PMs box related :(
