### ISSUE TITLE
Moderator options on Profile Management fail to get saved

### ISSUE THREAD

**Issue by demtor** [mybb/mybb#3736]
Moderator options (suspend signature, suspend/moderate posting) on Profile Management fail to get saved.

**Comment by effone** [comment]
Which field is failing to get saved? I can't find any.
Also the suggested fix is not correct. Please review.

**Comment by demtor** [comment]
Those of the `$moderator_options` array (suspend signature, suspend/moderate posting).

`if(!is_array($errors))` refers just to `$errors[] = $lang->$string;`, there is no need to check the whole `$errors` var. It can be replaced with `if(!$errors)` or `if(empty($errors))` but I do not see the need, feel free to fix it as you prefer.

**Comment by effone** [comment]
https://github.com/mybb/mybb/pull/3714/files
