### ISSUE TITLE
New hook in newreply.php page for lastposts view

### ISSUE THREAD

**Issue by jakubwilk** [mybb/mybb#3745]
There is no hook in Mybb docs for management content in lastposts section in newreply.php

![screenshot-www mageguildwars pl-2019 07 01-00-25-24](https://user-images.githubusercontent.com/16987072/60402971-4286ac80-9b97-11e9-8dfe-a4839cd1bdde.png)

In my plugin I need to modify content of posts in this section, but I don't see any way to do it. All **newreply_** hooks don't work.

It will be grateful if someone could confirm if I have right and devteam change it in future.

**Comment by euantorano** [comment]
This does look like it could be a good place to add a hook. I'd probably sugegst adding it before the parser is run: https://github.com/mybb/mybb/blob/feature/newreply.php#L1287

**Comment by Eldenroot** [comment]
+1, @jakubwilk will you open a PR?
