### ISSUE TITLE
White Forum Page After Creating New Thread in MyBB 1.9

### ISSUE THREAD

**Issue by ks129** [mybb/mybb#3751]
After I create new thread and want return to forum in MyBB 1.9, I get white page. Forum page show correctly, when there isn't any thread, but after creating is there just white page. I can't give more information, because MyBB didn't fill error_log (I enable this in ACP).

**Comment by euantorano** [comment]
Can you turn on PHO’s error reporting settings in PHP.ini or check your web server logs? Hopefully an error should be shown/logged. 

Failing that, I’ll do some testing this weekend to track down the issue.

**Comment by ks129** [comment]
@euantorano Here is error:
`Fatal error: Uncaught Twig\Error\SyntaxError: Unexpected token "operator" of value "=" ("end of statement block" expected). in /var/www/html/inc/views/base/forumdisplay/thread.twig:5 Stack trace: #0 /var/www/html/inc/vendor/twig/twig/src/TokenParser/IfTokenParser.php(38): Twig\TokenStream->expect(3) #1 /var/www/html/inc/vendor/twig/twig/src/Parser.php(185): Twig\TokenParser\IfTokenParser->parse(Object(Twig\Token)) #2 /var/www/html/inc/vendor/twig/twig/src/Parser.php(98): Twig\Parser->subparse(NULL, false) #3 /var/www/html/inc/vendor/twig/twig/src/Environment.php(569): Twig\Parser->parse(Object(Twig\TokenStream)) #4 /var/www/html/inc/vendor/twig/twig/src/Environment.php(601): Twig\Environment->parse(Object(Twig\TokenStream)) #5 /var/www/html/inc/vendor/twig/twig/src/Environment.php(408): Twig\Environment->compileSource(Object(Twig\Source)) #6 /var/www/html/inc/vendor/twig/twig/src/Environment.php(382): Twig\Environment->loadClass('__TwigTemplate_...', 'forumdisplay/th...', NULL) #7 /var/www/html/inc/vendor/twig/twig/src/Te in /var/www/html/inc/views/base/forumdisplay/thread.twig on line 5`

**Comment by ks129** [comment]
CLOSED. I didn't added latest Twig update.

**Comment by euantorano** [comment]
Aha! That’s probably an easy fix, I’ll push one tonight. Thanks for investigating! :smile:
