### ISSUE TITLE
ICQ Number/Yahoo ID/Skype ID/Google Hangouts ID can exceed database field

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3753]
The values of ICQ Number, Yahoo ID, Skype ID and Google Hangouts ID are not validated (beside casting ICQ to integer) so you can easily exceed the length of the associated database fields:
Quote:SQL Error: 1406 - Data too long for column 'yahoo' at row 1

Original thread: [ICQ Number/Yahoo ID/Skype ID/Google Hangouts ID can exceed database field](https://community.mybb.com/thread-223686.html)

**Comment by Eldenroot** [comment]
This can be solved together with #3781

**Comment by Ben-MyBB** [comment]
Seems there is a feature to limit new custom profile fields so this will only apply to the default ones. I plan on taking a look at this.

**Comment by Eldenroot** [comment]
@Ben-MyBB you are on fire 🔥 👍
