### ISSUE TITLE
Upload paths inaccuracy

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3754]
Upload paths should support both forms, absolute and "relative" paths (if ./ is specified, you point the start of the path to MYBB_ROOT), as admin/modules/tools/system_health.php already does.

For example, on admin/modules/forum/attachments.php#L235, absolute paths would not be supported.

Or, the whole inc/functions_upload.php considers the admin directory one level up from MYBB_ROOT (what if I specify the admin directory two level ups?).

Not specifying MYBB_ROOT on upload paths (as function_upload does) could bring to unexpected behaviours (error due to the execution of tasks using cron, where $_SERVER['DOCUMENT_ROOT'] is not set):

&lt;error&gt;
    &lt;dateline&gt;1560304831&lt;/dateline&gt;
    &lt;script&gt;inc/functions_upload.php&lt;/script&gt;
    &lt;line&gt;160&lt;/line&gt;
    &lt;type&gt;2&lt;/type&gt;
    &lt;friendly_type&gt;Warning&lt;/friendly_type&gt;
    &lt;message&gt;opendir(./uploads/avatars): failed to open dir: No such file or directory&lt;/message&gt;
    &lt;back_trace&gt;#0  errorHandler-&gt;log_error(2, opendir(./uploads/avatars): failed to open dir: No such file or directory, inc/functions_upload.php, 160) called at [/***/inc/class_error.php:189]
#1  errorHandler-&gt;error(2, opendir(./uploads/avatars): failed to open dir: No such file or directory, inc/functions_upload.php
#2  opendir(./uploads/avatars) called at [/***/inc/functions_upload.php:160]
#3  remove_avatars(121577895) called at [/***/inc/datahandlers/user.php:1668]
#4  UserDataHandler-&gt;delete_content() called at [/***/inc/datahandlers/user.php:1536]
#5  UserDataHandler-&gt;delete_user(Array ([121577414] =&gt;

Original thread: [Upload paths inaccuracy](https://community.mybb.com/thread-223408.html)

**Comment by demtor** [comment]
A very temporary and specific fix for the following error, for who is using cron to run tasks:
in `inc/functions_upload.php` search in the `remove_avatars` function:
```php
if(defined('IN_ADMINCP'))
{
	$avatarpath = '../'.$mybb->settings['avataruploadpath'];
}
else
{
	$avatarpath = $mybb->settings['avataruploadpath'];
}
```
and replace with:
```php
if(defined('IN_TASK'))
{
    $avatarpath = MYBB_ROOT.$mybb->settings['avataruploadpath'];
}
elseif(defined('IN_ADMINCP'))
{
    $avatarpath = '../'.$mybb->settings['avataruploadpath'];
}
else
{
    $avatarpath = $mybb->settings['avataruploadpath'];
}
```
Back to the problem, before making the upload paths support both forms, uploaded avatars type of storage needs to be edited. Currently uploaded avatars are stored in the database in their full location (the upload path is included). Specifying an absolute upload path, bring to store the whole absolute upload path in the avatar column (error in showing the avatar and leak of www location).
