### ISSUE TITLE
Lost 'forum' query field during multipaging in AdminCP>Forum>Attachments>Find Attachments

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#3757]
Sorry for mistakenly submit the initial issue. My bad.

Here comes the problem. In the AdminCP > Forums & Posts > Attachments > Find Attachments, if a query is issued with forums selected, and the returned records are multipaged, the link of any page doesn't include a `&forum[]=` string in any subsequent GET request. Thus, all the following paging results are attachments queried in the board scope.

A quick fix is applicable. Should I post a diff first or pull a request after it's been confirmed?

**Comment by euantorano** [comment]
A PR would be most welcome, no need to wait for confirmation. I will test and confirm later then merge any PR :smile:

**Comment by yuliu** [comment]
> 
> A PR would be most welcome, no need to wait for confirmation. I will test and confirm later then merge any PR 😄
> […](#)
> On 25 Jul 2019, at 17:08, yuliu ***@***.***> wrote: — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thanks. I've made a PR. I think the paging links will work all right now. However, the URL will become longer or exceed the permitted length if multiple forums is selected in a query. The best way may be using a POST form, IMHO, since an explicit URL is pointless in the Admin area.

**Comment by yuliu** [comment]
@euantorano, I figure out a better version to fix this, a shorter URL with more code base changes, but still using GET request. Please wait for another PR and have a check with it against the previous one before any possible merge.

**Comment by euantorano** [comment]
Great, thanks. I’ll check later.
