### ISSUE TITLE
Purging guest sessions by IP address may invalidate anti-CSRF tokens between requests

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#3762]
The _Authorization code mismatch_ error, in addition to misconfiguration and outdated templates, can occur as a result of IP address collision between multiple users or user agents when logged out.

The CSRF prevention token generation was [changed](https://github.com/mybb/mybb/commit/84a8c1ac65dabea0985f70b68f8ed728f3a1ad4d#diff-7fe6e55397c77ab9a0f5d57bc4cbe5b9R627) in [MyBB 1.8.20](https://mybb.com/versions/1.8.20/) to rely on the session system (that involves IP addresses for guest users) instead of useragent strings.

Related: https://community.mybb.com/thread-223598-post-1331592.html#pid1331592

**Comment by yuliu** [comment]
In addition, the purge of sessions by IP is not limited to guest sessions. Active sessions of registered users will be all deleted from the `sessions` table, when a guest session is created and if they have an identical IP address recognized by MyBB (behind a NAT with a limited number of outbound IPs or serving MyBB through misconfigured http/cache/lb servers). The `load_guest()` function in the session class uses [`create_session()`](https://github.com/mybb/mybb/blob/84a63e2100af227af62dc23b45f84def5f1f003e/inc/class_session.php#L381) indiscriminately, in which [active sessions are purged by IP regardless who they are](https://github.com/mybb/mybb/blob/84a63e2100af227af62dc23b45f84def5f1f003e/inc/class_session.php#L509) if the user who is creating a new session is neither a registered nor a bot.

Seems no severe security problems by now, investigated by @dvz. But troubles do exist, see his posted link.
