### ISSUE TITLE
Missing improvement of `attach_quota` in editpost

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#3764]
It's a low priority problem.

See user's attachment quota `attach_quota` set up here in [editpost](https://github.com/mybb/mybb/blob/44fc01f723b122be1bc8daaca324e29b690901d6/editpost.php#L651) has 2 parameters, but in [newthread](https://github.com/mybb/mybb/blob/4ba89def36712d77abdd4d6fb34047139c224050/newthread.php#L966) and [newreply](https://github.com/mybb/mybb/blob/6ce374f5ea7dd3520afd83db2fb3c1aaf6ecacbf/newreply.php#L1115) there's only one. See also the latest language file for English in [global.lang](https://github.com/mybb/mybb/blob/9001292c4186a498d973c369cccdf18420f7f2eb/inc/languages/english/global.lang.php#L383), it accepts only one parameter.

It might be in [this commit](https://github.com/mybb/mybb/commit/cb5ce8ccc5a0a5b87b5fedbd32393682bd0ea5cb), `editpost` is left behind, see also #2067.

**Comment by Eldenroot** [comment]
Feel free to open a PR or contact me. It seems to be a reasonable report. Thank you

**Comment by yuliu** [comment]
I've committed one. Please also take a look at the theme changes.
