### ISSUE TITLE
Ambiguous time in online_today page

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#3766]
This could be a minor improvement.

As I understand, the Who Was Online Today page displays users who have visited the forum within past 24 hours. The output time for each user is formatted using `my_date()` function taking `$mybb->settings['timeformat']` as `$format`. Then regardless of timezone, a user's last visit time will be displayed as it's a today's time, even if it's yesterday. Those times are beyond now and then we know they're yesterday, this is not intuitive to users.

For `$format` in `my_date()`, `relative` will be OK ~~just as the most recent online users does~~, or `normal` will directly show a time with a today/yesterday prefix.

**Comment by Eldenroot** [comment]
It displays users for set period in ACP. Anyway why not, in some circumstances... Feel free to open a PR. :)

**Comment by yuliu** [comment]
Wuhh, not the [who's online](https://community.mybb.com/online.php) page, but [today's online](https://community.mybb.com/online.php?action=today) page. The threshold for displaying users who were online today is [24 hours](https://github.com/mybb/mybb/blob/84a63e2100af227af62dc23b45f84def5f1f003e/online.php#L40).

**Comment by Eldenroot** [comment]
Oh I am srry, you are right

**Comment by yuliu** [comment]
> It displays users for set period in ACP. Anyway why not, **in some circumstances**... Feel free to open a PR. :)

Yes, rare but we may see that if we're crossing midnight in our timezone.

**Comment by WildcardSearch** [comment]
Seems reasonable.
