### ISSUE TITLE
add another variable with a unique style

### ISSUE THREAD

**Issue by Javierj12** [mybb/mybb#3771]
**calendar**
template: calendar_weekrow_day

There is a variable ({$day_class}) which shows 3 styles which are (.trow1, .trow2 and .trow_sep), I ask for a unique variable for the style .trow_sep, which indicates the current day we are on the calendar EXAMPLE:

![image](https://user-images.githubusercontent.com/53314750/63063608-54b07600-becb-11e9-8e90-bc296973cdff.png)

Here's the problem (at least for me, I don't know if there is another solution), I don't want to use the trow1 and trwo2 styles for "x" reason and I just want to use the trow_sep style. But it won't be possible because it will always give me all three styles

Will there be another solution to what I ask? regards

**Comment by euantorano** [comment]
So basically you want a new variable which indicates whether the `calendar_weekrow_day` is today, and if so has the value `trow_sep`? That sounds sensible to me and shouldn't be much effort.

**Comment by Javierj12** [comment]
Hello euantorano `trow_sep` change the color indicating the day, example 15, I just want a variable for` trow_sep`, I think that's what you say.

I  use a translator I am Spanish speaking, so I do not understand much and it may be that I explained badly

**Comment by Javierj12** [comment]
I also want to notify that the `calendar_mini_weekrow_day` template also uses the style `{$day_class}`

**Comment by yuliu** [comment]
> Here's the problem (at least for me, I don't know if there is another solution), I don't want to use the trow1 and trwo2 styles for "x" reason and I just want to use the trow_sep style. But it won't be possible because it will always give me all three styles

So, you just want the `trow_sep` style for highlight today's cell in the calendar, but don't want to differential day cells of current displayed month from those cells of its previous month or next month, if any. Do I understand you correctly? @Javierj12, if this is what you mean, you may override the styles through CSS, by adding an `id` attribute to the calendar table and override styles through `#id .trow1` and `#id .trow2`.

> So basically you want a new variable which indicates whether the `calendar_weekrow_day` is today, and if so has the value `trow_sep`? That sounds sensible to me and shouldn't be much effort.

The classes for `current day`, `day in current month` and `day not in current month` are hardcoded as `trow_sep`, `trow2` and `trow1`, respectively. I understand `trow_sep` as it's just indicating today. @euantorano, do you mean a row of cells, actually a `<tr>`, highlighting a week in which today is, by `calendar_weekrow_day` or `calendar_weekrow_today`?

**Comment by Javierj12** [comment]
So this was forgotten?

**Comment by euantorano** [comment]
No, not forgotten. We just haven’t yet implemented this change.

**Comment by Ben-MyBB** [comment]
@Javierj12 if you still require this I have created an inital PR which I hope to have finished this week.
