### ISSUE TITLE
Thread Mode Selector

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3791]
Thread mode selector creates a dropdown to select mode. But...
- Why a selector is needed when there are only 2 options? Can be direct link based on set mode.
- The selector is driven by js and there is no fallback. The tool simply fails if the js is disabled.
- The selector trigger is bound to xmlhttp setting whereas it doesn't do any AJAX call.
- Unnecessary js functionality and js inclusion in template.

**Comment by Eldenroot** [comment]
I agree, I removed the thread more selector in all my themes. But it is a legacy feature so maybe it worth to change it for 1.8.x at least.

**Comment by effone** [comment]
I didn't mean to remove it, but to simplify it, when there are only 2 options with one in place we can just ask for the other, like thread subscribe / unsubscribe...
