### ISSUE TITLE
Update Twig version

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3798]
We're currently using Twig 2.4, while the current release is 2.11.3. We should update to the current release.

See the release notes for fixes and improvements in recent releases: https://github.com/mybb/mybb/issues/new

**Comment by yuliu** [comment]
Wrong link.

Besides, seems current composer.lock file leads to require PHP 7.1.0 at minimum, but in Wiki it says require PHP 7.0 or new, although it doesn't matter much.

**Comment by euantorano** [comment]
Yeah, the Wiki needs updating. PHP 7.0 is no longer supported by the PHP team, so we don't want to target an outdated version: https://www.php.net/supported-versions.php
