### ISSUE TITLE
Allow "action=do_search" to accept GET request_method

### ISSUE THREAD

**Issue by woostarUK** [mybb/mybb#3806]
Ref: https://schema.org/SearchAction
To use SearchAction it requires using a direct URL. Can we let search.php use the GET method?

https://github.com/mybb/mybb/blob/91ec04f52bec6b65e4086017dcae7bb1c5a052cc/search.php#L1541

W.>

**Comment by veryard** [comment]
Agreed, we'd need to update all search forms aswell.

**Comment by euantorano** [comment]
I don't see why not, would make sense to me.

If we just remove the check for `$mybb->request_method`, it should work for both GET and POST - we'd still update base templates, but that way there should be no broken 3rd party themes.
