### ISSUE TITLE
error: Attachment file name is too long

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3820]
When uploading an attachment, if the filename is longer than the field length, I get an error. This can happen if the filename details photo content.
Quote:SQL Error: 1406 - Data too long for column 'filename' at row 1
Query: 
                        INSERT
                        INTO mybb_attachments (pid,posthash,uid,filename,filetype,filesize,attachname,downloads,dateuploaded,thumbnail,visible)
                        VALUES (0,'82308f13b0ceb97b6b3d8988ef3af7a2','262','Marlene Dietrich, Jean Harlow, Joan Blondell (looking bored unknown ( Elizabeth Allan), Edward G. Robinson, and Dolores del Rio..jpg','image/jpeg',80341,'201910/post_262_1571487304_daacdaa987c4bdbfdf717ea2d58b462c.attach',0,1571487304,'201910/post_262_1571487304_daacdaa987c4bdbfdf717ea2d58b462c_thumb.jpg',1)

Error is backtraced to /inc/functions_upload.php line 764.

I have increased field length in table mybb_attachments / filename from varchar(120) to varchar(200). I hope this does not have unintended consequences. This option is better than allowing the field to be truncated by dropping STRICT_TRANS_TABLES from sql-mode.

However, a better solution would be validation of the filename length and generating an error message similar to what I would get if filesize is too great.

Would this work? Please suggest corrections to syntax.

438      // Check the filename length
439      if(strlen($attachment['filename']) &gt; 120 != &quot;&quot;)
440      {
441          $ret['error'] = $lang-&gt;sprintf($lang-&gt;error_filenamelength, htmlspecialchars_uni($attachment['name']), &quot;120&quot;);
442          return $ret;
443      }

It should be obvious I'm attempting to modify an existing portion of code, and it should *really* be obvious I am not experienced. But I am always willing to learn. :)

Where would I insert the new error message?

Original thread: [error: Attachment file name is too long](https://community.mybb.com/thread-225080.html)

**Comment by yuliu** [comment]
Increase the column length should be the best one for me. See filename length limits in different OSes: https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations (WTF is Smart File System doing??)

According to https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits , some counts by byte, some by character.

**Comment by euantorano** [comment]
I would agree with increasing the column length, seems like the best option to me.
