### ISSUE TITLE
"Access Own Unapproved Threads / Posts" breaks thread filters & pagination

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#3829]
The `showownunapproved` setting-dependent thread visibility condition (#3493) breaks the `AND`/`OR` logic in https://github.com/mybb/mybb/blob/mybb_1821/forumdisplay.php#L859, causing additional thread filtering (prefixes, dates) to be ignored when the setting is enabled.
Additionally, the visibility condition for own threads is absent in https://github.com/mybb/mybb/blob/mybb_1821/forumdisplay.php#L615, which may result in incorrect page (thread) count when the setting is enabled.

reported by @Eldenroot, @yuliu

**Comment by Eldenroot** [comment]
Thank you! Thx @yuliu for help!
