### ISSUE TITLE
Hide board, but show member profiles for guests?

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3832]
Is this possible to do? I have can view board unchecked, and view profiles checked, but it seems like guests usegroup still can not see member profiles. Is there a work around for it? 

I am not looking to make a new usergroup as it has to be the Guest usergroup

Original thread: [Hide board, but show member profiles for guests?](https://community.mybb.com/thread-225412.html)

**Comment by Ben-MyBB** [comment]
Seems the "Can view board" permission overrides 
"Can view threads"
"Can search forums"
"Can view user profiles"

**Comment by euantorano** [comment]
I believe it was intended that `Can view board` being false means no access to any of the forum at all. I'm not sure if we want to change that or not...

**Comment by Ben-MyBB** [comment]
I can see this being a strange decision decided on in the early days of 1.8 and in my opinion it doesn’t make much sense for it to override the other settings.


________________________________

**Comment by WildcardSearch** [comment]
I agree with @euantorano 

If you can't view the board, then that ***should*** override other settings.

**Comment by Ben-MyBB** [comment]
Seems to be it is just me confused then!

Points taken, thanks for your thoughts @euantorano @WildcardSearch 👍
