### ISSUE TITLE
Missing plugin language file for AdminCP prevents from using/entering AdminCP

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#3853]
There could be different circumstances where a missing plugin language file for AdminCP would make AdminCP inaccessible.

1. If a plugin has a language file for AdminCP in English, and the language file is not correctly uploaded, the AdminCP's plugin page will say `/inc/languages/english/admin/....lang.php does not exist`. **Yes, the forum owner should really have that file uploaded.**

2. If a plugin has a language file for AdminCP only in English, and all files are correctly uploaded:
   - but the user's AdminCP preference is set to another language, maybe Swedish, the AdminCP's plugin page will say `/inc/languages/swedish/admin/....lang.php does not exist` before activating this plugin.
   - or Administrator A who uses English for AdminCP activated the plugin first, and then Administrator B who uses Swedish visiting the plugin page will get a `XXX does not exist` error.
   - or worse for the previous circumstance, if the plugin has registered a header menu link at AdminCP, this Administrator B who uses Swedish will never make it to the AdminCP page. Any visits to the AdminCP will result in a blank page with `XXX does not exist` message.

Here are my thoughts:
- If a plugin is using any language file for AdminCP, a non-officially supported language file missing should trigger AdminCP's resorting to use a default language file for correctly displaying for AdminCP. I.e., AdminCP code should detect missing language files and use a default one upon that.

- If a plugin is using any language file for AdminCP, it might not always be English. The plugin should declare some property of a default AdminCP language, such as `English`, `Japanese`, etc, which used by AdminCP for the last resort.

However, I doubt the feasibility of the above-mentioned method under current MyBB's language handling way. WordPress's way seems good but its language file packaging is not trivial as a plain PHP file.

**Comment by yuliu** [comment]
A user has also [reported this issue in Discord](https://discordapp.com/channels/215876847634743296/215877079911104522/715271548079964212).

And it seems that the front-end language system has a fallback option which can be implemented for AdminCP.

**Comment by euantorano** [comment]
Yes, would be a good idea to have a fall-back in the ACP. No idea why it doesn't at the moment.

**Comment by JordanMussi** [comment]
This is because there are two calls to `set_language` in the Admin CP and each time the fallback has `/admin` appended:
https://github.com/mybb/mybb/blob/76bd4568a4cbbf35b6b3922b8605e40809d7d6d2/inc/class_language.php#L121

Causing the use of the fallback to fail:
https://github.com/mybb/mybb/blob/76bd4568a4cbbf35b6b3922b8605e40809d7d6d2/inc/class_language.php#L149-L152

As it is looking for a `inc/languages/english/admin/admin/PLUGIN_LANG.lang.php` file
