### ISSUE TITLE
Quoting issue of English language for entry `warnings_reached_max_warnings_day`

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#3856]
Seems should use double quotes here, but single quotes is used with an double quote at the end of string.

https://github.com/mybb/mybb/blob/mybb_1822/inc/languages/english/datahandler_warnings.lang.php#L8

**Comment by yuliu** [comment]
By the way, the language manipulator at the AdminCP is using [var_export()](https://www.php.net/manual/en/function.var-export.php) to export language entry content in single quoting. So it should not be a big deal to choose double quotes or single quotes. Just get rid of that ending `"` and replace `'` with `"` would be fine I think.

**Comment by euantorano** [comment]
Single quotes would definitely be preferred.
