### ISSUE TITLE
misc_imcenter_skype

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3865]
Nothing appears in the navigation bar {&#36;navigationbar}.

Original thread: [misc_imcenter_skype](https://community.mybb.com/thread-224050.html)

**Comment by PaulBender** [comment]
Probably worth removing it, since there's nothing to navigate.

**Comment by yuliu** [comment]
IM center seems a legacy feature. There are also some language file entries for it. What's it exactly?

**Comment by euantorano** [comment]
I might be remembering wrongly, but I believe it showed Skype online status (in the case of Skype), and could do so for some other IM systems.

**Comment by Sama34** [comment]
If we can't remember the feature then it's about time to drop all traces of it :P

**Comment by Eldenroot** [comment]
There is no more a possibility to check online status for Skype users... so it should be removed, please can you open a PR @PaulBender or anybody else? Thx!
