### ISSUE TITLE
Search by Username field issues on search system start page

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3866]
https://community.mybb.com/search.php

1st: Search by Username field doesn't have a clear, i.e., 'x' function

Input something in the field "Search by Username", and then there's no way of clearing existing input. So there are further problems:Refresh that page won't clear that field. Seems it's a browser behavior.

Click "back" from browser in a search result page, if the search had "Search by Username", it can't be cleared.

The only way to have a blank "Search by Username" field is to re-enter the search page either by Enter/Go from the address bar or click the search link.

2nd: Search by Username field doesn't allow arbitrary username, which maybe leaves unchecked "match exact username" useless

These two issues might be relating to JavaScript, IMO. A similar search function to the search system start page which does support clear function (like a x in input field) and arbitrary input is user search in member list: https://community.mybb.com/memberlist.php

Original thread: [Search by Username field issues on search system start page](https://community.mybb.com/thread-225790.html)

**Comment by Eldenroot** [comment]
@Ben-MyBB - I am not sure if I understand correctly to the description of this bug but if yes this was fixed by me here, not? https://github.com/mybb/mybb/pull/3621

**Comment by effone** [comment]
This is not at all an issue. As I have said in case of `memberlist.php`
https://community.mybb.com/thread-221231-post-1321045.html#pid1321045

User can easily achieve it adding single plugin option through template.

**Comment by effone** [comment]
Note, the second issue mentioned above still requires attention apart from the submitted PR.

**Comment by Eldenroot** [comment]
Yes, my PR will fix only the first point which is fair simple.
