### ISSUE TITLE
Hook positions improvements

### ISSUE THREAD

**Issue by Eldenroot** [mybb/mybb#3872]
Some hooks in USER CP are not placed correctly...

**Comment by Sama34** [comment]
I would rather suggest to left hook movements for 1.9

**Comment by Eldenroot** [comment]
I think this would be harmless, no drastic changes and it could help a lot for plugin developers.

**Comment by JordanMussi** [comment]
Yeah the changes in #3648 seem safe enough (mostly just moving hooks to after permission checks)

**Comment by Eldenroot** [comment]
This is fixed, right? @euantorano - can we close?
