### ISSUE TITLE
Update attachment

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3873]
Completely confused about "Update Attachment" button. The thing its doing currently is nothing but what "Add Attachment" does. So why the button is there? Can anyone guide me in which step this buttons action is unique?

This button should be removed or if really intended to update the attachment - it should be multiple, per already attached file list.
Point me out if I am missing something.

And now the bug:

We have switched to AJAX file remove. Well.
Update attachment appears only if atleast one file is already attached. But AJAX delete does not respect it.
Remove all the already attached files - "Update Attachment" button is still there. Refresh the page - its gone.

Original thread: [Update attachment](https://community.mybb.com/thread-222514.html)

**Comment by Eldenroot** [comment]
@lairdshaw what do you think, you have done a lot of work with attachments lately :)

**Comment by lairdshaw** [comment]
@Eldenroot Agreed that this button is useful, as explained by doylecc in the original thread (post #3). Also agreed that it should not be visible when there are no longer any attachments. It should be pretty simple to remove/hide it in Javascript if/when "Remove" is clicked (and confirmed) for the last attachment.

**Comment by rajat315315** [comment]
I think it does the same work as deleting an attachment with name "xyz" and then re-adding some attachment with the same name.
So, in this case, it seems redundant.

**Comment by lairdshaw** [comment]
> I think it does the same work as deleting an attachment with name "xyz" and then re-adding some attachment with the same name.

It does one other thing which makes it non-redundant and worth keeping: it maintains the same attachment ID.

**Comment by rajat315315** [comment]
@lairdshaw  for the user updating his attachment, does it even matter?

**Comment by lairdshaw** [comment]
@rajat315315 Yes, it sometimes does: when the attachment is included already in one or more posts using `[attachment=the_attachment_id]`.

**Comment by Sama34** [comment]
> @lairdshaw for the user updating his attachment, does it even matter?

If we remove we would be removing a feature that is useful for some people and might be used by somebody.
