### ISSUE TITLE
$_FILES['attachment'] instead of $_FILES['attachments']

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3888]
There are 3 files where &#36;_FILES['attachment'] is checked. However the input field has been renamed to attachments.

https://github.com/mybb/mybb/blob/1313f3...t.php#L195
https://github.com/mybb/mybb/blob/4ba89d...d.php#L160
https://github.com/mybb/mybb/blob/6ce374...y.php#L206

Original thread: [$_FILES['attachment'] instead of $_FILES['attachments']](https://community.mybb.com/thread-226313.html)

**Comment by yuliu** [comment]
#3886
