### ISSUE TITLE
username with an apostrophe does not parse correctly in quotes

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#3889]
as the title states, if a user has an apostrophe in their username, when someone quotes them, mybb does not parse their username correctly.

clean install of mybb 1.8.22:

![2020-02-07 15_20_58](https://user-images.githubusercontent.com/2748980/74063127-cf130c00-49bd-11ea-8680-a445f919f340.png)

Original thread: [username with an apostrophe does not parse correctly in quotes](https://community.mybb.com/thread-226389.html)

**Comment by euantorano** [comment]
This issue affects the quote alerts in MyAlerts. I seem to remember finding some weird stuff in SCEditor when I investigated the MyAlerts issue.
