### ISSUE TITLE
managegroup.php can only be used to remove users for whom it is not the primary group

### ISSUE THREAD

**Issue by dsyalex** [mybb/mybb#3894]
It will list users for whom the group is primary, but it calls the leave_usergroup function which only removes additional groups.
When this happens it pretends everything is fine but the user does not actually get removed. It should either:
* error (or block in the UI) if this operation is not possible for the particular user
* allow removing the user from their primary group (presumably selecting a new primary group from one of their other additional groups and erroring out if they have none?)

The latter sounds preferable but I don't know the full implications.

**Comment by Sama34** [comment]
As far as I understand this feature primary group is meant to never be removable.

**Comment by euantorano** [comment]
Yes, that is my belief too.
