### ISSUE TITLE
Remove Maxlength on email input. I have an email with a length of 51, changing the html and submitting causes the account to be created but in most cases, no verification email to be sent to me.

### ISSUE THREAD

**Issue by gh0s-t** [mybb/mybb#3895]

**Comment by Sama34** [comment]
Could you clarify the issue? I'm having a hard time understanding the issue.

**Comment by Sama34** [comment]
I think I understand the title now, but this seems like a suggestion. If so, @gh0s-t please use the community forums to send suggestions:
https://community.mybb.com/forum-199.html
