### ISSUE TITLE
Rating Topics as Guests

### ISSUE THREAD

**Issue by ThorgerJ** [mybb/mybb#3896]
It seems like even when the Group Permission for Guests to rate topics is that that its still not possible to do so. Ratings made by guests are not shown to others.

**Comment by euantorano** [comment]
I cannot replicate this. I've just created a thread on my test board, ticked `Can rate threads?` under ACP -> Users & Groups -> Groups -> Guests -> Forums & Posts -> Posting/Rating Options; then rated the thread as a uest. The rating shows for the guest that rated it and for me as a logged in account.

If you look inside the database using phpMyAdmin or a similar tool, what is shown in the `mybb_threadratings` table?

**Comment by ThorgerJ** [comment]
As far as ive seen its was problem with 3rd party software as i could not replicate the issue. Thanks for the effort though

**Comment by euantorano** [comment]
Alright, I'll close this issue then. Thanks for checking!
