### ISSUE TITLE
Send safe HTTP cache headers by default

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#3908]
Modify the `nocacheheaders` setting and [`send_page_headers()`](https://github.com/mybb/mybb/blob/mybb_1822/inc/functions.php#L4693) behavior to include `Cache-Control: private` in HTTP headers for dynamic HTML content.

Other headers set in the function may no longer be necessary.

**Comment by yuliu** [comment]
`Cache-Control: private` vs `Cache-Control: no-cache, must-revalidate`:

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control :

- `private`
    The response is for a single user and **must not** be stored by a shared cache. _A private cache (like the user's browser cache) may store the response._

- `no-cache`
    Caches must check with the origin server for validation before using the cached copy.

- `must-revalidate`
    Indicates that once a resource becomes stale, caches must not use their stale copy without successful validation on the origin server.

Seems `private` won't work in the same way as `no-cache, must-revalidate`, since only requiring `private` won't force a client's browser to check content's validity.

But `Pragma: no-cache` looks like a redundancy to `Cache-Control: no-cache, must-revalidate`. Oh, the former one is for backwards compatibility with HTTP/1.0, and the latter is for HTTP/1.1.

**Comment by dvz** [comment]
We could make it send `Cache-Control: private, no-cache` (and remove anything that's not needed anymore) when `nocacheheaders` is enabled, and make it the default state (including after the upgrade). Then it could be easily customized in server configuration when needed.

**Comment by yuliu** [comment]
> We could make it send `Cache-Control: private, no-cache` (and remove anything that's not needed anymore) when `nocacheheaders` is enabled, and make it the default state (including after the upgrade). Then it could be easily customized in server configuration when needed.

Yes, seems `Cache-Control: private, no-cache` is the proper thing to work with. From https://csswizardry.com/2019/03/cache-control-for-civilians/#must-revalidate :
 - Where `no-cache` will immediately revalidate with the server, and only use a cached copy if the server says it may, `must-revalidate` is like no-cache with a grace period.

And add `Pragma: no-cache` as an extra directive for compatibility for HTTP/1.0, if we have to.

> But `Pragma: no-cache` looks like a redundancy to `Cache-Control: no-cache, must-revalidate`. Oh, the former one is for backwards compatibility with HTTP/1.0, and the latter is for HTTP/1.1.

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma :
 - `Pragma` is not specified for HTTP responses and is therefore not a reliable replacement for the general HTTP/1.1 `Cache-Control` header, although it does behave the same as `Cache-Control: no-cache`, if the `Cache-Control` header field is omitted in a request. Use `Pragma` only for backwards compatibility with HTTP/1.0 clients.

**Comment by Eldenroot** [comment]
@dvz since you are the main leader in MyBB security (DVZ secure, some of your PRs) would you make a PR? Improving security is the no. 1 nowadays
