### ISSUE TITLE
This is not a bug ticket

### ISSUE THREAD

**Issue by henk23** [mybb/mybb#3910]
Yesterday I was hired by a client to update an old mybb forum from version 1.8.4 (~2014) to the current 1.8.22. I expected the experience to be awful, an old PHP codebase, probably lots of warnings and notices, an un-migratable database, conflicting directory names for user uploads...

None of that happened. I rsync'd the new files, clicked update and everything worked smoothly, the update was done in a few minutes, I installed the Amnesia plugin for GDPR complience (also no problems), the forum was up and running again within half an hour, my client is happy and so am I.

Great work by all of you, keeping this project alive and maintainable over so many years. :) Thank you.

**Comment by euantorano** [comment]
That’s awesome! It’s always nice to receive positive feedback, so thanks for taking the time to do so :)
