### ISSUE TITLE
Changing IP address invalidates anti-CSRF tokens between requests for guests

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#3912]
The [IP address check in `session::init()`](https://github.com/mybb/mybb/blob/mybb_1822/inc/class_session.php#L57) effects in MyBB creating new session entries whenever the address changes, even when a `sid` is provided. Since the anti-CSRF token [depends](https://github.com/mybb/mybb/blob/mybb_1822/inc/functions.php#L627) on the session identifier for guests, it is not accepted when the session is overwritten.

Regression [introduced in 1.8.20](https://github.com/mybb/mybb/commit/84a8c1ac65dabea0985f70b68f8ed728f3a1ad4d#diff-7fe6e55397c77ab9a0f5d57bc4cbe5b9).

This problem especially affects Tor Browser users.

Referenced in https://community.mybb.com/thread-223288.html

**Comment by Sama34** [comment]
Do you have reproduction steps for this? I tried to reproduce in Tor Browser but was unable to do so.

**Comment by yuliu** [comment]
> Do you have reproduction steps for this? I tried to reproduce in Tor Browser but was unable to do so.

Different access IP would result in this. Check https://community.mybb.com/thread-223288-post-1346002.html#pid1346002 . And maybe you could try Firefox's Private Network as well, the IP addresses accessing a website tends to change, but not frequently now.

**Comment by PirataNervo** [comment]
This happens a lot for me on my phone. I suppose my IP address changes frequently when using mobile data.

I don't understand what that commit is about though. What was the purpose behind the change? Why would a "MyBB 1.8.20" version change commit have other changes? Is this linked to a Pull Request? I would like to understand the implications of reverting that particular line change.

Thanks!

**Comment by euantorano** [comment]
@DiogoParrinha it being included in the 1.8.20 release commit means it was likely in relation to a security report. Looking at [the 1.8.20 release blog post](https://blog.mybb.com/2019/02/27/mybb-1-8-20-released-security-maintenance-release/) confirms this:

> Low risk: Predictable CSRF token for guest users — reported by [Devilshakerz](https://community.mybb.com/user-47371.html) of MyBB Team

**Comment by Sama34** [comment]
Ok, I was to reproduce and test your fix in Tor Browser and it seems fixed to me.

**Comment by DiogoParrinha** [comment]
> @DiogoParrinha it being included in the 1.8.20 release commit means it was likely in relation to a security report. Looking at [the 1.8.20 release blog post](https://blog.mybb.com/2019/02/27/mybb-1-8-20-released-security-maintenance-release/) confirms this:
> 
> > Low risk: Predictable CSRF token for guest users — reported by [Devilshakerz](https://community.mybb.com/user-47371.html) of MyBB Team
> 
> Good to see you by the way, hope you're keeping well.

Alright, thanks. I would suggest keeping it in a separate commit maybe. Ideally each security vulnerability would be fixed in a separate commit as well, so it can be quickly identified and patched individually if needed (or reverted if needed). Anyway, just a suggestion!

**Comment by euantorano** [comment]
That would probably make sense, mind creating an issue in https://github.com/mybb/mybb-build - that’s the repository used to manage the release workflow.
