### ISSUE TITLE
Add cache busting for CSS

### ISSUE THREAD

**Issue by ievgent** [mybb/mybb#3927]
After editing a theme stylesheet, the changes are not showing in browser due to caching.

There are some forum-topics related to this issue:
- [[Rejected] Theme Caches When Changing CSS Around](https://community.mybb.com/thread-161108.html)
- [Preventing CSS Files From Getting Cached](https://community.mybb.com/thread-120243.html)
- [ [Performance] Forum not updating when I edit CSS](https://community.mybb.com/thread-180988.html)
- [Theme CSS Cache Query String Hashes to bust caches](https://community.mybb.com/thread-214223.html)
- [Add force cache refresh](https://community.mybb.com/thread-137537.html)
- [Global.css Changes Aren't Showing Up?](https://community.mybb.com/thread-100336.html)
- [CSS not updating](https://community.mybb.com/thread-102994.html)

...ect.

**Comment by euantorano** [comment]
Related to #3482
