### ISSUE TITLE
Checkbox in group settings doesn't work

### ISSUE THREAD

**Issue by GasmoN** [mybb/mybb#3947]
I go to **ACP** > **Users & Groups** > **Groups**, and open any group I have created,
Than i go under "Publicly Joinable Options" and select "Yes, users must be invited in order to join this group" and when I click "Save user group" I get "The selected user group has been updated successfully." message. Until this point everything is okay, but the problem is that this checkbox didn't applied to group settings, so when I came back to chack settings, I saw that checkbox isn't selected. 
I tried this few times with few other groups and the issue is the same.

**Comment by dvz** [comment]
Does it work with _Yes, users can freely join and leave this group_ checked?
> Users must be able to freely join and leave this group for this to take effect.

**Comment by GasmoN** [comment]
When both of the options are selected, than this option I was talking about stays selected. 
https://i.postimg.cc/7hHsCHdg/screenshot-34.png

**Comment by effone** [comment]
This is obvious as it is clearly indicated under the option in subject that `Users must be able to freely join and leave this group for this to take effect.`
So even if you select that (third) option to make it actually effective you need to select the first check box alongwith.

I agree that the UI is not friendly, but this is not a bug.
