### ISSUE TITLE
Please add Notification system and like/unlike/reaction system

### ISSUE THREAD

**Issue by ALiveVam** [mybb/mybb#3951]
Please add Notification system and like/unlike/reaction system. We want

**Comment by euantorano** [comment]
Hi, GitHub issues aren't the place for suggestions and feature requests, please post suggestions and feature requests on the community forums: https://community.mybb.com/forum-199.html

Also note that notifications can be provided by my MyAlerts plugin: https://github.com/mybbstuff/myalerts

There are also several plugins to provide likes, including my SimpleLikes plugin: https://github.com/MyBBStuff/SimpleLikes
