### ISSUE TITLE
Unwanted undefined rating language variable.

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3953]
This language variable `$lang->ratings_update_error` is included in templates [forumdisplay_threadlist_rating](https://github.com/mybb/mybb/blob/feature/install/resources/mybb_theme.xml#L4130) and [showthread_ratethread](https://github.com/mybb/mybb/blob/feature/install/resources/mybb_theme.xml#L11681). This string piece is used in concatenation to the main error message in [rating.js](https://github.com/mybb/mybb/blob/feature/jscripts/rating.js#L91).

But this language variable is not defined anywhere in language files and always carries blank value. Looking at the message displayed by jGrowl it is hard to understand what this string should be. Suggested wiping its trace completely.

**Comment by Eldenroot** [comment]
So you just wanna delete lang string in forumdisplay_threadlist_rating and showthread_ratethread?

**Comment by JordanMussi** [comment]
Looks like the string was missed in #613. Should probably add a definition for it to: https://github.com/mybb/mybb/pull/613/files#diff-3ea9773affe02a0fa78965ca14e068fcR261
