### ISSUE TITLE
Implementation for fallbacks for empty email-address fields

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3955]
phpmail returns a error due to empty adminmail. Fall back should be implemented for empty email-address fields.

Related: https://github.com/mybb/mybb/pull/2520

Original thread: [Implementation for fallbacks for empty email-address fields](https://community.mybb.com/thread-227463.html)

**Comment by Sama34** [comment]
I think https://github.com/mybb/mybb/pull/2520#issuecomment-265735687 summarises the fix.

The settings module should stop empty values for this field.

**Comment by Ben-MyBB** [comment]
I think this should be treated as a High priority issue, this can explain a number of problems some people have been having with sending emails.

**Comment by effone** [comment]
Can be fallen back to board contact email? Or a strict validation is required?

**Comment by euantorano** [comment]
We should make the setting required in the ACP and the upgrade script should IMO set a value if a value is missing. The value should be taken from the contact email if set, or the logged in admin’s email address.

**Comment by Sama34** [comment]
I think it should take it from the contact email if set but fail if it is empty. Administrators should be notified in the release post instead of using the administrator account (without considering that there might be multiple administrators and none of them could not be UID=1 anyways).

**Comment by Ben-MyBB** [comment]
Whoever is creating a PR for this it may be worth checking https://community.mybb.com/thread-224905.html

**Comment by yuliu** [comment]
> (...) The value should be taken from the contact email if set, or the logged in admin’s email address.

> (...) Administrators should be notified in the release post instead of using the administrator account (without considering that there might be multiple administrators and none of them could not be UID=1 anyways).

I have a thought of not updating this data field for existing boards where this field is empty, but triggering an error at AdminCP to notify admins about updating its value. Though I'm not sure if this is applicable.

> Whoever is creating a PR for this it may be worth checking https://community.mybb.com/thread-224905.html

Yeah the mailing currently uses many addresses as `from:` and several fallback options, but it doesn't matter whether or not and how we implement the adminemail's empty check.

**Comment by Sama34** [comment]
> Though I'm not sure if this is applicable.

I think it should be like that. It can be as simple as ignoring the setting (not being saved) and append a message to the flash message as we currently do for the login methods setting.

**Comment by dvz** [comment]
IMO we should avoid unexpected changes (like using an account address #3993) or requiring input during upgrades.

Looks like the technical inconsistencies and unclear setting labels mentioned in https://community.mybb.com/thread-224905.html should be addressed first, potentially including setting verification; with an accompanying Docs article, we can refer users with mailing problems to it.
