### ISSUE TITLE
SMTP return code upon message sending completion should be checked

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#3984]
Community thread: https://community.mybb.com/thread-224905-post-1349025.html#pid1349025

Relevant code that will trigger errors:
https://github.com/mybb/mybb/blob/4c5451a241fabdfd22eff085a9336e3373deb64d/sendthread.php#L215
`./sendthread.php` - send thread to a friend:
`$from`: `$mybb->input['fromemail']` from `$mybb->user['email']` for logged in user
`$return_email`: `$mybb->input['fromemail']` from `$mybb->user['email']` for logged in user
The mail will be sent from [b]a user-specified email address[/b] which confronts mail SMTP service's requirement, like [Zoho's](https://www.zoho.com/mail/help/zoho-smtp.html#alink4) requiring `from` is the same as sending account's email address.

Still for Zoho, setting a different `Return Email` other than SMTP username will result in no mail delivered and MyBB frequently set Return Email as `from:` field if it's empty.

So in the above circumstances, Zoho's SMTP authentication will pass but when the full message is sent with a final ending `.`, the server will probably return a 553 code `553 Relaying disallowed as xxx@yyy.zzz`, which MyBB doesn't take care of.

**Comment by yuliu** [comment]
Oh by the way, the underlying reason that prevents mail's delivering is MyBB's wildly setting `from:` (and `return-path:`).

Ah just find it a duplicate of #2644. Should we fix it? @euantorano 

According to https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#SMTP_transport_example , a final 250 upon message acceptance should be issued from server and we should check.

**Comment by euantorano** [comment]
Yeah, I think it’s worth fixing if the fix is simple.
