### ISSUE TITLE
Invisible Captcha is broken sendthread

### ISSUE THREAD

**Issue by n-thumann** [mybb/mybb#3990]
When using "Send Thread to a Friend" (`sendthread.php`), the invisible Captcha (e.g. reCaptcha) cannot be bound to the submit button.
Basically the same issue & fix as https://github.com/mybb/mybb/issues/3915.

**Comment by Eldenroot** [comment]
@n-thumann please can you check this one? https://github.com/mybb/mybb/issues/3630#issuecomment-627516472 - maybe same issue with reset password page :(
