### ISSUE TITLE
Only parent forum's mod/modcp permissions are used in ModCP

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#3995]
It means that individual settings of mod/modcp permissions of the user or user group won't work for child forums in ModCP, if the child forums exist and child's permissions are different from the parent's.

**Comment by yuliu** [comment]
Currently, if a user has an individual mod permission in one forum and he will get such permission in all child forums of this one, regardless of what such permission settings in child forums are.

Suppose there are forums A, B, and C, where A is the parent of B and B is the parent of C. And let's take `canviewmodlog` for example, the explicit permission setting for `canviewmodlog` for a user in forum A is _yes_, and in forum B is _no_, and in forum C is _no_:

|  forum  |   canviewmodlog    |
|---------|--------------------|
|     A      |        yes            |
|     B      |        no             |
|     C      |        no              |

Then, by current ModCP code, mod logs in forum A/B/C will be fetched for this user, by the "where" clause for the query which includes all possible sub forums of a forum the user has `canviewmodlog` in:

https://github.com/mybb/mybb/blob/mybb_1822/modcp.php#L125-L131

Other moderator/modcp permissions are treated the same way.

It should be easy to fix this bug, I think.

**Comment by yuliu** [comment]
Regarding the above example, I have a question about permissions with no explicit setting in child forums, i.e., by inheritance.

Still using that example, if we have set one permission for a user in forum A to _yes_, and in forum B to _no_, and haven't explicitly added this user to forum C's moderator list, then what should such permission for this user in forum C be?

**Comment by yuliu** [comment]
I find that using `is_moderator()` or further the primitive one `get_moderator_permissions()` would return correct results, except that mod usergroup's permission is overriding individual user's one specific in #3996.

However, the performance and query accuracy vary between using `is_moderator()` and `get_moderator_permissions()`for supermods and mods:

Results:
|                  |   `is_moderator()`   |   `get_moderator_permissions()`  |
|------------|---------------------|--------------------------------------|
|supermods|  correct (supermods considered) |    wrong (supermods not considered) |
|   mods     |   correct                |          correct                                   |

Performance for traversing in numerous forums:
|                  |   `is_moderator()`   |   `get_moderator_permissions()`  |
|------------|---------------------|--------------------------------------|
|supermods|  good                     |    bad                                             |
|   mods     |   bad                     |          good                                      |

So if we gonna fix this issue, better choose `is_moderator()` for supermods and `get_moderator_permissions()` for mods without supermods privilege.

**Comment by Sama34** [comment]
> Still using that example, if we have set one permission for a user in forum A to yes, and in forum B to no, and haven't explicitly added this user to forum C's moderator list, then what should such permission for this user in forum C be?

Permissions should be inherit from the direct parent. Is that what you are asking?

Does this affects only the MCP?

> So if we gonna fix this issue, better choose is_moderator() for supermods and get_moderator_permissions() for mods without supermods privilege.

Sounds like a good approach, why did you stroke it out?

**Comment by yuliu** [comment]
> > Still using that example, if we have set one permission for a user in forum A to yes, and in forum B to no, and haven't explicitly added this user to forum C's moderator list, then what should such permission for this user in forum C be?
> 
> Permissions should be inherit from the direct parent. Is that what you are asking?

Yeah, they are. Sorry I didn't make my though clear. It should be about some other permission systems we've discussed in Discord.

Since there's no clear instructions/rules, users may have some idea that they can set up a permission setting in a parent forum and let all its child forums follow this setting but for only one child forum (also has child forums) has some special settings. So they will probably configure the moderating permissions as shown in the question, set permissions in forum A and B, not in C, but think C would follow A's settings.

Never mind..

> Does this affects only the MCP?

All permissions specified in table `moderators` are affected, including forum moderating permissions and ModCP permissions.

> > So if we gonna fix this issue, better choose is_moderator() for supermods and get_moderator_permissions() for mods without supermods privilege.
> 
> Sounds like a good approach, did you stroke it out for some reason?

Yes, the performance evaluation was wrong. The result should be that `get_moderator_permissions()` would always have poor performance for either supermods or mods. And the conclusion is that `get_moderator_permissions()` and `is_moderator()` are both fine for mods, but we could use former one in ModCP, and `is_moderator()` is preferred for supermods.

**Comment by Sama34** [comment]
> It should be about some other permission systems we've discussed in Discord.

Oh, so it should be fixed by the _Never_ or _Always_ permission scheme that has been discussed. Better documentation on permissions should also help.
