### ISSUE TITLE
PM Compose Message - Select from Buddies, Checkbox

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4005]
Low-grade and non-critical issue on Private Messages when selecting buddies in modal popup.

PM &gt; Compose Message &gt;

1. "Select from Buddies" &gt; Popup
Select a member via checkbox. This member is displayed under Selected recipients -&gt; OK, Popup closed.
This member is listed in the input field for recipients.

1.1. Do another "Select from Buddies" -&gt; Popup
The previous selected member is checkmarked but not displayed under Selected recipients.
Unchecking will display this member in Selected recipients and vice versa.
(Listed member in input field will keep, no matter if it was checked/unchecked in a second attempt.)

2. "Select from Buddies" -&gt; Popup
Do not choose a member -&gt; OK, Popup closed
An "empty block with an x" is listed in the input field for recipients with no user name.

Regards,
[ExiTuS]

Original thread: [PM Compose Message - Select from Buddies, Checkbox](https://community.mybb.com/thread-227903.html)

**Comment by Ben-MyBB** [comment]
I initally thought that I couldn't replicate this but for point 1.1 you should try and remove the member you just added by unticking the box, it doesn't let you. Then if you tick the box again it inserts a empty username box into the recipients field.

**Comment by Eldenroot** [comment]
@JordanMussi - please can you look at this :) thank you!
