### ISSUE TITLE
Jump Page Input type should be number

### ISSUE THREAD

**Issue by effone** [mybb/mybb#4018]
The multipage_jump_page input type should be number.
Currently the input type is text that allows to input anything and upon submitting an invalid / out of range value it resets to first page.

Should be changed to number, because:
- We expect only numeric value as page number
- We can define the acceptable range of input to get auto-validated

![snap](https://i.imgur.com/cgtizSr.png)

**Comment by euantorano** [comment]
I believe the original reason for using text was that the theme is XHTML rather than HTML5 and (off the top of my head), the number input type is HTML5. If making this change here, it might be worth using email input types for registration and such too.

**Comment by effone** [comment]
I didn''t know we are strict about this.
We already use number input types for ACP, so I thought ...

**Comment by euantorano** [comment]
@effone Sorry, I might not of been clear. I meant that in the past we might have been strict about it, but I don’t think we should be. In fact, I think we should use semantic elements more, such as `<input type=“email”>` for email inputs, etc.

**Comment by effone** [comment]
There are several places to correct, leading by this change. I will make a PR soon.
With that saying, are we gonna adapt other semantic tags like 'header` / `footer` / `main` / `article` / `section` / `nav` etc?

**Comment by euantorano** [comment]
I think bigger changes for those types of tags are best for 1.9 - I believe the new theme already uses them?

Input elements have less chance of breaking things though and have a large benefit (eg: built in client side validation). Would be nice to get those in 1.8.24 for sure!
