### ISSUE TITLE
Attachments aren't parsed in print preview

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4026]
Apparently attachments aren't parsed in print preview (printpreview.php) whereas the post parser works fine.

I don't think this is expected behavior.

Original thread: [Attachments aren't parsed in print preview](https://community.mybb.com/thread-227269.html)

**Comment by rajat315315** [comment]
Can anybody review and pull?

**Comment by euantorano** [comment]
We’re currently preparing 1.8.23 and pulling in PRs for that, sorry for the delay.
