### ISSUE TITLE
CAPTCHA code improvements

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4070]
Not exactly related to this PR, but I think we should introduce some constants/static variables to define these captcha types rather than having these types of checks scattered throughout the codebase.

_Originally posted by @euantorano in https://github.com/mybb/mybb/pull/4003#discussion_r439869586_

<hr>

Not related to this PR as such, but this is one wild `if` branch. Would be a good idea to try and clean this up in a. future release.

_Originally posted by @euantorano in https://github.com/mybb/mybb/pull/4003#discussion_r439869231_

**Comment by dvz** [comment]
https://github.com/mybb/mybb/pull/4122#issuecomment-744686665
