### ISSUE TITLE
Nested lists not working properly

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4074]
Hello,

When composing a post containing nested lists, an extra &lt;ul&gt; is added on each switching between text editor and SCEditor.

For example this code :
To Do:
[list]
[*]Fix the boiler
[*]Buy:
[list]
[*]Eggs
[*]Milk
[/list][*]Call mother
[/list]
is rendered as :
To Do:Fix the boiler

Buy:
Eggs

Milk

Call mother

As you can see, an extra line is added before "Eggs", and every switching between text/rich editor adds an extra line at the beginning of each nested list.

This behaviour was the same with 1.8.21.. and earlier I think.

The use of nested \[list\] mycodes is really very inconvenient! (and this for a long time)

Edit : I edited my post and now there are two blank lines before "Eggs"...

Original thread: [Nested lists not working properly](https://community.mybb.com/thread-225891.html)

**Comment by effone** [comment]
My comment from main thread:

>While looking into the issue further; I don't agree with the second part.
Catching `poop` in a greedy match will consider words like `nincompoop` as well; which is not a bad word. Suggested add all the expected variants of the bad words to the bad word list as well, as we don't have an exception list or dictionary loaded in parser.
