### ISSUE TITLE
Paste image into SCEditor gives data-uri instead of URL for [img] BBcode

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4078]
I haven't upgraded my forum to 1.8.21 yet, thought it would be better to try &amp; test things in community forum to see if anything is wrong. Well..

Description: When you paste an image directly to editor, it creates huge URL (like 800k characters.) Forum can't show the image and trying to edit the message with 800k characters gives you "1406 - Data too long for column 'originaltext' at row 1" MySQL error.

Reproduction steps:
Right click on any image and click on "Copy image" (not link of image, but image itself)

Paste this image on message editor with Ctrl V

Notice that instead of your image you see that 800k characters between IMG codes.

Thread I tested it in Community Forums: https://community.mybb.com/thread-223398...pid1330487

Original thread: [Another image bug in editor](https://community.mybb.com/thread-223399.html)

**Comment by Ben-MyBB** [comment]
Team members can view an example posted - https://community.mybb.com/thread-228216.html

**Comment by dvz** [comment]
Related: https://github.com/mybb/mybb/issues/2440

**Comment by Ben-MyBB** [comment]
@effone any chance you would have time to get another look at #2440 ?

**Comment by JordanMussi** [comment]
Just been doing a dive into this to see how we can fix the problems.

The code causing this issue is here:

https://github.com/samclarke/SCEditor/blob/65cc347e5fe764e8e58aa1a9af9c0b531195f666/src/lib/SCEditor.js#L1505-L1508

The URL from the clipboard of the image is converted into the base64 data
Then `handlePasteData` is called:

https://github.com/samclarke/SCEditor/blob/65cc347e5fe764e8e58aa1a9af9c0b531195f666/src/lib/SCEditor.js#L1483-L1491

But the initial `data` has been lost. So I think we need to patch SCEditor to add an option for choosing to use URL vs raw data.

**Comment by FurkanGozukara** [comment]
i really need this feature urgently. anyway to fix it? even a messy one.

**Comment by JordanMussi** [comment]
This will disable all paste format filtering but it will resolve the issue temporarily until MyBB 1.8.23:

In `jscripts/sceditor/jquery.sceditor.bbcode.min.js` find:
```js
i=e.clipboardData;
```
replace with:
```js
i=e.clipboardData;return;
```

**Comment by FurkanGozukara** [comment]
> This will disable all paste format filtering but it will resolve the issue temporarily until MyBB 1.8.23:
> 
> In `jscripts/sceditor/jquery.sceditor.bbcode.min.js` find:
> 
> ```js
> i=e.clipboardData;
> ```
> 
> replace with:
> 
> ```js
> i=e.clipboardData;return;
> ```

Thank you very much. Do this have any security vulnerability or just messy format?

**Comment by JordanMussi** [comment]
No it simply exits from the paste event handler without interfering and attempting to use the base64 paste formatting.

That is the modification for the minified file, for the source it would be like adding the `return;` after this line: https://github.com/mybb/SCEditor/blob/4d7c6b3a0a30d2bff93aaf55c83febe5853bf15a/src/lib/SCEditor.js#L1482

**Comment by FurkanGozukara** [comment]
@JordanMussi i have added but still the pasted image is converted to base 64

here the code i have modified : https://forumturkce.pokemonpets.com/jscripts/sceditor/jquery.sceditor.bbcode.min.js

**Comment by FurkanGozukara** [comment]
@JordanMussi 

the scripts included in the edit page is like below


```
<script type="text/javascript" src="https://forumturkce.pokemonpets.com/jscripts/jquery.js?ver=1813"></script>
<script type="text/javascript" src="https://forumturkce.pokemonpets.com/jscripts/jquery.plugins.min.js?ver=1813"></script>
<script type="text/javascript" src="https://forumturkce.pokemonpets.com/jscripts/general.js?ver=1813"></script>
<script type="text/javascript" src="https://forumturkce.pokemonpets.com/images/dark-fire/js/main.js"></script>
<script src="https://forumturkce.pokemonpets.com/jscripts/report.js?ver=1804"></script>
<script src="https://forumturkce.pokemonpets.com/jscripts/jeditable/jeditable.min.js"></script>
<script src="https://forumturkce.pokemonpets.com/jscripts/thread.js?ver=1808"></script>	
<script type="text/javascript" src="https://forumturkce.pokemonpets.com/jscripts/thankyoulike.min.js"></script>
<script type="text/javascript" src="https://forumturkce.pokemonpets.com/jscripts/thankyoulike.min.js"></script>
<script type="text/javascript" src="https://forumturkce.pokemonpets.com/jscripts/thankyoulike.min.js"></script>
		<script src="https://forumturkce.pokemonpets.com/jscripts/rating.js?ver=1808"></script>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<script src="https://forumturkce.pokemonpets.com/jscripts/inline_moderation.js?ver=1807"></script>
<script src="jscripts/unreadPosts.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://forumturkce.pokemonpets.com/images/dark-fire/js/jquery.tipsy.js"></script>
```

**Comment by Eldenroot** [comment]
Any progress guys?

**Comment by euantorano** [comment]
None as far as I’m aware, it’ll likely not be done until 1.8.27.

**Comment by Eldenroot** [comment]
@euantorano @JordanMussi - any workaround for this? It would be really useful to put images directly into posts (CKeditor for @martec - Rin editor supports this feature unofficialy… first step, but limited by mybb?)

**Comment by euantorano** [comment]
No, there is no workaround yet. There needs to be several changes made:

- On paste into the editor, get hold of the image data and upload it to the server as a new attachment.
- Insert the MyCode necessary to embed the attachment into the post.
- If the attachment fails to upload (unsupported type, out of attachment space, attachment quota exceeded, etc.) show an error.

It's actually quite a big feature, and not just a small patch.

We did previously look at just embedding the image as a data URI, but for the case of larger images, this would quickly make the database size grow by massive amounts.

**Comment by ghost** [comment]
There is a workaround:  

add two replace calls before return the message in "\inc\class_parser.php"
`
function parse_message(...)
{
$message = str_replace("[img]", "<img src='", $message);
$message = str_replace("[/img]", "' />", $message);
return $message;
}`

**Comment by ThatDataGuyScott** [comment]
> 
> 
> There is a workaround:
> 
> add two replace calls before return the message in "\inc\class_parser.php"
> ` function parse_message(...) { $message = str_replace("[img]", "<img src='", $message); $message = str_replace("[/img]", "' />", $message); return $message; }`

This worked beautifully, thank you.

**Comment by Sama34** [comment]
I think the above edit seems a little too drastic, probably causing additional concerns.

I think the ideal is to upload the image to the server as an attachment if it is allowed by the forum settings. Also, perhaps make it so that plugins such as ezGallery could hook into it rather than just the attachment system.

**Comment by effone** [comment]
https://community.mybb.com/thread-232121-post-1366038.html#pid1366038

I'll make a PR soon.
