### ISSUE TITLE
When `Hide Private Forums?` is off users can view forum lastpost for forums where can view threads but not forum

### ISSUE THREAD

**Issue by JordanMussi** [mybb/mybb#4097]
It seems that some threads/posts info (threads no., posts no., last post) will leak when forum permissions "Can view forum?" &amp; "Can view threads within forum?" are set to No and Yes respectively.

Note: "Hide Private Forums?" is set to No.

For a user in only one usergroup and set this usergroup's permission for a specific forum as follows:

"Can view forum?" - Yes
"Can view threads within forum?" - Yes

.. will result that the user:can see all the forum's info listed in index/forumdisplay (threads no., posts no., last post)

can enter the forum

can access/read threads in the forum

With both set to No, the result is three can'ts

"Can view forum?" - yes
"Can view threads within forum?" - no

.. will result that the user:can't see any the forum's info listed in index/forumdisplay (no threads no., no posts no., and no last post)

can enter the forum

can't see the thread list (Sorry, but you do not have permission to view threads in this forum.)

can't access/read threads in the forum (You do not have permission to access this page. This could be because of one of the following reasons:)

"Can view forum?" - no
"Can view threads within forum?" - Yes

.. will result that the user:can see all the forum's info listed in index/forumdisplay (threads no., posts no., last post)

can't enter the forum (You do not have permission to access this page. This could be because of one of the following reasons:)

can't access/read threads in the forum (You do not have permission to access this page. This could be because of one of the following reasons:)

Original thread: [Question about Can view forum? & Can view threads within forum?](https://community.mybb.com/thread-228380.html)

**Comment by Sama34** [comment]
So we are going with "Can view forum?" > "Can view threads within forum?", is this correct?

**Comment by JordanMussi** [comment]
That's already the case, if you cannot view a forum you cannot view the threads even if can view threads is enabled for that forum.
