### ISSUE TITLE
How to add copy paste image as attachment

### ISSUE THREAD

**Issue by FurkanGozukara** [mybb/mybb#4099]
I know that it is in development for further release but i need it urgently

Could anybody point me out to make which changes to enable it?

my forum : http://forum.monstermmorpg.com/

V 1.8.22

**Comment by JordanMussi** [comment]
We are already tracking this issue in #4078. The fix is being worked on, once it is completed and merged you can apply to your board or wait for the pre-release and upgrade to that.
