### ISSUE TITLE
Insecure connection used for Stop Forum Spam API

### ISSUE THREAD

**Issue by JordanMussi** [mybb/mybb#4100]
https://github.com/mybb/mybb/blob/dd960626c1035a4962b1375c77266385ddbe411c/inc/class_stopforumspamchecker.php#L21

> ### HTTP and HTTPS Support
> The API supports HTTP however the client must support SNI in order to validate certificate chains. If the client verifies the certificate chain by default, and SNI is not supported, then the connection will fail unless verify is disabled.
>
> \* The python included in Ubuntu 14.04 and below does not support SNI.
>
> The API will accept connections on the following ports
>
> HTTP
>   - Port 80
>
> HTTPS
>   - Port 443 (client must support SNI otherwise must have certificate verification disabled)
>
> &mdash; <cite>[Stop Forum Spam API Usage](https://www.stopforumspam.com/usage#:~:text=HTTP%20and%20HTTPS%20Support)</cite>

**Comment by euantorano** [comment]
Note: This will be fixed in 1.9 already when #3812 is finished: https://github.com/mybb/mybb/pull/3812/files#diff-35445ea221965cd8d7825ebab057df23
