### ISSUE TITLE
Member registration JS validator doesn't use translation for `required` message

### ISSUE THREAD

**Issue by JordanMussi** [mybb/mybb#4103]
Hello
With polish translation:

After we send empty register form, login input error is in english instead of polish just like others. Probably is hardcoded instead of placing it in langs.

Original thread: [[polish translation] no lang for error login input after send empty register form](https://community.mybb.com/thread-228392.html)

**Comment by effone** [comment]
Is it? We just moved the js chunks out. We didn't see any hard-coded language variables at MyBB part. Is it anything related to the validator library directly?

**Comment by JordanMussi** [comment]
Yep we don't overwrite the default message for the required error: https://github.com/jquery-validation/jquery-validation/blob/79bed393e6f4bf6876d0e917baed7ef6447efe6a/src/core.js#L354

`This field is required.` isn't in the MyBB repo anywhere. The PR you did before is totally fine, this issue predates your move of the JS.
