### ISSUE TITLE
Inconsistent spaces around "] = " in language files

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4107]
I found 22 lines with inconsistent spaces around the "] = " in the english language files.  Doubtful that it will break anything, but as there are 3459 that are consistent, perhaps these 22 lines should be the same.

Attached is a spreadsheet showing current text and what would be consistent.

Original thread: [Inconsistent spaces around "] = " in language files](https://community.mybb.com/thread-228435.html)

**Comment by RadiKalli** [comment]
I found two more lines in the admin files.
File: tools_spamlog.lang.php
Lines 9 and 11
double space before = sign:
$l['spam_logs_desc']    = 'This section allows you to view a history of users blocked by the   spam filters.';
$l['prune_spam_logs_desc']  = 'Here you can prune the spam logs   matching a specified criteria.';

**Comment by Ben-MyBB** [comment]
> 
> 
> I found two more lines in the admin files.
> File: tools_spamlog.lang.php
> Lines 9 and 11
> double space before = sign:
> $l['spam_logs_desc']  = 'This section allows you to view a history of users blocked by the spam filters.';
> $l['prune_spam_logs_desc']  = 'Here you can prune the spam logs matching a specified criteria.';

Will you be submitting a PR?

**Comment by Eldenroot** [comment]
I will

**Comment by Eldenroot** [comment]
OK, I will send a PR today, almost done. I think that all cases are covered.
