### ISSUE TITLE
If moderator can't warn some user, [Warn] link could be not exists in this profile

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4116]
Hello,
if i am a moderator and i am in admin profile i see [Warn] link which leads to page with error: You do not have permission to warn this user.
I think this link could be not exists for these profiles which user can't warn just like it's done for your own profile.

Original thread: [If moderator can't warn some user, [Warn] link could be not exists in this profile](https://community.mybb.com/thread-228512.html)

**Comment by Ben-MyBB** [comment]
Although this is a valid issue I wonder if we should change the target to 1.9 to minimise 1.8 template changes?

**Comment by JordanMussi** [comment]
This won't need template changes since the warning row is displayed conditionally already. We only need to add an extra condition:

https://github.com/mybb/mybb/blob/9feef312dc22abef36dcc1ddb1a703e66d9c2fe1/member.php#L2650

**Comment by Ben-MyBB** [comment]
> 
> 
> This won't need template changes since the warning row is displayed conditionally already. We only need to add an extra condition:
> 
> https://github.com/mybb/mybb/blob/9feef312dc22abef36dcc1ddb1a703e66d9c2fe1/member.php#L2650

Ah nice, I hadn't actually looked into it yet, I was just speaking from memory, which was wrong.

Do you plan on submitting a PR or shall I?

**Comment by JordanMussi** [comment]
You can go ahead! 😀

**Comment by JordanMussi** [comment]
Lol clicked assign yourself by accident 😛

**Comment by Ben-MyBB** [comment]
> 
> 
> Lol clicked assign yourself by accident 😛

Would the best thing here not be to update the default value for the admin group for canrecievewarnings to 0? It is currently set to 1 (yes) by default hence why the link is shown. The correct check is already being done with `$memperms['canreceivewarnings'] != 0`

Edit: perhaps set the default option to 0 but also hide it if editing group ID 4.

**Comment by effone** [comment]
Same applies to ban as well.

**Comment by Ben-MyBB** [comment]
> 
> 
> Same applies to ban as well.

I can have a look at that, not sure if we would fix it in this issue or not because if my above suggested fix is agreed on it will need to be a different fix to the ban instance.

**Comment by Ben-MyBB** [comment]
What's the thoughts on a fix for this in 1.8? @euantorano

**Comment by euantorano** [comment]
We should fix it in 1.8. Anything that can be fixed in 1.8 should be.
