### ISSUE TITLE
Delete Selected Attachments button is visible if i haven't got any attachments

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4117]
Hello,

In /usercp.php?action=attachments

We see this message: You currently do not have any files attached to your posts. and despite that we have this button Delete Selected Attachments
I just want to remind you that we don't have any attachments let alone selected attachments

I think this button could be visible only if we have available attachments (but best if we chose some attachments)

Original thread: [Delete Selected Attachments button is visible if i haven't got any attachments](https://community.mybb.com/thread-228515.html)

**Comment by rajat315315** [comment]
I would be grateful if someone can review/test these PRs and Pull them.

**Comment by Eldenroot** [comment]
@rajat315315 - all will be merged and tested, but please wait few more days until we get 1.8.23 release. After that all PRs will be tested/merged. So please feel free to send more PRs and MyBB team will check them soon :) thx for your contribution!
