### ISSUE TITLE
mybb incorrectly shows version 1.8.17 in mybb ACP 1.9

### ISSUE THREAD

**Issue by rajat315315** [mybb/mybb#4129]
Hi,

I am working with mybb develop/1.9 branch and I have noticed that Dashboard has Version --> 1.8.17.

**Comment by chack1172** [comment]
I'm sure the version is always update before the new version is released

**Comment by stardust342** [comment]
1.9 is currently based on 1.8.17 as of #3683
I don't think the version reported in ACP (and likely other places) needs to be updated until 1.9 is closer to release.

**Comment by andrewjs18** [comment]
The 1.9 code base is only in sync up to 1.8.17 at the moment, if I'm not mistaken.

**Comment by Ben-MyBB** [comment]
> 
> 
> The 1.9 code base is only in sync up to 1.8.17 at the moment, if I'm not mistaken.

Correct, the rebase is being done manually and the last time the changes were pushed was to bring up-to-date with 1.8.17.
