### ISSUE TITLE
Add `lastip` column handling to UserDataHandler

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4132]
The [`UserDataHandler`](https://github.com/mybb/mybb/blob/mybb_1823/inc/datahandlers/user.php) processes inserts and updates related to the user table's `regip` column, but support for `lastip` is missing.

`regip` references:
https://github.com/mybb/mybb/blob/mybb_1823/inc/datahandlers/user.php#L1154
https://github.com/mybb/mybb/blob/mybb_1823/inc/datahandlers/user.php#L1372-L1375

**Comment by Xazin** [comment]
Before I create a pr for this, I have a feeling something is missing, can someone check?

https://github.com/Xazin/mybb/blob/3e7fc232d951e4162fd36cb2f8e9c57cb2812693/inc/datahandlers/user.php#L1155

**Comment by euantorano** [comment]
> Before I create a pr for this, I have a feeling something is missing, can someone check?
> 
> https://github.com/Xazin/mybb/blob/3e7fc232d951e4162fd36cb2f8e9c57cb2812693/inc/datahandlers/user.php#L1155

I __think__ that should be it.

Regarding the earlier Discord discussion about escaping binary contents, the way they're handled is a little odd.

There is a field called [`$binary_fields` in the `MyBB` class](https://github.com/Xazin/mybb/blob/feature/inc/class_core.php#L159). The database methods [then check](https://github.com/Xazin/mybb/blob/feature/inc/db_mysqli.php#L814) this field when doing insert queries and such to decide whether to quote the value or escape it as binary or not.

The `lastip` column is already in the list of columns to escape as binary for the `users` table, so this should be all that's needed.
