### ISSUE TITLE
Add style variable in survey template

### ISSUE THREAD

**Issue by KeteTheme** [mybb/mybb#4136]
Hello good morning, I wanted to make a request to the MyBB developers which is to add a style variable in the survey template that indicates which of the survey options you voted for. I ask is asking for more options on customizing the survey in CSS. I think it would be a great idea for MyBB 1.9. The other way to do what I ask is to create a new template specifically where the user voted and thus add a unique class (html).

Example:

**polls_showresults_resultbit**

![image](https://user-images.githubusercontent.com/37380981/88487381-84c51d80-cf52-11ea-91ca-2500e284b8e7.png)

Thanks for your help and for your amazing MyBB software.

**Comment by Matslom** [comment]
Isn't this currently available through `$optionbg`? For row that indicates user chosen option `$optionbg` is equal `trow2`, `trow1` otherwise. See https://github.com/mybb/mybb/blob/feature/showthread.php#L562-L566

**Comment by Eldenroot** [comment]
I think this one can be solved with adding different than trow2 css class. What do you think?
