### ISSUE TITLE
Unclear reason of setting ['-1'] => '1' to $permissioncache which value is null

### ISSUE THREAD

**Issue by kamil256** [mybb/mybb#4142]
In `index.php` there is an instruction setting value `1` to `$permissioncache` array at index `-1`. 

https://github.com/mybb/mybb/blob/4ae73bc086ab87c045a860c1e3314ffdf75b5270/index.php#L417

Later, there's an instruction for running `index_end` hooks.

https://github.com/mybb/mybb/blob/4ae73bc086ab87c045a860c1e3314ffdf75b5270/index.php#L430

Some plugins call functions which use `$permissioncache`. Those functions check if it's an array, and if it is - they don't recalculate  its value.

Example:
https://github.com/mybb/mybb/blob/4ae73bc086ab87c045a860c1e3314ffdf75b5270/inc/functions.php#L4378

```php
        if(!is_array($permissioncache))
	{
		$permissioncache = forum_permissions();
	}

        $unviewable = array();
	foreach($forum_cache as $fid => $forum)
	{
		if($permissioncache[$forum['fid']])
		{
			$perms = $permissioncache[$forum['fid']];
		}
		else
		{
			$perms = $mybb->usergroup;
		}
```

When function is called after setting `1` to null `$permissioncache` at index `-1` - It uses `$mybb->usergroup` for each forum, no matter which groups a user is in. Sometimes that function returns an empty list of unviewable forums and users can see content that should be hidden for them.

**Comment by dvz** [comment]
It doesn't look like anything would break if we simply set it to `null` (removing it completely may cause PHP 8 to emit Warnings).
