### ISSUE TITLE
Can't delete user from BCC Private Message

### ISSUE THREAD

**Issue by thunderclap82** [mybb/mybb#4150]
I was going to send a PM to several people and one of those people have PM's turned off and received a notice. I deleted their name from the recipient list (BCC) and tried to re-send but the notice reappeared as did the name. It looks like you can't delete recipients.

**Comment by Xazin** [comment]
I tried this on my testing board, and couldn't manage to find an actual bug.

Steps I took:
- On one account I disabled receiving PM's.
- Another account tried PM'ing that user (as only recipient) and got the usual error "_user_ has private messaging disabled ..."
- I then refreshed and added another user and then added that same user, tried to send. Still got the same error on the same user.
- After removing that user from recipients (bcc) the PM sent successfully.

V: _MyBB 1.8.24_ - Default Theme

**Comment by Eldenroot** [comment]
I tried to reproduce too but without success. Could you give us more info?

**Comment by Ben-MyBB** [comment]
Sounds similiar to https://github.com/mybb/mybb/issues/4005 ?

**Comment by effone** [comment]
> Sounds similiar to #4005 ?

No its a different issue and I couldn't reproduce it as well considering every possible scenario.
This report is invalid.
