### ISSUE TITLE
Clearer error messages when internal issues arise.

### ISSUE THREAD

**Issue by rjhancock** [mybb/mybb#4156]
Just today had an issue where, after a maintenance reboot on the server, the forums completely stopped working. Was receiving 503 errors with nothing showing up in any logs. Apache, PHP, Syslog, or even logs generated by MyBB.

While investigating, noticed the settings were not being loaded, either from settings.php nor from the database. Had to modify the `class_error.php` file to force show the error.

Error was the Redis server had failed to load upon reboot. Although the issue is now fixed, had there been a log of this issue somewhere, it would have saved 3 hours of debugging.

Issued appeared on 1.8.24 with Redis Caching enabled.

**Comment by euantorano** [comment]
Would you mind sharing the modification you made to `class_error.php`?

Part of the problem is likely due to the error handling code path requiring settings to figure out how it should behave, which is problematic when an error occurs before settings have been loaded.

**Comment by rjhancock** [comment]
Around line 441 I adjusted the IF condition to include `true ||` at the beginning to see what would happen.

**Comment by euantorano** [comment]
Yeah, seems to be as I suspected - settings weren't yet loaded, which the code doesn't handle and as such just doesn't show anything.

I'm not sure what the best course of action is here. Perhaps we shouldn't configure our special error handler until after settings are loaded? Otherwise we can't know the various required pieces like:

- Whether to show or hide errors
- Whether to log errors to a file
- If logging errors to a file, where to write that file

We currently set up the error handler very early on in `inc/init.php`:

https://github.com/mybb/mybb/blob/feature/inc/init.php#L47:L48

This is before we even try to load configuration, connect to the DB, or load settings.

We either need to change where we attach the handler, or have some flag to tell it we're still in early initialisation stages.

Thoughts @mybb/developers?

**Comment by Sama34** [comment]
I think the root for this specific issue could have been spotted faster by the forum administrator if errors were displayed in full to administrators regardless of the settings.

**Comment by euantorano** [comment]
In this case, the database connection wouldn’t have been opened, nor would the settings have been read or anything. As such, we wouldn’t know if the user was an administrator yet.

**Comment by rjhancock** [comment]
True, but there should be output of the error somewhere for admins to look at it. Maybe default to the error_log in the install folder?

**Comment by euantorano** [comment]
> True, but there should be output of the error somewhere for admins to look at it. Maybe default to the error_log in the install folder?

Agreed, for sure. That might be a good approach, though if that file is not writable for some reason I'm not sure what to then fall back on.

**Comment by rjhancock** [comment]
Attempt to write to the file with an indication on the front end that it can be found in the logs and failing that just output the error itself to the web page. But only as a last resort.

**Comment by dvz** [comment]
Can it display any sensitive information before the settings are loaded?

We probably wouldn't want it to write to files that may be accessible publicly, unless it's configured that way (the installer may be an exception). If it helps, we can add documented `$config` overrides for error handling.

**Comment by euantorano** [comment]
> Can it display any sensitive information before the settings are loaded?

Not sure off the top of my head. I know the error handling goes out of its way to not print contents of the settings or config files.

> We probably wouldn't want it to write to files that may be accessible publicly, unless it's configured that way (the installer may be an exception). If it helps, we can add documented `$config` overrides for error handling.

Adding `$config` overrides might be a good approach, with some sensible defaults.

**Comment by yuliu** [comment]
Hmm..

It just comes to my mind that it might be good to always write error logs into PHP's system logger, like
https://github.com/mybb/mybb/blob/feature/inc/class_error.php#L357
and make sure it will write.

Or, we may set up a variable in MyBB's `errorHandler` class:
- If settings & user privileges are read, unset the variable in `./inc/init.php` and let MyBB uses its own error handler.
- Or the variable is found still existent during handling errors, (that may mean missing/wrong settings or script hangs before MyBB settings are read, etc.,) we resort to write errors to PHP's system logger.
