### ISSUE TITLE
[Feature Suggestion] Force Attachment Download

### ISSUE THREAD

**Issue by GasmoN** [mybb/mybb#4163]
This suggestion is related to this thread: https://community.mybb.com/thread-229749.html
In future, it would be nice to add option in Attachments Types that will allow us to choose will that attachment will be downloadable or will it be opened in a browser (For example, .txt files).
I am running forum where users can upload their extensions for games, so when they upload language files that are in .txt extension or settings files in .ini, those files are opened in browser.

This option should't affect types that are already selected as downloadable in attachment.php file, so my idea is to add function  in this line https://github.com/mybb/mybb/blob/aacebaecb49d0cb951096134277250192a2cedba/attachment.php#L182
that will check is file extension is marked as downloadable or not. If it's marked as downloadable, it will be downloaded, if not it will be opened in the browser. That way, other file types won't be affected.

**Comment by effone** [comment]
Any reason this is assigned for 1.9 while tagging as `easy-pick` ?
