### ISSUE TITLE
Seo Issues

### ISSUE THREAD

**Issue by Mrsihag** [mybb/mybb#4189]
Mybb should have Good seo system
It should have :- Custom tags below every post
- Permalink should be user friendly (i.e. it should have permalink on name of post)
- Admin can customize header for seo

**Comment by Stefan-MyBB** [comment]
> To **suggest changes or features**, go to the [**Suggestions and Feedback**](https://community.mybb.com/forum-199.html) forum. Please make sure that your feature hasn't already been suggested and is not already planned.

https://github.com/mybb/mybb/blob/feature/.github/CONTRIBUTING.md

**Comment by Eldenroot** [comment]
You can do it with SEO plugin easily. 

Please close this one @euantorano
