### ISSUE TITLE
Threads should have Custom icons

### ISSUE THREAD

**Issue by Mrsihag** [mybb/mybb#4190]
Whenever user is posting a thread he can customize the thread icon which gives it premium look.

Please work on it

**Comment by Stefan-MyBB** [comment]
> To **suggest changes or features**, go to the [**Suggestions and Feedback**](https://community.mybb.com/forum-199.html) forum. Please make sure that your feature hasn't already been suggested and is not already planned.

https://github.com/mybb/mybb/blob/feature/.github/CONTRIBUTING.md

**Comment by Eldenroot** [comment]
This one should be closed  @euantorano
