### ISSUE TITLE
Drop inclusion of 3rd party 'json.php'

### ISSUE THREAD

**Issue by effone** [mybb/mybb#4202]
`inc/3rdparty/json/json.php` is a third party library for backward compatibility of PHP < 5.2 which defines only `json_encode` and `json_decode` functions.

Since we don't support that low version of PHP and that file has some incompatibility with PHP 8; we can consider of dropping it from MyBB package.

**Comment by Eldenroot** [comment]
Maybe together with #4095 to fully support php 8?

**Comment by euantorano** [comment]
I think it’s not only needed for PHP < 5.2, but also versions that need a PHP extension for JSON support.

**Comment by effone** [comment]
I didn't exactly get what you said. As per PHP doc JSON is supported in all versions  >= 5.2.0

**Comment by euantorano** [comment]
> I didn't exactly get what you said. As per PHP doc JSON is supported in all versions >= 5.2.0

See some of the comments here: https://www.php.net/manual/en/json.installation.php

on some versions of PHP on some operating systems you have to install a `php-json` extension to get the JSON functions. 

The PHP documentation suggests it should always be available but it doesn’t seem to be on some systems and versions. 

Don’t get me wrong though - I would definitely love to remove it, just got to hope it doesn’t break anything for anyone.

**Comment by effone** [comment]
OK. Better not to invite trouble removing a file which is there for long.
This can be closed.
