### ISSUE TITLE
Password Length Settings

### ISSUE THREAD

**Issue by effone** [mybb/mybb#4219]
In ACP > Login and Registration Options, Minimum Password Length (`minpasswordlength`) can be set greater than Maximum Password Length (`maxpasswordlength`).
There is no validation in place. Resulting user impossible to register.

**Comment by Xazin** [comment]
The same would be the case for (`minnamelength`) and (`maxnamelength`)

**Comment by Xazin** [comment]
Possibly adding something like _below_ to settings.php _(line: 967)_
```
if ($gid == 9)
{
    if ($mybb->input['upsetting']['minnamelength'] > 0 && $mybb->input['upsetting']['maxnamelength'] > 0 && $mybb->input['upsetting']['minnamelength'] > $mybb->input['upsetting']['maxnamelength'])
    {
        flash_message($lang->error_field_minnamelength, 'error');
        admin_redirect("index.php?module=config-settings&action=change&gid=".$gid);
    }
    
    if ($mybb->input['upsetting']['minpasswordlength'] > 0 && $mybb->input['upsetting']['maxpasswordlength'] > 0 && $mybb->input['upsetting']['minpasswordlength'] > $mybb->input['upsetting']['maxpasswordlength'])
    {
        flash_message($lang->error_field_minpasswordlength, 'error');
        admin_redirect("index.php?module=config-settings&action=change&gid=".$gid);
    }
}
```

and remembering the config_settings.lang.php file:
```
$l['error_field_minnamelength'] = "Minimum name length can not be larger than maximum name length";
$l['error_field_minpasswordlength'] = "Minimum password length can not be larger than maximum password length";
```

**Comment by effone** [comment]
Is `0` input validated? Its validated at frontend though through native form validation.

**Comment by Xazin** [comment]
> Is `0` input validated? Its validated at frontend though through native form validation.

I believe there are some validation, if you manipulate the front-end to set the values to 0, it gets set to 1 (back-end).

_Note: Since 1 is the lowest value, minnamelength and minpasswordlength set to 1 will always be acceptable._

**Comment by effone** [comment]
> Note: Since 1 is the lowest value, minnamelength and minpasswordlength set to 1 will always be acceptable.

Also to note here, if the requirement is set to have complex password then the lowest value must be 3 in place of 1 as complex password needs minimum 1 uppercase letter, 1 lowercase letter and 1 number. In that case hard reset of value to 1 will not work, a proper validation should be in place.
