### ISSUE TITLE
Use cached values for calculating thread count in forum view

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4253]
The number of threads counted using a single query at https://github.com/mybb/mybb/blob/mybb_1824/forumdisplay.php#L610 can be optimized by taking advantage of visible, soft-deleted, and unapproved thread counts available in the `mybb_forums` table, depending on the user's permissions.

Similar solution was removed in https://github.com/mybb/mybb/pull/3190/files

Regression after #3190

**Comment by Sama34** [comment]
Wasn't this accepted in part because counter bugs were common with the former code? I haven't seen a pagination report being posted in a while now.

**Comment by dvz** [comment]
It looks like the problems were related to filtering by thread prefix, which wasn't accounted for at https://github.com/mybb/mybb/blob/mybb_1815/forumdisplay.php#L615
