### ISSUE TITLE
Not possible to remove signature length limit

### ISSUE THREAD

**Issue by Walter-Correa** [mybb/mybb#4258]
"_The maximum number of characters a user can place in a signature. Set to 0 to disable the limitation._"

**If you set 0:** "_You cannot update your signature because it is too long. The maximum length for signatures is 0 characters._"

But wasn't 0 to remove the limit?

**Comment by awslabspl** [comment]
@Walter-Correa Ive noticed this too.....

**Comment by dvz** [comment]
Regression after #2347 (`0` check removed at https://github.com/mybb/mybb/pull/2347/files#diff-f7fdbf357a321ef157867099148616d4fda48504a761d7db5aca5d3076cd293cL93)

No limit feature description added at https://github.com/mybb/mybb/pull/2526/files#diff-066cb7349a723bf1fe1b43f9a87d1c12bc560e51cd10ba02247fabf730834c89R1082

**Comment by Eldenroot** [comment]
Regression :(
