### ISSUE TITLE
Add options to prevent spiders and thread autor from increasing thread view count

### ISSUE THREAD

**Issue by Walter-Correa** [mybb/mybb#4262]
I found a solution here: https://community.mybb.com/post-882217.html

But I ask why is there not an option in the settings to prevent this or even a standard configuration like the one above?

**Comment by Eldenroot** [comment]
I can open a PR, I think it should be in core.

**Comment by euantorano** [comment]
Yes, would be a useful addition to the core, with a setting. The setting should be whether to include guest/bot views, and should default to being switched off.

**Comment by Eldenroot** [comment]
Guys, PR is ready :)

**Comment by dvz** [comment]
It may be more sensible to only exclude bots by default (or none, to preserve current behavior, but add customization).

**Comment by Eldenroot** [comment]
OK, I have changed the default options.

Exclude spiders by default, guest and thread authors are included.

**Comment by Eldenroot** [comment]
Anyway this is duplication of #3935
