### ISSUE TITLE
I can't use Admin CP on mobile

### ISSUE THREAD

**Issue by Walter-Correa** [mybb/mybb#4264]
After logging in to Admin CP the page loads and goes to Admin CP> Home, but if I try to access any other page it asks to login again.

**Comment by Xazin** [comment]
I'm not able to recreate the issue.

Tested on iPad Pro, iPhone 11 Pro Max.

I don't have an android lying around, can you share the device, os version, browser, etc.?

**Comment by euantorano** [comment]
This may also be cookie related, please post your site's URL and the cookie settings you've got set. For more information, see here: https://docs.mybb.com/1.8/faq/login-problems/

**Comment by Walter-Correa** [comment]
> I'm not able to recreate the issue.
> 
> Tested on iPad Pro, iPhone 11 Pro Max.
> 
> I don't have an android lying around, can you share the device, os version, browser, etc.?



> This may also be cookie related, please post your site's URL and the cookie settings you've got set. For more information, see here: https://docs.mybb.com/1.8/faq/login-problems/

Solved, thank you!
