### ISSUE TITLE
Meta tags is not working

### ISSUE THREAD

**Issue by Walter-Correa** [mybb/mybb#4269]
Meta tags are only working if I put inside the **{$headerinclude}** template:
```
<meta property="og:title" content="{$mybb->settings['bbname']}" />
<meta property="og:description" content="This is my forum.">
<meta property="og:type" content="website">
<meta property="og:site_name" content="{$mybb->settings['bbname']}">
<meta property='og:image' content='http://www.mysite.com/images/logo.png'/>
<meta property="og:image:alt" content="My forum image" />
<meta property="og:url" content="https://www.mysite.com/forum/"> 
```
But if I use the same meta tags inside **forumdisplay** template it has no effect!

**Comment by Eldenroot** [comment]
It is not a core feature, so I think it is not a valid bug report. Also report bugs on mybb forum, not here.

SEO and meta tags are handled via plugins.

**Comment by euantorano** [comment]
They should work within the `forumdisplay` template, so long as you insert the tags before `</head>`.
