### ISSUE TITLE
Who is online limit (per page) setting is taken from thread settings

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4277]
The who is online list limit (per page) setting is taken from the show thread setting group, which makes no sense whatsoever  🤪

https://github.com/mybb/mybb/blob/66dca7...hp#L47-L53

It should have its own setting.

Original thread: [Who is online limit (per page) setting is taken from thread settings](https://community.mybb.com/thread-231404.html)

**Comment by Ben-MyBB** [comment]
@Eldenroot Not sure if this is one you'd like to tackle, if not I probably can at some point

**Comment by Eldenroot** [comment]
@Ben-MyBB - feel free to open a PR. Right now I am working on a different issue. Thank you!

**Comment by Sama34** [comment]
You can use the assignment tool of Github 😛

**Comment by Eldenroot** [comment]
OK, should be done :)
