### ISSUE TITLE
`isdefault` set to 0 for some default settings

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4278]
The `<isdefault>` value of certain default settings is incorrectly set to `0` instead of `1`.

- https://github.com/mybb/mybb/blob/8b22ad19b64acc14418b4dec3e19ec5b0f349b6a/install/resources/settings.xml#L1049
- https://github.com/mybb/mybb/blob/8b22ad19b64acc14418b4dec3e19ec5b0f349b6a/install/resources/settings.xml#L1869
- https://github.com/mybb/mybb/blob/8b22ad19b64acc14418b4dec3e19ec5b0f349b6a/install/resources/settings.xml#L2059

Not known to be causing any issues.

**Comment by lairdshaw** [comment]
Good catches.

Incidentally, I had a dig around in the code yesterday to try to understand the meaning of this property. It seems in effect to simply control whether the setting is editable or not in the ACP (its configuration, as in `title`, `description`, etc - obviously, setting _values_ are editable no matter what). 0 seems to correspond with "can be edited" and 1 with "is immutable". I don't really understand the point of it. Is there a reason why some settings should be editable, and others not, and why core settings in particular should _not_ be editable? Has my digging perhaps failed to uncover other effects of this property?

**Comment by dvz** [comment]
The codebase relies on the consistency of default settings (existence, types, allowed values) - allowing modification would go beyond reasonable extensibility and could cause unexpected behavior, errors, and security problems (e.g. some setting values are unfortunately not escaped nor sanitized for output / usage in SQL queries).

It looks like flags for individual settings were introduced in MyBB 1.4.0 via https://github.com/mybb/mybb/commit/bd82717de9af0bcc85c02940452159ea571a00ae and are set to `1` during the [installation](https://github.com/mybb/mybb/blob/8b22ad19b64acc14418b4dec3e19ec5b0f349b6a/install/index.php#L2064) and [upgrades](https://github.com/mybb/mybb/blob/8b22ad19b64acc14418b4dec3e19ec5b0f349b6a/install/upgrade.php#L956).

The property of setting groups also helps distinguish inbuilt settings [during the upgrade](https://github.com/mybb/mybb/blob/8b22ad19b64acc14418b4dec3e19ec5b0f349b6a/install/upgrade.php#L897) and on the [setting list](https://github.com/mybb/mybb/blob/8b22ad19b64acc14418b4dec3e19ec5b0f349b6a/admin/modules/config/settings.php#L1873).

**Comment by lairdshaw** [comment]
Thanks for the detailed explanation. It seems that plugin developers really do need to make sure that they (we) always set `isdefault` to zero.
