### ISSUE TITLE
"Click to edit" added when post content is empty

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4293]
A _Click to edit_ message is added to posts when their content is empty.

With the [Minimum Message Length](https://github.com/mybb/mybb/blob/mybb_1825/install/resources/settings.xml#L1285-L1293), empty posts may suggest a server-side problem, but the unnecessary client-side message may point in the wrong direction when troubleshooting.

Details: https://community.mybb.com/thread-231510-post-1364051.html

**Comment by Eldenroot** [comment]
@Sama34 - fix is quite simple - so just adding placeholder somewhere here https://github.com/mybb/mybb/blob/aacebaecb49d0cb951096134277250192a2cedba/jscripts/thread.js#L188-L196 and add a new lang variable into headerinclude to avoid other edits? What text for a new lang variable do you suggest?

**Comment by Sama34** [comment]
Something straightforward, like `There is no message.` should suffice.

**Comment by dvz** [comment]
Leaving it empty may be self-explanatory.

**Comment by Sama34** [comment]
Yes, I changed my mind. Since this is an issue with the Quick Edit feature, inserting a message, regardless of which messages it is, could be more confusing than simply leaving it empty.

@martec Sorry for making you work so much, thank you for your contribution!

**Comment by martec** [comment]
@Sama34 

sorry, but maybe you quoted the wrong person
