### ISSUE TITLE
Check table schema before altering it in upgrade52.php

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4297]
The database changes in the `upgrade52.php` upgrade script should verify existing database table structure to avoid errors when the process is run more than once.

https://github.com/mybb/mybb/blob/35203a4145e379e58d4bad326fece8f19d189f8f/install/resources/upgrade52.php#L32-L44

**Comment by Sama34** [comment]
I have made comments about this before, last time being told "upgrade scripts are meant to run only once" (years ago).

Rather, I agree with the suggestion on this issue.
