### ISSUE TITLE
Moving threads in 1.8.26 not possible

### ISSUE THREAD

**Issue by Platbodemforum** [mybb/mybb#4302]
When I (as an adminstrator user) want to move a thread to a different subforum I get an empty page and an error 500.  This is since 1.8.26 on platbodemforum.nl. Php 7.2.34 . Tested on several browsers and OS'ses, all of them up to date.

**Comment by euantorano** [comment]
Please check your server error log for any errors, which would help track down the problem.

In most webhosts that provide control panels such as cPanel, the server error log is available through the panel.

**Comment by Platbodemforum** [comment]
`[Fri Mar 12 16:03:09.115947 2021] [lsapi:error] [pid 958852:tid 139735731943168] [client 2001:980:616b:1:7f90:14c4:e6d8:d19c:53024] [host www.platbodemforum.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Moderation' not found in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php:30\nStack trace:\n#0 {main}\n  thrown in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php on line 30\n, referer: https://www.platbodemforum.nl/showthread.php?tid=1215&pid=10697
[Fri Mar 12 16:03:37.458416 2021] [lsapi:error] [pid 966065:tid 139735420815104] [client 2001:980:616b:1:7f90:14c4:e6d8:d19c:53024] [host www.platbodemforum.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Moderation' not found in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php:30\nStack trace:\n#0 {main}\n  thrown in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php on line 30\n, referer: https://www.platbodemforum.nl/showthread.php?tid=1215&pid=10697
[Fri Mar 12 16:03:43.938733 2021] [lsapi:error] [pid 966065:tid 139735578162944] [client 2001:980:616b:1:7f90:14c4:e6d8:d19c:53024] [host www.platbodemforum.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Moderation' not found in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php:30\nStack trace:\n#0 {main}\n  thrown in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php on line 30\n
[Fri Mar 12 16:04:31.443791 2021] [lsapi:error] [pid 969241:tid 139735731943168] [client 2001:980:616b:1:7f90:14c4:e6d8:d19c:53024] [host www.platbodemforum.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Moderation' not found in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php:30\nStack trace:\n#0 {main}\n  thrown in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php on line 30\n, referer: https://www.platbodemforum.nl/showthread.php?tid=1215&pid=10697
[Fri Mar 12 16:06:53.773845 2021] [lsapi:error] [pid 989382:tid 139735148078848] [client 2001:980:616b:1:7f90:14c4:e6d8:d19c:53024] [host www.platbodemforum.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Moderation' not found in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php:30\nStack trace:\n#0 {main}\n  thrown in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php on line 30\n, referer: https://www.platbodemforum.nl/forumdisplay.php?fid=36
[Fri Mar 12 16:08:27.136262 2021] [lsapi:error] [pid 998378:tid 139735200528128] [client 2001:980:616b:1:7f90:14c4:e6d8:d19c:53110] [host www.platbodemforum.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Moderation' not found in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php:30\nStack trace:\n#0 {main}\n  thrown in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php on line 30\n, referer: https://www.platbodemforum.nl/forumdisplay.php?fid=36
[Fri Mar 12 16:08:34.958720 2021] [lsapi:error] [pid 998378:tid 139735022200576] [client 2001:980:616b:1:7f90:14c4:e6d8:d19c:53110] [host www.platbodemforum.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Moderation' not found in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php:30\nStack trace:\n#0 {main}\n  thrown in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php on line 30\n
[Fri Mar 12 16:08:36.804321 2021] [lsapi:error] [pid 1000055:tid 139735473264384] [client 2001:980:616b:1:7f90:14c4:e6d8:d19c:53110] [host www.platbodemforum.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Moderation' not found in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php:30\nStack trace:\n#0 {main}\n  thrown in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php on line 30\n
[Fri Mar 12 16:22:40.730174 2021] [lsapi:error] [pid 85736:tid 139735700473600] [client 82.161.38.237:56352] [host www.platbodemforum.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Class 'Moderation' not found in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php:30\nStack trace:\n#0 {main}\n  thrown in /home/platbodem/domains/platbodemforum.nl/public_html/moderation.php on line 30\n, referer: https://www.platbodemforum.nl/forumdisplay.php?fid=36
`

**Comment by euantorano** [comment]
Does the file `inc/class_moderation.php` exist and does it look [like this](https://github.com/mybb/mybb/blob/feature/inc/class_moderation.php)? If not, download  afresh package and upload that file from it - it may have been corrupted by your FTP client when initially uploading.

You can also check the file verification tool in the ACP.

**Comment by Platbodemforum** [comment]
No it is zero bytes. That will be the problem. I will upload a better one . Thanks. Will let you know if that helps, I assume it will.

**Comment by Platbodemforum** [comment]
That was the solution, thank you.

**Comment by Platbodemforum** [comment]
Removed log file with ip addresses.
