### ISSUE TITLE
New forums are not cached properly

### ISSUE THREAD

**Issue by Xazin** [mybb/mybb#4316]
On the feature branch, when creating a new forum the rebuilding of the forum cache is done before the parent list of the forum is updated. This causes the new forum to be invalid when viewed, as a part of the forum is not being cached properly. 

https://github.com/mybb/mybb/blob/2e82a33a7052655f420ea876bc5d06a384f49789/admin/modules/forum/management.php#L894

Moving the above line down 3 lines fixed the issue for me. Can anyone recreate this issue?

**Comment by lairdshaw** [comment]
Yes. Issue + fix confirmed.

Warning to those who also wish to recreate this issue: first deactivate the XThreads plugin if you have it installed and active, because in its hook into `admin_forum_management_add_commit` it calls `$cache->update_forums()`, leading to the appearance that all is well.

**Comment by dvz** [comment]
Regression from #4152
