### ISSUE TITLE
ACP Multiple email registration & Login method settings

### ISSUE THREAD

**Issue by effone** [mybb/mybb#4324]
- ACP Multiple email registration notice gets displayed even if there is no conflict.
- A query is always run based on the existing settings to check existence of multiple emails no matter if its required or not.

![image](https://user-images.githubusercontent.com/21265591/111861840-4c59d000-8977-11eb-9850-6d5798490d7f.png)

**Comment by Eldenroot** [comment]
I can confirm, this has been here for ages :(
