### ISSUE TITLE
No data supplied for PM validation

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4345]
The code introduced in https://github.com/mybb/mybb/pull/4119/files doesn't supply subject and message data  correctly to the data handler (`postDataHandler::verify_subject()` and `postDataHandler::verify_message()` don't accept arguments), resulting in false errors and possibly PHP Warnings.

Regression from #4119

**Comment by Sama34** [comment]
Why does it verify only the subject and message? It should verify everything and output any error, IMO the following:
https://github.com/mybb/mybb/blob/f42221bd074bbeec5f3d8d8c2185148fd14afa98/private.php#L121-L124

Should be merged around here (with an `elseif`):
https://github.com/mybb/mybb/blob/f42221bd074bbeec5f3d8d8c2185148fd14afa98/private.php#L653-L666
