### ISSUE TITLE
Missing collation in upgrade script

### ISSUE THREAD

**Issue by effone** [mybb/mybb#4363]
MyBB `upgrade.php` is missing collation declaration while creating the table `upgrade_data`, resulting to fallback to `latin1`.

**Comment by dvz** [comment]
Does this produce any known bugs?

**Comment by effone** [comment]
No, as the upgrade data table hardly have any chance to get 4byte data. But it shows red under ACP UTF8 tab.

**Comment by effone** [comment]
It can be considered as an inconsistency to the nature of MyBB's auto table creation flow.
