### ISSUE TITLE
Soft deleted thread may be visible in User CP Home's subscriptions

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4384]
Threads that were soft-deleted may be displayed in UCP's Home page in the _Thread Subscriptions with New Posts_ list.

The condition at https://github.com/mybb/mybb/blob/mybb_1826/usercp.php#L4300 includes a `t.visible != 0` check, but the code associated with soft-deleted threads is `-1`.

Conditions on the dedicated `usercp.php?action=subscriptions` page (https://github.com/mybb/mybb/blob/mybb_1826/usercp.php#L1565) include a `t.visible >= 0` check, but may still produce inconsistent behavior.

Reported in https://community.mybb.com/thread-232604.html

**Comment by Sama34** [comment]
Related #1106
