### ISSUE TITLE
Missing HTML angle bracket in `post_attachments_new` template

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4391]
The `post_attachments_new` template contains a typo where the `#dropzone > div` element's code is missing a `>` character in the opening tag at https://github.com/mybb/mybb/blob/mybb_1827/install/resources/mybb_theme.xml#L9471

Not known to be causing any issues.

Added in #4195

**Comment by Ben-MyBB** [comment]
Note: Deferred label added. This issue will be resolved in any potential security fix releases of the 1.8 series.
