### ISSUE TITLE
Forum search filter may not apply when `forums` parameter not an array

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4393]
The `search.php` search filter limiting results to specific forum may not work when the forum ID, specified in the `forums` parameter, is passed as a string, and not an element of an array (`forums[]`).

The _Search this Forum_ form specifies the forum ID as a string, resulting in the filter not being applied:
https://github.com/mybb/mybb/blob/4817069fcaa5a5fcb82e34fc7f35091810c347e2/install/resources/mybb_theme.xml#L3981

 Third-party plugins and custom links may also be affected.

The accepted type was changed to `MyBB::INPUT_ARRAY` at https://github.com/mybb/mybb/commit/634257842da94abc2fadcf0ac628b273fc33ade9#diff-fe25e8545f067eb50fae0028b5dcdc76e168a985bd8806edcae066ae1f6a4f8bL1573-R1616

The `search.php` code should change the parameter type to an array if a string is received.

Regression from #4348

**Comment by dvz** [comment]
The _Search this Forum_ feature can be fixed manually by editing the `forumdisplay_searchforum` template (_Forum Display Templates_) and replacing
```html
<input type="hidden" name="forums" value="{$fid}" />
```
with:
```html
<input type="hidden" name="forums[]" value="{$fid}" />
```

**Comment by Sama34** [comment]
Will this be fixed at the template level?

**Comment by dvz** [comment]
We can add a type check and conversion for compatibility, but adding `[]` to the template may also make it more clear what type is generally expected (or in case the conversion is removed again later).
