### ISSUE TITLE
Moderation_queue.php doesn't work with MyBB 1.8.27

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#4398]
MyBB Version 
1.8.27

PHP Version
7.4 ( I have tested only on 7.4)

Issue
Inside Admin CP » Forums and Posts » Moderation Queue » Threads Awaiting Moderation
Moderation_queue.php doesn't work, basically when you select Ignore/Approve/Delete and click "Perform Action", nothing happens.

I reverted the moderation_queue.php to previous version(Github Link Here) and it works fine.

NOTE: This is issue with Moderation Queue inside Admin CP , the modcp.php moderation queue works fine.

Regards
WallBB

Original thread: [Moderation_queue.php doesn't work with MyBB 1.8.27](https://community.mybb.com/thread-232826.html)

**Comment by dvz** [comment]
Regression from #4207
