### ISSUE TITLE
Can you please change urlencode to rawurlencode in search.php?

### ISSUE THREAD

**Issue by FurkanGozukara** [mybb/mybb#4405]
I am using google seo plugin

This below code causes error when the search term includes space character

```
	// Work out if we have terms to highlight
	$highlight = "";
	if($search['keywords'])
	{
		if($mybb->seo_support == true)
		{
			$highlight = "?highlight=".urlencode($search['keywords']);
		}
		else
		{
			$highlight = "&amp;highlight=".urlencode($search['keywords']);
		}
	}
```

space character is being replaced with + character and it is breaking google seo pluing

why it is not being properly encoded?

when I change to rawurlencode  it works

**Comment by awslabspl** [comment]
Im with you on this one. Its minor change, but may cause some pretty serious damage, trouble

**Comment by FurkanGozukara** [comment]
> Im with you on this one. Its minor change, but may cause some pretty serious damage, trouble

Also if I change manually after each update I have to change again :(

**Comment by awslabspl** [comment]
> > Im with you on this one. Its minor change, but may cause some pretty serious damage, trouble
> 
> Also if I change manually after each update I have to change again :(

True, but its worth doing this; Trust me

**Comment by FurkanGozukara** [comment]
> > > Im with you on this one. Its minor change, but may cause some pretty serious damage, trouble
> > 
> > 
> > Also if I change manually after each update I have to change again :(
> 
> True, but its worth doing this; Trust me

rawurlencode is insecure compared to urlencode you mean?

**Comment by Sama34** [comment]
I can't see to replicate any issue with this and Google SEO.

Please provide steps or more information into the issue this causes, with screenshots, etc.

**Comment by FurkanGozukara** [comment]
> I can't see to replicate any issue with this and Google SEO.
> 
> Please provide steps or more information into the issue this causes, with screenshots, etc.

@Sama34 

I use windows server maybe that is why. simply when you make a forum search you get 404 error

e.g. https://forum.monstermmorpg.com/Thread-Guild-Wars&highlight=guild+war

you see your method currently adds `+` character instead of `%20` and it throws error

**Comment by awslabspl** [comment]
> your method currently adds `+` character instead of `%20` and it throws error

`%20`is just blank space, not harmful at all...........

**Comment by FurkanGozukara** [comment]
@awslabspl instead why you dont change urlencode to rawurlencode

**Comment by Sama34** [comment]
I just did test on WIndows 10 and I experience no similar issue with the default Google SEO setup.

**Comment by Sama34** [comment]
@FurkanGozukara please try @awslabspl server suggestion as it seems `urlencode()` works on most setups.

**Comment by lairdshaw** [comment]
Taking a step back, the problem seems to be that an ampersand is being generated in the thread URL without a question mark preceding it. I can reproduce it with the Google SEO plugin enabled and `Server and Optimization Options` » `Enable search engine friendly URLs?` set to `Disabled`. It works fine for me with that value set to either `Automatic Detection` or `Enabled` though.

Somehow, though, on my local setup, either MyBB, the Google SEO plugin, Apache, or my browser auto-corrects the ampersand into a question mark when I click on the link, so I don't actually experience the error.

Suggestion for @FurkanGozukara: change the setting I mentioned above to `Enabled`. Let us know whether this fixes the problem for you.

**Comment by lairdshaw** [comment]
Additional analysis:

Automatic detection probably fails on Windows Server when there is no equivalent of the following code from the default `.htaccess` file:
```
	<IfModule mod_env.c>
		SetEnv SEO_SUPPORT 1
	</IfModule>
```

This is because line #255 of `init.php` tests that server variable as part of its auto-detection: 

https://github.com/mybb/mybb/blob/4817069fcaa5a5fcb82e34fc7f35091810c347e2/inc/init.php#L255

**Comment by lairdshaw** [comment]
Probably, then, a lasting solution is for the Google SEO plugin to automatically set `$mybb->seo_support` to true.

**Comment by FurkanGozukara** [comment]
@lairdshaw good debugging

after changing from auto to enabled now works

**Comment by FurkanGozukara** [comment]
enabling search engine friendly URLs would not conflict with google seo plugin right?

@lairdshaw

**Comment by awslabspl** [comment]
> @awslabspl instead why you dont change urlencode to rawurlencode

you can do this as well

**Comment by lairdshaw** [comment]
> enabling search engine friendly URLs would not conflict with google seo plugin right?

To the best of my understanding: no, there is no conflict there.

**Comment by awslabspl** [comment]
> enabling search engine friendly URLs would not conflict with google seo plugin right?
> 
> @lairdshaw

No true at all

**Comment by FurkanGozukara** [comment]
> > enabling search engine friendly URLs would not conflict with google seo plugin right?
> > @lairdshaw
> 
> No true at all

You mean they won't conflict?

Your answers are pretty vague

**Comment by FurkanGozukara** [comment]
> > enabling search engine friendly URLs would not conflict with google seo plugin right?
> 
> To the best of my understanding: no, there is no conflict there.

Thank you for answer

**Comment by awslabspl** [comment]
> You mean they won't conflict?
> Your answers are pretty vague

There **should** be no conflict.
