### ISSUE TITLE
User Avatar, Profile picture shows blank no matter what is done

### ISSUE THREAD

**Issue by vdbhb59** [mybb/mybb#4406]
1. Writable folders/paths = Yes
2. Image restrictions = Yes/No (both scenarios)
3. Default Avatar = Yes/No (both scenarios)
4. Tried using: https://community.mybb.com/thread-166660.html (including the avatarfix)
5. GZip = Tried GZip ON/OFF
6. Avatar (Non-HTTPS) = Block/Non-Block (both scenarios)

Nothing seems to work. The profile images/avatars/gravatars all remain BLANK/WHITE irrespective.
Attached few images here.

![image](https://user-images.githubusercontent.com/60728004/124789461-d5ead900-df39-11eb-949c-4fa658da7b7d.png)
![image](https://user-images.githubusercontent.com/60728004/124789815-2104ec00-df3a-11eb-998d-69463184a4d2.png)
![image](https://user-images.githubusercontent.com/60728004/124790021-54477b00-df3a-11eb-8320-cd0e3999f32b.png)

Not sure if I am doing anything wrong here. I went through a lot of stuffs, but I am unable to fix it.

**Comment by lairdshaw** [comment]
This seems more suitable for a thread on the community forums, probably in the [General Support](https://community.mybb.com/forum-176.html) sub-forum. We generally prefer bugs to be reported on those forums too, in the [1.8 Bugs and Issues](https://community.mybb.com/forum-157.html) sub-forum prior to their being confirmed - if appropriate - and then pushed to GitHub. I'm closing this issue.

**Comment by vdbhb59** [comment]
Wow, that is odd. Why do you have github then? Would you not consider someone not wishing to be a user on your mybb forum/community?
So, I reiterate: what is the use of github, and why **force** to your forum?

**Comment by lairdshaw** [comment]
It's just the funnel that we have in place. We try to keep GitHub issues to confirmed bugs based on pushed reports from the community forums.

The issue you have reported is potentially not even a bug. We would at least need some sort of reliable recipe for replication to consider it to be a bug. As such, it is best that you work through the problem you're having on the community forums, in the sub-forum to which I linked you.

You are not forced there, it is just the best place for your concerns. If you prefer, you could ask for help on our Discord server.

I'm sorry if you find this offensive - like I said, it's just the funnel that we choose to use.
