### ISSUE TITLE
Raw URLs are not anymore automatically parsed as link after latest version upgrade?

### ISSUE THREAD

**Issue by FurkanGozukara** [mybb/mybb#4407]
Previously links were getting automatically parsed but not anymore

Here example thread : https://forum.monstermmorpg.com/Thread-Version-6-1-0

**Comment by lairdshaw** [comment]
This seems more suitable for a thread on the community forums. Since I see you've already created a thread there, I'm closing this issue. In future, please don't start issues on GitHub - instead, post to the community forum, and if your issue is deemed to be a bug, it will be escalated to GitHub.
