### ISSUE TITLE
Error suppression doesn't work on PHP 8

### ISSUE THREAD

**Issue by zingaburga** [mybb/mybb#4409]
When the `@` error suppression operator is used in PHP 8, the value returned by `error_reporting()` to the error handler [has changed](https://www.php.net/manual/en/language.operators.errorcontrol.php).  This causes MyBB's custom error handler to deal with errors that should be suppressed.

In inc/class_error.php:

	if(error_reporting() == 0)

should be:

	if((error_reporting() & $type) == 0)

**Comment by Sama34** [comment]
The specific fix for this in the attached PR works.
