### ISSUE TITLE
Font codes showing in some posts

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#4410]
After update to 1.8.27 font codes are showing in some posts. 

Mentioned here: https://community.mybb.com/thread-232927.html

It can be seen on MyBB's forum here:  forum: https://community.mybb.com/post-1342828.html

I have found it on my forum in an old post too. 

Thank you.

Original thread: [Font codes showing in some posts](https://community.mybb.com/thread-232943.html)

**Comment by lairdshaw** [comment]
As indicated in the original thread, this is a regression introduced in PR #4187, due to that PR removing the parser's ability to parse nested `[font]` tags. Will share a corrective PR shortly.
