### ISSUE TITLE
Display error in custom forum permission settings for guests in ACP

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4414]
If you go to "Set custom permissions" for guests in ACP forum management, the "Miscellaneous" tab looks like this:

The error is caused by an typo in admin/modules/forum/management.php line 791.

if(!in_array($field['field'], $hidefields) &amp;&amp;...
should be
if(!in_array($field['Field'], $hidefields) &amp;&amp;...

Original thread: [Display error in custom forum permission settings for guests in ACP](https://community.mybb.com/thread-232970.html)

**Comment by dvz** [comment]
Regression from #4353 (https://github.com/mybb/mybb/pull/4353/files#diff-4e5d8abaf751adbb34bf4e81a54b7dfae2869b0ba394fad9c2915b7d9c1d027aL780-R791)

Usergroups' custom forum permissions setting checkboxes may be missing, or displayed incorrectly: https://www.mybb.de/forum/thread-37889-post-248938.html#pid248938

**Comment by Sama34** [comment]
I was unable to debug the issue you mention @dvz
