### ISSUE TITLE
Admin permission management broken in PHP 8

### ISSUE THREAD

**Issue by lewislarsen** [mybb/mybb#4444]
Issues include:

- [x] Numerous undefined array key errors for the administrator who's permissions have changed.
- [x] Updating permission values will wipe the previously applied permissions for the admin instead of adding to them.
- [x] #4446

PHP Version: 8.0.9
MyBB Version: 1.8.27

Have tested this across two different MyBB 1.8.27 installs and they were both affected equally.

**Comment by euantorano** [comment]
Sounds like this ties in to the issue with all the PHP 8 issues. Good catch!

**Comment by dvz** [comment]
Some fixes were added via [PR 4447](https://github.com/mybb/mybb/pull/4447/files) and https://github.com/dvz/mybb/commit/b340ed03ad7f760ae67b47e7f99419006972a5d3.

Can you add steps to reproduce, and [error details](https://docs.mybb.com/1.8/faq/errors/#enabling-error-logs), for problems that remain?

**Comment by lewislarsen** [comment]
> Some fixes were added via [PR 4447](https://github.com/mybb/mybb/pull/4447/files) and [dvz@b340ed0](https://github.com/dvz/mybb/commit/b340ed03ad7f760ae67b47e7f99419006972a5d3).

Tested your fixes and the only issues that seem to remain are the errors shown to the admin with altered permissions. Editing admin permissions are working now.

> 
> Can you add steps to reproduce, and [error details](https://docs.mybb.com/1.8/faq/errors/#enabling-error-logs), for problems that remain?

Reproduction steps are to edit a user with ACP access and set any options you'd like to `No`. It doesn't seem to matter which options are set (although the array key error differs slightly from "config" to say.. "user" depending on what category the option belongs to)

Here are the below errors logged from changing a few values in the config category. This was produced by browsing the admin control panel as the admin with altered permissions.
```
<error>
	<dateline>1630694105</dateline>
	<script>C:\local\mybb-prs\admin\inc\functions.php</script>
	<line>362</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined array key "config"</message>
	<back_trace>#0  errorHandler->error() called at [C:\local\mybb-prs\admin\inc\functions.php:362]
#1  check_admin_permissions() called at [C:\local\mybb-prs\admin\modules\home\module_meta.php:77]
#2  home_action_handler() called at [C:\local\mybb-prs\admin\index.php:784]
</back_trace>
</error>

<error>
	<dateline>1630694105</dateline>
	<script>C:\local\mybb-prs\admin\inc\functions.php</script>
	<line>362</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Trying to access array offset on value of type null</message>
	<back_trace>#0  errorHandler->error() called at [C:\local\mybb-prs\admin\inc\functions.php:362]
#1  check_admin_permissions() called at [C:\local\mybb-prs\admin\modules\home\module_meta.php:77]
#2  home_action_handler() called at [C:\local\mybb-prs\admin\index.php:784]
</back_trace>
</error>
```
