### ISSUE TITLE
mybb install with postgresql

### ISSUE THREAD

**Issue by vncloudsco** [mybb/mybb#4459]
i know the source code support but i cant'n find any connection option how can i install postgresql for mybb?
![image](https://user-images.githubusercontent.com/41409442/134855657-e3601fa5-e5bc-411d-bc07-e6d7abbaf795.png)

**Comment by euantorano** [comment]
You need to make sure the PHP extension for PostgreSQL is installed. Are you using shared hosting or a VPS/dedicated server?

**Comment by Sama34** [comment]
Please open a thread in the community forums for support.
https://community.mybb.com/forum-182.html
