### ISSUE TITLE
SCEditor returns unsupported MyCode format for quotes with no username

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4492]
Quoting a Guest, who didn't supply a username, may result in unparsed MyCode being displayed when using SCEditor.

When a `[quote="" ...]` MyCode tag with an empty author value and additional attributes is created in the [`parse_quoted_message()` function](https://github.com/mybb/mybb/blob/mybb_1829/inc/functions_posting.php#L176) and added to `<textarea>` elements, SCEditor may remove the  empty attribute code `=""` and output a `[quote ...]` tag, a format not supported by the MyBB parser.

Reported in:
- https://community.mybb.com/thread-214064.html
- https://community.mybb.com/thread-234164.html
- https://www.mybb.de/forum/thread-35184.html

**Comment by mmikeww** [comment]
I also reported this bug here:
https://community.mybb.com/thread-234131.html

I just tested the fix in PR #4493 and confirmed it worked in both cases when quoting a guest with no username 1. when using quick reply box to quote, and 2. when using full editor to quote

**Comment by Eldenroot** [comment]
@mmikeww thx for testing the PR!

@dvz - can you add this to 1.8.30 milestone?
