### ISSUE TITLE
Found Stored XSS on application

### ISSUE THREAD

**Issue by noobpk** [mybb/mybb#4500]
Hi,
I found an XSS vulnerability in your application and reported it on Huntr a few months ago but it doesn't seem to have been sent to your team.
I hope you can visit Huntr to confirm the report
Disclosure: https://huntr.dev/bounties/2d2f9bc9-c686-4fa0-9d34-de4105d8d116/

**Comment by dvz** [comment]
Hello,

please send details of any suspected security issues directly to `security@mybb.com`, or to our [Private Inquiries forum](https://community.mybb.com/forum-135.html).

For more information, see [**mybb.com/security**](https://mybb.com/security).

We don't use any third-party platforms for security issues (and `huntr.dev` does a particularly bad job of notifying software maintainers and should be avoided).

**Comment by noobpk** [comment]
> Hello,
> 
> please send details of any suspected security issues directly to `security@mybb.com`, or to our [Private Inquiries forum](https://community.mybb.com/forum-135.html).
> 
> For more information, see [**mybb.com/security**](https://mybb.com/security).
> 
> We don't use any third-party platforms for security issues (and `huntr.dev` does a particularly bad job of notifying software maintainers and should be avoided).

I have emailed information about the vulnerability.
Thanks ^^!!
