### ISSUE TITLE
`drop_table()` in PostgreSQL and SQLite may result in errors

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#4502]
The primary part of DROP TABLE should work fine but the following DROP SEQUENCE part may not work:

https://github.com/mybb/mybb/blob/mybb_1...1286-L1293
https://github.com/mybb/mybb/blob/mybb_1...#L482-L487

As in the above code, there might be at least two issues:
1. The variable $table in the query doesn't have $table_prefix.
2. The query SQL to DROP SEQUENCE is using single quotes so the variables in it won't get expanded.
3. The query SQL to find any sequences that are still linked to the current table is wrong. The view that has sequence information is information_schema.sequences but not information_schema.constraint_column_usage which is used for constraints and keys.

About the sequence's add/drop:
 - In PostgreSQL 8.2 and later, CREATE SEQUENCE ... OWNED BY ... is allowed. Thus, when a table is dropped any sequences owned by it will also get dropped, created by either the serial data type or CREATE SEQUENCE ... OWNED BY ....
 - But in PostgreSQL 8.1 and previous versions, the OWNED BY clause hasn't been supported yet. ~~MyBB officially supports PostgreSQL &gt;= 8.1, so we have to maintain this code.~~

Original thread: [PostgreSQL's `drop_table()` may result in errors](https://community.mybb.com/thread-234455.html)

**Comment by yuliu** [comment]
With some further checks of the sequence drop and the column/table drop:

- If a sequence is owned by a column, dropping the column or the table which the column is in will automatically drop the sequence, at least in contemporary PostgreSQL (some older versions [may not](https://stackoverflow.com/a/8270947/6681141) and MyBB doesn't support such older versions already).
- If a sequence isn't owned by any column, one needs to manually query `DROP SEQUENCE seq_name` to drop it. The only thing we need to know is the sequence's name.

So, usually we don't have to take care of the sequence when dropping a table. One should care only if a sequence has been removed its ownership and if the sequence is not used it should be manually dropped.

Here I think we can keep the sequence check and removal part for the following situation:
- If a `serial`/`bigserial` column is altered to remove the default auto-increment value, and the sequence is also disowned by the column (though I believe MyBB never does that), MyBB will drop the sequence after dropping the table.

**Note:** developers should manage their sequence uses, including add sequence and drop sequence, and don't rely on MyBB's `drop_table()` to clean unused sequences. The fact is MyBB doesn't know the sequence name and can't drop it for you.

**Comment by yuliu** [comment]
OK, I finally understand why it was there. The short version is MyBB has a self managed sequence `mybb_userfields_ufid_seq`.

The whole story happened in a version 1.4.4 [bug report](https://community.mybb.com/thread-41314.html). The long version:
1. The PRIMARY KEY column `ufid` in table `mybb_userfields` is created as an `int` type, NOT a `serial` type. So it doesn't have a sequence associated with it.
2. When a user registers, other than a new row being created in the `mybb_users` table the system will also creates a user field row in `mybb_userfields`, and the `insert_query()` will request an insert id which it doesn't use at all, by `DB->insert_id()`.
3. The `DB->insert_id()` relying getting the current value of an existing sequence, of course, will fail, because there's no sequence for the column `ufid`. So there will be an SQL error like in the bug report.
4. **To fix this problem, a sequence was manually added in 1.4.3**
See `/install/resources/pgsql_db_tables.php`: [1.4.2](https://github.com/mybb/mybb/blob/mybb_1402/install/resources/pgsql_db_tables.php#L767-L773), [1.4.3](https://github.com/mybb/mybb/blob/mybb_1403/install/resources/pgsql_db_tables.php#L766-L773)
**NOTE:** Looks like the sequence was never added to be created in any upgrade script.
5. (optional) Since there's a manually created sequence and it'll not be dropped when the table/column is dropped, a re-install with the same table prefix as before will probably encounter a sequence already exists error. Again, to fix this problem, a drop sequence query was added in 1.4.4. However, it won't work if the user manually dropped all their tables can run the installer again, and it will have `0 - ERROR: relation "mybb_pgsql_userfields_ufid_seq" already exists `. The reason is simple, the query doesn't check the `information_schema.sequences` view but checks for a primary key existence.
See `/install/resources/pgsql_db_tables.php`: [1.4.4](https://github.com/mybb/mybb/blob/mybb_1404/install/resources/pgsql_db_tables.php#L774-L784)

So, if MyBB is going to drop the table `mybb_userfields`, it'll have to drop the sequence *manually*. And again, it can do that only if it knows the sequence name.

**NOTE:** Seems only the `pgsql` has a third argument for `insert_query()`.

**NOTE:** The above mentioned changes was committed in https://github.com/mybb/mybb/commit/632c595538711edfbabb9ced55bef8f4d7aa547c , including adding the 3rd arg `$insert_id` for `pgsql`'s `insert_query()`.

**Comment by yuliu** [comment]
But please notice that that drop sequence code was added to `drop_table()` in 1.6.

**Comment by yuliu** [comment]
And the table exist check seems not working because the function uses the table prefix internally.
https://github.com/mybb/mybb/blob/mybb_1829/inc/db_pgsql.php#L1276
https://github.com/mybb/mybb/blob/mybb_1829/inc/db_pgsql_pdo.php#L474

**Comment by dvz** [comment]
> The query SQL to DROP SEQUENCE is using single quotes so the variables in it won't get expanded.

~~These seem to be literal `'`, with the whole string in double quotes `"`.~~

The same `DB_Base::table_exists()` table prefix problem appears to affect the SQLite driver.

**Comment by yuliu** [comment]
> > The query SQL to DROP SEQUENCE is using single quotes so the variables in it won't get expanded.
> 
> These seem to be literal `'`, with the whole string in double quotes `"`.

The code line in question is `$this->write_query('DROP SEQUENCE {$table}_{$field}_id_seq');`.

> The same `DB_Base::table_exists()` table prefix problem appears to affect the SQLite driver.

For https://github.com/mybb/mybb/pull/4503#discussion_r923834930 , I'm not sure if the table prefix problem is worthy of fix in the 1.8 code base, as the issue of inconsistent uses and changes of table prefix may also affect other db methods/functions.

For the SQLite driver, let me change the issue title and push some more commits later.
