### ISSUE TITLE
Twitch video code is wrong

### ISSUE THREAD

**Issue by Eldenroot** [mybb/mybb#4504]
https://dev.twitch.tv/docs/embed/video-and-clips/

This needs a little change in
https://github.com/chack1172/mybb/blob/feature/jscripts/bbcodes_sceditor.js

Twitch video is not working anymore...

![image](https://user-images.githubusercontent.com/778890/147155012-5ffb15e4-178a-4f97-80a5-1b8716e6c7eb.png)

**Comment by yuliu** [comment]
In the documentation page:

`parent` (string)
**(required)** Domain(s) that will be embedding Twitch. You must have one parent key for each domain your site uses.

It seems we don't have a direct variable holding the domain/host in the forum URL `$mybb->settings['bburl']`.

Could replace this line
https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/install/resources/mybb_theme.xml#L13782
with
```html
		<template name="video_twitch_embed" version="1830"><![CDATA[<iframe src="https://player.twitch.tv/?{$id}&amp;parent={$parent_domain}&amp;autoplay=false" frameborder="0" scrolling="no" height="378" width="620"></iframe>]]></template>
```

and add a line before the `break;` in
https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/inc/class_parser.php#L1598-L1614

```php
				$parent_domain = parse_url($mybb->settings['bburl'], PHP_URL_HOST);
```

Though I'm not so sure.
