### ISSUE TITLE
MyBB 1.8.28 update broke several custom MyCodes

### ISSUE THREAD

**Issue by zinabat** [mybb/mybb#4511]
After running the MyBB 1.8.28 update, several custom MyCodes are no longer working.

### Profile shortcode
- RegEx: `\[p=([0-9]+)\](.*?)\[/p\]`
- Replacement: `<a href="member.php?action=profile&uid=$1" target="_blank">$2</a>`

### Image align
- RegEx: `\[image align=(left|right|center)\](.*?)\[/image\]`
- Replacement: `<div class="text-$1"><img src="$2" alt=""></div>`

The result for these always a blank post, overwriting all of the content after parsing with a blank string. Very strange.
________
There are several other working MyCodes that are almost identical to some of these, such as:
- RegEx: `\[t=([0-9]+)\](.*?)\[/t\]`
- Replacement: `<a href="showthread.php?tid=$1" target="_blank">$2</a>`

Help?

**Comment by zinabat** [comment]
## Update
This may be a moot point, but I'd like to leave it here for searchability. It seems any MyCode that fails XHTML parser validation will do this. For instance, the image align is missing a closing slash, e.g., `<div class="text-$1"><img src="$2" alt="" /></div>`.

Still can't figure out the other one though.

**Comment by dvz** [comment]
Try changing `&` to `&amp;` in _Replacement_.

**Comment by zinabat** [comment]
> Try changing `&` to `&amp;` in _Replacement_.

Yup, thank you, I forgot to alter this.

The other codes that were broken were using unicode shorthands such as `&nbsp;`, but xhtml requires the number code for such items. Closing this so that others may benefit from searchibility.
