### ISSUE TITLE
Banned users see only "Unknown" for reason and "Never" for lift time

### ISSUE THREAD

**Issue by lairdshaw** [mybb/mybb#4522]
The messages top of page shown to a banned user only ever show
```
Ban Reason: Unknown
Ban will be lifted: Never
```
regardless of the ban reason, and regardless of the time until ban lifting.

**Comment by dvz** [comment]
It looks like some of the changes from https://github.com/mybb/mybb/pull/3879/files#diff-7b7d4d5231d83ea738098e31c83ba44004c829ccf7c74ac947ab02b054fe39ce - other than removing the query - didn't make it into 1.9.

**Comment by lairdshaw** [comment]
@dvz, yes, apparently I got confused in the manual rebasing of #3879 and missed a few lines of code. Hopefully my new PR  #4524 completes the incomplete rebasing of that PR. Have closed my PR #4523 above given that #4524 supersedes it.
