### ISSUE TITLE
Found CRITICAL Vulnerability on your website !

### ISSUE THREAD

**Issue by imchiragprajapati** [mybb/mybb#4531]
Hello I am Chirag Prajapati a Certified Penetration Tester and Ethical Hacker my License no is: 10188-161-078-1726.

I found a CRITICAL Vulnerability on your website: community.mybb.com

For more information I request you to kindly revert me back so that I can share with you the report !
Looking forward to hearing from you !

**Comment by Stefan-MyBB** [comment]
Github is not the right way to report security issues. Please check the policy: https://mybb.com/get-involved/security/
