### ISSUE TITLE
TypeError reported due to $collapse being null

### ISSUE THREAD

**Issue by lairdshaw** [mybb/mybb#4535]
This occurs in the UserCP and the Mod CP. It seems that the global `$collapse` variable is no longer supported, and that we need to use instead the global `$collapsed` variable. I am not clued up on this area of the code but will shortly submit a PR which tries to fix it anyway. I hope that those in the know will correct it if it's deficient.

**Comment by Xazin** [comment]
Hey Laird, heads up, think you missed this one:
`inc/functions.php`: Line 651

**Comment by lairdshaw** [comment]
Grr. You're right, @Xazin, that one slipped past me (understanding that `inc/functions.php` was a typo for `inc/functions_user.php`). Have just pushed a cheeky little direct commit to fix that up. Thanks for the heads up!

**Comment by Xazin** [comment]
> Grr. You're right, @Xazin, that one slipped past me (understanding that `inc/functions.php` was a typo for `inc/functions_user.php`). Have just pushed a cheeky little direct commit to fix that up. Thanks for the heads up!

Haha yes that was a typo indeed.
