### ISSUE TITLE
dbpdoEngine __construct produces wrong driver options using array_merge (sqlite)

### ISSUE THREAD

**Issue by brianvanderburg2** [mybb/mybb#4554]
When attempting to create a board using the Sqlite3 driver, I get an errors during the install stages.
I've have traced this down to the following code:

```php
                        $driver_options = array_merge(
                               $driver_options,
                                array(
                                        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                                        PDO::ATTR_EMULATE_PREPARES => false,
                               )
                        );
```

The issue is that, while no arguments as $driver_options are being passed from the DB_Sqlite class, this section of code takes an empty array, and attempts to merge it with the array (3 => 2, 20 => false).  array_merge discards indices, so this becomes array(0 => 2, 1 => false), causes it to not properly receive PDO::ATTR_ERRMODE and PDO::ATTR_EMULATE_PREPARES.  Instead if receives whatever 0 and 1 are.  One of these I believe is PDO::ATTR_AUTOCOMMIT as if I insert a print statement in the exception handler, the resulting message contains:

DOException Object ( [message:protected] => The auto-commit mode cannot be changed for this driver

**Comment by brianvanderburg2** [comment]
I currently get the code working my removing/commenting out the array_merge as follows in the db_pdo.php file

```php
                        $driver_options = #array_merge(
#                               $driver_options,
                                array(
                                        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                                        PDO::ATTR_EMULATE_PREPARES => false,
#                               )
                        );
```

**Comment by dvz** [comment]
Regression from https://github.com/mybb/mybb/commit/67f1ee8683b8206f2d75cccc462350100c4adb1d#diff-d0384aa72c73937c8c5d61ce3dbd1de6c0ebab8dfe50a1329a5df4f65cf7cfbc

The accidental passing of `PDO::ATTR_AUTOCOMMIT` (`int(0)`) seems to be ignored on PHP >= 7.4.13 (https://github.com/php/php-src/commit/68dcaa29d8a2d51f0fed5fde9f3543a1338bfe44).
