### ISSUE TITLE
I can't run under ubuntu 22.0.4 with php8.1.2

### ISSUE THREAD

**Issue by ignacionf** [mybb/mybb#4563]
I move my site under ubuntu 18 to ubuntu 22 with php 8.1.2 and i get same error with a fresh mybb install:

[Screenshot](https://mfc-space.nyc3.digitaloceanspaces.com/mybb.png)

`

The following warnings occurred:
--
Warning [2] Undefined variable $menu_mfcwebsite - Line: 9 - File: global.php(961) : eval()'d code PHP 8.1.2 (Linux)FileLineFunction/inc/class_error.php153errorHandler->error/global.php(961) : eval()'d code9errorHandler->error_callback/global.php961eval/index.php18require_onceWarning [2] Undefined property: MyLanguage::$toplinks_mfcwebsite - Line: 15 - File: global.php(961) : eval()'d code PHP 8.1.2 (Linux)FileLineFunction/inc/class_error.php153errorHandler->error/global.php(961) : eval()'d code15errorHandler->error_callback/global.php961eval/index.php18require_onceWarning [2] Undefined variable $unreadreports - Line: 34 - File: global.php(961) : eval()'d code PHP 8.1.2 (Linux)FileLineFunction/inc/class_error.php153errorHandler->error/global.php(961) : eval()'d code34errorHandler->error_callback/global.php961eval/index.php | /inc/class_error.php | 153 | errorHandler->error | /global.php(961) : eval()'d code | 9 | errorHandler->error_callback | /global.php | 961 | eval | /index.php | 18 | require_once | /inc/class_error.php | 153 | errorHandler->error | /global.php(961) : eval()'d code | 15 | errorHandler->error_callback | /global.php | 961 | eval | /index.php | 18 | require_once | /inc/class_error.php | 153 | errorHandler->error | /global.php(961) : eval()'d code | 34 | errorHandler->error_callback | /global.php | 961 | eval | /index.php

/inc/class_error.php | 153 | errorHandler->error
/global.php(961) : eval()'d code | 9 | errorHandler->error_callback
/global.php | 961 | eval
/index.php | 18 | require_once

/inc/class_error.php | 153 | errorHandler->error
/global.php(961) : eval()'d code | 15 | errorHandler->error_callback
/global.php | 961 | eval
/index.php | 18 | require_once

/inc/class_error.php | 153 | errorHandler->error
/global.php(961) : eval()'d code | 34 | errorHandler->error_callback
/global.php | 961 | eval
/index.php

`

**Comment by Stefan-MyBB** [comment]
The warnings are caused by plugins. None of these variables exist in a fresh MyBB installation.

**Comment by ignacionf** [comment]
Ok, this data is in db? i dont change the db
