### ISSUE TITLE
Mybb 1.8.30 not compatible with PHP8

### ISSUE THREAD

**Issue by Tarekma7** [mybb/mybb#4589]
Hi
Forum:
https://www.promo2day.com/

I need help as I have disabled all plugins using the option in general settings in the adminCP then I upgraded PHP from 7.4 to 8

I still receive many errors:

Warning [2] Undefined variable $modlist - Line: 5 - File: inc/functions_forumlist.php(457) : eval()'d code PHP 8.0.23 (Linux)

Warning [2] Undefined variable $unreadreports - Line: 33 - File: global.php(961) : eval()'d code PHP 8.0.23 (Linux)

Undefined variable $myalerts_headericon - Line: 10 - File: global.php(553) : eval()'d code PHP 8.0.23 (Linux)

Warning [2] Undefined variable $welcomeguest - Line: 58 - File: index.php(468) : eval()'d code PHP 8.0.23 (Linux)

Warning [2] Undefined property: MyLanguage::$forum_locked - Line: 70 - File: index.php(468) : eval()'d code PHP 8.0.23 (Linux)

Warning [2] Undefined property: MyLanguage::$forum_locked - Line: 71 - File: index.php(468) : eval()'d code PHP 8.0.23 (Linux)

Warning [2] Undefined variable $dvz_shoutbox - Line: 30 - File: index.php(468) : eval()'d code PHP 8.0.23 (Linux)

Please help how to fix these errors?

Also, re-enable plugins under PHP 8 is not working and gives fatal error that stop adminCP ...It works again after reverting back to PHP 7.4

Any advice how to edit the code manually? Or there will be maintenance release to fix these errors?

PHP 7.4 will be removed from the servers after 2 months

**Comment by dvz** [comment]
https://community.mybb.com/thread-236562-post-1380099.html#pid1380099

**Comment by Tarekma7** [comment]
Thanks but still same error occurs after PHP 8 migration

Warning [2] Undefined variable $modlist - Line: 5 - File: inc/functions_forumlist.php(457) : eval()'d code PHP 8.0.23 (Linux)

AdminCP not working after PHP 8 update [HTTP 500]

More errors:

Warning [2] Undefined variable $welcomeguest - Line: 49 - File: index.php(468) : eval()'d code PHP 8.0.23 (Linux)

Warning [2] Undefined property: MyLanguage::$forumteam - Line: 20 - File: index.php(406) : eval()'d code PHP 8.0.23 (Linux)
Warning [2] Undefined property: MyLanguage::$forum_locked - Line: 61 - File: index.php(468) : eval()'d code PHP 8.0.23 (Linux)
Warning [2] Undefined property: MyLanguage::$forum_locked - Line: 62 - File: index.php(468) : eval()'d code PHP 8.0.23 (Linux)

Reverting to PHP 7.4: everything working again

**Comment by Tarekma7** [comment]
@dvz 
please help

**Comment by StrikerTheHedgefox** [comment]
Getting
`Warning [2] Undefined variable $numtot - Line: 462 - File: inc/plugins/onlinetoday.php PHP 8.1.2 (Linux)`

EDIT: Never mind, plugin issue. Fixed it.
