### ISSUE TITLE
Update package for 1831 missing inc/AbstractPdoDbDriver.php

### ISSUE THREAD

**Issue by KanyonKris** [mybb/mybb#4595]
Tried to upgrade myBB with the changes upgrade package from Github. Couldn't run the upgrade script, had an error. error.log noted this file was missing:
inc/AbstractPdoDbDriver.php
Downloaded the full upgrade package, copied the inc/AbstractPdoDbDriver.php file and the upgrade worked.

**Comment by yuliu** [comment]
Which version of MyBB were you upgrading from?

**Comment by Stefan-MyBB** [comment]
That package only includes the changes since MyBB 1.8.30. If you are using an older version you have to use the full package.
