### ISSUE TITLE
After upgrade to PHP 8.0: Boardstats counter of posts and threads does not increase anymore

### ISSUE THREAD

**Issue by Amseog** [mybb/mybb#4637]
Apart form [another issue I reported separately](https://github.com/mybb/mybb/issues/4530#issuecomment-1373697532), my MyBB forum has encountered a new problem ever since I switched from PHP 7.4 to PHP 8.0 yesterday:

The counter for the board's full number of posts and threads does not increase anymore. Only a manual "Recount statistics" via ACP fixes the number.

In order to rule out that this problem depends only on some faulty plugin or theme, I have now installed a completely new and fresh MyBB 1.8.33 on my webspace, complete with new database.
The problem still persists:

![Problem](https://user-images.githubusercontent.com/5350651/211032152-bf4b2219-88e9-4fb2-b0dd-011a902d61a5.PNG)

Here's the error log: https://jpstein.de/probeboard/error.log
And here's the link to the clean MyBB board: https://jpstein.de/probeboard/

**Comment by dvz** [comment]
Likely caused by the same factors: https://github.com/mybb/mybb/issues/4530#issuecomment-1373889203
