### ISSUE TITLE
[PHP 8] Undefined array key warnings in threads with video

### ISSUE THREAD

**Issue by ghost** [mybb/mybb#4650]
The page for viewing threads with Youtube video(s) displays undefined array key warnings.

You can view it from the link below:

👉 https://mybbcode.com/showthread.php?tid=1

Undefined array key "fragment" ⤵️

https://github.com/mybb/mybb/blob/44be739f817fcc4b04afcbb91fc6d91b59815bba/inc/class_parser.php#L1494

Undefined array key 0 ⤵️

https://github.com/mybb/mybb/blob/44be739f817fcc4b04afcbb91fc6d91b59815bba/inc/class_parser.php#L1587

It can be resolved with the `isset()` function.

**Comment by yuliu** [comment]
It's been fixed in #4613.

**Comment by ghost** [comment]
> It's been fixed in #4613.

Thanks. I checked before sending, but I missed it because it was bundled. It can be marked as closed.
