### ISSUE TITLE
Getting exception when sending SMTP email (via SMTP raw not PHP )  and connection fails to be established

### ISSUE THREAD

**Issue by glwrba** [mybb/mybb#4680]
This scenario has been reproduced on myBB latest stable 1.8.33 whenever trying to register a new user on myBB, after the information has been provided, the captcha provided and the "Submit Registration!" button has been clicked,  and after the SMTP configuration has been selected under Admin CP->Configuration->Mail Settings->Mail Handler and all details for the SMTP server have been provided accordingly.

When trying to establish the SMTP connection,  under myBB latest stable  1.8.33,  the code assumes that the socket being obtained is a valid one,  and performs a call to set the stream_set_timeout.  That's correct for a successful connection, however if a connection cannot be established the call to fsockopen returns a boolean FALSE which leads to an exception when trying to call the @stream_set_timeout function since it expects a handle rather than a boolean, leading to the below stacktrace and exception:

> Fatal error: **Uncaught TypeError: stream_set_timeout(): Argument #1 ($stream) must be of type resource, bool given in /opt/apache-2.4/sites/microforum.openservers.org/inc/mailhandlers/smtp.php:281 Stack trace: #0 /opt/apache-2.4/sites/microforum.openservers.org/inc/mailhandlers/smtp.php(281)**: stream_set_timeout(false, 5, 0) #1 /opt/apache-2.4/sites/microforum.openservers.org/inc/mailhandlers/smtp.php(199): SmtpMail->connect() #2 /opt/apache-2.4/sites/microforum.openservers.org/inc/functions.php(677): SmtpMail->send() #3 /opt/apache-2.4/sites/microforum.openservers.org/member.php(621): my_mail('glwrba@yahoo.co...', 'New registratio...', 'admin,\n\nThere i...') #4 {main} thrown in /opt/apache-2.4/sites/microforum.openservers.org/inc/mailhandlers/smtp.php on line 281

The snippet of code that fails is as below

`(Line 281) of inc/mailhandlers/smtp.php

  function connect()
        {
                global $lang, $mybb;

                $this->connection = @fsockopen($this->host, $this->port, $error_number, $error_string, $this->timeout);
        
                // DIRECTORY_SEPARATOR checks if running windows
                if(function_exists('stream_set_timeout') && DIRECTORY_SEPARATOR != '\\')
                {
                        @stream_set_timeout($this->connection, $this->timeout, 0);
                }
`

The solution is to check the handle being returned, and in case of getting a FALSE boolean,  we should immediately log the condition and return from the function with a FALSE flagging that something has failed while trying to send the mail via SMTP.

The snippet below represents one potential way to fix this issue

`function connect()
        {
                global $lang, $mybb;

                $this->connection = @fsockopen($this->host, $this->port, $error_number, $error_string, $this->timeout);

                if ( ! $this->connection )
                        {
                              $this->fatal_error("A connection cannot be established to the mail server specified.");
                                return false;

                      }
        
Said that, i'm afraid this is not the only change required for a consistent user experience, since after doing so, the user is sent a positive notification on the screen , rather than a message indicating that something went wrong, leading to a situation where a user is expecting an email that will never be delivered ( since connection failed).
    
I think a more deep analysis is required here in the upstream call chain so that when a FALSE is returned it must be interpreted as a failure and some action taken.   I didn't dig too much yet but i think these changes should be incorporated to turn the mail process robust enough. ( it seems quite rough for now )

**Comment by Sama34** [comment]
Co
