### ISSUE TITLE
forumbit_depth1_forum template is not cached

### ISSUE THREAD

**Issue by Eldenroot** [mybb/mybb#4698]
![image](https://github.com/mybb/mybb/assets/778890/21561ae5-689a-4ad7-ba73-9714c91e6efd)

**Comment by dvz** [comment]
Looks like a nonexistent template is being referenced (one with the same name was removed in f3d1eb095a43f8e6c88785f9fe5d2842ccca4e80). What circumstances result in it being called?

**Comment by Stefan-MyBB** [comment]
I can't confirm this issue either. That template doesn't exist and isn't referenced in any core file.

**Comment by Eldenroot** [comment]
It is called on index page... I do not why, I noticed it yesterday.

**Comment by RevertIT** [comment]
That template doesn't exist by default. 

Most likely a custom template by some plugin.
