### ISSUE TITLE
Automatic parsing of URL in brackets hangs system (1.8.33, PHP8.2)

### ISSUE THREAD

**Issue by AndrewWoodTIG** [mybb/mybb#4708]
With BB Code 'Automatically Parse URLs Into Links' set to on, the following message (excerpt shown) causes myBB to become unresponsive/hang:

> who he also misled. (Ref https://www.bbc.co.uk/news/entertainment-arts-65729361.) I imagine until now his lawyers 

Editing the message to add a space after the full stop at the end of the linked URL stops the issue.

> who he also misled. (Ref https://www.bbc.co.uk/news/entertainment-arts-65729361. ) I imagine until now his lawyers 

The full stop isn't part of the URL, but was typed by the poster.

**Comment by dvz** [comment]
Regression after #4320.

The array element overwrite at https://github.com/mybb/mybb/blob/d6a57e496dc46b56bccc4d1afbc6ffc33a14738c/inc/class_parser.php#L1752
was not changed from `$matches[4]` to `$matches['link']`, similar to other replacements made in https://github.com/mybb/mybb/commit/b887862fc47638aa3a9577f3c474cdd1c726e172.

This change seems to resolve the problem.

**Comment by AndrewWoodTIG** [comment]
Thank you! Very much appreciated.
