### ISSUE TITLE
Undefined array key "cancp"

### ISSUE THREAD

**Issue by Cx-Developments** [mybb/mybb#4712]
I keep getting this error within my admin control panel using mybb 1.8.34 release code no adaptions running minimal plugins and still occurs when plugins disabled.

admin/index.php | 529 | Warning | Undefined array key "cancp"

**Comment by Sama34** [comment]
What is your setup PHP version ?

**Comment by Cx-Developments** [comment]
8.2

**Comment by Cx-Developments** [comment]
This actually resolved the error but I am still unable to login to the administrative panel
