### ISSUE TITLE
CodeMirror PHP8 warnings

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#4723]
When using the _Diff Report_ feature on templates, the following warning might take place :
`./admin/index.php?module=style-templates&action=diff_report&title=showthread&sid2=1`

> Deprecated: Creation of dynamic property Horde_Text_Diff_Engine_Native::$ychanged is deprecated in /var/www/inc/3rdparty/diff/Diff/Engine/Native.php on line 46
> Deprecated: Creation of dynamic property Horde_Text_Diff_Engine_Native::$xchanged is deprecated in /var/www/inc/3rdparty/diff/Diff/Engine/Native.php on line 46
> Deprecated: Creation of dynamic property Horde_Text_Diff_Engine_Native::$yv is deprecated in /var/www/inc/3rdparty/diff/Diff/Engine/Native.php on line 47
> Deprecated: Creation of dynamic property Horde_Text_Diff_Engine_Native::$xv is deprecated in /var/www/inc/3rdparty/diff/Diff/Engine/Native.php on line 47
> Deprecated: Creation of dynamic property Horde_Text_Diff_Engine_Native::$yind is deprecated in /var/www/inc/3rdparty/diff/Diff/Engine/Native.php on line 48
> Deprecated: Creation of dynamic property Horde_Text_Diff_Engine_Native::$xind is deprecated in /var/www/inc/3rdparty/diff/Diff/Engine/Native.php on line 48

**Comment by chack1172** [comment]
I checked the external Text_Diff library and I'm not sure if it will be updated to fix PHP 8 issues.
