### ISSUE TITLE
3 Warnings under PHP8 in showthread

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#4732]
if a thread contains threadnotes by moderators three warnings appear under PHP8.1

Warning [2] Undefined array key "threadnotes" - Line: 5 - File: showthread.php(1328) : eval()'d code PHP 8.1.16 (Linux) 

Warning [2] Undefined array key "threadnotes" - Line: 6 - File: showthread.php(1328) : eval()'d code PHP 8.1.16 (Linux) 

Warning [2] Undefined array key "threadnotes_e" - Line: 11 - File: showthread.php(1328) : eval()'d code PHP 8.1.16 (Linux)

Original thread: [3 Warnings under PHP8 in showthread](https://community.mybb.com/thread-237843.html)

**Comment by w13** [comment]
<img width="1260" alt="image" src="https://github.com/mybb/mybb/assets/150587/953bde30-1b21-49e4-b23d-81effb81f907">
