### ISSUE TITLE
eMail issues with PHP mail()...

### ISSUE THREAD

**Issue by exdiogene** [mybb/mybb#4734]
Because I did not receive any response on the MyBB Community website for 4 days, I am posting the bug here!

MyBB Version 1.8.34
PHP Version 8.0.29
SQL Engine MySQLi 8.0.33

This is a plain english default installation without any plugins.

I was able to find why no email was able to be sent from anywhere in the MyBB forum.

Inside the file "/inc/mailhandlers/php.php" there is 2 lines causing the problem. The headers lines are not separated with CRLF (\r\n), and because the mailhandler delimiter is changed in the code blocking also the mass mail.

PHP ask for a CRLF (\r\n) separator between headers lines...
This is the section where the headers and delimiter are wrongly changed in the file "/inc/mailhandlers/php.php" :

```
if($this->sendmail)
{
// to be commented $this->headers = str_replace("\r\n", "\n", $this->headers);
$this->message = str_replace("\r\n", "\n", $this->message);
// to be commented $this->delimiter = "\n";
}

```

Without the commented lines, this is causing the PHP mail() silent error!

**Comment by dvz** [comment]
Looks like it was supposed to address some specific 3rd party problems:
https://github.com/mybb/mybb/blob/d84d4df9e8fe2516b5882a32ff219e68acbb07a0/inc/mailhandlers/php.php#L38

Possibly related: https://github.com/php/php-src/issues/8086

**Comment by exdiogene** [comment]
If we refer to the PHP Mail() function description it seem preferable to use an Array for data transfer instead of not knowing if it is a CRLF or a LF that should be used in the user hosting environment?

Hoping that PHP would format the mail properly with the Array...

> mail
> 
> (PHP 4, PHP 5, PHP 7, PHP 8)
> 
> mail — Send mail
> Description
> mail(
>     string $to,
>     string $subject,
>     string $message,
>     array|string $additional_headers = [],
>     string $additional_params = ""
> ): bool
> 
>  
> 
>  additional_headers (optional)
> 
>     String or array to be inserted at the end of the email header.
> 
>     This is typically used to add extra headers (From, Cc, and Bcc). Multiple extra headers should be separated with a CRLF (\r\n). If outside data are used to compose this header, the data should be sanitized so that no unwanted headers could be injected.
> 
>     If an array is passed, its keys are the header names and its values are the respective header values.
> 
>         ...
>         ...
> 
>         Note:
> 
>         If messages are not received, try using a LF (\n) only. Some Unix mail transfer agents (most notably » qmail) replace LF by CRLF automatically (which leads to doubling CR if CRLF is used). This should be a last resort, as it does not comply with » RFC 2822.

**Comment by dvz** [comment]
Yes, one solution may be to split the final string with the used delimiter to pass an array on PHP >= 7.2.0 (when `array` became an accepted type for the parameter).
