### ISSUE TITLE
Upgrade from 1.8.34 to 1.8.35 on PHP 8.1.14 Errors

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#4736]
Tryied to make an upgrade, install script throws these errors:

Warning [2] Trying to access array offset on value of type null - Line: 795 - File: install/upgrade.php PHP 8.1.14 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler-&gt;error
/install/upgrade.php	795	errorHandler-&gt;error_callback
/install/upgrade.php	372	get_upgrade_store
Warning [2] Trying to access array offset on value of type null - Line: 795 - File: install/upgrade.php PHP 8.1.14 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler-&gt;error
/install/upgrade.php	795	errorHandler-&gt;error_callback
/install/upgrade.php	373	get_upgrade_store

The upgrade looks completed, but there is also an error:

Upgrade Complete
Warning [2] Trying to access array offset on value of type null - Line: 795 - File: install/upgrade.php PHP 8.1.14 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler-&gt;error
/install/upgrade.php	795	errorHandler-&gt;error_callback
/install/upgrade.php	638	get_upgrade_store
/install/upgrade.php	405	upgradedone

Congratulations, your copy of MyBB has successfully been updated to 1.8.35.

Original thread: [Upgrade from 1.8.34 to 1.8.35 on PHP 8.1.14 Errors](https://community.mybb.com/thread-238808.html)

**Comment by yuliu** [comment]
These warnings appear when: 1, an upgrade isn't needed (eg., from 1834 to 1835), and 2, the upgrade script is started and the **Next** button is clicked to lock the installer.

It means that when the **Next** button is clicked to execute the `upgradedone()` function, and it tries to fetch `allow_anonymous_info` at 

https://github.com/mybb/mybb/blob/d84d4df9e8fe2516b5882a32ff219e68acbb07a0/install/upgrade.php#L638

via `get_upgrade_store()` in which the warning appears at 

https://github.com/mybb/mybb/blob/d84d4df9e8fe2516b5882a32ff219e68acbb07a0/install/upgrade.php#L795

because in the situation of no upgrade needed, there's no `upgrade_store` data being populated to table `mybb_upgrade_data`, and thus no `allow_anonymous_info` as well.

**Comment by yuliu** [comment]
Another report was attached in the original thread at: https://community.mybb.com/thread-238808-post-1387518.html#pid1387518

```
Warning [2] Undefined variable $written - Line: 674 - File: install/upgrade.php PHP 8.2.8 (Linux)
File Line Function
/inc/class_error.php 153 errorHandler->error
/install/upgrade.php 674 errorHandler->error_callback
/install/upgrade.php 405 upgradedone
Congratulations, your copy of MyBB has successfully been updated to 1.8.31.

Please remove this directory before exploring your upgraded MyBB. 
```

**Comment by dvz** [comment]
https://community.mybb.com/thread-239484-post-1392814.html#pid1392814
```
Warning [2] Undefined property: MyLanguage::$task_versioncheck_ran_errors - Line: 26 - File:
inc/tasks/versioncheck.php PHP 8.2.12 (Linux)
```
