### ISSUE TITLE
Awaiting Moderation thread count issue

### ISSUE THREAD

**Issue by AndrewWoodTIG** [mybb/mybb#4789]
When moved posts are set to 'unapproved', they count as a thread awaiting moderation, not a post, as the 'reply-to' flag is set to 0. Maybe the code global.php is a little too streamlined?!

```
	$unapproved_posts = $unapproved_threads = 0;
	$query = $db->simple_select("posts", "replyto", "visible = 0");
	while($unapproved = $db->fetch_array($query))
	{
		if($unapproved["replyto"] == 0){
			$unapproved_threads++;
		} else {
			$unapproved_posts++;
		}
	}
```

**Comment by AndrewWoodTIG** [comment]
Using 1.8.37 on a clean install.

**Comment by dvz** [comment]
Looks like `replyto` is incorrectly set to `0` in `Moderation::merge_threads()` and `Moderation::split_posts()`.

Otherwise, it's corrected in `PostDataHandler`:
https://github.com/mybb/mybb/blob/d1b1d45994e5b190e49973b8d658a89bc4e6fd3f/inc/datahandlers/post.php#L628-L639
