### ISSUE TITLE
MyBB 1.8.37 Error 500 "PHP Fatal error: Cannot redeclare error()"

### ISSUE THREAD

**Issue by KamillaPup** [mybb/mybb#4794]
```
AH01071: Got error 'PHP message: PHP Fatal error: Cannot redeclare error() in on line 938'
```
I am getting the above error after copying the installer files from Upload to my Plesk server, renaming .htaccess, renaming config.default.php, and setting all the listed chmods. I can't even load the installer as I keep getting this error in my PHP logs. I have tried both nginx and the apache2 proxy.

Is there a beta of 1.9 I can try? Is there something else I can try?

I installed phpbb without error but I really don't want to use that but at least PHP is working (8.2.17).

**Comment by dvz** [comment]
Are there more details for this or any other errors?

If you open MyBB's main directory (rather than `/install`), does it also result in a 500 error?

This may be caused by another scripts incorrectly loaded before/after MyBB in the server configuration.

**Comment by KamillaPup** [comment]
That's all I have. This is a fresh install and I'm going to /install. Also the config.php file is 0 bytes. Is that by design?

**Comment by dvz** [comment]
> Also the config.php file is 0 bytes. Is that by design?

Yes, it's populated during installation.

> This is a fresh install and I'm going to /install.

If it's redirecting there from the main directory, it may be specific to the installation (otherwise, MyBB or the server).

It's not an usual error, so it's likely related to the server.

You can create a new `test.php` file, upload it, and access it to generate some information:
```php
<?php

// included files diagnostics
var_dump(
	get_included_files()
);

// function definition diagnostics
$name = 'error';

$methods = [
	'getFileName',
	'getNamespaceName',
	'getStartLine',
	'getEndLine',
	'getExtension',
	'isInternal',
];

if (function_exists($name)) {
	$reflection = new ReflectionFunction($name);
	
	$data = [];
	
	foreach ($methods as $method) {
		$data[$method] = $reflection->$method();
	}
	
	var_dump($data);
} else {
	echo "Function {$name} is not defined";
}
```
and paste the output here.

**Comment by KamillaPup** [comment]
`array(1) { [0]=> string(59) "/var/www/vhosts/example.com/httpdocs/install/test.php" } array(6) { ["getFileName"]=> bool(false) ["getNamespaceName"]=> string(0) "" ["getStartLine"]=> bool(false) ["getEndLine"]=> bool(false) ["getExtension"]=> object(ReflectionExtension)#2 (1) { ["name"]=> string(11) "kolabformat" } ["isInternal"]=> bool(true) }`

**Comment by dvz** [comment]
Looks like an extension `kolabformat` adds a function with a conflicting name - see if you can disable it for the server where MyBB is supposed to be run.

**Comment by KamillaPup** [comment]
That was it! I went into the Plesk extensions, disabled Plesk Premium Email by Kolab, and it worked.

Although I was using that extension. Would there be anyway to get them to work together?

**Comment by dvz** [comment]
Keeping MyBB's function renamed would be difficult, so it may be best to reach out to the provider/Plesk/extension maintainers about addressing the underlying issue, or creating separate configurations for the mail-related software.

Apparently relevant issue: https://git.kolab.org/T5746
