### ISSUE TITLE
Missing "my_post_key" code in cancel subscription email notification

### ISSUE THREAD

**Issue by Walter-Correa** [mybb/mybb#4802]
The problem is reported by another user and I can confirm this issue:
https://community.mybb.com/thread-238945-post-1393424.html#pid1393424

**Comment by Eldenroot** [comment]
Valid

**Comment by Walter-Correa** [comment]
User **Devilshakerz** explained the reason for this issue: https://community.mybb.com/thread-238945-post-1393430.html#pid1393430

Basically the token system was removed and the English language variables were also updated.

**The solution to this problem is to update the language variables of your current language.**
