### ISSUE TITLE
Never Visited: Staff List & ModCP Bug

### ISSUE THREAD

**Issue by effone** [mybb/mybb#4814]
Rare scenario, but if any staff has never visited the forums he will be shown in staff list page as `Last Visit: Less than 1 minute ago`

Following is the snap of staff list with generated staffs which are actually dummy accounts and never visited the forums:

![snap](https://i.ibb.co/51c9rvV/image.png)

**Comment by Ben-MyBB** [comment]
I believe this is a wider issue, I think on the last online date on the profile it shows the time they have registered even if they have never logged in. On 23 May 2024, at 23:22, Debabrata Trivedi ***@***.***> wrote:﻿
Rare scenario, but if any staff has never visited the forums he will be shown in staff list page as Last Visit: Less than 1 minute ago
Following is the snap of staff list with generated staffs which are actually dummy accounts and never visited the forums:

**Comment by effone** [comment]
Nope, there is no fall back to reg time.
If there is no timestamp in lastvisit column, MyBB shows `Last Visit: Never`. Its like that everywhere.

**Comment by effone** [comment]
Reopening to correct the logic as well as addressing very identical bug in ModCP > finduser:

Never visited users in ModCP displays as `Last Visit: Less than 1 min ago` ...

![snap](https://i.ibb.co/0Gg2MZC/Screenshot-2024-05-26-222328.png)
