### ISSUE TITLE
Calendar, Week Overview: Week period calculated wrong

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#511]
![calendar](https://cloud.githubusercontent.com/assets/1917879/2984635/61f7973c-dc34-11e3-95b4-5fddca8a3a21.png)

As you can see, it tells me that the week has more than 2000 years :P (Note that the fix for #346 was applied on this board)

**Comment by Destroy666x** [comment]
To be more specific, it happens only for years 0-100. After that it's ok: http://community.mybb.com/calendar-1-week-n58979921800.html

**Comment by Devilshakerz** [comment]
[gmmktime()](https://secure.php.net/manual/en/function.gmmktime.php)'s return value seems to overflow back to positive numbers in https://github.com/mybb/mybb/blob/mybb_1807/calendar.php#L2039 when the `$year` parameter is less than 101, however it's possible to get correct values using other parameters:
```php
function gmmktime_fix($hour, $minute, $second, $month, $day, $year)
{
    if ($year < 101) {
        $month -= (12 * (101 - $year));
        $year = 101;
    }

    return gmmktime($hour, $minute, $second, $month, $day, $year);
}
```

**Comment by Destroy666x** [comment]
Yeah, noticed that too before I went to sleep: https://github.com/php/php-src/blob/0c3022f436f6adf1afe8db2f7d8356e9b1892aad/ext/date/php_date.c#L1521-L1525 I wonder what's the point of it.. And the fix seems to be reasonable to push.

**Comment by Devilshakerz** [comment]
https://secure.php.net/manual/en/function.mktime.php:
> The number of the year, may be a two or four digit value, with values between 0-69 mapping to 2000-2069 and 70-100 to 1970-2000.

Note that the calendar doesn't reach before year 0 anyway.

**Comment by Destroy666x** [comment]
That's stupid. Could have added a boolean argument for short years or whatever.

**Comment by JN-Jones** [comment]
@Devilshakerz Can you create a PR for this? Even if it's a small bug I don't see a reason to keep it open for so long.
