### ISSUE TITLE
Line breaks in templates search fails

### ISSUE THREAD

**Issue by JordanMussi** [mybb/mybb#674]
....epically :tongue:

If you search templates using a string that contains a line break even if a template with this string exists it will not be returned. *sad admin*

For example searching for:

``` html
</head>
<body>
```

Does not return the `index` template.

1.8 acts differently. When searching with an indent it fails. The following should return `memberlist_user`

``` html
    {$usergroup['groupimage']}
    {$user['userstars']}
```

http://community.mybb.com/thread-153845.html

**Comment by JN-Jones** [comment]
The whole template search seems odd. The first example of @JordanMussi returned the `showthread` template for me but not the `index` one which still has the closing/opening tags. However the indents search works as long as you don't combine it with a linebreak. So it seems that mainly the linebreak is causing this behavior.
