### ISSUE TITLE
Reputation from post - Popup text and auto refresh

### ISSUE THREAD

**Issue by DiogoParrinha** [mybb/mybb#952]
when we add reputation from a post, it asks for comments which isn't needed. it must be noted that the text on the popup box says comments isn't needed.

second thing is that after adding the reputation the thread is not auto refreshed to update the reputation.

Original thread: [Reputation from post - Popup text and auto refresh](http://community.mybb.com/thread-155651.html)

**Comment by sparkks** [comment]
My users are already bitching about it not refreshing.. I vote this is an issue and should be fixed soon. Thanks.

**Comment by JN-Jones** [comment]
You're the first one complaining about it since 1.8.0 and the second since I joined the team. Also I don't see a reason to change it, it's only one small number. And please don't post the same comment here and on the forums, one place is enough.
